### ISSUE TITLE
Admin Panel - Login not working

### ISSUE THREAD

**Issue by zak2008** [pH7Software/pH7-Social-Dating-CMS#100]
I have been getting the same result after a fresh install of either 'Dating' or 'Social Dating' niches, i.e. Admin Panel - Login displays no login/join form when I try to access the Admin panel using "www.ethiomeetup.com/admin123". It keeps displaying "Please sign in first". Also, no join form appears when "Join Now" is clicked. The version I used is pH7CMS-3.1.0, and hosting it with Arvixe. By the way, the rest of the menus work fine.
I have double checked folder permissions too. Please help me if I am missing something? I've been stuck for three days. Thanks.

**Comment by pH-7** [comment]
You have two solutions to fix that problem.

* Use PHP 7 or newer (PHP 7 fixes that problem)
* or open `_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php` and replace the whole contents by https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/d69fd86af9a45ce2ea58520fbb6ebe77e62240ce/_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php

Thanks

**Comment by pH-7** [comment]
You have two solutions to fix that problem.

* Use PHP 7 or newer (PHP 7 fixes that problem)
* or open `_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php` and replace the whole contents by https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/d69fd86af9a45ce2ea58520fbb6ebe77e62240ce/_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php
* or replace `_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php` file by https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/d69fd86af9a45ce2ea58520fbb6ebe77e62240ce/_protected/framework/Layout/Form/Engine/PFBC/Element/Token.php file

Thanks

**Comment by pH-7** [comment]
I added a public post explaining that as well http://ph7cms.com/problem-ph7cms-3-1/

**Comment by pH-7** [comment]
I also added a public post explaining that http://ph7cms.com/problem-ph7cms-3-1/
