### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by GarfieldsPipe** [pH7Software/pH7-Social-Dating-CMS#1009]
Using PHP 8.1 on Debian 10 with MariaDB.

Fatal error: Declaration of PH7\Admin::logout(PH7\Framework\Session\Session $oSession) must be compatible with PH7\UserCore::logout(PH7\Framework\Session\Session $oSession): void in /home/_protected/app/system/modules/admin123/inc/class/Admin.php on line 22

**Comment by pH-7** [comment]
Thanks very much for reporting this @GarfieldsPipe!

I will have a look and give a fix to it ASAP.

Was the version from the latest GitHub version or from the zip archive downloaded from Sourceforge?

**Comment by pH-7** [comment]
I've now identified the issue and fixing it 🙂
