### ISSUE TITLE
Unable to use the universal login with fb and google with ph7cms

### ISSUE THREAD

**Issue by itsarijeet** [pH7Software/pH7-Social-Dating-CMS#101]
I am unable to use the universal login.
i have entered the secret code and everything , it authenticates and comes back but does not login the user.
please help me,
I am using ph7cms 4.0 version also have the license.

**Comment by pH-7** [comment]
It seems Google has again changed their API. So we will have to update our code to meet their new API requirements (same for Facebook). 

For the moment, it is wise to disable that module.

Thanks

**Comment by itsarijeet** [comment]
Ok, Thanks for the information, please tell me how to remove the "Universal
Login" option from the home page.
Else users will click on it and land up on a blank page.
Secondly, even the Google map api is not working, the video upload option
throws error for some "ffmpeg", need help with that too. its been 4 days i
have bough the licence but have not yet able to launch my website :(
please help.

**Comment by itsarijeet** [comment]
Hi,
Just an update, the map seems to work now. Kindly help with the removal of
universal login and video upload option.
Thank you.

**Comment by pH-7** [comment]
Go to admin panel -> Modules -> Enable/Disable Modules and untick "connect" module


Concerning FFMPEG, please ask you host to install it and make sure the path is correct (in config.ini like the support told you)

Next time, please just log a ticket through your member area (and reply there, not by email).

Many thanks.

Have a good weekend

**Comment by itsarijeet** [comment]
Thank you very much, yes i have raised a ticket already. :)
