### ISSUE TITLE
Signup email activation gives blank page when different theme is set

### ISSUE THREAD

**Issue by coolyou11** [pH7Software/pH7-Social-Dating-CMS#1015]
Once you set this software up and a person joins, it shows everything correct regards and tells the new user to get the activation email. I have noted that if you change  to a new theme are change some settings then when a new person joins  there is just a blank page and it does not say anything about activating with persons email , even though in admin its set to user needs to active account by email

**Comment by pH-7** [comment]
Hi @coolyou11 🙂 Thanks very much for reporting this issue @coolyou11!

What is the new theme you have set as default?
Could you share a screenshot of the blank page?

**Comment by pH-7** [comment]
Finally, there must be an internal PHP error causing this blank page.

You can enable the development mode to show the PHP errors (exceptions) on that page. 

To do so, edit `_protected/app/configs/config.ini`, and replace `environment = production` to `environment = development`, and then save it.

You can also see the PHP logs located at `_protected/data/log/pH7log/`

Let me know how it goes 😊

Hope it helps!

**Comment by coolyou11** [comment]
Thank you for your reply, the problem was I was trying to create test accounts using different web browsers but from with the same IP, and it does not work. Thanks for the info for putting the website into development mode.
