### ISSUE TITLE
unable to access user section from admin page

### ISSUE THREAD

**Issue by itsarijeet** [pH7Software/pH7-Social-Dating-CMS#102]
Hi,
Please help me as i am unable to access the admin section of users from admin panel.
i get the below error. Please help.

Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

**Comment by pH-7** [comment]
Can you give the full URL where you get that issue (and/or send here a full screenshot of your screen where you see that error)

**Comment by pH-7** [comment]
You have to ask your host to disable Mod_Security
