### ISSUE TITLE
The login page is not loading after successful installation

### ISSUE THREAD

**Issue by shree0** [pH7Software/pH7-Social-Dating-CMS#1027]
Hello, 
 I am trying to install ph7builder latest version(i.e. 17.2.0) in cPanel. I am able to install it successfully but when I try to load the login page it is not loafing showing `This page isn’t working` with `HTTP ERROR 500` error. I have checked `.htaccess` also, but I was unable to resolve it. I am able to load the login page in the previous version i.e. 17.1.8 without any error and it's working fine. Can you please help to resolve it?
 Thanks.

**Comment by shree0** [comment]
it is solved.

**Comment by user14983** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/1033#issue-1301361041
