### ISSUE TITLE
Errors in install

### ISSUE THREAD

**Issue by 2dned** [pH7Software/pH7-Social-Dating-CMS#1032]
After installing pH7 on a paid hosting service i get these errors.

Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, bool given in /home/novaoutp/public_html/date/_pussy/framework/Server/Server.class.php:165 Stack trace: #0 /home/novaoutp/public_html/date/_pussy/framework/Server/Server.class.php(165): strtolower(false) #1 /home/novaoutp/public_html/date/_pussy/app/Bootstrap.php(78): PH7\Framework\Server\Server::isRewriteMod() #2 /home/novaoutp/public_html/date/index.php(45): PH7\Bootstrap->run() #3 {main} thrown in /home/novaoutp/public_html/date/_pussy/framework/Server/Server.class.php on line 165

I installed via hosting script, got these errors. deleted everything and started again with latest copy, same errors.
PHP7.4

**Comment by msburgess3200** [comment]
The following function does not return "on" or "off" anymore. It will return true or false. This was changed in PHP 7.4. Comment it out and it works just fine. Btw, make sure you turn GZIP off on your PHP settings.

```
public static function isRewriteMod(): bool
    {
        // Check if mod_rewrite is installed and is configured to be used via .htaccess
        /*if (!strtolower(getenv('HTTP_MOD_REWRITE')) === 'on') {
            $sOutputMsg = 'mod_rewrite Works!';

            if (Uri::getInstance()->fragment(0) === 'test_mod_rewrite') {
                exit($sOutputMsg);
            }

            $sPage = @file_get_contents(PH7_URL_ROOT . 'test_mod_rewrite');
            return $sPage === $sOutputMsg;
        }*/

        return true;
    }
```

**Comment by pH-7** [comment]
Thanks very much for reporting this type error due to the usage of PHP 7.4+ type declaration and strict type check in Server.class.php 

This issue has been fixed in git commit https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/88c58904a65c015309fab4bef9a3f4d9118a0cd5
The patch is available in the `18.x` branch and will be available in the next release.
