### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by a1gamingonline** [pH7Software/pH7-Social-Dating-CMS#1043]
**Describe the bug**

(a clear and concise description of what the bug is.)

Warning: Unsupported declare 'strict_type' in /home/kiaoraga/public_html/hizup/WebsiteChecker.php on line 10

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/kiaoraga/public_html/hizup/WebsiteChecker.php on line 20

**Comment by pH-7** [comment]
I looks like you are running a PHP version lower than v7.1 pH7Builder requires at least PHP 7.4 before v18, and now with the v18 coming very soon, you will need at least PHP 8.0
