### ISSUE TITLE
Ph7cms debug exception i

### ISSUE THREAD

**Issue by Mj5333** [pH7Software/pH7-Social-Dating-CMS#1046]
Message:	/home/jayhouse/public_html/getsfreehugs/templates/themes/zendate/tpl/disclaimer-dialog.inc.tpl file does no exist.
File:	/home/jayhouse/public_html/getsfreehugs/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php
Line:	339
Trace:	
#0 /home/jayhouse/public_html/getsfreehugs/_protected/data/cache/pH7tpl_compile/user_12d6c9dbe561282c5c0b52b4dd5273ae/base/main/layout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('disclaimer-dial...', '/home/jayhouse/...')
#1 /home/jayhouse/public_html/getsfreehugs/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/jayhouse/...')
#2 /home/jayhouse/public_html/getsfreehugs/_protected/data/cache/pH7tpl_compile/public_main/zendate/layout.cpl.phplayout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/jayhouse/...')
#3 /home/jayhouse/public_html/getsfreehugs/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/jayhouse/...')
#4 /home/jayhouse/public_html/getsfreehugs/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/jayhouse/...')
#5 /home/jayhouse/public_html/getsfreehugs/_protected/app/system/modules/user/controllers/MainController.php(94): PH7\Framework\Mvc\Controller\Controller->output()
#6 [internal function]: PH7\MainController->login()
#7 /home/jayhouse/public_html/getsfreehugs/_protected/framework/Mvc/Router/FrontController.class.php(661): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array)
#8 /home/jayhouse/public_html/getsfreehugs/_protected/framework/Mvc/Router/FrontController.class.php(619): PH7\Framework\Mvc\Router\FrontController->runController()
#9 /home/jayhouse/public_html/getsfreehugs/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter()
#10 /home/jayhouse/public_html/getsfreehugs/index.php(46): PH7\Bootstrap->run()
#11 {main}

**Comment by pH-7** [comment]
FYI, the issue has been fixed here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/233df1a631971d73e0cdd6382823f34f669fc4a5

**Comment by Mj5333** [comment]
It still is the problem.


Mary Johnson 

On Sunday, October 9, 2022, 4:49 PM, ♚ PH⑦ de Soria™♛ ***@***.***> wrote:




FYI, the issue has been fixed here: 233df1a
