### ISSUE TITLE
Blank page after install

### ISSUE THREAD

**Issue by exander77** [pH7Software/pH7-Social-Dating-CMS#105]
I have blank page after install, no error anywhere, return code 200.

PHP 5.6 on Debian under Nginx.

**Comment by exander77** [comment]
After turning on development mode I get:

`Fatal error: Class 'PH7\Framework\Core\Kernel' not found in /var/_protected/framework/Server/Server.class.php on line 52`

The file /var/_protected/framework/Core/Kernel.class.php exists.

**Comment by exander77** [comment]
It could be related to: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/32

**Comment by pH-7** [comment]
Please remove `_protected/framework/Core/Kernel.class.php` and `_protected/framework/Core/License.class.php` and load it again.
Please make sure that your server doesn't block external websites. 
I answered to that ticket as well https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/32#issuecomment-266912330
