### ISSUE TITLE
This script suck

### ISSUE THREAD

**Issue by MarceloRojasOlivos** [pH7Software/pH7-Social-Dating-CMS#1053]
This script is a real example of a poorly made program. They don't even load in a service like XAMPP or LAMPP to test...
It is very poorly documented installation and there are no error files.
On the Hostinger server it simply does not load the initial page and does not indicate the possible error and where to find it...
There is also no access to previous versions.
The one who makes a good installation script for Softacoulus or Fantastico is assured a prize...

**Comment by pH-7** [comment]
I think you have some issues with your PHP environment. The server requirements can be found at https://ph7builder.com/doc/en/requirements

Thank you for sharing your frustrations, but it's a bit hard to help you here with only little information about the reason/error why it doesn't work for you.

**Comment by ediblepeachey** [comment]
I'm just getting going on PH7.  Did you find a way to load using XAMPP?
