### ISSUE TITLE
after comlete installation only white screen

### ISSUE THREAD

**Issue by AleksandarLindic** [pH7Software/pH7-Social-Dating-CMS#1057]
**Describe the bug**

Nach beendeter Installation und entfernen des _install Verzeichniss nur Weisser Bildschirm
After finished installation and removing the _install directory only white screen

**To Reproduce**

1. pH7 17.2.1 auf gehostetem Server mit PHP8.1 installiert
          pH7 17.2.1 installed on hosted server with PHP8.1
2. Nach erfolgreicher Installation und Wahl des gewünschten Layouts (empfohlenes Layout gewählt), wie verlangt
das _install Verzeichniss entfernt.
          after successful installation and selection of the desired layout (recommended layout selected), as requested
          removed the _install directory.
3. Eine Email wurde durch pH7 gesendet, mit allen wichtigen Informationen und der Bestätigung Ph7 sei vollständig installiert worden.
          An email was sent by pH7 with all the important information and confirmation that Ph7 was fully installed.
4. Danach war nur noch ein weisser Bildschirm ohne Inhalt zu erreichen, egal ob als ../admin123 oder direkt zum ph7.
          after that only a white screen without content was reachable, no matter if as ../admin123 or directly to ph7.
5. In php die ausgabe von Fehlern aktiviert. >> Keine Fehlerausgabe.
          in php the output of errors activated. >> No error output.
6. Im Browser Code untersucht. >> Es wird nur: <html><head></head><body></body> </html> ausgegeben.
          in the browser code examined. >> Only: <html><head></head><body></body> </html> is output.
7. php verion 8.0 und 7.4 auch probiert. Mit aktivierten GD und ZIP Erweiterungen >> das selbe Ergebniss.
          php verion 8.0 and 7.4 also tried. With enabled GD and ZIP extensions >> the same result.
8. Erneut Datenbank zurück gesetzt und _constants.php gelöscht um Neu zu installieren.  >> selbes Ergebniss.
          reset database again and deleted _constants.php to reinstall.  >> Same result.

Wer kann mir helfen?
Ho can help me?

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)

**Comment by 2dned** [comment]
go to file _protected/app/configs/config and open

[mode]
; 'production' or 'development'
environment = development

change the production to development as above, save close.
Now it will show errors related to the site as to why you get white screen.

**Comment by AleksandarLindic** [comment]
thank youIt's a long time ago.may i trye again....Freundliche GrüsseAleksandar Lindic...find ich no cool!  www.gogosing.chKaraoke Jukebox mit mega Sound und Licht. Eifach istecke, Internetverbindung mache und los lege!Let's get out!...Am 27.09.22, 11:47 schrieb 2dned ***@***.***>:

   
  go to file _protected/app/configs/config and open 
  [mode] ; 'production' or 'development' environment = development 
  change the production to development as above, save close. Now it will show errors related to the site as to why you get white screen.

**Comment by mkmorfius** [comment]
Here is what I did:
- manually instaled ph7builder (100% successful)
- tryed to open main page / admin page - I get 500 error
- changed "mode" in _protected/app/configs/config.ini to development

Now, I can see this FatalError:

Fatal error: Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, bool given in /home/poljubcki/public_html/_protected/framework/Server/Server.class.php:165 Stack trace: #0 /home/poljubcki/public_html/_protected/framework/Server/Server.class.php(165): strtolower() #1 /home/poljubcki/public_html/_protected/app/Bootstrap.php(78): PH7\Framework\Server\Server::isRewriteMod() #2 /home/poljubcki/public_html/index.php(45): PH7\Bootstrap->run() #3 {main} thrown in /home/poljubcki/public_html/_protected/framework/Server/Server.class.php on line 165

Who can help me with this error?

**Comment by NSXsystems** [comment]
Rename sample.htaccess to just .htaccess

It's that simple. However, there are more errors down the line that I'm trying to work out.

**Comment by 2dned** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/1032

**Comment by pH-7** [comment]
Thanks very much for reporting this one!

This issue has been fixed in git commit https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/88c58904a65c015309fab4bef9a3f4d9118a0cd5
The patch is already available in the `18.x` branch and will be available in the next release build.
