### ISSUE TITLE
Possible bug with gzip

### ISSUE THREAD

**Issue by nileshd** [pH7Software/pH7-Social-Dating-CMS#106]
After a new install on php 7.0.14, none of the styles are showing up in the size. When I look at the source code the rendering of addresses such as 

> /asset/gzip/?t=css&d=static/css/js/jquery/box/&f=box.css

 are not rendering any css code.. the output is only

> /*Cached on 17 Dec 2016 22:30:04*/

and nothing else.

**Comment by nileshd** [comment]
Found the issue.. i was running ph7cms inside docker... but i was accessing through my host at localhost.. but when it curled within the docker for localhost:92, that was not valid as port 80 had been mapped to 92.

**Comment by pH-7** [comment]
:+1: thanks for posting your solution. It might helps for others.
Also, please make sure you deleted all static files cached in `/_protected/data/cache/pH7_static/*`, otherwise the static files (css/js) won't be updated.
