### ISSUE TITLE
How Payment module be remove complete?

### ISSUE THREAD

**Issue by GizehFire** [pH7Software/pH7-Social-Dating-CMS#1060]
How can the "payment" module be removed completely?

Thank you

**Comment by mkmorfius** [comment]
How did you even managed to install this script and make it work? Any clue? All I get is error 500 page after install thru "softaculus" and I also tried manual install. Both ate "successful" but main page returns error  500 and admin page also return 500.

Can you share how did you install ph7builder?

**Comment by pH-7** [comment]
> How can the "payment" module be removed completely?
> 
> Thank you

Excellent question!

You will need to select the "Regular (Free)" membership as the default one.

<img width="734" alt="Screen Shot 2022-10-10 at 4 30 33 pm" src="https://user-images.githubusercontent.com/1325411/194826480-e098901b-4df0-4985-b4bc-5825879229f4.png">

And removing any "Paid" memberships through the Billing module

<img width="502" alt="Screen Shot 2022-10-10 at 4 32 21 pm" src="https://user-images.githubusercontent.com/1325411/194826489-a655ad89-e305-4ef8-9814-39189954859d.png">
