### ISSUE TITLE
SOLVED - HTTP ERROR 500: Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, bool given in /home/XYZ/public_html/_protected/framework/Server/Server.class.php:168

### ISSUE THREAD

**Issue by mkmorfius** [pH7Software/pH7-Social-Dating-CMS#1061]
I'm working on this 500 error page for two days now...

I maneged to get an error response instead of error 500 page...

Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, bool given in /home/poljubcki/public_html/_protected/framework/Server/Server.class.php:165 Stack trace: #0 /home/poljubcki/public_html/_protected/framework/Server/Server.class.php(165): strtolower(false) #1 /home/poljubcki/public_html/_protected/app/Bootstrap.php(78): PH7\Framework\Server\Server::isRewriteMod() #2 /home/poljubcki/public_html/index.php(45): PH7\Bootstrap->run() #3 {main} thrown in /home/poljubcki/public_html/_protected/framework/Server/Server.class.php on line 165

Can someone take a look at the code, coz here is where it stops for me...

Big thank you

**Comment by mkmorfius** [comment]
SOLVED!

I had to hide some code in _protected/framework/server/Server.class file....

I had to comment this part:

    /**
     * Check if Apache's mod_rewrite is installed.
     *
     * @return bool
     */
    public static function isRewriteMod(): bool
    {
#        // Check if mod_rewrite is installed and is configured to be used via .htaccess
#        if (!strtolower(getenv('HTTP_MOD_REWRITE')) === 'on') {
#            $sOutputMsg = 'mod_rewrite Works!';
#
#            if (Uri::getInstance()->fragment(0) === 'test_mod_rewrite') {
#                exit($sOutputMsg);
#            }
#
#            $sPage = @file_get_contents(PH7_URL_ROOT . 'test_mod_rewrite');
#            return $sPage === $sOutputMsg;
#        }
#
        return true;
    }

------------------------------

My site is now working, juhuuuuu :)

**Comment by digiloo** [comment]
Hi group.

I can fix your current and coming problems for a minor cost.

Regards
***@***.***

**Comment by pH-7** [comment]
@mkmorfius FYI, a patch has been pushed for the issue you have mentioned - See here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/88c58904a65c015309fab4bef9a3f4d9118a0cd5
And the changes will be also available in the next version.

Thank you so much for reporting this issue Matija! And thank you for helping the community by posting your solution. This is awesome!
