### ISSUE TITLE
Disclaimer enalbe error

### ISSUE THREAD

**Issue by Shearsmith1337** [pH7Software/pH7-Social-Dating-CMS#1064]
Hello guys, 

When I enable Disclamer, I receive this error:

`Message:	/home/site/public_html/dating/templates/themes/datelove/tpl/disclaimer-dialog.inc.tpl file does no exist.
File:	/home/site/public_html/dating/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php
Line:	339
Trace:	

#0 /home/site/public_html/dating/_protected/data/cache/pH7tpl_compile/user_a36188d696d9f9e274ceddf9aee407aa/base/main/layout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('disclaimer-dial...', '/home/site/...')
#1 /home/site/public_html/dating/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/site/...')
#2 /home/site/public_html/dating/_protected/data/cache/pH7tpl_compile/public_main/datelove/layout.cpl.phplayout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/site/...')
#3 /home/site/public_html/dating/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(358): require('/home/site/...')
#4 /home/site/public_html/dating/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/site/...')
#5 /home/site/public_html/dating/_protected/app/system/modules/user/controllers/MainController.php(85): PH7\Framework\Mvc\Controller\Controller->output()
#6 [internal function]: PH7\MainController->index()
#7 /home/site/public_html/dating/_protected/framework/Mvc/Router/FrontController.class.php(661): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array)
#8 /home/site/public_html/dating/_protected/framework/Mvc/Router/FrontController.class.php(619): PH7\Framework\Mvc\Router\FrontController->runController()
#9 /home/site/public_html/dating/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter()
#10 /home/site/public_html/dating/index.php(46): PH7\Bootstrap->run()
#11 {main}

V17

i found in **templates\themes\datelove\disclaimer.inc.tpl**
`{def_main_auto_include}``

Where can I found **disclaimer-dialog.inc.tpl** ?

Thanks in advance

**Comment by pH-7** [comment]
Thanks for reporting this issue @Shearsmith1337.

This issue has been already fixed in the default branch `18.x` and will be available in the next release archive.

In the meantime, if you aren’t using the **base** theme, please rename the disclaimer file as shown here on the patch: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/233df1a631971d73e0cdd6382823f34f669fc4a5


Have a great day! Thank you!
