### ISSUE TITLE
Home page loading indefinitely after installation and stays blank 

### ISSUE THREAD

**Issue by AchrafLaabassi** [pH7Software/pH7-Social-Dating-CMS#1067]
Hello,

I have an issue after the installation,
When i try to access the homepage trough localhost, the page signals that it is loading but never gives any response

![Screenshot 2022-11-02 23 35 10](https://user-images.githubusercontent.com/35596346/199615567-ad6ec2cb-b822-4b4b-a271-b805cadd03e5.png)

When i try to access with index.php, i have this error : 

![image](https://user-images.githubusercontent.com/35596346/199617012-bf2be5a2-d552-4796-81ec-0eae776048b2.png)

I did try to comment the lines after 164 in Server.class.php as discussed here before

Could you please advise on what to do to get the home page working ?
thanks!

**Comment by 2dned** [comment]
Try put into 'development' Mode via config file /_protected/app/configs/config
See if it loads or gives errors

**Comment by AchrafLaabassi** [comment]
Hello,
It's already in developpement mode 
![image](https://user-images.githubusercontent.com/35596346/199684603-48995382-dab4-40b4-b495-8f03d860161b.png)
BR,

**Comment by 2dned** [comment]
i see your using php8.1 can you change it php 8.0? think that might be the issue

**Comment by AchrafLaabassi** [comment]
i removed php8.1 and installed php7.4 as it is the required version, still the same issue:

![image](https://user-images.githubusercontent.com/35596346/199835432-a5a05b13-6357-4232-b783-46884663037c.png)


![image](https://user-images.githubusercontent.com/35596346/199835544-85516e6b-e2ce-4724-9d78-9de25f0ce363.png)

**Comment by AchrafLaabassi** [comment]
i think it has mainly to do with this trace i get on index.php (second screenshot)

Trace:	
#0 /home/achraflaabassi/projects/pH7Builder-17.2.1/_protected/framework/Mvc/Router/FrontController.class.php(870): PH7\Framework\Mvc\Router\FrontController->notFound()
#1 /home/achraflaabassi/projects/pH7Builder-17.2.1/_protected/framework/Mvc/Router/FrontController.class.php(88): PH7\Framework\Mvc\Router\FrontController->indexFileRouter()
#2 /home/achraflaabassi/projects/pH7Builder-17.2.1/_protected/framework/Pattern/Singleton.trait.php(31): PH7\Framework\Mvc\Router\FrontController->__construct()
#3 /home/achraflaabassi/projects/pH7Builder-17.2.1/_protected/app/Bootstrap.php(92): PH7\Framework\Mvc\Router\FrontController::getInstance()
#4 /home/achraflaabassi/projects/pH7Builder-17.2.1/index.php(45): PH7\Bootstrap->run()
#5 {main}

Do you have an idea of where this might come from ?
Thanks !

**Comment by AchrafLaabassi** [comment]
I do finally get this message when installing a fix for the Server.class.php
![image](https://user-images.githubusercontent.com/35596346/199844762-6dbc1363-9a73-4d80-bb53-cc70831dbe10.png)
it says i don't have mod_rewrite, i did all the steps to enable it : 
>sudo a2enmod rewrite 
>Module rewrite already enabled


>cat /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName localhost
        <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        </Directory>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        # LogLevel debug ssl:debug

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        Include conf-available/serve-cgi-bin.conf
</VirtualHost>


i saved the file and restarted apache 2 and still the same message

**Comment by 2dned** [comment]
download this 
https://github.com/pH7Software/Rewrite-Mod-Test

Upload folder and see if Rewrite is on or off
----------------------------------------------------

Are you using virtual host ( Xampp/Wamp) or proper hosting service?
I ask so i can give better information, well try at least lol.

You could try re upload the files, I had errors like so when the ftp failed on transfer of some files.

The steps that worked for me were:
1. Install, get white page....
2. edit config to 'development'....
3. will get error related to Server.class line 165.... 
4. add the /* at begin and end of code */  ( can change at beginning before installation)

public static function isRewriteMod(): bool
    {
        // Check if mod_rewrite is installed and is configured to be used via .htaccess
        **/*i**f (!strtolower(getenv('HTTP_MOD_REWRITE')) === 'on') {
            $sOutputMsg = 'mod_rewrite Works!';

            if (Uri::getInstance()->fragment(0) === 'test_mod_rewrite') {
                exit($sOutputMsg);
            }

            $sPage = @file_get_contents(PH7_URL_ROOT . 'test_mod_rewrite');
            return $sPage === $sOutputMsg;
        }***/**

        return true;
    }
    
6. refresh and see if it works or get errors.

**Comment by pH-7** [comment]
Is your issue fixed by now?
