### ISSUE TITLE
Installation license page loops

### ISSUE THREAD

**Issue by yoshida-git-ai** [pH7Software/pH7-Social-Dating-CMS#1069]
Check three boxes and click "OK"
The same page loads and I can't proceed.

any permissions?
looking for a solution
![loop](https://user-images.githubusercontent.com/94094919/201390840-501999b9-0349-42ff-ba42-4b906df9a74d.png)

**Comment by pH-7** [comment]
Hi @yoshida-git-ai 

Could you try again on a private incognito tab or with a different web browser?
This could have be caused by some conflicts with session’s cookies.

**Comment by yoshida-git-ai** [comment]
Thanks for your advice
But that method didn't give good results.

I deleted all the folders and started over.
From sourceforge pH7Builder-17.2.1

There was a strange display on the way
pH7Builder-17.2.1/_install/data/caches/? ? ? /e7? Cannot create folder

I changed the permissions of some of them to "777"

The strange display disappeared
but it's the same screen

Need to manipulate permissions?

Or does it stop at this screen if there is a problem with MySQL?

**Comment by yoshida-git-ai** [comment]
unable to create directory /var/www/html/composer/ph7builder/_install/data/caches/smarty_compile/c9/f8/4c

Using Composer

**Comment by pH-7** [comment]
It seems you have some permission issues here. You will need to change the permissions for `var/www/html/composer/ph7builder/_install/data/caches/`  to write mode (CHMOD 777). Unix command `sudo chmod -R 777 /var/www/html/composer/ph7builder/_install/data/caches/` or through cPanel.

You could eventually ask your Web hosting company to know how you could change the permissions of some directories.

Hope it helps! Have a great day!
