### ISSUE TITLE
Error 500 when opening the site

### ISSUE THREAD

**Issue by alex7070m** [pH7Software/pH7-Social-Dating-CMS#1070]
Hello! After installation, Error 500 occurs when opening the site (php 7.4)

https://audiobook-online.com/ph7builder1721/

(a clear and concise description of what the bug is.)

**To Reproduce**

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)
![11](https://user-images.githubusercontent.com/69157204/202914647-036feaa4-41cb-45d7-b3b1-321823fb69aa.jpg)
![22](https://user-images.githubusercontent.com/69157204/202914648-227e5bee-3e77-4980-81ce-986c3e02322e.jpg)
![33](https://user-images.githubusercontent.com/69157204/202914649-1fa716c4-44e2-4f87-983b-f8b5566b4fc7.jpg)
![44](https://user-images.githubusercontent.com/69157204/202914652-718ffdc3-aef6-4dcc-92a2-7f59d1366f59.jpg)

**Comment by pH-7** [comment]
Hi @alex7070m 

There must be an internal PHP error causing this 500 page you mentioned (on your last screenshot).

Can you enable the development mode to show the PHP errors (exceptions) on the page?

To do so, please edit `_protected/app/configs/config.ini`, and replace `environment = production` to `environment = development`, and then save it.

Then, go back to your web browser and  refresh the page.
From there, you will normally see an explanatory PHP error message. Let me know the error you will see there.


Have a great day! 😊

**Comment by alex7070m** [comment]
Thanks, I did as you wrote, such error message appeared.

Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, bool given in /home/audioboo/public_html/ph7builder1721/_protected/framework/Server/Server.class.php:165 Stack trace: #0 /home/audioboo/public_html/ph7builder1721/_protected/framework/Server/Server.class.php(165): strtolower(false) #1 /home/audioboo/public_html/ph7builder1721/_protected/app/Bootstrap.php(78): PH7\Framework\Server\Server::isRewriteMod() #2 /home/audioboo/public_html/ph7builder1721/index.php(45): PH7\Bootstrap->run() #3 {main} thrown in /home/audioboo/public_html/ph7builder1721/_protected/framework/Server/Server.class.php on line 165

**Comment by pH-7** [comment]
Thank you. This issue has been already patched in `18.x` default branch https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/88c58904a65c015309fab4bef9a3f4d9118a0cd5 
However, hasn’t been release in the zip archive yet.
In your website, can you go to `protected/framework/Server/Server.class.php` and copy/paste the content of this file https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/18.x/_protected/framework/Server/Server.class.php and save it

**Comment by pH-7** [comment]
Same problem as https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/1061

**Comment by alex7070m** [comment]
Thank you! That helped.
