### ISSUE TITLE
Can this script be install in a shared Hosting

### ISSUE THREAD

**Issue by marksikaundi** [pH7Software/pH7-Social-Dating-CMS#1076]
Was looking at the script and been planning to create a dating site but unfortunately wasnt able to find a documentation for installation. in nutshell is it possible to install this script in a shared hosting like from hostinger. Your response will be helpful.

**Comment by marksikaundi** [comment]
No one is able to help me with this issue please

**Comment by pH-7** [comment]
Yes it can. With the newest version though, it will require at least PHP 8.0. Usually, pH7Builder is also available through Softaculous.

Hope it helps!
