### ISSUE TITLE
What file should I edit to add an API call after registration?

### ISSUE THREAD

**Issue by alessandrocarrese** [pH7Software/pH7-Social-Dating-CMS#1077]

**Comment by alessandrocarrese** [comment]
I would like to know what are the php files involved in the registration process.

**Comment by pH-7** [comment]
After all the registration steps? Then, it should be here: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/18.x/_protected/app/system/modules/user/controllers/SignupController.php#L126

**Comment by pH-7** [comment]
You could also do it during the registration form processing here: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/18.x/_protected/app/system/modules/user/forms/processing/JoinFormProcess.php
