### ISSUE TITLE
Internal Server Error 500 after installing [How to solve]

### ISSUE THREAD

**Issue by xinternetx** [pH7Software/pH7-Social-Dating-CMS#109]
Hi, 

I was getting that error inmediately after installing, mod_rewrite was ok and chmod was ok. 

The solution is in the .htaccess file adding a slash on line 600:

Changing this:
RewriteRule ^(.*)$ index.php?$1 [L,QSA]

for this:
RewriteRule ^(.*)$ /index.php?$1 [L,QSA]

Regards.

**Comment by pH-7** [comment]
Thanks a lot your contribution. Highly appreciated. I will move it to the wiki so might help others.

Finally, please note @xinternetx that if you would uncommented [`RewriteBase /`](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/.htaccess#L20) it would have done the same effect.
