### ISSUE TITLE
CSV Files not uploading

### ISSUE THREAD

**Issue by ippikio** [pH7Software/pH7-Social-Dating-CMS#1094]
when trying to upload a csv file, it seems like it is only importing the headers and storing these as field values.  but does not import any other data aside from the headers.  Subsequent attempts produces this error message:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'email' for key 'email'

**Comment by pH-7** [comment]
Hi @ippikio,

Thanks very much for reaching out! 
At the moment, the CSV importer cannot allow more than 1 of the same email value.

It seems that you have either partially imported some data of your CSV or you have the same email address already containing in the database.

**Comment by pH-7** [comment]
I’m now closing this one. Feel free to open a new issue if you get other questions.

Have a great day!
