### ISSUE TITLE
Admin Login Problem

### ISSUE THREAD

**Issue by Bulli77** [pH7Software/pH7-Social-Dating-CMS#1095]
**Describe the bug**

I installed pH-Social and when I tried to access the admin link, I was prompted to create an account. However, every time I try to create an account, I receive an error message stating that my email or password is incorrect.

**To Reproduce**

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)![Obraz 03 03 2023, godz  23 59](https://user-images.githubusercontent.com/105981247/222850213-7807c651-fb45-431f-b771-60815083826e.jpeg)

**Comment by Bulli77** [comment]
its fixed - just im installed newest php 8.0

**Comment by MAD-King** [comment]
I have the same issue and I am running PHP 8.0
