### ISSUE TITLE
website works and all features but is text only

### ISSUE THREAD

**Issue by mattis1231231** [pH7Software/pH7-Social-Dating-CMS#1105]
I got my site working, but now I have a problem I can log in and do everything, but I don't really have the design as it is on the sample pictures on GitHub, how can I fix this? Thank you in advance.

(i use siteground)

![Screenshot 2023-04-23 060827](https://user-images.githubusercontent.com/71038341/233819355-0996ca9e-e0cf-41b0-a18f-02244374a6f2.png)

**Comment by 2dned** [comment]
seems to be a problem in your theme. Are you using the base theme? has it been modified?

**Comment by mattis1231231** [comment]
> seems to be a problem in your theme. Are you using the base theme? has it been modified?

I'm using the base theme and haven't changed anything yet, it looked like this right after the installation and I've also tried turning off all the different cache options but that didn't help

**Comment by 2dned** [comment]
What php and apache versions are they using?
I have no idea but trying to brake down the option of what might cause the issue
Which CMS version are you using?

**Comment by mattis1231231** [comment]
i use php version 8.2 and i can't find the apache version directly the cms version i use is the latest version 17.9.1, but i have also tried to solve the problem with older versions and other versions of php but nothing seems to work.

**Comment by 2dned** [comment]
ok that is where your problem lays
The CMS doesn't like 8.2

**Comment by pH-7** [comment]
Thanks very much for reporting this @mattis1231231!

Anything in the PHP log? (PHP logs are located at _protected/data/log/pH7log/ and open the file there if any).

If there is something, could you share the error message here?

**Comment by xtodaimand** [comment]
I have exactly the same problem. I installed it via softaculous but the picture looks like him. I took php 8.0 but it doesn't work :-(

**Comment by dac2020** [comment]
I went from 8.2 to 8.0 then to 8.1 now and still get the same as above.

Always the missing gzip;

/asset/gzip/?t=js&d=static/js/&f=lang/en.js HTTP/1.1" 500

and
PHP Warning: Unknown: function "1" not found or invalid function name in Unknown on line 0

**Comment by dac2020** [comment]
Why did you close the issue without bothering to input what you did to solve the problem? It could help others.

**Comment by mattis1231231** [comment]
maybe because I haven't found a solution at all and I'm not working on it anyway

**Comment by mattis1231231** [comment]
> Why did you close the issue without bothering to input what you did to solve the problem? It could help others.

maybe because I haven't found a solution at all and I'm not working on it anyway

**Comment by dac2020** [comment]
We have no way to know that unless you tell us so appreciate you doing that :).

**Comment by mattis1231231** [comment]
> We have no way to know that unless you tell us so appreciate you doing that :).

it's a problem that i've seen quite a few people have so if i were you i might switch to another platform or you can just wait for a fix

**Comment by dac2020** [comment]
I have to agree. Holding a little hope but my associate has already given up on this.
Waiting is fine but the unknown of no one on the team ever updating anyone here is the killing aspect of this.

What a huge waste of effort, all that cool marketing and for what. 

Thanks again for the update.
