### ISSUE TITLE
Browse Users

### ISSUE THREAD

**Issue by Mateable-com** [pH7Software/pH7-Social-Dating-CMS#1108]
**Describe the bug**

Doesn't show all of the users  when you browse uses in the admin panel

Attached is the screenshot of it 
![useradmin](https://user-images.githubusercontent.com/120243085/234179372-26c59912-5c29-4456-b9d9-80f6bf861596.png)

**Comment by Mateable-com** [comment]
@pH-7 I found out that its not showing the nav bar or the footer for this.   I know you are busy.   Hit me up when you have a chance so we can fix this..   I have been looking over the code for this but couldn't find that...    I know when i do page view source it wont show all of the code it stops at login   and wont show the nav part or the footer..   

Looking forward to hear back from you on this..

**Comment by paulfrancis556** [comment]
+1 same issue here after clean version install. v17.9.1 stable download. 
![image](https://user-images.githubusercontent.com/122187116/235011291-cb009147-292e-4dfb-a1c0-b5fca45dfb99.png)

Refreshing page shows a different user each time - but only one user at a time.

**Comment by paulfrancis556** [comment]
Enabling developer mode outputs the following errors
![image](https://user-images.githubusercontent.com/122187116/235014020-fed1b663-740a-4566-8322-c3a5885c0cb1.png)

PHP v8.1

Fatal error: Uncaught TypeError: PH7\Framework\Url\Url::encode(): Argument #1 ($sUrl) must be of type string, int given, called in /var/www/clients/client1/web7/web/_protectedsecure/framework/Layout/Html/Design.class.php on line 326 and defined in /var/www/clients/client1/web7/web/_protectedsecure/framework/Url/Url.class.php:29 Stack trace: #0 /var/www/clients/client1/web7/web/_protectedsecure/framework/Layout/Html/Design.class.php(326): PH7\Framework\Url\Url::encode() #1 /var/www/clients/client1/web7/web/_protectedsecure/data/cache/pH7tpl_compile/admin123_da8e79671268676c5445b24dee646dc0/base/user/browse.cpl.php(15): PH7\Framework\Layout\Html\Design->popupLinkConfirm() #2 /var/www/clients/client1/web7/web/_protectedsecure/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(353): require('...') #3 /var/www/clients/client1/web7/web/_protectedsecure/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(15): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display() #4 /var/www/clients/client1/web7/web/_protectedsecure/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(353): require('...') #5 /var/www/clients/client1/web7/web/_protectedsecure/framework/Mvc/Controller/Controller.class.php(85): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display() #6 /var/www/clients/client1/web7/web/_protectedsecure/app/system/modules/admin123/controllers/UserController.php(92): PH7\Framework\Mvc\Controller\Controller->output() #7 [internal function]: PH7\UserController->browse() #8 /var/www/clients/client1/web7/web/_protectedsecure/framework/Mvc/Router/FrontController.class.php(656): ReflectionMethod->invokeArgs() #9 /var/www/clients/client1/web7/web/_protectedsecure/framework/Mvc/Router/FrontController.class.php(615): PH7\Framework\Mvc\Router\FrontController->runController() #10 /var/www/clients/client1/web7/web/_protectedsecure/app/Bootstrap.php(92): PH7\Framework\Mvc\Router\FrontController->runRouter() #11 /var/www/clients/client1/web7/web/index.php(45): PH7\Bootstrap->run() #12 {main} thrown in /var/www/clients/client1/web7/web/_protectedsecure/framework/Url/Url.class.php on line 29

**Comment by paulfrancis556** [comment]
@Mateable-com I found changing PHP from V8.1 down to V8.0 fixes the issue

**Comment by Mateable-com** [comment]
Its crazy it works on 8.0 but not on 8.2   but the admin browse works just fine.   there has to be away to take the admin one and make it work with the user one and modify it..  I am still trying to learn where all the files are at cause there are soooo many files.

**Comment by pH-7** [comment]
Thanks very much for reporting this @Mateable-com! I really appreciate it. I gave a fix (available here https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/005fe0633506e0f44d0c62e1f92278a6ec4a3dfd).

It will also be release in the next version of pH7Builder 😊

**Comment by pH-7** [comment]
> Its crazy it works on 8.0 but not on 8.2 but the admin browse works just fine. there has to be away to take the admin one and make it work with the user one and modify it.. I am still trying to learn where all the files are at cause there are soooo many files.

@Mateable-com @paulfrancis556 Keep PHP 8.0 for now. That's absolutely fine too! 🙂

**Comment by pH-7** [comment]
This should be completely fixed by now
