### ISSUE TITLE
Admin Login not creating session

### ISSUE THREAD

**Issue by MAD-King** [pH7Software/pH7-Social-Dating-CMS#1110]
When I try to log in to the admin area, the session is not created in the database.
When I log in to the front end as a user, the session is created.

Seems there is something wrong with the software.

**Comment by 2dned** [comment]
To set the development mode, please edit ~/_YOUR-PROTECTED-FOLDER/app/configs/config.ini
Replace “environment = production” to “environment = development” at the beginning of the file and then save it.

**Comment by pH-7** [comment]
@MAD-King Any lucks?

**Comment by MAD-King** [comment]
> @MAD-King Any lucks?

I am using my own server for this software now and it works as supposed to. Somehow, it does not like shared hosting accounts. I think this is good so. I also would rather pay for a yearly license to have better support.

**Comment by pH-7** [comment]
Great to hear this @MAD-King! What's the VPS/dedicated server specification (PHP/MySQL versions) in comparison with the shared hosting you had? 
Anyway, if you have any further issues, please have a look first at the log folder (`_protected/data/log/pH7log/ `) and enabling the development (debug) mode (enableable from Admin Panel -> Tools -> Environment Mode).

Thanks for your support supporting the software! Have a great weekend!

**Comment by pH-7** [comment]
Great to hear this @MAD-King! What's the VPS/dedicated server specification (PHP/MySQL versions) in comparison with the shared hosting you had? 
Anyway, if you have any further issues, please have a look first at the log folder (`_protected/data/log/pH7log/ `) and enabling the development (debug) mode (enableable from Admin Panel -> Tools -> Environment Mode).

Thanks for your support, and eventually supporting the software! Have a great weekend @MAD-King! 🙂

**Comment by MAD-King** [comment]
I have a Vultr server with 2Gb and PHP PHP 8.0 and MySQL MariaDB 10.4. IMO, the software should run on its own server anyway.
