### ISSUE TITLE
Stable version of pH7Builder

### ISSUE THREAD

**Issue by jameswill** [pH7Software/pH7-Social-Dating-CMS#1120]
Hi,

I was trying to download the latest version of pH7Builder i.e 17.9.1 from the website. It took me to the Github download page.https://github.com/pH7Software/pH7-Social-Dating-CMS/releases/tag/v17.9.1 From  where I have downloaded the 17.9.1 version. However on trying to install it states that the version is 18.0.0

![image](https://github.com/pH7Software/pH7-Social-Dating-CMS/assets/6368036/67b47901-d355-45d9-9f56-9098c9f22749)

On further looking into the files I found "/_protected/framework/Security/Version.class.php (Line No:54)" also states KERNEL_VERSION = '18.0.0';

I wanted to confirm which is the stable version ?

**Comment by pH-7** [comment]
Hi @jameswill! Thanks for asking! That's a great question. You can start already using `v18.0.0` right now (the one you got). This shouldn't be an issue. Let me know if you have further questions by opening a new GitHub issue.

Have a great weekend ahead!

**Comment by jameswill** [comment]
Hi,

Is there any ETA for 18.0.0 stable release ?
