### ISSUE TITLE
Your server has to be connected to the Internet in order to get your website working ph7cms

### ISSUE THREAD

**Issue by konohanaruto** [pH7Software/pH7-Social-Dating-CMS#113]
Oh, I'm having trouble with the installation,It gives the following tips:

NO INTERNET CONNECTION Whoops! 
Your server has to be connected to the Internet in order to get your website working ph7cms.

I am in the virtual machine vmware lnmp environment and I bought a linux online server test is the error, if you really want to connect to the Internet, I online server, there are public network ip and I also with the Dns domain name analysis, always so, days, how can I do in the end to be successful?

Hope someone can help me, thanks!

**Comment by polynamaude** [comment]
The system will be needing to have a live internet access for many reason including :

Getting composer package install (need to connect to the packagist service).
And possibly simple use of Google Fonts. You'll need to do some editing by yourself at first starting by changing the composer cache or backing it up on a computer with online access.
