### ISSUE TITLE
php5.6+mysql5.7+apache2.4 it always fails to install

### ISSUE THREAD

**Issue by konohanaruto** [pH7Software/pH7-Social-Dating-CMS#115]
I was based on the wamp environment is always wrong, one is prompted 'settings' table does not exist, the second is to manually create a 'settings' table, the installation of the page without content, view the database, which on the five tables, take the trouble to ask you to install Success is what version of the use, I tried ph7cms 4.0 and 5.0 and the latest 6.0 is not a success, oh, I really crazy, I hope someone can give a successful environment version, thanks!

**Comment by pH-7** [comment]
Try to run the following (in a new database) in your mysql prompt and see if you have an error.

```SQL
CREATE TABLE IF NOT EXISTS pH7_Settings (
  `name` varchar(64) NOT NULL,
  value varchar(150) DEFAULT '',
  `desc` varchar(120) DEFAULT '' COMMENT 'Informative desc about the setting',
  `group` varchar(12) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO pH7_Settings (`name`, value, `desc`, `group`) VALUES
('siteName', 'My Social Dating App', '', 'general'),
('adminEmail', @sAdminEmail, '', 'email'),
('defaultLanguage', 'en_US', '', 'language'),
('defaultTemplate', 'base', '', 'design'),
('defaultSysModule', 'user', 'The default module running by default on the index page. Recommended to keep the "user" module', 'general'),
('emailName', 'pH7CMS', '', 'email'),
('feedbackEmail', @sFeedbackEmail, '', 'email'),
('splashPage', 1, 'Use Splash Page | enable = 1 or disable = 0', 'homepage'),
('usersBlock', 1, '0 to disable or 1 to enable the profile photos on the homepage', 'homepage'),
('bgSplashVideo', 1, '0 to disable or 1 to enable the background splash video', 'homepage'),
('numberProfileSplashPage', 44, 'Number of profiles to display on the splash homepage', 'homepage'),
('fullAjaxSite', 0, 'enable = 1 or disable = 0', 'general'),
('ipLogin', '', '', 'security'),
('timeDelayUserRegistration', 1440, '1440 minutes = 24 hours (in minutes!)', 'spam'),
('timeDelayAffRegistration', 2880, '2880 minutes = 2 days (in minutes!)', 'spam'),
('timeDelaySendNote', 20, 'Waiting time to add a new note post, in minutes!', 'spam'),
('timeDelaySendMail', 3, 'Waiting time to send a new message, in minutes!', 'spam'),
('timeDelaySendComment', 5, 'Waiting time to send a new comment, in minutes!', 'spam'),
('timeDelaySendForumTopic', 5, 'Waiting time to send a new topic in the forum, in minutes!', 'spam'),
('timeDelaySendForumMsg', 10, 'Waiting time to send a reply message in the same topic, in minutes!', 'spam'),
('isCaptchaUserSignup', 0, '0 for disable or 1 for enable', 'spam'),
('isCaptchaAffiliateSignup', 0, '0 for disable or 1 for enable', 'spam'),
('isCaptchaMail', 0, '0 for disable or 1 for enable', 'spam'),
('isCaptchaComment', 0, '0 for disable or 1 for enable', 'spam'),
('isCaptchaForum', 0, '0 for disable or 1 for enable', 'spam'),
('isCaptchaNote', 0, '0 for disable or 1 for enable', 'spam'),
('mailType', 'mail', '', 'email'),
('mapType', 'roadmap', 'Choose between: ''roadmap'', ''hybrid'', ''terrain'', ''satellite''', 'map'),
('maxAgeRegistration', 99, '', 'registration'),
('minAgeRegistration', 18, '', 'registration'),
('minUsernameLength', 3, '', 'registration'),
('maxUsernameLength', 30, '', 'registration'),
('requireRegistrationAvatar', 0, '', 'registration'),
('userActivationType', 1, '1 = no activation, 2 = email activation, 3 = Manual activation by the administrator', 'registration'),
('affActivationType', 1, '1 = no activation, 2 = email activation, 3 = Manual activation by the administrator', 'registration'),
('defaultMembershipGroupId', 2, 'Default Membership Group', 'registration'),
('minPasswordLength', 6, '', 'security'),
('maxPasswordLength', 60, '', 'security'),
('isUserLoginAttempt', 1, 'Enable blocking connection attempts abusive. Enable = 1 or disable = 0', 'security'),
('isAdminLoginAttempt', 1, 'Enable blocking connection attempts abusive. Enable = 1 or disable = 0', 'security'),
('isAffiliateLoginAttempt', 1, 'Enable blocking connection attempts abusive. Enable = 1 or disable = 0', 'security'),
('maxUserLoginAttempts', 30, 'Maximum login attempts before blocking', 'security'),
('maxAffiliateLoginAttempts', 20, 'Maximum login attempts before blocking', 'security'),
('maxAdminLoginAttempts', 10, 'Maximum login attempts before blocking', 'security'),
('loginUserAttemptTime', 60, 'Time before a new connection attempt, in minutes!', 'security'),
('loginAffiliateAttemptTime', 60, 'Time before a new connection attempt, in minutes!', 'security'),
('loginAdminAttemptTime', 120, 'Time before a new connection attempt, in minutes!', 'security'),
('avatarManualApproval', 0, '0 to disable or 1 to enable ', 'moderation'),
('bgProfileManualApproval', 0, 'Background Profile Manual Approval. 0 to disable or 1 to enable ', 'moderation'),
('noteManualApproval', 0, '0 to disable or 1 to enable ', 'moderation'),
('pictureManualApproval', 0, '0 to disable or 1 to enable ', 'moderation'),
('videoManualApproval', 0, '0 to disable or 1 to enable ', 'moderation'),
('webcamPictureManualApproval', 0, '0 to disable or 1 to enable', 'moderation'),
('nudityFilter', 0, '1 = enable | 0 = disable', 'moderation'),
('defaultVideo', @sDefaultVideoUrl, 'Video by default if no video is found', 'video'),
('autoplayVideo', 1, '1 = Autoplay is enabled, 0 = Autoplay is disabled', 'video'),
('returnEmail', @sNoReplyEmail, 'Generally noreply@yoursite.com', 'email'),
('sendReportMail', 1, 'Send the Report by eMail (1 = enable, 0 = disable)', 'security'),
('siteStatus', 'enable', 'enable or maintenance', 'general'),
('smtpHostName', 'mail.example.com', '', 'email'),
('smtpPassword', 123456, '', 'email'),
('smtpPort', 25, '', 'email'),
('watermarkTextImage', 'pH7CMS.com', 'Watermark text', 'image'),
('sizeWatermarkTextImage', 2, 'Between 0 to 5', 'image'),
('banWordReplace', '[removed]',  '',  'security'),
('securityToken', 0, '0 to disable or 1 to enable the CSRF security token in the forms', 'security'),
('securityTokenLifetime', 720, 'Time in seconds to the CSRF security token. Default 720 seconds (12 mins)', 'security'),
('DDoS', 0,  '0 to disabled or 1 to enabled the DDoS attack protection',  'security'),
('isSiteValidated', 0,  '0 = site not validated | 1 = site validated',  'security'),
('cleanMsg', 0, 'Delete messages older than X days. 0 = Disable', 'pruning'),
('cleanComment', 0, 'Delete comments older than X days. 0 = Disable', 'pruning'),
('cleanMessenger', 0, 'Delete IM messages older than X days. 0 = Disable', 'pruning'),
('cronSecurityHash', 'change_this_secret_cron_word_by_yours', 'The secret word for the URL of the cron', 'automation'),
('userTimeout', 1, 'User inactivity timeout. The number of minutes that a member becomes inactive (offline)', 'automation'),
('ipApi', @sIpApiUrl, 'IP Api URL', 'api'),
('chatApi', @sChatApiUrl, 'Chat Api URL', 'api'),
('chatrouletteApi', @sChatrouletteApiUrl, 'Chatroulette Api URL', 'api'),
('googleApiKey', '', 'Google Maps API key https://developers.google.com/maps/documentation/javascript/get-api-key', 'api'),
('socialMediaWidgets', 0, 'Enable the Social Media Widgets such as Like and Sharing buttons. 0 = Disable | 1 = Enable', 'general'),
('disclaimer', 0, 'Enable a disclaimer to enter to the site. This is useful for sites with adult content. 0 = Disable | 1 = Enable', 'general'),
('cookieConsentBar', 0, 'Enable the cookie consent bar to prevent your users that your site uses cookies. 0 = Disable | 1 = Enable', 'general'),
('isSoftwareNewsFeed', 1, 'Enable the news feed. 0 = Disable | 1 = Enable', 'general');

```


Please let me know if you got an error from MySQL @konohanaruto

**Comment by pH-7** [comment]
@konohanaruto  Please let me know

**Comment by konohanaruto** [comment]
Thank you for your answer, manually create the 'settings' table after it seems to work, but I can not see any data, and the page can not be displayed properly, once again look at the database, found that the database table only only a few tables...

`mysql> show tables;
+---------------------+
| Tables_in_ph7cms   |
+---------------------+
| ph7_admins            |
| ph7_games             |
| ph7_gamescategories |
| ph7_memberships  |
| ph7_settings           |
+---------------------+
5 rows in set (0.00 sec)`

Is this the problem related to my environment? I am just a wamp environment and are not too able to understand the real meaning of 'Specific Requirement Server has to be connected to Internet'...

Here are some screenshots in my installation, as follows:

![image](https://cloud.githubusercontent.com/assets/18207841/23897976/30789162-08ea-11e7-9163-bfb3d9c0dc6e.png)

![image](https://cloud.githubusercontent.com/assets/18207841/23897987/401b7df0-08ea-11e7-9f0c-d3ad0726e1f4.png)

![image](https://cloud.githubusercontent.com/assets/18207841/23898011/57286954-08ea-11e7-8951-ccae0e12ddfd.png)

But in the end it is so ...

![image](https://cloud.githubusercontent.com/assets/18207841/23898055/8a7ea2aa-08ea-11e7-911c-614de66ac69b.png)

Look at the database, not as expected as there are a lot of database tables, just some of the initialization database tables...

![image](https://cloud.githubusercontent.com/assets/18207841/23898139/db0866a2-08ea-11e7-8489-359cd41fe5c2.png)


Which in the end is why? I have to see the relevant installation video, for example:https://www.youtube.com/watch?v=4XZw_Z_Dz8s ，Unfortunately, I and their installation results are not the same...

@pH-7

**Comment by pH-7** [comment]
Please change "production" to "development" in _protected/app/configs/config.ini (in the top on the file). THen, save it and refresh the page to see the error on the homepage and post it here

**Comment by pH-7** [comment]
Finally, did you run the SQL code I told you in my previous post?

**Comment by konohanaruto** [comment]
Yes i did try this if i just created the table without inserting the data you gave above it just as I did on the screenshot above, is a blank error page once i created the 'settings' table and inserted the data , It suggests that my wamp environment is not connected to the Internet ,this makes me unable to install the next step ...

![image](https://cloud.githubusercontent.com/assets/18207841/23943643/10c79b6c-09ab-11e7-8f76-d76738f12c00.png)

If you still just create the 'setting' table as I did before, but do not insert any data, the installation is smooth, and then I will change the configuration file environment from 'production' to 'development', it is wrong, as shown below

![image](https://cloud.githubusercontent.com/assets/18207841/23943780/8f00c242-09ab-11e7-8c12-bd9aa15129e3.png)

Yes, I really like this program, I have crazy for it, just do not know how to solve, why my installation so unfortunate, other friends seem to install very smoothly.

**Comment by konohanaruto** [comment]
Looked at the discussion before being closed, so saw the xampp, yes, it is perfect work, but wamp I still can not succeed, but I am ready to study the code, do not consider the troubles of the environment, thank you to share @pH-7 

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/95

**Comment by pH-7** [comment]
Good to know @konohanaruto 
Each time I release a new version, I test it on XAMPP, MAMP, LAMP and WAMP.
@konohanaruto  Can I know what WAMP version you use..? and with what PHP version? So I will try to make a fresh installation with that MAMP version during my weekend and see if I get the same issue than you.

**Comment by konohanaruto** [comment]
Hi,
@pH-7 

I use the wamp3.0 version and operating system is windows 7, the following is a detailed list :

WampServer Version 3.0.4 32bit
Apache 2.4.18
PHP 5.6.19
MySQL 5.7.11

Thanks.

**Comment by pH-7** [comment]
I cannot reproduce it.
BTW @konohanaruto, if you download it from Github, please make sure to run composer for installing the dependencies before proceeding to the installation.

https://github.com/pH7Software/pH7-Social-Dating-CMS#installation

**Comment by pH-7** [comment]
@konohanaruto 

Can you run in phpmyadmin of your "WampServer Version 3.0.4 32bit", the following files (in the same order I give you here)

1- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
2- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_DataGame.sql
3- https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know if you see errors from your phpmyadmin when executing those files

**Comment by jazzy1993** [comment]
Stop. Mute thread

Sent from my iPhone

On 23 Mar 2017, at 5:41 am, ♚ PH⑦ Soria ♛ <notifications@github.com<mailto:notifications@github.com>> wrote:


I cannot reproduce it.
BTW @konohanaruto<https://github.com/konohanaruto>, if you download it from Github, please make sure to run composer for installing the dependencies before proceeding to the installation.

https://github.com/pH7Software/pH7-Social-Dating-CMS#installation

**Comment by pH-7** [comment]
@konohanaruto If you still need, I'm still ready to help you 😸 
Please let me know when done so will be able to see your problem

**Comment by konohanaruto** [comment]
Hi, @pH-7  according to your method, it can work in the **wamp** environment, thank you very much~

**Comment by pH-7** [comment]
Very happy! Let me know if you need further helps ;) Take care. I will close this issue by now
