### ISSUE TITLE
Composer Installer error 

### ISSUE THREAD

**Issue by glombers** [pH7Software/pH7-Social-Dating-CMS#118]
```
 [InvalidArgumentException]
  Could not find package ph7software/ph7-social-dating-cms with stability sta
  ble.
```

**Comment by pH-7** [comment]
Hi,

Sorry the path was wrong. Please try with
```
composer create-project ph7software/ph7cms --prefer-dist website
```

**Comment by pH-7** [comment]
Fix here https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7500570b785b205a0b1e57b00360058404866b59

**Comment by glombers** [comment]
Important that someone saw it. Thanks to good support, I will continue :)

**Comment by jazzy1993** [comment]
Stop

Sent from my iPhone

On 6 Apr 2017, at 7:00 am, Webo <notifications@github.com<mailto:notifications@github.com>> wrote:


Important that someone saw it. Thanks to good support, I will continue :)

**Comment by jazzy1993** [comment]
I want to unsubscribe.

Sent from my iPhone

On 6 Apr 2017, at 9:30 am, Brendon <bdjoyce@live.com<mailto:bdjoyce@live.com>> wrote:

Stop

Sent from my iPhone

On 6 Apr 2017, at 7:00 am, Webo <notifications@github.com<mailto:notifications@github.com>> wrote:


Important that someone saw it. Thanks to good support, I will continue :)
