### ISSUE TITLE
Typo: Missing Semicolon

### ISSUE THREAD

**Issue by vectorpayton** [pH7Software/pH7-Social-Dating-CMS#134]
Bro, I don't know if this is intended to be like this or what but i find this as error..

> pH7-Social-Dating-CMS/static/PFBC/ckeditor/ckeditor_php4.php line `240`

just add a `";` after of `$js .= "CKEDITOR.replaceAll( function(textarea, config)`
and at line `396` after `$_config['on'][$eventName] = '@@function (ev)` you forgot to add `';`

same at 

> pH7-Social-Dating-CMS/static/PFBC/ckeditor/ckeditor_php5.php at line `236` and `390`

**Comment by vectorpayton** [comment]
@pH-7 :octocat:

**Comment by vectorpayton** [comment]
@pH7Software :octocat:

**Comment by pH-7** [comment]
This has been fixed.

**Comment by pH-7** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/32c57706480497898fe33cbc2590144a364d4773
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/2e87bcfd6c4db2e8421302fb62be1b6e5be320cd
