### ISSUE TITLE
Double Dolar

### ISSUE THREAD

**Issue by vectorpayton** [pH7Software/pH7-Social-Dating-CMS#135]
`_install\library\smarty\plugins\block.textformat.php` 3 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.html_checkboxes.php` 4 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.html_image.php` 2 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.html_options.php` 2 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.html_radios.php` 4 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.html_select_date.php` 8 hits of `$$_key` should be `$_key` and 2 `$$_variableName` should be `$_variableName`
`_install\library\smarty\plugins\function.html_select_time.php` 3 hits of `$$_key` should be `$_key` and 2 `$$_variableName` should be `$_variableName` and 2 hits of `$$k` should be `$k`
`_install\library\smarty\plugins\function.html_table.php` 4 hits of `$$_key` should be `$_key`
`_install\library\smarty\plugins\function.mailto.php` 1 hit of `$$var` should be `$_key`
`_install\library\smarty\sysplugins\smarty_internal_method_configload.php` 1 hit of `$$varName` should be `$varName`
`_install\library\smarty\sysplugins\smarty_internal_method_gettemplatevars.php` 1 hit of `$$varName` should be `$varName`
`_protected\app\system\modules\admin123\assets\ajax\fileManaer\elfinder.class.php` 2 hits of `$$_key` should be `$_key`
`_protected\framework\layout\tpl\engine\ph7tpl\ph7tpl.class.php` 1 hit of `$$l` should be `$l`

**Comment by vectorpayton** [comment]
@pH-7

**Comment by vectorpayton** [comment]
@pH7Software

**Comment by pH-7** [comment]
Like I told you by email, those files are from third-party libraries. It's not part of pH7CMS. It's Smarty ;) Finally, the errors you mentioned don't seem to be an error... double `$$` is possible with PHP. It means http://fr.php.net/manual/en/language.variables.variable.php
