### ISSUE TITLE
Private Photos feature & Responsive site

### ISSUE THREAD

**Issue by kisssssss** [pH7Software/pH7-Social-Dating-CMS#14]
Dear ph7 team
That would be really great if you can add a small feature where users can upload photos as private too. And they can unlock those photos for anyone they want..
In dating sites this is the most common feature and I think it should be in ph7 too.
This feature will make ph7 more awesome.

Make something only the paid members can upload private photos or make private album and can unlock to anyone they want..

2nd thing is, these days people mostly use these kind of sites on the move, so that would be much better if ph7 can become a responsive site. So that users use it on their mobile devices that would be really great.

Look forward to the ph7 team, hope they will try to help and make it a much better place for us.

I'm loving ph7, testing it these days would be so happy to see these above features in it.

Cheers

**Comment by pH-7** [comment]
Currently this feature will not be added as it is not a priority for this kind of software
