### ISSUE TITLE
Quick Search Queries

### ISSUE THREAD

**Issue by rajasekharponakala** [pH7Software/pH7-Social-Dating-CMS#148]
Hi,

There are few errors in the search filter. In pH7_Members tables, there are two fields namely 'sex' and 'matchSex'. When a user(male) want to look for a couple, it should the return the users in the database who mentioned that they are interested in couples, but this is not happening in the right way. Even though the user interested in the couple query is not returning the proper results. what I can do to alter this situation.

**Comment by pH-7** [comment]
Tested and was working fine for me.

Please make sure you have another user, with the same country and who is a (x)couple and looking for a (x)woman, then create another profile, and with that one search for I am (x)Woman and looking for (x) Couple 

Please leave blank all other fields such as city, provinces, postal codes, etc.

**Comment by rajasekharponakala** [comment]
It's still the same. What is this couple field usually meant for?

**Comment by pH-7** [comment]
Very strange. I don't have any issues on my side.. Something must be wrong. Please try either on the Quick Search or Advance Search.

When you tick Couple, it means you are looking for couple profiles (but couple profiles displayed will be displayed related to your gender, so if you are a man and tick Couple but the only couple on your dating site is looking for women, no results will be returned). Hope that makes sense

**Comment by pH-7** [comment]
@rajasekharponakala Since I didn't hear from you and as I can't replicate the problem, I will close the issue for now.

If you have further details or did a screencast showing the problem, **PLEASE reopen** this issue and I will be pleased to assist you .

Thanks @rajasekharponakala!
