### ISSUE TITLE
Install Issue Duplicate entry

### ISSUE THREAD

**Issue by Monknot** [pH7Software/pH7-Social-Dating-CMS#155]
I am at step 4/8 and when I hit submit I get this error. 
Error connecting to your database.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
I am also incredibly new at this so I may of missed something obvious.

**Comment by pH-7** [comment]
Hi @Monknot

Are you sure you install pH7CMS on a new fresh database?

If the problem persists, can you create a new database through your phpmyadmin and run the following files (in the same order) 

* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know if you see any errors from there.

Thanks

**Comment by Monknot** [comment]
Second one created this error.

CREATE TABLE IF NOT EXISTS pH7_AdminsLogSess (
  profileId tinyint(3) unsigned DEFAULT NULL,
  username varchar(40) DEFAULT NULL,
  password varchar(240) DEFAULT NULL,
  email varchar(120) DEFAULT NULL,
  firstName varchar(50) DEFAULT NULL,
  lastName varchar(50) DEFAULT NULL,
  sessionHash varchar(40) NOT NULL,
  idHash char(32) NOT NULL,
  lastActivity int(10) unsigned NOT NULL,
  location varchar(255) DEFAULT NULL,
  ip varchar(45) NOT NULL DEFAULT '127.0.0.1',
  userAgent varchar(100) NOT NULL,
  guest smallint(4) unsigned NOT NULL DEFAULT 1,
  dateTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY profileId (profileId),
  FOREIGN KEY (profileId) REFERENCES pH7_Admins(profileId),
  KEY sessionHash (sessionHash),
  KEY lastActivity (lastActivity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

MySQL said: Documentation
#1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

**Comment by pH-7** [comment]
Thanks @Monknot . I published a patch.

Can you remove your database and create a new one and do the same again with these new updated files
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

**Comment by Monknot** [comment]
# 2 rows affected.

**Comment by Monknot** [comment]
First result.

 "# MySQL returned an empty result set (i.e. zero rows)."

Second result.

"# 2 rows affected."

**Comment by Monknot** [comment]
I also get the same error at the same place in the install.

**Comment by pH-7** [comment]
So, now it works by running the both SQL files manually through PHPMyAdmin but when you go the pH7CMS installer, it doesn't work. Is that right? Please confirm @Monknot

**Comment by Monknot** [comment]
Correct.

**Comment by pH-7** [comment]
Thanks. Are you sure you installed pH7CMS with a new database (empty one) for installing pH7CMS (to make sure you won't get duplicate entries)

**Comment by Monknot** [comment]
In phpMyAdmin I typed in a new name (Several different names and times just to make sure) and hit create. I than put the name of that new database in the database field on the forum when filling it out.

**Comment by Monknot** [comment]
I am also wondering should I tag you in my responses like you do me? I am new to GitHub and tickets so I am unsure about proper etiquette.

**Comment by pH-7** [comment]
No need to tag me ;)
Thanks for those details. In order to reproduce the error, could you tell me if you tried to install pH7CMS on a local host (MAMP, XAMPP, WAMP, ...?) or with a sharing web hosting. If so, what's the name? 

Once I have the details of your environment, I will try to install pH7CMS with the same web environment.

Thanks

**Comment by Monknot** [comment]
I installed it on my Linux laptop and I placed it in my /home/var/www/html folder. I setup a LAMP environment. I am not using anything other than LAMP. I have the required mods for Apache as well.

**Comment by pH-7** [comment]
Could you tell me your MySQL version you are using? I will try to setup on LAMP env on my linux machine.

P.S. If you don't use MySQL strict mode, it should work.

**Comment by Monknot** [comment]
Server version: 5.7.20-0ubuntu0.16.04.1 - (Ubuntu)

**Comment by pH-7** [comment]
Hi installed it again with latest versions (and with Ubuntu 16 BTW).
With PHP 7.2 and with MySQL 5.7.2 and the installer went fine. Unfortunately, I couldn't reproduce any of your issues. 

Please use another host if the error persists.

**Comment by pH-7** [comment]
Hi again!

Alright, I installed it again with latest versions (and with Ubuntu 16 BTW like you mentioned).
With PHP 7.2 and with MySQL 5.7.2 and the installer went fine. Everything was OK for me.

Unfortunately, I couldn't reproduce any of your issues. 

Please use another host if the error persists. And make a new installation from the code of this Github repo  (not from Sourceforce like I said above, [I published a patch concerning the primary key](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/155#issuecomment-352209403)).

**Comment by Monknot** [comment]
OK I will try updating and see what happens. Thank you for your time and effort.
