### ISSUE TITLE
login page broken and admin123 not found

### ISSUE THREAD

**Issue by almoondsllc** [pH7Software/pH7-Social-Dating-CMS#159]
Hello,
I'm trying to install ph7csm on debian9, all seems ok but at the end the login page is broken and http://35.205.176.19/admin123 is not found. Can you post the correct configuration for apache2 ? I've this:

/etc/apache2/sites-enabled/000-default.conf

<VirtualHost *:80>

	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

and in .htaccess in /var/www/html I've this:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?$1 [L,QSA]

Thank you

UPDATE:
from the main installation directory I copied the .htaccess file in /var/www/html and in apache config file I addedd:

	<Directory "/var/www/html">
		AllowOverride All
	</Directory>

**Comment by pH-7** [comment]
Hi @almoondsllc 
Thanks for your message. I don't know what you changed, but your problem seems now resolved. Happy for you!

<img width="1045" alt="screen shot 2017-12-28 at 2 06 34 pm" src="https://user-images.githubusercontent.com/1325411/34411674-96034b36-ebd8-11e7-9e03-41d3ca534b4d.png">


Let me know if you need further help 😃

**Comment by pH-7** [comment]
I will close it for now. Please raise a new ticket if you have another problem.

Happy New Year!

**Comment by almoondsllc** [comment]
Hi and thank you.
Yeah I updated the ticket if you look and I wrote what I did:

UPDATE:
from the main installation directory I copied the .htaccess file in /var/www/html and in apache config file I addedd:
<Directory "/var/www/html">
	AllowOverride All
</Directory>

**Comment by pH-7** [comment]
Modifs to this issue: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/62e6c2d21dee3fd7cf0b317fad05d7cc2d07b981

Add more details in the doc https://ph7cms.com/doc/en/how-to-install-rewrite-module
