### ISSUE TITLE
Friend request shows twice

### ISSUE THREAD

**Issue by kisssssss** [pH7Software/pH7-Social-Dating-CMS#16]
When a user sends a friend request it shows twice in the list. The one user shows twice where we accept the friendship request.

Please fix this bug also :)

Cheers

**Comment by pH-7** [comment]
Can you shoot an email containing a screenshot with what you see?
ph7software[AT]gmail[DOT].com

**Comment by pH-7** [comment]
Never came back :cry: I'll close it for now.
