### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by jordan3250** [pH7Software/pH7-Social-Dating-CMS#160]
Stuck on page 3/6. 
Once I submit the third page I get internal 500 hundred error.

**Comment by pH-7** [comment]
Happy new year @jordan3250!

Could you open `_install/data/logs/php_error.log` and let me know what you see in there?

**Comment by jordan3250** [comment]
It could not generate an error log. Maybe shell_exec isn't functioning properly.

**Comment by jordan3250** [comment]
I am using a local host do I need a host name to continue?

**Comment by jordan3250** [comment]
https://pastebin.com/dl/Khm8yCW6 Has my php configuration.
Happy new year as well.

**Comment by pH-7** [comment]
So sorry, I really can't help you for that one. I might need more information in order to help you. I can suggest you trying to install pH7CMS on another web hosting... hopefully, it will work next time 🤞
