### ISSUE TITLE
CSS static cache issue

### ISSUE THREAD

**Issue by Calvinism** [pH7Software/pH7-Social-Dating-CMS#163]
I found that there is issue with the page loading from domain vs localhost
1. The page does not load properly unless it is first loaded from localhost. Everytime when the theme is changed, you need to clear static cache folder and load the page on localhost
2. image file on static cache is not able to load as it is pointing to localhost and not relative
eg. #logo {
   37      padding-left: 50px;
   38      background: url(../img/logo.png) no-repeat;
this on common.css become 
#logo{
padding-left:50px;
background:url(http://localhost/templates/themes/base/css/../img/logo.png)no-repeat;

**Comment by pH-7** [comment]
Hi @Calvinism 

Like you said, all static files are cached for performance reasons. 
The static files (CSS or JS) are updated if you modify them, but not if you change your domain name.

In your case, you will need to clear the static cache. Go to Admin Panel, -> Tool -> Caches -> Caches Manager and clear the static cache https://ph7cms.com/doc/en/how-to-clear-caches

or remove all folders in `_protected/data/cache/pH7_static/`

Hope that helps!
