### ISSUE TITLE
CSS static cache issue - still not solve after clearing cache

### ISSUE THREAD

**Issue by Calvinism** [pH7Software/pH7-Social-Dating-CMS#164]
I found that there is issue with the page loading from domain vs localhost

1. The page does not load properly unless it is first loaded from localhost. Everytime when the theme is changed, you need to clear static cache folder and load the page on localhost. Tried clearing the whole cache folder and loading from domain and the page is loading empty css. Have to clear the cache again and load from localhost in order for the page to load properly
2. But after loading from localhost the first time, image file on static cache is not able to load as it is pointing to localhost and not relative. I have not changed anything from css. I checked the css file is relative pointing to the file but the static file show otherwise. 
view-source:https://dating.r2dy.com/asset/gzip/?t=css&d=templates/themes/base/css/&f=common.css,style.css,layout.css,menu.css,like.css,color.css,form.css,js/jquery/rating.css,js/jquery/apprise.css,js/jquery/tipTip.css
    eg. #logo {
    37 padding-left: 50px;
    38 background: url(../img/logo.png) no-repeat;
    this on common.css become
    #logo{
    padding-left:50px;
    background:url(http://localhost/templates/themes/base/css/../img/logo.png)no-repeat;

3. In your case, you will need to clear the static cache. Go to Admin Panel, -> Tool -> Caches -> Caches Manager and clear the static cache https://ph7cms.com/doc/en/how-to-clear-caches
Tried clearing from admin is not working. Nothing happen after clicking on the link as suggested. I did remove folder in the static folder but like I said in point 1, loading from domain is not working and in point 2, loading from localhost caused issue for image not loading for css.
or remove all folders in _protected/data/cache/pH7_static/

**Comment by pH-7** [comment]
I tested as mentioned, and unfortunately I'm not able to reproduce your issue on my side.

You can also go to Admin Panel -> Tool -> Cache -> And disable the cache, "static cache",  "static data uri"
Please let me know if you have further updates. Hope that helps!

**Comment by pH-7** [comment]
I tested as mentioned, and unfortunately I'm not able to reproduce your issue on my side.

You can also go to Admin Panel -> Tool -> Cache -> Cache Settings -> And disable the cache, "Enable Static Cache",  "Enable Static Data Uri"

Please let me know if you have further updates. Hope that helps!

**Comment by Calvinism** [comment]
No that does not helps. Still have the issue for all image ref from css
