### ISSUE TITLE
Error displaying first-page on pH7CMS-10.2.0 and failed accessing admin panel ....../admin123

### ISSUE THREAD

**Issue by kangojie** [pH7Software/pH7-Social-Dating-CMS#165]
Installation seems no problem. But when loading the site, the front-page is scattered. the video background is placed up, while the people icon along  with the registration form are placed below. and when I accessed the admin panel ...../admin123, the server (local XAMPP) said "Object not found" - Error 404. When I tried to sign-up-for-free it also said 'object not found'.  But earlier version (pH7CMS-8..0) runs well.  I'm running XAMPP v3.2.2 compiled Nov.12. 2015 on widows 7. Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.0 Server at localhost Port 80:

**Comment by pH-7** [comment]
For the record, the problem was caused from URL rewriter issues.
Either, Apache mod_rewrite wasn't enabled or .htaccess file wasn't uploaded to the root directory.
