### ISSUE TITLE
[FAQ] Open Source, Restrictions (got from contact form)

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#166]
Hi there,

No, actually it's on the same license than Joomla or Wordpress and works the same.

If you create some features and modules, and decided for some reason not to contribute and share the code with me on our Github repo, it's you choice and the code or feature you added to the software will always belong to you ;)

Hope to help ;)

 

On 2018-01-15 20:34, Don't mine wrote:
> NAME: Don't mine
> 
> EMAIL: nothing@gmail.com
> 
> WEBSITE: 
> 
> COMMENT: Dear Sir/Madam
> 
> Can you please tell me, What is the meaning of open source ? If we
> develop some feature and We work for you, what is our benefit. You are
> giving source code with full restrictions. No use, No development.
> 
> Don't mine I am afraid
> Thank you
>

**Comment by polynamaude** [comment]
At first I'll give you a hint, you work for your own self. You get to use thousands of line / time of code for free in your own project. Maybe if you take the time to really read what does the GPL v2 license prohibit you'll see that it more protect you from people making money on your work than anything else. it just says that you can't sell the software you get for free (and that's great). When you pay for a GPL software, you pay for the service you get (like troubleshooting, custom development, etc) and you also pay for the time invested in answering many many complains about person who don't even try to do some troubleshooting before asking. And for now, it's still free ! (yayyy!)

**Comment by polynamaude** [comment]
And may I'll add one thing...
Do some source code digging and try to find a function limit imposed by the license code !?

I'll give a hint to those who complain, the answer is in the 'CONSTANT LICENSE_STATUS' ;-)
