### ISSUE TITLE
Wall bug (Edit button everyone can see)

### ISSUE THREAD

**Issue by kisssssss** [pH7Software/pH7-Social-Dating-CMS#17]
On the wall when we post the other user can also edit our post. This bug should be fixed. So that the other user can only delete the post from his/her wall only .

But the Edit button shows on the wall for both users the one who writes on wall and the one who receives on his/her wall. Both can see the edit button.

Edit button should see only the one who is writing on wall. But the receiver should only see the delete button on his/her wall and not the edit button.

Please review it..

Cheers

**Comment by pH-7** [comment]
Never came back :cry: I'll close it for now.
