### ISSUE TITLE
Site Already Installed error

### ISSUE THREAD

**Issue by 8373474** [pH7Software/pH7-Social-Dating-CMS#174]
Just uploaded files and went to _install. Step 2 fails and it says Site Already Installed

> Your site is already installed. If you want to redo a clean installation, please delete your "_constants.php" file and delete all the content of your database.

**Comment by pH-7** [comment]
Please remove the "_constants.php" file, and try again the installer (in another browser or with incognito mode if possible to avoid any further problems)

**Comment by 8373474** [comment]
Where is the _constants.php file?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by 8373474** [comment]
There is no "_constants.php" file in the root folder.

![screenshot](https://user-images.githubusercontent.com/36782955/37013273-cb2dfd8c-2144-11e8-9633-c55720472afe.jpg)

**Comment by 8373474** [comment]
When I try in "incognito mode" it says the following error instead:

> "/storage/ssd3/113/4844113/public_html/_protected/app/configs/config.ini" is not found.

**Comment by 8373474** [comment]
I get to the second install phase, the part where it says enter protected directory then the "Site Already Installed" error occurs.

When I go back to the root folder in the browser, it says the config error.

I assume this is because there's an issue in the install process. I've changed over all directory permissions as instructed.

Any other tips?

Or anyway to do a manual install?

Thank you very much for your assistance!

**Comment by pH-7** [comment]
Hi again!

The error message you got only shows up if _constants.php exists. Maybe you have cache issues (from is_file() or browse). 

For this reason, can you please remove the whole pH7CMS folder, re-unzip  pH7CMS zip file and make a new installation from scratch (and with a new browser session and using a new database as well).

Hope that will work!

**Comment by 8373474** [comment]
Where is the _constants.php file? I asked that before but didn't get an answer.

I downloaded the v12 update the other day.

**Comment by pH-7** [comment]
_constants.php file is generated once the website in installed.

**Comment by 8373474** [comment]
Is there anyway to do a manual install? Obviously the _constants.php file doesn't exist because the website isn't installed and it's not in the directory.

Deleting all the files and trying again doesn't help either as I've tried that over and over again and receive the same result.

**Comment by pH-7** [comment]
Manual installation is difficult to do (follow what InstallController does...).
I suggest to try with another host or with another local host environment. I see you use Windows, so the best would be to switch to another one (XAMPP, WampServer, etc)

**Comment by 8373474** [comment]
Thanks for the reply.

That sucks... checked all server requirements and they seem to be fine. It's not a Windows server, using Linux.

All good, will go try some other dating software with better support.

Thanks for your help though.

**Comment by pH-7** [comment]
Your screenshot was taken on Windows. Did many installations on Debian, openSUSE, CentOS and Fedora and never had any issues.

**Comment by polynamaude** [comment]
Sorry there, big mistake ! I don't use Windows ever since 2004. I have many system and there all done on either Debian Jessie, Stretch or at worst a Slackware. But you didn't get it right as like I said, the installation worked fine on my self-hosted server from home and I only got problem when I pushed the installation over onto my shared hosting. After I checked out the log, there was a security issue raised by mod_security and needed to change some option to ask apache to modify the some variables to make sure it does include the real domain name and not the shared one (the make REQUEST_URI match what a loopback would give on a machine with one IP and many different dns ie Vhost).

The screenshot was took over a Gnome 3
![screenshot from 2018-03-19 20-52-52](https://user-images.githubusercontent.com/21186871/37629862-96ca1724-2bb7-11e8-9164-32161d993c75.png)
 with standard GTK look
`

**Comment by 8373474** [comment]
polynamaude I think the response regarding Windows was to me... yes it was a screenshot of Windows but it was the local files after unpacking the .zip, not a screenshot of the server files which appear exactly the same BEFORE the installation process.

**Comment by polynamaude** [comment]
Oh freak sorry ! I must have been more tired than I was initially thinking to have got messed up between two completely different conversation, one that I was part of and the other I was only following.

Sincere excuses
