### ISSUE TITLE
Problem when enabling Enable Static Cache and Enable Static Minify

### ISSUE THREAD

**Issue by polynamaude** [pH7Software/pH7-Social-Dating-CMS#178]
Hi,
I had some problem with the display being a bit misplaced when I first installed on my hosting provider (namecheap).

Afterward I did some debugging and found out that some referenced weren't being properly served by the webserver even if my "htaccess" and rewriting seem working good.

So I first disabled all the caching and everything was solved.

I started back putting the options to "enabled" one by one. And the only two that need to be disabled are "Static Cache" and "Static Minify". Even if the "Enable general cache" is Enabled it works but as long those two are off.

![screenshot from 2018-03-12 03-17-27](https://user-images.githubusercontent.com/21186871/37270147-ff8f0cfc-25a3-11e8-8bc8-d5fbfe24b2fd.png)

See a screenshot enclosed.

Do you have a clue where that I could continue to look around for solving this ? Maybe if you give me more information on what exactly those two options do (like the way the interact or change the request processing).

Thanks

Polyna-Maude R.-Summerside

B.A., B.Sc, Security system specialist and threat analyst

**Comment by pH-7** [comment]
Hi @polynamaude!

How are things in Montreal? 

It might be related to what I said here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/154#issuecomment-351591753

**Finally, files that might be useful for debugging 😃** 
1. https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Layout/Gzip/Gzip.class.php (that file will fetch all static files, will compress them with gzencode and will store them in _protected/data/cache/pH7_static/ folder)

2. https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Compress/Compress.class.php (that file will minify those files).

Hope that helps! 🎉

**Comment by polynamaude** [comment]
Thanks for those hint, i'll take a deeper look and do some testing. As I'm running of a shared hosting, the problem probably reside in the use of mod_security. The comment #154 gave me a good idea that it's where the problem is..

I get some style sheetlink (<link rel="stylesheet" href=".." /> that give me a "<h1> Error 401, unauthorized </h1>". That's pretty strange as it should be a 403 for such a error type. I'll do some test with my server at home if I can repeat the problem. But I didn't have that problem at home, the only thing I did get was the usual messed up display when you don't have "mod_rewrite" setup properly.

Thanks for that quick answer, pretty fast...

Took a peek at the source code you linked me, i'll push some test later on but for now I'm only going to say that you must be a well organized person because it's really clean-coded.

Btw, we're getting a snow storm here in Montreal today, hope it's the last one of the year but still the weather is nice around 1 -2 degree over zero.

**Comment by pH-7** [comment]
H again @polynamaude! 

Might be from that... I usually don't recommend to have mod_security/mod_security2 enabled since other users already got some issues with it. Most of the shared hosts can disable it on your account if you ask then. 
Anyway, speak to them about the issue you encounter and the 401 error.


Yes, for the moment, pH7CMS needs mod_rewrite setup in order to run (there is no way to run it without mod_rewrite).

Hopefully you will find a way to get it running 🤞 
Good luck for the storm then! Stay cozy at home as much as possible then! :)

**Comment by polynamaude** [comment]
it was running but not exactly as intended and a bit more resource hungry than supposed. But now it work great with both the static cache and static minify enabled. The problem was exactly 'mod_security' that was blocking a request thinking it was some type of XSS.

I asked the hosting provider to disable the mod_security and now it's working as you intended the product to be.

![screenshot from 2018-03-16 18-34-33](https://user-images.githubusercontent.com/21186871/37547550-bc3fa5f8-2948-11e8-9ad2-b9ffa0a056c5.png)

Told them that I already had many protecting rules in my configuration including bot and bad ip list. At first they said it was going to make risky for other user of shared account but when I insisted that it was going to be less resource intensive, they agreed.

Thanks for the help.

I read somewhere that the actual facebook API doesn't work ? Maybe I can do a bit of work to get it back on track. Must be something like you using a direct Graph call for version 2.4 and they're now at a newer level or something alike. I'll take a look this weekend.

**Comment by polynamaude** [comment]
Strange, it came back but only for a part.. the static mimify that was enabled now cause me problem ! I'll take a peek if I changed something in the .htaccess file but don't think I did !
If you ever feel like taking a peek, my website is at www.polynamaude.com

**Comment by polynamaude** [comment]
Strange strange stange... I changed one line in my .htaccess ... from DirectoryIndex init.php to DirectoryIndex index.php (as I saw a RewriteRule that said index.php).

Now seem refixed !

**Comment by pH-7** [comment]
Strange 🤔 Normally your Apache config should recognize index.php as an index file by default... Anyway.. Really happy it works now 😃 

Oh yes, indeed, there is some issues with FB Connect (which is in "[connect](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules/connect)" module). 

A while ago, I updated it to a newer SDK version with their composer package https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/composer.json#L29
