### ISSUE TITLE
French langage contain small error, mainly typo. I corrected some.

### ISSUE THREAD

**Issue by polynamaude** [pH7Software/pH7-Social-Dating-CMS#180]
Hi,
I found some small error in the french langage file (mainly some mistake between %site name de% and %site name%). I fixed them, created a fork over my github account, created a branch and pushed the correction.

Is that the way to do?

I found out some deeper error that look more like translation that got made from someone who doesn't speak french from the childhood as those are the same I see quite often. For example I saw the English sentence saying :
Be on the best place to meet people!
French:
Soyez le meilleur endroit pour rencontrer des personnes!
Which would translate to
Be the best place to meet people!
So the good way of saying it should be:
Soyez à la meilleur place pour rencontrer des personnes!
or
Soyez au meilleur endroit pour rencontrer des personnes !

Nothing really of a big problem, already did quite some of the changes.
I'll give them a fix to finish during the week. Just wanted to know how to get others to benefit !

Also there was some tricky with the SQL file that some table name changed so I fixed them up too. You can see that by looking at my repo/fork https://github.com/polynamaude/pH7-Internationalization

**Comment by pH-7** [comment]
Merci beaucoup pour vos changement. Je vais y jeter un coup d'oeil ;)

**Comment by pH-7** [comment]
Once you pushed the new commits over your forked repo, you will have an option to create a new Pull Request over https://github.com/pH7Software/pH7-Internationalization/pulls

**Comment by pH-7** [comment]
Thanks for the table fixes. Indeed, I renamed them (https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/170) and forgot to update that file

**Comment by polynamaude** [comment]
I'll take a look at the option on my gitHub later on. I found some other glitches in the french file, like I said, I'll do it as the week goes by. But the other one are pure translation that we're too literal (word by word).

**Comment by vinny1962** [comment]
Well pam I will soon be helping also I would like to see this software
become very viable.


Regards Vinny

**Comment by polynamaude** [comment]
Not sure to understand the exact choice of the word you used as this software is already "viable". Completing a already "nearly" translated French language file is only a drop of water in the ocean that was required to get it where it's now. Anyway, there will always need to have some work done customising the language file for each own site, whatever language you use, for all of them.

**Comment by vinny1962** [comment]
I am sorry if you misunderstood me I have looked at PH7 for a long time and
I have seen so many different changes in the way it is being sold and
developed its confusing. I am not really a PHP programmer do not consider
myself one. I am a admin I am seeking a great solution for a social dating
site for my domain. However I see this software is open source and I made
donations I can not find the upgrade files this is not viable its confusing
to me this is what I was trying to say.  According to the online
documentations you have to login to hizup.com and download them and I never
had a chance to get licensed copy until now after a install on 3/17/2018 I
have one licensed copy.

Regards Vinny

**Comment by polynamaude** [comment]
First of all, may I suggest that you go to the good place for that kind of problems that may arise ?
This "issue" is about the French langage file and not licensing problem. Maybe open a new one or send a email.

Anyway, for the upgrade, simply do a git https://github.com/pH7Software/pH7-Social-Dating-CMS or use the "download" button to get a copy of the repo with the good version you need (latest is 12.1.2). 
Do a backup of your software installation including MySQL database. Copy over the files as indicated in the documentation or on the website.
You should now be good.
I don't think you need to get the upgrade from the hizup site as you can get them over this repository.
Also, maybe you should take more attention to the way you write your posts if you want some help back. As you said "make a donation", to make a donation imply to give, not to get something in return. At the same time, you should understand that no one has the obligation to help you out, it's a voluntary work. Everyday I see people write out that they think they changed the world by donating a "load of bread". Do you how much if would cost you to get a programmer to do a simple site installation and basic customization ? Probably around 1 000$ if you go with a big provider and 500$ with a freelance. A basic website is around 5 000$ with a graphic chart and 20 - 50 pages. You already have a big part of the job done, now you have to continue on. So if you think that your PayPal donation of the suggested amount of 40$ did something other than send a nice birthday card, then sorry about that but I have big doubt.

You can easily go out and download PoEdit (community version available on all Linux distro and Windows download available from the author site). You'll be able to edit the French language file as you'll still need to do it if you want some customisation (and it will be needed if you want to have something with a personality). I don't know where you are in your business plan or if it's a hobby thing but maybe a brainstorming will help.
If you installed your software on the 17th then you have the latest version.
Maybe you should look a bit more at what is the open-source philosophy. If you're French then Framasoft has a nice one about that.
