### ISSUE TITLE
Encoding issue in geolocation

### ISSUE THREAD

**Issue by fmonts** [pH7Software/pH7-Social-Dating-CMS#181]
I just installed it and the city is not displayed correctly. 
I set the db charset to `utf8mb4`, the http response has `content-type:text/html; charset=UTF-8`... 
What can it be?

![image](https://user-images.githubusercontent.com/8755314/37628962-b0783df4-2be4-11e8-964c-5308569836b1.png)

(it should be **Brașov**)

**Comment by fmonts** [comment]
I removed the utf8_encode function from here and it fixed the issue:
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Geo/Ip/Geo.class.php#L101

I guess for getCountry is the same

**Comment by pH-7** [comment]
Hi @fmonts!

Countries don't have such characters... So, you are save with just getCity() (don't bother with the other functions).

Have a great day in Romania!
