### ISSUE TITLE
Cron; 403 error

### ISSUE THREAD

**Issue by polynamaude** [pH7Software/pH7-Social-Dating-CMS#182]
I always get a 403 when I try to run curl for my crontab ie

/usr/bin/curl -G https://www.polynamaude.com/asset/cron/24h/Birthday/?secret_word=blowitup

**Comment by pH-7** [comment]
Hi @polynamaude!

Are you sure it is setup to be ran every 24 hours (and not less). If it runs more than once every 24 hours, it will give 403 HTTP code
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/4047bb4aaed7f22df906ad03da2e9c58dbc5830a/_protected/app/includes/classes/Cron.php#L31

Hopefu

**Comment by pH-7** [comment]
Should be a GET request; Something like below:

crontab -e
0 0 * * *  GET "https://www.polynamaude.com/asset/cron/24h/Birthday/?secret_word=blowitup"

**Comment by polynamaude** [comment]
Hi !
Thanks for the reminded that I was on my way to a solution. Found out by using Curl that my .htaccess user-agent filter was rejecting the regular "curl". So I simply added a --user-agent option to my command and "voilà" like the french guy say.

By the way the vinny user got onto the French translation thread with complains about license, donation and alot of hope. I kindly and a bit hardly reminded him that he used the word donation and it means to "give with getting something in exchange". I may have been a bit harsh by shaking him and reminding him that he should ask the questions on the appropriate thread and not many many time, expecting answer in 5 minutes turn around and added a small note with the price a line of code is worth when you have thousand of them, plus what does the "opensource" model means. I don't think you're Microsoft or that you sell thousands of license a week so all should be indulgent.

Thanks alot Mister PH

**Comment by pH-7** [comment]
Really happy you figured out! 

Thanks for this @polynamaude!

It's the first donation I got since I added the donation module and apparently it wasn't clear for him. Anyway, I replied to his email he sent to me. I really appreciate your help! :)

**Comment by polynamaude** [comment]
How long ago did you add the donation module ?

Little question, do you have any UML or something alike so I can figure out how the output override works for modules and templates ? I'm doing a new template and found out that most of the stuff seem to be residing in the modules to really customize the output.

If you've got a list of TODO for the software then maybe I can give hand. I have some free time a contract aren't coming in too fast those day.
Thanks
