### ISSUE TITLE
allow_url_fopen PHP directive needs to be enabled.

### ISSUE THREAD

**Issue by ohmygoshandy** [pH7Software/pH7-Social-Dating-CMS#184]
I am having trouble installing the software, when I go to my domain.com/_install I get the following error

                       You have 1 error(s):
1) allow_url_fopen PHP directive needs to be enabled.

![install_error](https://user-images.githubusercontent.com/37665622/37779375-a1a4e78e-2dc2-11e8-899d-6fc13947842a.JPG)

I cannot find the file necessary to complete the installation, any help would be greatly appreciated

**Comment by pH-7** [comment]
If it still doesn't work (no luck :(), I suggest you google it
