### ISSUE TITLE
[Blog|Note] Category List and Author List are duplicated + Inaccurate Number 

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#189]
On the main Blog and Note homepage, on the left column there is a Category list box, with the number of posts displayed to the right of blog category name. 
When a new post is added to a category, instead of increasing the number by 1, it adds a new line of category name followed by (1) like this....

Dating - (1)
Dating - (1)
Dating - (1)
Dating - (1)
Dating - (1)

Note: It has also the same issue with the Author column on Note homepage.

The way how it selects the categories and counts the number of posts in each category is wrong.

Places where the SQL queries have to be fixed:
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/3e7c3c8ee22cff848e333399fc0016932ce964d7/_protected/app/system/modules/blog/models/BlogModel.php#L32-L34
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/3e7c3c8ee22cff848e333399fc0016932ce964d7/_protected/app/system/modules/note/models/NoteModel.php#L31-L33
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/3e7c3c8ee22cff848e333399fc0016932ce964d7/_protected/app/system/modules/note/models/NoteModel.php#L73-L75

**Comment by pH-7** [comment]
Image Example:
<img width="240" alt="screen_shot_2018-03-28_at_22_35_45" src="https://user-images.githubusercontent.com/1325411/38057833-9eb3f496-32d8-11e8-81aa-4e553a8d40b0.png">

**Comment by polynamaude** [comment]
How long ago did you discover that there was this problem ? Have you done some work for a fix or else maybe I'll give a check.

I go work going one faster than I presumed so I'll have few hours over this week.

**Comment by pH-7** [comment]
I recently discovered that issue (although it was there for years 😂).
I will fix that one ;) Thanks a lot anyway! 😃

**Comment by pH-7** [comment]
Fixed! 🎉 The fix will be included in the next release.
