### ISSUE TITLE
Is there any place where i can see the live demo of ph7 dating cms?

### ISSUE THREAD

**Issue by FaizanZahid** [pH7Software/pH7-Social-Dating-CMS#196]
I want to test the software live so that we can make a decision.

**Comment by pH-7** [comment]
Hi @FaizanZahid!

Here https://ph7cms.com/demo (hosted by Softaculous). However, you don't have access to admin panel and some features "might" not be working properly on that demo version.

---
I used to host pH7CMS version for demo, but it was too much work for maintaining it.


Hope that helps!

**Comment by pH-7** [comment]
![Demo pH7CMS social dating CMS; screenshot](https://user-images.githubusercontent.com/1325411/38780427-e1fcf880-40cd-11e8-8e1c-e0d8c9e29da7.png)

**Comment by polynamaude** [comment]
Installation is a 15 minutes job and totally free ! Just get the sources and follow instruction !
