### ISSUE TITLE
pH7CMS Internal Server Error - something  is full 

### ISSUE THREAD

**Issue by dplay74** [pH7Software/pH7-Social-Dating-CMS#197]
pH7CMS
Internal Server Error
The server encountered an error. This is most often caused by a scripting problem, a failed database access attempt, or other similar reasons.
If you are the administrator of the site, please go to your admin panel -> Tools -> Environment Mode and set to "Development", then go back here to see the details of the error.

after checking  logfiles  i got this

AH01797: client denied by server configuration: /home/ttt/www.site.com/htdocs/index.cgi
[access_compat:error] [pid 23812]  AH01797: client denied by server configuration:/htdocs/index.pl
[log_config:warn] [pid 23266] (28)No space left on device: [client 1 AH00646: Error writing to /var/log/apache2/dating_access_log

i cleand  the disk and the rest  maybe  i need to clean something  on the  phf  folders also 
I cannot access the admin panel anymore 

whats the  best  option in this  can you help Thx

**Comment by dplay74** [comment]
![48b62bfd17b7ee9aef5a89e3313354a9](https://user-images.githubusercontent.com/37182939/39088766-5a5bda0a-45b8-11e8-9310-10da68b90c46.png)

**Comment by dplay74** [comment]
Hum, interesting ... How much disk space do you have? 1000 mb Did you upload many photos/videos..(or maybe you used too many times the fake generator profiles which download several images every time)?

no  do you  have the  path to that for  me  

 Normally, you should remove big files from /home/ttt/www.site.com/htdocs/ or contact your web hosting to see with them

Do use XAMPP/Wamp? no apache  unbuntu 

Finally, what is the error you get when you try to access to admin panel?

 i cannot reach it  at all see  screenshot

**Comment by polynamaude** [comment]
Hi,
I used to get the same error as you mentionned in your log. Does your hosting provider has "modsecurity" enabled? If so it blocks some request by error thinking it's XSS.

**Comment by polynamaude** [comment]
Also check your umask and permissions for both hosting directory and /var/log.

**Comment by polynamaude** [comment]
Check your firewall log and rules (using syslog). Are you enforcing quota on your disk / accounts) ?

Seem to be a problem with 1: log file writting by apache (check your configuration ie virtual host/apache2.conf).

2: Access denied refer to either index.pl (Perl file referenced by a module) or index.cgi (internal reference to hooks by apache cgi interface). Check in depth log for PHP trace or enable xDebug. But at first I'd go with a modsecurity or alike as it's not even treated by pH7.

You get the error page because one the request done by the CMS failed. You can use a MySQL admin interface to go and modify directly configuration to disable all caching. Should get a bit further down the road afterward.

**Comment by polynamaude** [comment]
I don't understand what you are saying...

What logs are talking about ? I don't think it's the fact that logs accumulated that could cause your problem.

Please read back what I wrote about describing your problem please.

Why would log accumulation cause such problem as you described ? What takes you to this conclusion ? Being in the software business for the passed 15 years and more but never heard such a funny idea without no proof to back it.

Have you contacted your hosting provider as they may have changed some security rules lately.
Take a look at other issue alike yours and you should get some solutions.

By reading at your writing, either you misunderstood what I told you or knowledge to use this system is lacking.

**Comment by pH-7** [comment]
@dplay74 If the issue is still occurring, a good option is to ask and search on https://stackoverflow.com/
This issue wasn't related with pH7CMS, but with your web server.

**Comment by pH-7** [comment]
I'm closing it by now. Please feel free to reopen a new issue if you have any further issues related with the software and didn't find the answer on 
- https://github.com/pH7Software/pH7-Social-Dating-CMS/issues
- https://ph7cms.com/doc/
- https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki

Good luck and have a nice day!
