### ISSUE TITLE
Video Chatting Problem

### ISSUE THREAD

**Issue by Prinz234** [pH7Software/pH7-Social-Dating-CMS#200]
Please, how can I block this advert/alert **Get your free HTML5 now here** from popping up in the Chat terminal?
And how can I make the Video Chat work or do I need to install a third-party pluggin?

Any suggestion or solution is appreciated.
Thanks.

**Comment by polynamaude** [comment]
Read the docs ! It's all explained.
RTFM !  www.ph7cms.com or _doc on your server. Don't ask damn stupid questions that we took the time to explain in the written documentation.

As you're new (created your account on the 23rd), please look around and feel the vibe, look at the type of questions written down (here, other repo, stackoverflow, etc). There's simple rules (unwritten) that states that you don't ask question that the answer are simply in the manual. And if you don't like to read book, then you know what ? We don't care ! READ THE FUCKIN MANUAL !

RTFM

Chat service is not provided by us (and you know that). Video chat is the same.

Le 27 avril 2018 10:16:33 EDT, Prinz234 <notifications@github.com> a écrit :
>Please, how can I block this advert/alert **Get your free HTML5 now
>here** from popping up in the Chat terminal?
>And how can I make the Video Chat work or do I need to install a
>third-party pluggin?
>
>Any suggestion or solution is appreciated.
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/200

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
Just tried out. Video work good, only webcam is not finished writing.

Le 27 avril 2018 10:16:33 EDT, Prinz234 <notifications@github.com> a écrit :
>Please, how can I block this advert/alert **Get your free HTML5 now
>here** from popping up in the Chat terminal?
>And how can I make the Video Chat work or do I need to install a
>third-party pluggin?
>
>Any suggestion or solution is appreciated.
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/200

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
As the doc says, you need a YouTube key.

Extract the installation archive and read through the code. It's easy ! And well documented.

Le 27 avril 2018 10:16:33 EDT, Prinz234 <notifications@github.com> a écrit :
>Please, how can I block this advert/alert **Get your free HTML5 now
>here** from popping up in the Chat terminal?
>And how can I make the Video Chat work or do I need to install a
>third-party pluggin?
>
>Any suggestion or solution is appreciated.
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/200

-- 
Polyna-Maude R.-Summerside

**Comment by Prinz234** [comment]
@polynamaude  YOUR VIBE KICKS ME OFF!
I have done customizing, so don't bother, I won't ask you anything about HTML or CSS.
I have read and researched before asking my question, and if you think am being stupid, just simply ignore the question. All the you have spent talking all these is enough to respond to my question. And if you wish to work with me, am ready to pay, but I know your next response would be,"So this guy doesn't know about UPWORK"

Thanks for the jest.

**Comment by pH-7** [comment]
Hi again!

I received your email concerning this issue and I think it's a better place to post my answer here, so anyone can take advantage of my answer.

If you use the current chat provider (which is on mywebsite.com/chat), you will have to leave the copyright notice as you can understand (they already provide it for free which is awesome).
If now, you were talking about the chatroulete (which is on mywebsite.com/chatroulette), the same applies to it.

Note that you can also change to another chat provider by just changing it through your admin panel https://ph7cms.com/how-to-change-chat/


Finally (and this might be the best with a full integration with your users), you can ask CometChat to integrate their chat with pH7CMS. They confirmed that they can integrated it with pH7CMS without any problem.
I used them years ago and they are really awesome!

Neel from their support service confirmed me that with their Premium and Platinum Edition, the integration and installation is performed by their developers (https://www.cometchat.com/pricing/self-hosted).

Hope this will help.

P.S. The Youtube Video API thing is just for the "video" module (Admin -> Mod -> Video -> Config). Nothing related with the Chat feature.

**Comment by pH-7** [comment]
You're very welcome @Prinz234!
BTW, something that can help me a lot, is to leave a nice review at https://sourceforge.net/projects/ph7socialdating/
Review page https://sourceforge.net/projects/ph7socialdating/reviews/ (you will just have to create an account in order to log a review there).

Thanks anyway! Have a great week :)

**Comment by Prinz234** [comment]
@pH-7 I just did, my username at SourceForge is: prinz23
You deserve more than just a review, and my review is not a hype but a report based on personal experience with pH7CMS.

Thanks.

**Comment by Prinz234** [comment]
@pH-7 I don't want to open a new "ISSUE" because this is not serious, but I will be glad if I get a lead on how to handle this. 
The "Profile Background Picture" is not writable and I think it has to do with Permission settings but I don't know the exact File to change its Permissions for this to work. I changed Permissions of all Folders under /data/system/modules but it's still not working. Even my LOGO is having same issue, can't change.

Thanks.

**Comment by polynamaude** [comment]
If the problem you describe was related to a file system permission then you'd normally get a error from php. Is your site in development mode ? To change your site logo, you can do so in the admin panel. Look around, there just been a issue about changing site logo that was closed.

By the way, file system permission aren't related to the CMS permissions. There's a whole level of abstraction between.

Le 8 mai 2018 03:30:09 EDT, Prinz234 <notifications@github.com> a écrit :
>@pH-7 I don't want to open a new "ISSUE" because this is not serious,
>but I will be glad if I get a lead on how to handle this. 
>The "Profile Background Picture" is not writable and I think it has to
>do with Permission settings but I don't know the exact File to change
>its Permissions for this to work. I changed Permissions of all Folders
>under /data/system/modules but it's still not working. Even my LOGO is
>having same issue, can't change.
>
>Thanks.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/200#issuecomment-387311525

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
Hi !

Just tried out to change background picture for profile. You can do so by going to "account", "edit profile" and "profile wallpaper".

For your information, operating system security and web application security are not so linked together. As a proof you normally get one user account linked to a general group when you use shared hoating but still your application will manage on it's own hundred of "user". Same for apache login (authentication) and CMS or OS login.

Same for the CMS where the main process has master access to everything but will create own limits to user. For example you can't edit other people profile except when you're admin.

If you give more information to permit to reproduce what you say then it should be easier to find if there's a problem.

Like I already explained, to consider something as possible to investigate you have to give enough information so we can reproduce what you say. It's procedure for every bug investigation. Be it Linux Kernel or a Social Dating Web Application !

Cheer !

Le 8 mai 2018 03:30:09 EDT, Prinz234 <notifications@github.com> a écrit :
>@pH-7 I don't want to open a new "ISSUE" because this is not serious,
>but I will be glad if I get a lead on how to handle this. 
>The "Profile Background Picture" is not writable and I think it has to
>do with Permission settings but I don't know the exact File to change
>its Permissions for this to work. I changed Permissions of all Folders
>under /data/system/modules but it's still not working. Even my LOGO is
>having same issue, can't change.
>
>Thanks.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/200#issuecomment-387311525

-- 
Polyna-Maude R.-Summerside
