### ISSUE TITLE
Logo image loading on tab bar and home page.

### ISSUE THREAD

**Issue by developer1sirimarketing** [pH7Software/pH7-Social-Dating-CMS#201]
Hi guys. 
The logo does not fit properly on the Home page and I can´t find how to change the logo on the browser tab (little heart on the tab).

I have tried different image sizes for the logo on Home page but it is still cutted off at the bottom of the image.  Also I have used an image with transparent backgroud but when I loaded the website the image backgroud goes black.

Please anyone?

**Comment by pH-7** [comment]
Hi @developer1sirimarketing! This should help you https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Manually-change-the-logo-of-my-website (hopefully it will ;))

**Comment by pH-7** [comment]
Hopefully the doc helps you. I will close it for now. Please reopen another ticket if you have further issues ;) Have a nice day!

**Comment by developer1sirimarketing** [comment]
Thank you.
