### ISSUE TITLE
Problem with Searching for Males looking for Males. 

### ISSUE THREAD

**Issue by spl357** [pH7Software/pH7-Social-Dating-CMS#202]
I believe this is related to the closed issue "Quick Search Queries #148"
There's a problem when searching as a Male looking for a Male. Doing this search should only return Males ALSO looking for Males, but it returns Males looking for only Females as well. This is because the search query looks something like this:

`SELECT blah blah AND matchSex LIKE '%male%'  AND sex IN ('male')`

The problem is that  '%male%' matches 'female' as well as 'male' because of the leading % wildcard, so the search returns Males looking for only Females when it shouldn't.

**Comment by pH-7** [comment]
Thanks @spl357 for the digging there! Would you be able to open a PR for it?
Otherwise, I will try to reproduce the issue and see how the fix will work.

**Comment by pH-7** [comment]
@spl357 Normally, this should be fixed by now. It's now working as inspected for me.
I removed the wildcard and used the specific MySQL function especially optimized for looking in that SET field.

Please just open a new issue if you have any similar issue with the search resuls :)

Thanks!

**Comment by pH-7** [comment]
Issue fixed. Closing it by now 🎉
