### ISSUE TITLE
Gifts

### ISSUE THREAD

**Issue by zine1959** [pH7Software/pH7-Social-Dating-CMS#208]
Can you please add gifts to send to users

**Comment by pH-7** [comment]
HI @zine1959 

For the moment, this feature isn't planned in the near future.
P.S. Remember that pH7CMS is 100% open source and any good PHP developer can add a new module into pH7CMS for sending virtual gifts between users.

Have a great day anyway! And enjoy your website.

**Comment by pH-7** [comment]
Finally, don't forget to Star the repo

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
