### ISSUE TITLE
cant login to admin

### ISSUE THREAD

**Issue by zeerprettiggestoord** [pH7Software/pH7-Social-Dating-CMS#211]
Hi, I did a fresh install of the software (downloaded from sourceforge).
Followed all the steps successfully.
Renamed the install folder just to check if everything was all right.
When using the admin login link I do not get the login stuff but this: http://prntscr.com/jmxpk4

The log files error log https://pastebin.com/W5H6JfhA 
log  https://pastebin.com/Qfs9VzYR

**Comment by pH-7** [comment]
Hi @zeerprettiggestoord!

Thanks for the details. SInce it is after the installation, can you please set the development mode.
To set the development mode, please edit ~/_YOUR-PROTECTED-FOLDER/app/configs/config.ini
Replace "environment = production" to "environment = development" at the beginning of the file and then save it.

Then, refresh the page.

**Comment by zeerprettiggestoord** [comment]
Done it.
http://prntscr.com/jn0wtb
Still no go.
Also cant register new users

**Comment by pH-7** [comment]
According to your screenshot, you didn't set correctly the development mode. That's why you still got the same page.
You moved  "[software]" on the same line where you changed the environment value.

Should be like the following
![ok-config](https://user-images.githubusercontent.com/1325411/40584501-25e87dcc-61a2-11e8-90d9-803f9e0f3164.png)

**Comment by pH-7** [comment]
Concerning your second error, it looks like the software couldn't fetch the template file. Maybe it isn't there (wasn't copy well to the directory) or you have permission issues and the template file's permission doesn't allow the software to read it. More info https://ph7cms.com/doc/en/install


Hope that helps!

**Comment by zeerprettiggestoord** [comment]
all permissions that needed change are 777, files in it are 644

the tpl files are are 644 and accountable.

Still gives 


Message: | Template Fetch Error: /home/gerrizk257/domains/lucky-you.nl/public_html/templates/themes/base/tpl/top_menu.inc.tpl
-- | --
File: | /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php
Line: | 351
Trace: | #0 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(507): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->compile() #1 /home/gerrizk257/domains/lucky-you.nl/_protected/data/cache/pH7tpl_compile/public_main/datelove/top_menu.inc.cpl.phptop_menu.inc.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('top_menu.inc.tp...', '/home/gerrizk25...') #2 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(518): require('/home/gerrizk25...') #3 /home/gerrizk257/domains/lucky-you.nl/_protected/data/cache/pH7tpl_compile/admin123_cb0e8a7590831e248d6c4a50be928211/base/mainlayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('top_menu.inc.tp...', '/home/gerrizk25...') #4 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(518): require('/home/gerrizk25...') #5 /home/gerrizk257/domains/lucky-you.nl/_protected/data/cache/pH7tpl_compile/public_main/datelove/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/gerrizk25...') #6 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(518): require('/home/gerrizk25...') #7 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Mvc/Controller/Controller.class.php(82): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/gerrizk25...') #8 /home/gerrizk257/domains/lucky-you.nl/_protected/app/system/modules/admin123/controllers/MainController.php(60): PH7\Framework\Mvc\Controller\Controller->output() #9 [internal function]: PH7\MainController->login() #10 /home/gerrizk257/domains/lucky-you.nl/_protected/framework/Mvc/Router/FrontController.class.php(566): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array) #11 /home/gerrizk257/domains/lucky-you.nl/_protected/app/Bootstrap.php(99): PH7\Framework\Mvc\Router\FrontController->runRouter() #12 /home/gerrizk257/domains/lucky-you.nl/public_html/index.php(46): PH7\Bootstrap->run() #13 {main}

what am I doing wrong?

**Comment by pH-7** [comment]
You have quite an odd issue... sadly.. and it's a bit difficult for me to debug it for you.
Can you try to edit `templates/themes/base/tpl/top_menu.inc.tpl` (open the file, add a blank space, and save it again) and see if it does something...

**Comment by zeerprettiggestoord** [comment]
Well the space trick did it!
Thank you!!

**Comment by zeerprettiggestoord** [comment]
I just noticed that the menu in top doesnot show.
http://prntscr.com/jn90oh

Should I add more blank spaces in other templates?

**Comment by zeerprettiggestoord** [comment]
I did a complete re-install with correct permissions.
Now its working again as it should.
Closing the issue

**Comment by pH-7** [comment]
Really happy to hear that @zeerprettiggestoord 
It would be great if you can log a nice review about pH7CMS :smile: https://sourceforge.net/projects/ph7socialdating/reviews/

Thanks!
