### ISSUE TITLE
suggestion for block countries

### ISSUE THREAD

**Issue by zeerprettiggestoord** [pH7Software/pH7-Social-Dating-CMS#213]
I am testing the block countries tool.
If you want to block all but 2 countries its hard to do it in the current setup.
Might I suggest to make tick boxes in front of the countries names and have a select all tick box option?
That way you can deselect the tick box of the countries you do want to have access to your website.
Also a question: if a user is in one of the blocked countries will they still be able to log in?

**Comment by pH-7** [comment]
Hi @zeerprettiggestoord 

1. This can be done easily by a good usage of your web browser and shortcuts.
- Click on the select list box 
- Do `CTRL+A` to select all countries
- then CTRL+F to find the two countries you want to allow from the list
- then BEFORE to reclick on the country you want to unselect, press on CTRL kek
- then click on the country you want to unselect (without unselecting all of them) 

You see, will get all it done very easily (just a matter of shortcuts :smiley:).

**Comment by pH-7** [comment]
Concerning your second question,
Using this option (like what the name says), the user won't be able to use your service at all.

He will see a page like the following
![page-block-country](https://user-images.githubusercontent.com/1325411/40663150-5a48608e-6358-11e8-8b19-87e5f91920f7.png)


More info https://ph7cms.com/ph7cms-12-6-released/


Hope that helps!

**Comment by pH-7** [comment]
Apparently, it was helpful.. since you read it and didn't get back to me. I'm closing it by now :smiley:
