### ISSUE TITLE
global.pot

### ISSUE THREAD

**Issue by zeerprettiggestoord** [pH7Software/pH7-Social-Dating-CMS#214]
In global.pot there is a mistake in the source file:
Your custon JavaScript code
reference= _protected/app/system/modules/admin123/forms/ScriptForm.php:31

**Comment by zeerprettiggestoord** [comment]
Typo custon should be custom. I added the comment so you could find where
it belonged

Op wo 30 mei 2018 00:25 schreef ♚ PH⑦ Soria ♛ <notifications@github.com>:

**Comment by pH-7** [comment]
That's clearer :smiley: Thanks for mentioning the typo!

**Comment by pH-7** [comment]
I added a fix for it.

**Comment by pH-7** [comment]
If you find something similar in the future, don't hesitate to let me know by opening an issue :smile:
