### ISSUE TITLE
how can i make check box options on user profile "add field" menu?

### ISSUE THREAD

**Issue by mingkan** [pH7Software/pH7-Social-Dating-CMS#217]
Dear pH,

how can i make check box options on user profile "add field" menu?

for example, I would like to ask visitor a question during registration:
what is your hobbies?
*swimming *play balls *sleeping *eating *yoga *Other ________

How can I add my code to your cms? Which files do I need to change?

Thanks.
Ming

**Comment by polynamaude** [comment]
Hi !

May I give you some hint.

You may only edit the views with the templates. That is, you can't modify underlying data processing and storage. To do so would require to modify the UserController and database tables.

I would suggest that you create a module for those needs as it's more easily done.

Maybe pH will have better to answer you.

PM

Le 10 juin 2018 16:41:56 EDT, Ming Kan <notifications@github.com> a écrit :
>Dear pH,
>
>how can i make check box options on user profile "add field" menu?
>
>for example, I would like to ask visitor a question during
>registration:
>what is your hobbies?
>*swimming *play balls *sleeping *eating *yoga *Other ________
>
>How can I add my code to your cms? Which files do I need to change?
>
>Thanks.
>Ming
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217

-- 
Polyna-Maude R.-Summerside

**Comment by mingkan** [comment]
Thanks, should I disable your module "Dating-Style Profile Page" if I create my own module for check box options on user profile "add field" menu.

Or can I just modified  "Dating-Style Profile Page" module for my own needs? and where is the file?

**Comment by mingkan** [comment]
I think your cms becomes useless if you don't have more options for users to choose. But you have some useless modulles have been built.

**Comment by polynamaude** [comment]
Hi !
First, I'm not the one who did build all of the software. You're entitled to your opinion and as I already mentionned you can build pretty easily a module for your customised need. And that what the software is made for, to give you a framework to build your site.

Maybe you should take time to learn that not everything is done by point and click. Building a website with a unique look will require you to do some coding such as template building and modules development for Joomla/Drupal/WordPress.

You must be a senior programmer with indepth knowledge of the work involved in the development to make such fact based affirmation.

Le 10 juin 2018 19:43:22 EDT, Ming Kan <notifications@github.com> a écrit :
>I think your cms becomes useless if you don't have more options for
>users to choose. But you have some useless modulles have been built.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396091325

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
Hi,

You can do as you feel ! You're the one who decide.

You could simply add a module with something like "UserFacts" and use the database script that is run when the module is enabled.

You can look in the _protected folder and you'll find a helloworld module that can guide you.

The source code is pretty much self describing when you consider the basic Design Pattern like MVC, Observer, Singleton and ORM.

There's also a small documentation that you access by _doc on your server.

It would be wise to consider that it's one man job that gave birth to what you are seeing.

pH may give you more information than me.

PM

Le 10 juin 2018 19:28:12 EDT, Ming Kan <notifications@github.com> a écrit :
>Thanks, should I disable your module "Dating-Style Profile Page" if I
>create my own module for check box options on user profile "add field"
>menu.
>
>Or can I just modified  "Dating-Style Profile Page" module for my own
>needs? and where is the file?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396090422

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
If you disable the user profile then you need to add back those questions into your modules and I'm sure it could cause problem down the road. Why do so?

If you modify the actual profile module then you'll need to manually modify your database as it's already setup.

By using a module you simply use the setup script in the enable/disable hook.

PM

Le 10 juin 2018 19:28:12 EDT, Ming Kan <notifications@github.com> a écrit :
>Thanks, should I disable your module "Dating-Style Profile Page" if I
>create my own module for check box options on user profile "add field"
>menu.
>
>Or can I just modified  "Dating-Style Profile Page" module for my own
>needs? and where is the file?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396090422

-- 
Polyna-Maude R.-Summerside

**Comment by mingkan** [comment]
Excuse me. Are you talking about \_protected\app\system\modules\cool-profile-page\? Where is "Dating-Style Profile Page" please? thanks.

**Comment by pH-7** [comment]
Hi @mingkan 
1. The join form is located in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/forms/JoinForm.php
You can add new checkbox there thanks PFBC. However, you will have to change the database structure as well. 
Then, change the [UserModel](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/models/UserModel.php) used in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/forms/processing/JoinFormProcess.php

**Comment by mingkan** [comment]
thanks, pH7.

I know it will involve databases. Would you able to add the checkbox options on next version of your cms, please?

**Comment by polynamaude** [comment]
Hi Ming,

I will add something nice to this thread.
This is a one man job that accept contribution from developpers and provide all this for free.

You can add the code by yourself, clone the repo and make a Pull Request afterward.

All the users will be happy to enjoy the work you've done too !

PM

Le 10 juin 2018 20:30:02 EDT, Ming Kan <notifications@github.com> a écrit :
>thanks, pH7.
>
>I know it will involve databases. Would you able to add the checkbox
>options on next version of your cms, please?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396094391

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
Hi!

Give PHP a try if you haven't done so. It's a quite easy language to learn with loose typing and litteral keyword that look much like english.

You'll get much more ability to customize about everything on the web except what's written in Ruby !

I'm confident that in a month you master the basic and even less with a 24 hours book.

Good luck and get back with screenshot of your site so we can create a gallery one day.

PM

Le 10 juin 2018 21:06:00 EDT, Ming Kan <notifications@github.com> a écrit :
>Thank you for your contributions, PM, ph7. Let me see my abilities.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396097116

-- 
Polyna-Maude R.-Summerside

**Comment by mingkan** [comment]
Your codes should be better than mine. Let me know the update for this. Thanks.

**Comment by polynamaude** [comment]
Hi,

Why would mine be better than yours ?
It's not something pretty hard to do. Have you took a look at the files we cited you?

You don't seem to get what I'm saying here. If you need some help, you'll find as much you'll need.

But I'm not going to take your hand to write the code and neither will I write it just because you ask. Maybe if you give a try I'll dive in to guide you.

As for pH, I think he wrote something like "We're accepting contribution from developper(you!)".

You use this free product, don't give a dime or thnks whatsoever and expect others to satisfy your need without a basic effort ?

PM

Le 10 juin 2018 23:40:37 EDT, Ming Kan <notifications@github.com> a écrit :
>Your codes should be better than mine. Let me know the update for this.
>Thanks.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396114190

-- 
Polyna-Maude R.-Summerside

**Comment by mingkan** [comment]
Sorry, I will try my best.

**Comment by polynamaude** [comment]
No sorry !
But repeat in your head what I just said. We all have jobs, rent to pay and busy life.
What's wrong with learning how to do what's needed for yourself?
It's like if I go on Joomla blog and say your product is useless, could you modify the template to suit MY OWN NEED and I expect to get a positive answer. And even more that they take a plane to install in my computer too ? You know, just jumbo hope.

PM

Le 10 juin 2018 23:58:54 EDT, Ming Kan <notifications@github.com> a écrit :
>Sorry, I will try my best.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/217#issuecomment-396116129

-- 
Polyna-Maude R.-Summerside

**Comment by mingkan** [comment]
Sorry
