### ISSUE TITLE
Which files can I completely change the contents of the homepage?

### ISSUE THREAD

**Issue by mingkan** [pH7Software/pH7-Social-Dating-CMS#218]
Which files can I completely change the contents of the front page?

I have tried to change \_protected\app\system\modules\user\views\base\tpl\main\index.guest.inc.tpl , and delete cache, it does not change in the website, even I rename the file,  it does not change in the website.

/templates/themes/base/tpl/layout.tpl works.

**Comment by polynamaude** [comment]
Hi !
You'll need to modify the core php controller (User) plus the database tables to store your results. I would suggest that you create a module. It would be more simply done.

The templates only modify the views but not the underlying data storage or processing.

Le 10 juin 2018 16:54:51 EDT, Ming Kan <notifications@github.com> a écrit :
>Which files can I completely change the contents of the front page?
>
>I have tried to change
>\_protected\app\system\modules\user\views\base\tpl\main\index.guest.inc.tpl
>, and delete cache, it does not change in the website, even I rename
>the file,  it does not change in the website.
>
>/templates/themes/base/tpl/layout.tpl works.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/218

-- 
Polyna-Maude R.-Summerside

**Comment by polynamaude** [comment]
Hi ! Look under the templates folder for the themes/base. You'll find the basic for the site and under themes/zendate, themes/datelove and themes/cartoon for the main page (Before logging in).

Hope this help !
If not maybe pH will do better.

PM

Le 10 juin 2018 16:54:51 EDT, Ming Kan <notifications@github.com> a écrit :
>Which files can I completely change the contents of the front page?
>
>I have tried to change
>\_protected\app\system\modules\user\views\base\tpl\main\index.guest.inc.tpl
>, and delete cache, it does not change in the website, even I rename
>the file,  it does not change in the website.
>
>/templates/themes/base/tpl/layout.tpl works.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/218

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
P.S. @mingkan Don't forget to star the repo https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png

**Comment by pH-7** [comment]
P.S. @mingkan Don't forget to star the repo 
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by mingkan** [comment]
where did you find splash videos in creativecommons.org?

**Comment by polynamaude** [comment]
Why that question ? It's part of the software and copyrighted. It's for use in the CMS.

Le 10 juin 2018 23:53:25 EDT, Ming Kan <notifications@github.com> a écrit :
>where did you find splash videos in creativecommons.org?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/218#issuecomment-396115538

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
Last thing @mingkan 😄 
If you like the software, can you give a nice review at https://sourceforge.net/projects/ph7socialdating/ This really help me! (you will just need to register, and [then add a review](https://sourceforge.net/projects/ph7socialdating/reviews/) :smile:

**Comment by pH-7** [comment]
@mingkan 😄 If you like the software, can you give a nice review at https://sourceforge.net/projects/ph7socialdating/ This really help me! (you will just need to register, and [then add a review](https://sourceforge.net/projects/ph7socialdating/reviews/) :smile:
