### ISSUE TITLE
After installing pH7CMS using Softaculous the site isn't loading correctly... Any feedback on this issue?

### ISSUE THREAD

**Issue by juancito82** [pH7Software/pH7-Social-Dating-CMS#220]

**Comment by pH-7** [comment]
Please also make sure with your web hosting that your web hosting plan meets the requirements https://ph7cms.com/doc/en/requirements

**Comment by polynamaude** [comment]
Hi !

Get back to us if you solved your issue so we can close the subjet !

Also, if you like the software then could you please give us a nice review on sourceforge ?
https://sourceforge.net/projects/ph7socialdating/

Also don't forget to "star" the repo !
