### ISSUE TITLE
PH7CMS FRENCH LANGUAGE PROBLEM

### ISSUE THREAD

**Issue by hotdate** [pH7Software/pH7-Social-Dating-CMS#226]
Good morning.
I just discovered PH7CMS and am pleased with your services but right now am facing a language programme.

Am in Cameroon and most of the users here are french speaking so its not easy for them to use my site.

I used the french language codes but its not complete as you specified.

If you can help me with complete french language files i will be greatful. I used the POEDIT app but its not really giving the best.

Am held up right now but am hopeful you will intervene in my favour.

Yours regards
Jefkin Nkaka

**Comment by polynamaude** [comment]
@hotdate 
Hi/Bonjour,

J'utilise la langue française avec pH7Cms et je peux vous confirmer que la traduction de l'interface frontale aux usagers est complété à plus de 99%. Il reste quelques traductions à faire pour l'administration.

Dernièrement j'ai corrigé quelques erreurs qui existaient en utilisant poEdit. C'est le meilleur outil que vous pouvez utiliser. Les autres logiciels sont pour l'usage console ou pour la programmation.

Puisque vous êtes intéressé à contribuer une version camerounaise il vous suffit de faire les modifications dans une "branch" que vous nommez en fonction du code ISO pour le français camerounais si possible.

Par la suite il vous suffira de faire un "PR" pour partager votre travail avec les autres.

Si vous aimez le logiciel alors n'oublier par un "star" sur gitHub.

Un commentaire positif sur SourceForge sera très appréciée. C'est le salaire de notre travail.

N'hésitez pas s'il y a un problème.

Ps:Soyez certain d'utiliser pH7-International.

Merci PM

**Comment by hotdate** [comment]
Comment le fair svp
Parceque la jai cru tout traduire mais certaines textes reste le meme.

**Comment by polynamaude** [comment]
@hotdate 
As-tu pris le temps de compiler le fichier global.pot pour obtenir global.po ?

Par la suite tu le télécharge vers ton site dans _protected/app/lang/fr ...

Les instructions sont fourni avec pH7Cms.

Tu dois aussi modifier config.ini et language.php

Ensuite tu édites pH7CMSLangs.sql puis tu exécutes avec phpMyAdmin.

Si tu as toujours de la difficulté alors fais un fork, branch, push puis un Pull Request. Nous pourrons regarder si quelques chose manque.

Sinon tu as la documentation sur _doc localement ou sur le site ph7cms.com

Voilà!

**Comment by hotdate** [comment]
Merci.
Je essaye voir

**Comment by polynamaude** [comment]
@hotdate 

N'oubliez pas de "star" sur gitHub et nous laisser un jolie commentaire sur sourceforge.

Et partager avec les autres usagers. C'est important.

PM

**Comment by hotdate** [comment]
Pas vraiment
Je m'ensort vraiment pas

**Comment by polynamaude** [comment]
@hotdate Je vous ai dit quoi faire pour que l'on puisse vous aider.

Créer un repo sur gitHub et envoyez y votre travail. Ainsi nous pourrons voir ce qui se passe au niveau de votre traduction.

Que voulez dire que ça ne fonctionne pas?

Si vous voulez de l'aide alors il faut commencer par soi-même faire le travail de bien expliquer notre problème.

**Comment by hotdate** [comment]
En fait suit au défaut financière j'ai pas pu acheté poedit pro

**Comment by polynamaude** [comment]
@hotdate Il n'est pas nécessaire d'avoir poedit pro. Je ne sais pas ce dont vous parler.

**Comment by polynamaude** [comment]
@hotdate Je comprends, mon erreur. Je croyais que vous étiez sous Unix/Linux. Je vais vérifier quels solutions gratuites existent pour Windows.

Par contre je suis certaine que 99% du frontal a été traduit. Est-ce que vous utiliser bien le repo pH7-Software/pH7-International ?

PM

**Comment by polynamaude** [comment]
@hotdate 
Bonne poursuite dans votre projet. Néanmoins je crois qu'il n'y a pas place à maintenir une "issue" puisqu'il y a aucun problème logiciel lié à notre système. C'est uniquement dans votre domaine privé si vous avez des difficultés financières pour l'achat de poedit ou que vous considérez inadéquat notre traduction.

Vous pouvez toujours utiliser des outils "gettext" sous Mingw ou Cygwin mais là encore, ça relève pas de nous.

PM

**Comment by hotdate** [comment]
Merci
Oui oui

**Comment by polynamaude** [comment]
@hotdate À la place de simplement répondre "oui oui", il aurait été apprécier d'y donner suite et fermer votre "issue" puisque ce n'est pas un problème logiciel.

Un nombre incalculable d'heure a été investit par un programneur solitaire pour vous permettre d'utiliser ce système et même d'en tirer profit.

Après vérification, le fichier language.php doit être traduit. Ce qui se fait avec un éditeur de texte classique.

Je crois que ce n'est pas la place pour parler de souci financier compte tenu du coût que vous auriez à payer pour un système équivalent.

Soyez sympathique et vous aurez plus de chance que les gens veulent vous aider.

PM
