### ISSUE TITLE
install

### ISSUE THREAD

**Issue by rthuey** [pH7Software/pH7-Social-Dating-CMS#230]
Hello. I am trying to take a test run to see if the software does what i want. I have installed it and get to step 7/7. When i open go to my website link i get a list of the directories. When i open go to my admin panel i get a 404 page The requested URL /ph7/admin123 was not found on this server.

I have actually did the install 5 times now and the same thing happens. Might you suggest what i am doing wrong please.

**Comment by polynamaude** [comment]
Hi !

Have you used the .htaccess file that we provide?

You seem to have DirectoryIndex On and mod_rewrite Off.

Also it would be helpful for you (if you want help) to describe your system. Because other than what I told you now, there's nothing else we can do. We can solve a problem when we can repeat it onto our system.

Thanks

Le 10 juillet 2018 13:03:42 EDT, rthuey <notifications@github.com> a écrit :
>Hello. I am trying to take a test run to see if the software does what
>i want. I have installed it and get to step 7/7. When i open go to my
>website link i get a list of the directories. When i open go to my
>admin panel i get a 404 page The requested URL /ph7/admin123 was not
>found on this server.
>
>I have actually did the install 5 times now and the same thing happens.
>Might you suggest what i am doing wrong please.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/230

-- 
Polyna-Maude R.-Summerside

**Comment by rthuey** [comment]
Hello thank you for your time.I did not touch/change any of  the files. Yet, grin. Will have to read up on the .htaccess file I am using 1and1 hosting. OS = CentOS-7 64bit with a LAMP stack.Is that the type of info you needed?-----Original Message-----

**Comment by rthuey** [comment]
Oh my, my. I just realized each time i copied the folders over from my local folder up to the server for your product. I never included all the loose files including .htacess

My question then is should i start over again or can i just move the files over now?

**Comment by rthuey** [comment]
My reference is only that .htaccess was a loose file along with the other 14 loose files outside of the 6 folders that were in the downloaded zip file that makes up the ph7 software package.

I restored my blank server snapshot, added the 15 files next to the 6 folders and ph7 installed fine. It was a complete oversite/error on my part not uploading all zipped files and folders. I can't apologize for reaching out since by doing so you were able to help me just by mentioning the .htaccess file.

 Thank you, thank you, thank you!!!

**Comment by polynamaude** [comment]
You could have got the same information from reading the docs that come with the software.

We appteciate if you could "star" our product and make a review on SourceForge.

Also close your issue when your problem is solved.

You could have solved it yourself with more attention to your acts.
