### ISSUE TITLE
Cron directory wrong path in docs

### ISSUE THREAD

**Issue by BlackTiger63** [pH7Software/pH7-Social-Dating-CMS#232]
Just installed new pH7 CMS version.
From the doc:

> All cron jobs are located in the following directory: <code>"/YOUR-PATH/YOUR-PROTECTED-FOLDER/app/system/assets/cron/"</code><br />

But there is no /assets/cron directory under the _protected directory.
So why is this stated or where are these directory's and the cronjobs which should be there according to the doc?

**Comment by BlackTiger63** [comment]
Found it, it's just a little error in the doc, wrong path mentioned.
should not be /app/system/assets/cron but /app/system/core/assets/cron/ so only the "/core/" part is missing from the online doc.
Same for the "cron list" documentation.

**Comment by pH-7** [comment]
Good catch @BlackTiger63! I will add a commit fixing it. 

P.S. For the "cron list" doc, they are correct. They aren't the file system path, but the URLs. The cron URLs are rewritten by pH7CMS Router/FrontController, so that's why they don't match the file system path.
