### ISSUE TITLE
Problems with editing site content

### ISSUE THREAD

**Issue by 000kelvin** [pH7Software/pH7-Social-Dating-CMS#236]
I have tried editing some items on the site without much success. My problem comes from identifying the file structure of the website and where all the file where info is stored.

**Comment by polynamaude** [comment]
@000kelvin Look at issue #232 to get information about the front controller that translate the request. Also #234 can help (see my explanation for modules).

**Comment by polynamaude** [comment]
@000kelvin The templates are in the template folder, you got different one for each theme and a base.

**Comment by polynamaude** [comment]
@000kelvin Also, take a look at the documentation as it give some information too. Either www.ph7cms.com or _doc on ypur local installation.

**Comment by 000kelvin** [comment]
Thanks for the info, but I guess I didn't explain myself well enough. I actually want to integrate my template with the site but the framework seems quite too confusing to grab. I don't actually even know where to start from to change stuffs like for example the registration input boxes and text on the website without editing using the admin. Thank you

**Comment by polynamaude** [comment]
@000kelvin Hi,
Like I just mentionned, you'll find the templates in /templates . There's two folder, the first (system)is used for modules customisation. The second (themes)is used for the templates themselves. The "base" is used for common inclusion into other templates.
The 3 others (cartoon, datelove and zendate) are for the 3 templates included in the cms.

The main file is "layout.tpl" and will include other file.

There's no such thing as a "template editor" but a generic text editor is available in the admin interface.

PM

**Comment by 000kelvin** [comment]
Oh, so I guess there's no way to integrate my own custom made template with the site?

**Comment by 000kelvin** [comment]
Also making major edits like adding more text fields to like the splash registration page for instance seem quite difficult. What I'm trying to achieve is editing the source codes directly.

**Comment by polynamaude** [comment]
@000kelvin If you read back what I said.... There's three templates that are supplied and you can add more.

What make you think you can't add new one?

Have you took the time to read the docs or you ask me because it's simpler ?

A complete templating system wouldn't be designed if you couldn't add new one

**Comment by polynamaude** [comment]
@000kelvin What prevent you from editing the source code?

**Comment by 000kelvin** [comment]
I have actually gotten through with the project and my issues. I was quite in a rush and I did not calm down to study the whole thing. thanks for your assistance

**Comment by pH-7** [comment]
FYI, you can edit ALL files/pages thanks the File Manager System (Admin Panel -> File/Page
<img width="1216" alt="screen_shot_2018-07-14_at_4_21_26_pm" src="https://user-images.githubusercontent.com/1325411/42725309-1ba3aef8-8782-11e8-995c-aff720f7b7b5.png">
