### ISSUE TITLE
pH7CMS in Installatron?

### ISSUE THREAD

**Issue by BlackTiger63** [pH7Software/pH7-Social-Dating-CMS#243]
pH7CMS is already in Softaculous, one of the major installation scripts.
One of the other is Installatron.

Wouldn't it be good idea to have pH7CMS also in Installatron?

It's just a feature idea, i don't know if and how many work this will cost.

**Comment by polynamaude** [comment]
There's not many person working on the project. It's what I'd call a one man full time and helpers or contributor (like myself). I'm sure Pierre Henry would be glad to get more visibility. If you can do some research and get back with information.

Thanks for the idea

**Comment by polynamaude** [comment]
I'd suggest you simply open a ticket with them. I just received a email from them and it's by user request that they choose inclusion.

The same information was in the FAQ.

Thanks for the idea again but we can't do nothing more. So you may close the issue.

Thanks for the idea.

**Comment by pH-7** [comment]
That's a great suggestion @BlackTiger63 Thanks!
Indeed, https://installatron.com/plugin/faq#recommend

**Comment by BlackTiger63** [comment]
Thank you for poiting it out guys and checking it, if it's by user request then I surely will open a ticket for you with them.

As for the idea, you're welcome.

**Comment by BlackTiger63** [comment]
Ticket send in, I will let you know the outcome if they answer.

**Comment by pH-7** [comment]
Thank you @BlackTiger63! I also created one, so there may be more luck 🤞

**Comment by BlackTiger63** [comment]
Update, got a reply from them, you might get or have gotten a similar reply:

> It's already in a list of scripts that we keep that we will be looking at when we start adding new installers. We're just getting Installatron ready to make supporting new installers easier so hopefully we can have a look at that and the others soon.

So it looks as if there is a good chance to be added. Fingers crossed indeed.

**Comment by pH-7** [comment]
Great! Thanks @BlackTiger63 for the update :)
