### ISSUE TITLE
Cron jobs work every other time (delay check condition is wrong)

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#245]

**Comment by polynamaude** [comment]
Hi @pH-7
Can you tell me more about what you found so I can check my logs ? I've noticed that they seem to run randomnly but didn't look deeper as it caused me zero problems.

**Comment by pH-7** [comment]
I'm investigating actually. I created the issue for the record and to link my commit to the task (that's why there is no much details).

It's mainly from this https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Cron/Run/Cron.class.php#L54

Every other time, it would show "This cron has already been executed." error message.

**Comment by polynamaude** [comment]
@pH-7 Wouldn't it be easier to calculate the number of seconds passed since 1970 (Unix clock), write it once with the name of the class as a file (ex: birthday1335678) when first runned then check against at the next call. If less than delay then you exit, else run and write a new one ?

**Comment by polynamaude** [comment]
Or maybe use the database (excess overhead)

**Comment by pH-7** [comment]
@polynamaude It actually already does something very similar :)

**Comment by pH-7** [comment]
Fixed:
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7e473d15ce679582f291621be2fb3b03b44549dc#diff-abcbfd84d0d61c247c9c2c03921df7ad
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/ed38525606441fa25aae1fa3549302aef6e4761e#diff-abcbfd84d0d61c247c9c2c03921df7ad
