### ISSUE TITLE
Can't access login panel locally

### ISSUE THREAD

**Issue by filipe-martins** [pH7Software/pH7-Social-Dating-CMS#249]
Hello,

I've installed PH7CMS in a web server and then copy it locally to develop and test. By the way, is it better to develop locally or directly in the web server?

I had some troubles running locally because of the path separator in windows. In the web server is Linux. It's working OK.
Now I can't go to admin panel. I've tried in several browsers.

When I put the admin page: http://localhost/carametade.tk/admin123/ > it redirects to the index.php main page. It could be something to do with Rewrite in htaccess? In the server works good.

My htaccess file has:  RewriteBase /carametade.tk/

 I've windows 10. Xamp with apache and mysql. PHP Version 7.1.19.

Thank you.
Best regards,
Luis Martins

**Comment by polynamaude** [comment]
@filipe-martins Hi,

Have you used the included .htaccess ? If so you shouldn't need to modify anything.

**Comment by filipe-martins** [comment]
Yes I use the original .htaccess changing only the line RewriteBase /carametade.tk/

But I can't access the admin panel.

**Comment by polynamaude** [comment]
@filipe-martins Hi,
Just leave the file as is. You don't change the RewriteBase unless you host under a subfolder.

Go to apache documentation and look at what does it do.

Just leave RewriteBase /
and you should be good.

**Comment by polynamaude** [comment]
@filipe-martins Also please leave us a nice review on sourceforge.

For your question about development. It is something pretty dangerous to use a live system for live development. You want to test before going live.

**Comment by polynamaude** [comment]
@filipe-martins Sorry my error. I was thinking this was the domain name. Have you configured the admin panel name as the documentation says?

We don't support windows platform. So I may not have much help. But I'll do my best to solve this.

**Comment by polynamaude** [comment]
@filipe-martins Windows get problem with case and path separator.

**Comment by filipe-martins** [comment]
Yes I've configured the admin panel correctly.

**Comment by polynamaude** [comment]
@filipe-martins What do the log says?

**Comment by filipe-martins** [comment]
In Apache error.log I don't see nothing.
I've found these in Apache Access.log:

127.0.0.1 - - [25/Jul/2018:11:41:02 +0100] "GET /carametade.tk/admin123/ HTTP/1.1" 200 24228 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

127.0.0.1 - - [25/Jul/2018:11:41:05 +0100] "GET /carametade.tk/asset/gzip/?t=css&d=static/css/js/jquery/box/&f=box.css HTTP/1.1" 200 24338 "http://localhost/carametade.tk/admin123/" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [25/Jul/2018:11:41:05 +0100] "GET /carametade.tk/asset/gzip/?t=css&d=templates/themes/datelove\\css/&f=common.css,style.css,layout.css,menu.css,like.css,color.css,form.css,js/jquery/rating.css,js/jquery/apprise.css,js/jquery/tipTip.css HTTP/1.1" 200 24599 "http://localhost/carametade.tk/admin123/" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

127.0.0.1 - - [25/Jul/2018:11:41:05 +0100] "GET /carametade.tk/asset/css/color.css HTTP/1.1" 200 24248 "http://localhost/carametade.tk/admin123/" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by polynamaude** [comment]
@filipe-martins Could you please use the file attachment option for your log file. Also give me your modified htaccess, apache logs and apache configuration file.

I will take a look at what you've got.

Also, please tell me the apache version. Not the wamp/xampp version.

Thanks

**Comment by polynamaude** [comment]
@filipe-martins Could you add the file, one by one ? So they'll be available directly in gitHub to be quoted ?

Look at the documentation for WampServer/Xampp but you should have one option of directly opening the configuration file. It should tell you where they are on the disk. Also, the version of your apache server so I can look config for 2.2 vs 2.4.

**Comment by filipe-martins** [comment]
Here goes the files individually:

[php.ini.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229445/php.ini.txt)

[my.ini.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229452/my.ini.txt)


[httpd-xampp.conf.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229442/httpd-xampp.conf.txt)

[htaccess.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229416/htaccess.txt)

[error.log](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229422/error.log)

[httpd.conf.txt](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229421/httpd.conf.txt)


[access.log](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2229415/access.log)

**Comment by polynamaude** [comment]
@filipe-martins Hi,
Would it be hard to give me the version of Apache and PHP used? Three strike out/last chance

**Comment by pH-7** [comment]
Is this issue still relevant?

**Comment by filipe-martins** [comment]
I've stopped using it because of that.
If it's fixed I'll use it in the future.

**Comment by pH-7** [comment]
I'm not really sure of your problem. Maybe, try directly with a web hosting (some good can be found [here](http://ph7cms.com/hosting)) or use WampServer instead (https://ph7cms.com/doc/en/use-it-on-a-non-linux-host).

Unfortunately, I can't really do more. There is something wrong with the server's setup... but not sure what's the cause.


Have a great day! Thanks

**Comment by filipe-martins** [comment]
Thank you.

If I find the problem I'll post it.

**Comment by pH-7** [comment]
That would be awesome @filipe-martins 

Have a great day, thanks!

**Comment by pH-7** [comment]
Hi again  @filipe-martins 😊
If you are happy with the support and the software, it will be very nice of you to give a nice review at https://sourceforge.net/projects/ph7socialdating/
