### ISSUE TITLE
PH7 CMS base script Install not work

### ISSUE THREAD

**Issue by DEATHJ0KER** [pH7Software/pH7-Social-Dating-CMS#251]
Good morning, I installed the basic version of the PH7 CMS script and found many problems. By performing a quick installation from the CPanel, you encounter several errors and can not access the administrator settings. The database is created correctly. To install the source of the script I had to use the database created by the fast installation because following the wizard returned an error when creating the database root password. Basically now it is installed, everything works, except saving the graphic settings and saving the general settings that preclude me to upload the logo and change the site name.

Thanks for your attention

**Comment by polynamaude** [comment]
@DEATHJ0KER Hi,
Could you give a bit more info? What version you use ? Have you tried to contact softaculous as this is out of our control ?

Give us some information so we can try to reproduce what you say. We have users running instances of pH7Cms over many system but the software you talked about use our software, it's not our.

Even myself do give a try of the softaculous installer when a new version get out and often can find bugs from them. I suggest you install using the archive and use the usual way.

Thanks

**Comment by polynamaude** [comment]
@DEATHJ0KER Reading more about your problem saving settings seem odd. Do you get a message of any kind ?

**Comment by polynamaude** [comment]
@DEATHJ0KER By the way, I said softaculous because cPanel doesn't give access to application installer.

**Comment by DEATHJ0KER** [comment]
The problem is simple to reproduce.
The script is installed by CPanel through Softaculous app installer offered by the host https://x10hosting.com/
Returns several errors using the php version 7.2 with default settings.

By installing the last version of the script taken from the official site, other problems are encountered, always referred to the same host service.

All the installation operations have been performed as expected, but I have found several bugs, to test from you to believe ;)

Thanks again for your availability and with the opportunity I offer you my best regards.

Inviato da Posta per Windows 10

Da: Polyna-Maude R.-Summerside
Inviato: giovedì 26 luglio 2018 04:59
A: pH7Software/pH7-Social-Dating-CMS
Cc: Valentino Decaroli; Mention
Oggetto: Re: [pH7Software/pH7-Social-Dating-CMS] PH7 CMS base script Installnot work (#251)

@DEATHJ0KER Hi,
Could you give a bit more info? What version you use ? Have you tried to contact softaculous as this is out of our control ?
Give us some information so we can try to reproduce what you say. We have users running instances of pH7Cms over many system but the software you talked about use our software, it's not our.
Even myself do give a try of the softaculous installer when a new version get out and often can find bugs from them. I suggest you install using the archive and use the usual way.
Thanks

**Comment by DEATHJ0KER** [comment]
Of course, problems are returned by the hosting service, because everything works fine locally. Thanks again for the spanking, mine was just an observation.
Great work this script, congratulations!

Inviato da Posta per Windows 10

Da: Polyna-Maude R.-Summerside
Inviato: giovedì 26 luglio 2018 05:26
A: pH7Software/pH7-Social-Dating-CMS
Cc: Valentino Decaroli; Mention
Oggetto: Re: [pH7Software/pH7-Social-Dating-CMS] PH7 CMS base script Installnot work (#251)

@DEATHJ0KER Hi !
Then I suggest you contact your hosting company and/or softaculous.
As already mentionned, we don't make the softaculous installer. The installer provided with the pH7Cms archives from SourceForge or gitHub works great.
It's easy for you to say that "it's easy to reproduce" but do you think we hold a hosting account with every provider out there ?
We provide a software for free. They use our software and that's out of our control. We don't do support for hosting provider, we do resolve problems with pH7Cms.
Have you tried using the archive to get the installation done? Do so and it will work.
Also you talked about root password and that's wrong because hosting provider like yours only give user level access to MySQL/MariaDB.

**Comment by polynamaude** [comment]
@DEATHJ0KER The softaculous installer is not from us. They modify our product and this is the cause of the actual problem.

If you install by the standard installer with a archive from Source forge or github then I'll be more than happy to help you with problems.

There's no such "default" php and we don't have any idea of your actual configuration. We can fix problem when they are caused by our software only but not the underlying infrastructure.

Tell me that you used Apache 2.22 with php 7.2 under Linux. With the following config file joined so I can make a exact copy of your system and if I find the problems you said then we'll be glad to fix them as we know it's on our side.

You just say stuff but don't bring something to work upon. Not even a single log file or screenshot (when useful).

And it's a problem that occur only on your system but don't want to check with your hosting provider. Have you asked them if they use modsecurity_crs ?

There may be where to look.

If your issue is considered finished then please close it.

You can also make review on Source forge. Thanks

**Comment by DEATHJ0KER** [comment]
I opened a ticket to resolve the problem to the host, I will definitely solve it, it is not a serious problem, I check again the restrictions, as you rightly observed. Thanks again for the availability and good work.
