### ISSUE TITLE
Error installing ph7cms

### ISSUE THREAD

**Issue by HenningNoergaard** [pH7Software/pH7-Social-Dating-CMS#254]
Hello,

When installing ph7cms i get followin error:

Sorry, we haven't found the "protected" directory.

I've been trying with;
/www.singlesiden.dk/public_html/_protected/
/www.singlesiden.dk/_protected/

I've uploaded source to both directories...... And they exists on WEBserver

Can anyone help me?

Best regards
- and have a nice day

Henning

**Comment by polynamaude** [comment]
Have you followed the docs about protected folder?

**Comment by HenningNoergaard** [comment]
Sorry i'm newbie - what docs about protected folder?

**Comment by polynamaude** [comment]
@HenningNoergaard New is no excuse for not thinking about checking website for docs.

www.ph7cms.com

You need to rename / move the _protected folder and put the location in the config file.

When you buy a new brand of instant noodle, do you read the instructions before cooking or you prepare without and make a complaint that the result is not as expected.

RTFM

**Comment by pH-7** [comment]
Hi @HenningNoergaard 

Normally, the value should be pre-indicated in the field. 
The file system path isn't related with your website URL. It should be something like `home/<USERNAME>/public_html/WHERE_PH7CMS_IS_UPLOADED/_protected/` or `/var/www/html/WHERE_PH7CMS_IS_UPLOADED/_protected/`
Please ask your web host what's the full path to where you uploaded pH7CMS.

Another solution can be to install it with Softaculous (if available with your cPanel). Hope it helps 🤞

**Comment by HenningNoergaard** [comment]
The only suggestion i have was renaming protected folder and that didnt bring me any futher....
I've been trying an extra underscore /www.singlesiden.dk/__protected/ and /www.singlesiden.dk/public_html/__protected/
with same result "Sorry, we haven't found the "protected" directory"
