### ISSUE TITLE
Change Google Maps API for a free open souce OpenStreetMap or similar

### ISSUE THREAD

**Issue by developer1sirimarketing** [pH7Software/pH7-Social-Dating-CMS#262]
Hi guys.

I woud like to change de Google Maps API on general settings. Google Maps now is charging for requests and I have been having issues (it was working fine until couple of days ago) to load the google map on members profile so I would like to replace for some open source alternatives (OpenStreetMap and others) that I have found. I would like to implement the code of some of them and test it or if someone know the solution to this issue with a message "This page didn't load Google Maps correctly" would like to hear from.

I have tried different Google API Keys but the issue persists.

Which file would I be able to change and/or replace the Google Maps JavaScript API? 

![change api](https://user-images.githubusercontent.com/37934272/43726437-86102550-9975-11e8-945e-6c27a2fb58de.png)

<img width="1082" alt="screen shot 2018-08-06 at 7 09 30 pm" src="https://user-images.githubusercontent.com/1325411/43730640-4a6e3d3e-99ac-11e8-8683-16dcf0ccecc5.png">

**Comment by developer1sirimarketing** [comment]
Yes. I have been looking for an answer for this issue but I have not got any good one.  I found out that I have exceeded the daily limit requests as it says on my error report on Google Developers and on Chrome Developer tools. It says I have one load request per day. I did not understand it.

As you can see on the images I reckon that an Open Source Map platform would fit nicely from now on. LOL 
I have found OpenStreetMap and third parties that use their data such as MapQuest, MapBox Leaflet, Here and others.

If you could replace Google Maps it would be nice. I am just giving an suggestion. Have a look at this link about OpenStreetMaps Frameworks https://wiki.openstreetmap.org/wiki/Frameworks

I will carry on this issue and find what to do for my website.

![google maps issue](https://user-images.githubusercontent.com/37934272/43745140-a0e6f8c0-99b3-11e8-9950-50077d766b88.png)
![google maps api error 2](https://user-images.githubusercontent.com/37934272/43745148-a65f3524-99b3-11e8-9707-bab1f5903ce3.png)
![google maps issue 2](https://user-images.githubusercontent.com/37934272/43745149-a67d6dc8-99b3-11e8-9433-d054ff7e8162.png)

**Comment by polynamaude** [comment]
Yes, even to use the free amount of request you still need to setup a credit card. They introduced this about 3 month ago.

**Comment by developer1sirimarketing** [comment]
My website was working fine even about 3 days ago but anyway. I will set it up for while but at the moment from my search this (https://wiki.openstreetmap.org/wiki/Nominatim) is the best FREE Open Source option for Geolocation API to integrate. If we could have it as a second option or even main option on our CMS would it be nice.

Looking forward to it. Thanks

**Comment by polynamaude** [comment]
You can make the coding and make a pull request to make everyone else benefit afterward. Must be that you didn't make request to the Google API in those three days. No magic there, it's a choice google did long time ago. Great to make request but better to contribute.

**Comment by developer1sirimarketing** [comment]
It has been sorted it out. I will try to integrate the OSM geocoding API on a copy and if I get right I will bring here. Thank you.

**Comment by pH-7** [comment]
Thanks for sharing @developer1sirimarketing  And happy to hear that :)
