### ISSUE TITLE
about profile style

### ISSUE THREAD

**Issue by PRINCEPANNU** [pH7Software/pH7-Social-Dating-CMS#265]
how to Change  a different profile page style in ph7cms builder

**Comment by pH-7** [comment]
Hi there @PRINCEPANNU 

You have the Admin Panel -> CSS Style where you can directly inject CSS customisation according to the CSS classes you have in the profile page.

Or you can even change the profile design page to another one (Admin Panel -> Mod -> Enable/Disable Modules -> Tick/Untick "Dating-Style Profile Page"

Hope this helps! 😊

Have a great day! 🌞
