### ISSUE TITLE
Unable to Login into Admin panel or reset admin password. 

### ISSUE THREAD

**Issue by atarashid** [pH7Software/pH7-Social-Dating-CMS#266]
Hi there, 

I have just installed fresh pH7CMS version 12.9.8 from softaculous and also after downloading from sourceforge. I tried several times to uninstall and reinstall. But all times I get error in Login to admin panel. 
Please see attached file so you can get more idea. 
![help](https://user-images.githubusercontent.com/42271129/43959528-d3689180-9cb7-11e8-887c-e2a40261748c.png)

I see the error message: "Please login first"

Please help me.

Thanks

**Comment by polynamaude** [comment]
@

**Comment by polynamaude** [comment]
@atarashid Check if your host use modsecurity

**Comment by atarashid** [comment]
Dear @polynamaude, please guide me... how to check the host's modsecurity?
Thanks

**Comment by polynamaude** [comment]
@atarashid You can ask your hosting provider. If you are self hosting then check apache documentation.

**Comment by atarashid** [comment]
Dear @polynamaude,
Thanks for your response. 
Really I have cPanel, can I check by myself? and what I have to do if I found modsecurity is activated... ?
thanks again.

**Comment by polynamaude** [comment]
@atarashid ModSecurity can cause this type of problem and it may be better to disable it. It's something that is managed by your provider and not yourself. On shared hosting you don't control the modules that apache load.

So you should contact them.

Have you looked through out your logs for errors ?

**Comment by atarashid** [comment]
@polynamaude,
Thank you so much for your clarification. 
Later I tried the same in other hosting package with I have with another service provider. 
Now it's working well in other hosting plan. 
Thanks again.

**Comment by polynamaude** [comment]
You should still look into your logs maybe you will understand why it didn't work and ask your hosting provider about modsecurity to rule out this possibility.

Also we'd appreciate a review on sourceforge and a star on github.

You can close this issue if your problem is solved.

If you want to share results of investigation with us then other users who may be with the same host will be able to refer.

Thanks

**Comment by pH-7** [comment]
Hi again @atarashid 
Have you seen our above comments?

**Comment by atarashid** [comment]
I was bit busy.. very soon I will write review ..
Thanks for your support.

**Comment by pH-7** [comment]
Thanks @atarashid! I understand this. That would be awesome for me if you could just write something quick and nice at https://sourceforge.net/projects/ph7socialdating/ 😊

Have a lovely day ☀️

**Comment by pH-7** [comment]
Just a friendly reminder @atarashid 😊
> If you are happy by the benevolent support and by the software I did, it will be very nice from you to give a nice review at https://sourceforge.net/projects/ph7socialdating/
