### ISSUE TITLE
after submit google search engine shows ph7cms description

### ISSUE THREAD

**Issue by vimgau28** [pH7Software/pH7-Social-Dating-CMS#269]
after submit google search engine shows ph7cms description.

see the image http://prntscr.com/khetcn

**Comment by pH-7** [comment]
Hi @vimgau28 

The page indexed by Google is the installer. 
Maybe you have leave your website for a long time without installing it and Google indexing the installer.
Next time the bot will refetch your website, the page title will be updated.
