### ISSUE TITLE
Unable to Login into Admin panel also not able to any user login

### ISSUE THREAD

**Issue by pheonix200** [pH7Software/pH7-Social-Dating-CMS#275]
I have install cms as per install intruction. Im able to register and upload photo but not able to login.
Also not able to login into admin panel. It showing error message please signin first.
I have read answer to disable mod_security, but i need solution without disabling mod_security.

Thanks,
Lalit

**Comment by pH-7** [comment]
Hi @pheonix200!
Do you mean when you try to login with correct credentials, it shows "please signin first" error message?
If so, the problem might be from sessions. Are you sure they are correctly setup? 
Or maybe your server has permission issues to write the sessions.

Can you please ask your web host to investigate there or see if there isn't log files that can help?

Thanks

**Comment by pheonix200** [comment]
Resolved that issue but now I have new issue how change domain after installing on other domain.
