### ISSUE TITLE
Restricting access to specific features based on account type

### ISSUE THREAD

**Issue by 000kelvin** [pH7Software/pH7-Social-Dating-CMS#277]
Hello, I tried coding a feature to enable or disable users from using some services like chatroulette for instance based on the type of user account i.e paid or free. I want to know if I could get help on this issue or some directives.

**Comment by pH-7** [comment]
HI @000kelvin 
This feature is already embedded.
Go to Admin Panel -> Billing -> Membership Manager (or add a new free/paid membership, Admin -> Billing -> Add a new Membership).
If you are happy with the software I did, it would be nice of you to give a review at https://sourceforge.net/projects/ph7socialdating/ 
(it really helps and motivates me!)

Hope this helps!

**Comment by 000kelvin** [comment]
Oh, that's really code - I'm pretty happy I didn't need to code anything.
Also, I just gave you an awesome review, thanks for the good job!

**Comment by pH-7** [comment]
That's awesome Kelvin! Really happy 😊
