### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by radmax42** [pH7Software/pH7-Social-Dating-CMS#279]
Im trying to install this script 

When I go to the install URL i get THIS error:

CONFIG FILE NOT FOUND! If you want to make a new installation, please re-upload _install/ folder and clear your database.

where do I find the config file?
Ughhh.. not even installed and already im stuck ... feel like a n00b

**Comment by radmax42** [comment]
yes i do i uploaded it 3 times now


heres a screenshot:

**Comment by radmax42** [comment]
@pH-7  anything else I should try?

**Comment by pH-7** [comment]
That's strange. Try to directly go to `YOUR-WEBSITE.COM/_install/`

Otherwise, try to add `var_dump(is_file(__DIR__ . '/' . self::REQUIRED_CONFIG_FILE_NAME));exit;` in the `index.php` (the one located in the root directory). It should return TRUE since your `_install/` folder exists, but for some reason it looks like it doesn't on your side.

**Comment by pH-7** [comment]
Last solution, I would suggest to chat with your web hosting support. Maybe a permission problems?? Mention everything [you have here](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/279), etc, and see with them.

Hope this will help 😊

**Comment by radmax42** [comment]
Yeah that code line didnt change a thing.

Guess Ill have to shell out hundreds for a commercial script *im literally crying right now*

**Comment by pH-7** [comment]
Have you tried to directly go to http://YOUR-WEBSITE.COM/_install/ ?

**Comment by radmax42** [comment]
Yes I had tried that before I even posted this help request.
...of course i tried again after all this.

I'll have to contact HostGator strange because I never had an issue installing anything before (doing this 20+ years)

**Comment by pH-7** [comment]
What do you have when you go at  http://YOUR-WEBSITE.COM/_install/ ?
Yes, like I told you, you should contact your web host because something is caused by them.

P.S. I usually don't recommend HostGator (and it's not the first time someone has an issue installing pH7Builder with HostGator).

**Comment by radmax42** [comment]
Youre right! After sitting om tech support chat for over an hour they couldnt find a problem.
Fortunately I have 2 accounts with them so I uploaded it to another server

so I uploaded and went to install URL... and guess? what it worked
...ok it didn't ACTUALLY work ..
it TRIED to install but Hostgator isn;t running the correct version of PHP they have an older version

Im online right now setting up a new hosting account with someone else.

Thankyou so much for all your patience and help :-D

**Comment by pH-7** [comment]
Hi @radmax42 

Really happy for you that you finally figured out the problem 😊

If you are looking to a good web hosting, you can use Webfaction or another one here: https://ph7cms.com/doc/en/hosting

P.S. If you are happy with the support and the software, it will be very nice of you to give a nice review at https://sourceforge.net/projects/ph7socialdating/ (it really helps and motivates me!)
