### ISSUE TITLE
Website wont log out in Microsoft Edge (explorer browser)

### ISSUE THREAD

**Issue by radmax42** [pH7Software/pH7-Social-Dating-CMS#283]
Testing the site front end as a user... 
In microsoft edge (formerly internet explorer) once I log out a user , I am instantly logged back into the site.

Obviously for a dating site this is a HUGE privacy issue
How to fix it? 

(works fine logging out in Chrome and Firefox browsers)

**Comment by pH-7** [comment]
Thanks for reporting it. Have you used the "Remember Me' checkbox?

I will try to test it with Edge soon.
Code: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/8a5eceaf111daac5b3537e79b953d37b0fc8d96c/_protected/app/system/modules/user/inc/class/User.php#L27-L33
