### ISSUE TITLE
Paypal check out won't work with GBP currency

### ISSUE THREAD

**Issue by CharleeHan** [pH7Software/pH7-Social-Dating-CMS#285]
Hi All,

I am getting "Things don't appear to be working at the moment. Please try again later" (After I click on any membership button). on redirected paypal.com page 

Please advise.
Thanks
Charlee

**Comment by CharleeHan** [comment]
Look like it is currency issue. I changed to USD and it worked. How can I make it work with GBP, please?

**Comment by pH-7** [comment]
Interesting. according the the [currency code supported by PayPal](https://developer.paypal.com/docs/classic/api/currency_codes/#paypal), if you enter `GBP` in [Admin Panel](https://ph7cms.com/doc/en/how-to-go-to-admin-panel) -> Mod -> Billing -> Gateway Config -> Currency field, it should work too.

Maybe Paypal has a better answer to it... 

Is the sandbox enabled?

**Comment by CharleeHan** [comment]
Yes it is.

**Comment by pH-7** [comment]
It works well for me. Are you sure you didn't do a typo like GDP? Please make sure you correctly enter GBP in the field without anything else.

**Comment by CharleeHan** [comment]
I was using UK instead of GBP. Sorry. Yes it is working now.

**Comment by pH-7** [comment]
I'm glad you found the problem @CharleeHan! BTW, would do be able to write a review at https://sourceforge.net/projects/ph7socialdating/ (and/or just "Star" the Github) if you are happy with the software I made. It really helps me and motivates me 😊

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
FYI, I implemented a drop-down list containing the available currency codes in order to avoid wrong inputs/typos (although it will still have to meet the accepted currencies of your payment gateway you enable).

<img width="766" alt="screen shot 2018-09-08 at 2 22 46 pm" src="https://user-images.githubusercontent.com/1325411/45249398-b2f7df00-b373-11e8-9f46-c9a25e6c5d0a.png">
<img width="1010" alt="screen shot 2018-09-08 at 2 22 38 pm" src="https://user-images.githubusercontent.com/1325411/45249399-b3907580-b373-11e8-89b8-e629ccce9d61.png">

**Comment by CharleeHan** [comment]
is this change will be on next version? or is it possible to just download it now? Thanks

**Comment by pH-7** [comment]
It will be available on the next release (v14.3).
If you like my work, would you be able to write a review at https://sourceforge.net/projects/ph7socialdating/ ?
It really helps me and motivates me! 😊 Thanks for understanding it & enjoy your weekend!

**Comment by CharleeHan** [comment]
Please make interface similar to greensingles.com if you can.
I find it more user friendly and please add paypal express option too.

Search date option "All countries" is not included.

Thanks,
Charlee

[https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif]<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>  Virus-free. www.avast.com<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>

**Comment by CharleeHan** [comment]
hi, sorry I ment, when you are searching for man or woman you don't have "All countries" option.
 someone may like to search a man or woman globally.

________________________________

**Comment by pH-7** [comment]
@CharleeHan Yes you do. On the search form, all countries are displayed, unless you use the Country Restriction (Admin -> User/Admin -> Users -> Country Restriction).

Ref: https://ph7cms.com/ph7cms-12-9-released/

**Comment by pH-7** [comment]
Actually, it used to be in the past, prior pH7Builder, v12.9
It's a kinna bug, since Country Restriction has been implemented. Now, it only fetches countries from the database without having an empty (`-- Select --`) value.
