### ISSUE TITLE
Admin->Moderation - Refusing Pictures with justification/message

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#287]
When Admin refusing pictures, there should be a field to add a personalized message to user
like: Your picture wasn't approved because ____________________ (insert message)

Does it make sense ? Otherwise the Admin just refuse but no justification.

Thank you and Congrats for this great project

**Comment by pH-7** [comment]
I added something similar. https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/287
The system will email the user when the moderator approved/disapproved user contents.
These changes should be released in pH7Builder v14.3.0
