### ISSUE TITLE
Captcha not working on Google Chrome

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#289]
I am trying to resend activation email for a valid email but the captcha nor working on Google, no matter what I do, please see attached.
![issue](https://user-images.githubusercontent.com/43084373/45251075-13692b00-b338-11e8-8f9f-5647b215bf9c.jpg)
![issue2](https://user-images.githubusercontent.com/43084373/45251076-1401c180-b338-11e8-88a8-5735a0738f55.jpg)
Regards

**Comment by pH-7** [comment]
Must be a problem with the session somewhere... Never had this problem.

Please try to reproduce it on the demo http://demo.ph7cms.com/ Go to the contact form and try the captcha there (I just did and works like a charm).

**Comment by Mobiller** [comment]
Hi.
You are right. It's working fine ;)
Thank you

**Comment by pH-7** [comment]
You're very welcome @Mobiller! By the way, would do be able to write a review at https://sourceforge.net/projects/ph7socialdating/ if you are happy with the software I made? It really helps me and motivates me! 😊 Thanks for understanding it
