### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by geidorei** [pH7Software/pH7-Social-Dating-CMS#292]
I have deleted the webspace, reinstalled, gone round in circles....

When I run _install I get the following - it is not installed, completely clean:

Your site is already installed.
If you want to redo a clean installation, please delete your "_constants.php" file and delete all the content of your database.

Note: _constants.php does not exist either

Any ideas??? Many thanks.

**Comment by geidorei** [comment]
dont worry ive fixed it

**Comment by pH-7** [comment]
Really happy to hear that @geidorei!
BTW, if you like the software I did, something nice you could do is to star this Github repository (or just give a review on [Sourceforge](https://sourceforge.net/projects/ph7socialdating/))

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
