### ISSUE TITLE
Not logged in visitors can view photo/video albums

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#293]
There are links to view photo gallery and videos movie on the sitemap page and anyone can see. The person should be logged in to see the pictures right ?
Cheers

**Comment by pH-7** [comment]
Hi @Mobiller 
What links is it? Can you send it, so I can check.

Other possibility, it might be from the permissions you set for the "Visitor" membership (in Admin -> Billing -> Memberships List).

**Comment by Mobiller** [comment]
Sorted. I didn't know that we could set permissions :) Thanks

**Comment by pH-7** [comment]
Beautiful!
