### ISSUE TITLE
Adding more Genders?

### ISSUE THREAD

**Issue by VeggiesAreYucky** [pH7Software/pH7-Social-Dating-CMS#296]
Is this possible? i.e. "Other" or "M2F" or "F2M"?

**Comment by Mobiller** [comment]
Interested as well and I would like to remove the option for couples

**Comment by Savaena** [comment]
Also very interested to do this. Is there documentation somewhere in the PHP file?

**Comment by Outlines** [comment]
I'd be interested in this as well.  I want to remove/rename female to FTM
