### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#302]
I created the API as instructed however the map only shows Paris ? and the user (tester) address is Brazil not France ?
any help ?
![issue](https://user-images.githubusercontent.com/43084373/45634555-9148d700-ba9a-11e8-9185-63da00ed8623.jpg)

**Comment by pH-7** [comment]
What's the address you specified? Have you used `setCenter()` or `setCenterLatLng()` method?
Try to do something similar to https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/controllers/CountryController.php#L105-L117

**Comment by Mobiller** [comment]
Hi pH-7, 
Good Morning
I haven't touch the code and my lines look exactly as above
`{
        $sFullAddress = $this->registry->country . ' ' . $this->registry->city;
        $sMarkerText = t('Meet new people here thanks <b>%site_name%</b>!');

        $oMap = new Map;
        $oMap->setKey(DbConfig::getSetting('googleApiKey'));
        $oMap->setCenter($sFullAddress);
        $oMap->setSize(self::MAP_WIDTH_SIZE, self::MAP_HEIGHT_SIZE);
        $oMap->setDivId('country_map');
        $oMap->setZoom(self::MAP_ZOOM_LEVEL);
        $oMap->addMarkerByAddress($sFullAddress, $sMarkerText, $sMarkerText);
        $oMap->generate();
        $this->view->map = $oMap->getMap();
        unset($oMap);
    }`

**Comment by pH-7** [comment]
Can you paste the full address you have in `$sFullAddres` variable. So, I can try to reproduce the error.

**Comment by Mobiller** [comment]
`private function setMap()
   {
        $sFullAddress = $this->registry->country . ' ' . $this->registry->city;
        $sMarkerText = t('Meet new people here thanks <b>%site_name%</b>!');
        $oMap = new Map;
        $oMap->setKey(DbConfig::getSetting('googleApiKey'));
        $oMap->setCenter($sFullAddress);
        $oMap->setSize(self::MAP_WIDTH_SIZE, self::MAP_HEIGHT_SIZE);
        $oMap->setDivId('country_map');
        $oMap->setZoom(self::MAP_ZOOM_LEVEL);
        $oMap->addMarkerByAddress($sFullAddress, $sMarkerText, $sMarkerText);
        $oMap->generate();
        $this->view->map = $oMap->getMap();
        unset($oMap);
    }`

**Comment by Mobiller** [comment]
private function setMap()
   {
        $sFullAddress = $this->registry->country . ' ' . $this->registry->city;
        $sMarkerText = t('Meet new people here thanks <b>%site_name%</b>!');
        $oMap = new Map;
        $oMap->setKey(DbConfig::getSetting('googleApiKey'));
        $oMap->setCenter($sFullAddress);
        $oMap->setSize(self::MAP_WIDTH_SIZE, self::MAP_HEIGHT_SIZE);
        $oMap->setDivId('country_map');
        $oMap->setZoom(self::MAP_ZOOM_LEVEL);
        $oMap->addMarkerByAddress($sFullAddress, $sMarkerText, $sMarkerText);
        $oMap->generate();
        $this->view->map = $oMap->getMap();
        unset($oMap);
    }

**Comment by polynamaude** [comment]
No, that code is something he already has ! I'm pretty sure if he wanted code, he would have said "code" and not address. So it must be a "adress" with number, street and such so he can make the same request as you and see the results.

PM

On September 23, 2018 1:25:46 PM EDT, Mobiller <notifications@github.com> wrote:
>> Can you paste the full address you have in `$sFullAddres` variable.
>So, I can try to reproduce the error.
>
>Is that code above that you mean by "full address"
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/302#issuecomment-423832667

-- 
Polyna-Maude R.-Summerside

**Comment by Mobiller** [comment]
> Can you paste the full address you have in `$sFullAddres` variable. So, I can try to reproduce the error.

Address: R. de São Bento 157
Street: R. de São Bento 157
City: Lisboa
State: Lisboa
Post Code/Zip: 1200-821
Country: Portugal

**Comment by pH-7** [comment]
Yes, this is what I meant (sorry about the confusion).

Can you check your web browser's console error log?
Press Ctrl + Shift + J (Windows/Linux) or Cmd + Opt + J (on Mac).

**Comment by pH-7** [comment]
Are you on localhost?
You will probably have an error like the following.
<img width="1434" alt="screen shot 2018-09-24 at 10 31 24 pm" src="https://user-images.githubusercontent.com/1325411/45947862-e613c100-c049-11e8-8023-d35e27c9070e.png">

**Comment by pH-7** [comment]
Google did recent changes the last 1-2 months.
https://developers.google.com/maps/documentation/geocoding/usage-and-billing

Probably, your account isn't setup correctly. I believe that's the reason why you got a default fallback address.

**Comment by pH-7** [comment]
I know, it becomes more and more complicated 😃 (not so long ago, it didn't even require a api key or any kind of registration).

**Comment by Mobiller** [comment]
> Are you on localhost?
> You will probably have an error like the following.
> <img alt="screen shot 2018-09-24 at 10 31 24 pm" width="1434" src="https://user-images.githubusercontent.com/1325411/45947862-e613c100-c049-11e8-8023-d35e27c9070e.png">

Here is the error:

Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable)
45:1 Failed to load https://freegeoip.io/json/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://namoromaduro.com' is therefore not allowed access. The response had HTTP status code 503.
js?key=AIzaSyCqQJkAvDwArjizf5TwVX****************&language=pt:48 Geocoding Service: This API project is not authorized to use this API.  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key
_.Ec @ js?key=AIzaSyCqQJkAvDwArjizf5TwV******************&language=pt:48
45:24 Opa! O Mapa Geográfico não foi bem sucedido pelo seguinte motivo:REQUEST_DENIED

PS: I just changed the API for security reasons ;)

**Comment by Mobiller** [comment]
I think I solved
The problem was to Enable Google Maps Geocoding API -> Enable API. 
Thank you for your help, specially @polynamaude ;)
