### ISSUE TITLE
Facebook Sharing Preview

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#303]
Hello, 
When I try to share a blog entry on Facebook, instead of a preview of the blog entry, this is what I got it.
![issue2](https://user-images.githubusercontent.com/43084373/45681991-e63a2b00-bb36-11e8-908a-d354d35f34db.jpg)
Any help ?

**Comment by pH-7** [comment]
Thanks for the reporting this issue @Mobiller!
This is strange! This shouldn't happen! Are you sure FB is getting the right page. It looks like you blocked the United States with the "[Country Blocker](https://ph7cms.com/ph7cms-12-6-released/)" tool, so FB see the banned message page https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/global/views/base/tpl/other/msg.html.php#L19-L20 
https://unfurls.co/

**Comment by pH-7** [comment]
You blocked the "United States", right? The Facebook server that fetches the websites has probably a US IP address. That's why when it was fetching your website, FB wasn't able to access to your website, because it was blocked.
