### ISSUE TITLE
Country selector on Profile editor

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#304]
Hello,

Even with the Country Blocker and only 2 countries allowed on registration field, after registration users can change to whatever country as they like, please see attached.

![issue](https://user-images.githubusercontent.com/43084373/45736478-f9a2d000-bbe2-11e8-8397-369b7e84c7b4.jpg)

**Comment by pH-7** [comment]
Hi @Mobiller 
This isn't a bug. Your website won't be accessible from any of those countries (this will block the country IP). However, it doesn't amend any user form fields.

You can try with a blocked country VPN, or block your own country (if you aren't on a local host), and logout from your admin panel and go to the homepage, you will see, your website won't be accessible. You will just receive a friendly message saying that your website isn't available in that country.

Hope this helps! 🤞
