### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by micropuce** [pH7Software/pH7-Social-Dating-CMS#306]
Hello,

after installation, i have the admin folder that does not install! the css did not set up and I have a 500 error when accessing the admin panel, could someone tell me why? I am heberger at 1and1.fr 

thank you

**Comment by Mobiller** [comment]
Sometimes when you install on https instead of http the same error occur, have a look into it.

**Comment by pH-7** [comment]
@phhpro Please create a new issue, since the error is different. You probably have issue with mod_rewrite with your host. There are already similar solved threads in the closed issues.

**Comment by pH-7** [comment]
@micropuce Please let me know if this issue is still relevant?

**Comment by pH-7** [comment]
@micropuce Please reopen the ticket if you have further information concerning your error. Thanks.
