### ISSUE TITLE
Profile with no pictures to be deleted in xx days

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#307]
How can be add a function to auto delete a profile without a picture in xx days?

Some people create profiles but not upload pictures.

Cheers

**Comment by pH-7** [comment]
The best would be to make the "Profile Photo" field required during the registration (Admin -> Setting -> General -> Registration tab, -> "Require photo to be uploaded". However, some users leave the registration process after the step one but don't go until step 4, so you might still have some users without a profile photo.

**Comment by pH-7** [comment]
What you asked is doable, but it requires work! You will have to create a new cron job that runs every day for instance to delete all users without profile photos. You will have to ask it to a good PHP programmer (Toptal for example), or a very good one on UpWork, but I've heart that it's harder to find good ones there).
