### ISSUE TITLE
Error on showing page

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#310]
Notice: Undefined offset: 1 in /home/subdir/mydomain.com/_protected/data/cache/pH7tpl_compile/public_main/base/browse_user.inc.cpl.php_user.inc.cpl.php on line 19

When going to https://www.mydomain.com/meet-people

![issue](https://user-images.githubusercontent.com/43084373/45890114-0fb6b900-bdba-11e8-943a-0f9b6fa6bfa7.jpg)

**Comment by pH-7** [comment]
It looks like one of your users has an invalid date of birth, and so the [$aAge[]](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/browse_user.inc.tpl#L16) array has undefined offset. This sometimes happen somehow, although the date field in the registration form makes sure the date pattern is valid. 

I will make a fix in case a user has invalid birth of date.
