### ISSUE TITLE
Unable to login to admin and register to website

### ISSUE THREAD

**Issue by Ghost173** [pH7Software/pH7-Social-Dating-CMS#311]
i install pH7Builder-14.0.0  and select 3rd option (dating only)   after finish setup cant login admin panel and register user also not save in database 

these are also not save data base 
1.admin login attempts anything not store in data base    

**only one think i find in database while setup i enter admin login details only**

**Comment by Ghost173** [comment]
only problem cant login chrome its work firefox ( developer )  my chrome version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by rimer10** [comment]
same issue i cant register i try in my love server ubuntu 16.04

**Comment by polynamaude** [comment]
Have you followed the config step ?

Protected folder, rename admin modules... ?

For the guy with chrome, don't hijack others thread with your problems. So open your own...

Also, take a minute to think if you're at the good place to talk about browser. Maybe not so much, ain't a general computer all-you-can-do help line ;-)

On September 24, 2018 11:12:58 AM EDT, Ghost173 <notifications@github.com> wrote:
>i install pH7Builder-14.0.0  and select 3rd option (dating only)  
>after finish setup cant login admin panel and register user also not
>save in database 
>
>these are also not save data base 
>1.admin login attempts anything not store in data base    
>
>**only one think i find in database while setup i enter admin login
>details only** 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311

-- 
Polyna-Maude R.-Summerside

**Comment by rimer10** [comment]
my data base connection good cant login admin ,and if i create user its not save :( but i got mail

**Comment by pH-7** [comment]
@Ghost173 FYI, this issue is caused by a different problem than https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311 (unlike what you were saying in the issue's subject).

**Comment by pH-7** [comment]
I tried to replicate the issue for you with Chrome (version 69.0.3497). However, everything works well for me. Can you please clear your browser's cache or open an incognito navigation. 
Chrome caches a lot, so you have problems with it quite often.

**Comment by rimer10** [comment]
hii iam also facing same issue what i did download ph7 dating from [here](https://sourceforge.net/projects/ph7socialdating/)  and follow everything after install  register fail and cant login admin also i try in live server

**Comment by pH-7** [comment]
Have you tried to clear your browser's cache or with your mobile phone?

**Comment by rimer10** [comment]
yes i have no idea y i cant :( 1st time css not load so i re install and my vps already have mail function when i try forget password that also not working how to fix this  and im 100% sure my admin mail user name password are correct

**Comment by polynamaude** [comment]
What have you tried already on your side ?
What do your logs says?

On September 25, 2018 7:48:45 AM EDT, rimer10 <notifications@github.com> wrote:
>yes i have no idea y i cant :( 1st time css not load so i re install
>and my vps already have mail function when i try forget password that
>also not working how to fix this  and im 100% sure my admin mail user
>name password are correct 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311#issuecomment-424311541

-- 
Polyna-Maude R.-Summerside

**Comment by EclipseFLG** [comment]
Also having the same issue, cannot login to admin area, very annoying, anything we can try here? really need a solution to this that is user friendly. Thanks!

**Comment by polynamaude** [comment]
Don't wanna be "rude" but "user friendly" is for users. A system administrator need to have some knowledge that goes further than using a mouse for everything. Some file edition, command line work and investigation is a must.

Unless you're just praying not to be hacked or want to outsource that work. In the last case, there's no need to expect such solution as a professionnal that has knowledge also know how to search answer.

Instead of saying "need something" it would be better to appreciate the work already done as you didn't pay a penny and if you did then it wasn't for this software.

Have you looked the docs on ph7cms.com?

Looked at your logs ? (hum what do logs mean?)

Did something before just asking for help ?

It's not because you install a software that you install something that you got knowledge for use. Or you'll never know that seed got to be changed.

Just a hint about life...

On September 25, 2018 3:29:25 PM EDT, EclipseFLG <notifications@github.com> wrote:
>Also having the same issue, cannot login to admin area, very annoying,
>anything we can try here? really need a solution to this that is user
>friendly. Thanks!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311#issuecomment-424471314

-- 
Polyna-Maude R.-Summerside

**Comment by EclipseFLG** [comment]
> Don't wanna be "rude" but "user friendly" is for users. A system administrator need to have some knowledge that goes further than using a mouse for everything. Some file edition, command line work and investigation is a must. Unless you're just praying not to be hacked or want to outsource that work. In the last case, there's no need to expect such solution as a professionnal that has knowledge also know how to search answer. Instead of saying "need something" it would be better to appreciate the work already done as you didn't pay a penny and if you did then it wasn't for this software. Have you looked the docs on ph7cms.com? Looked at your logs ? (hum what do logs mean?) Did something before just asking for help ? It's not because you install a software that you install something that you got knowledge for use. Or you'll never know that seed got to be changed. Just a hint about life...
> […](#)
> On September 25, 2018 3:29:25 PM EDT, EclipseFLG ***@***.***> wrote: Also having the same issue, cannot login to admin area, very annoying, anything we can try here? really need a solution to this that is user friendly. Thanks! -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#311 (comment)](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311#issuecomment-424471314)
> -- Polyna-Maude R.-Summerside

Sorry if it came off that way, did not intend for that... As far as user friendly, I was looking for just a little more than the generic "go google it" answer, which is how i ended up here in the first place.. I have looked in docs, i have tried things that are listed, was wondering if maybe there was a file out of place or something that could be changed.. Simply looking for some direction, and yes im glad its free software and think its fantastic!!!

**Comment by polynamaude** [comment]
Don't be sorry instead make it easier for people to help you ! I already gave you hint about that. Doesn't help much to get a idea about what's going on when the person give you nothing more than the usual "not working" ! No logs, no info about what's running on, no info about what got tried 

PM

On September 25, 2018 3:56:12 PM EDT, EclipseFLG <notifications@github.com> wrote:
>> Don't wanna be "rude" but "user friendly" is for users. A system
>administrator need to have some knowledge that goes further than using
>a mouse for everything. Some file edition, command line work and
>investigation is a must. Unless you're just praying not to be hacked or
>want to outsource that work. In the last case, there's no need to
>expect such solution as a professionnal that has knowledge also know
>how to search answer. Instead of saying "need something" it would be
>better to appreciate the work already done as you didn't pay a penny
>and if you did then it wasn't for this software. Have you looked the
>docs on ph7cms.com? Looked at your logs ? (hum what do logs mean?) Did
>something before just asking for help ? It's not because you install a
>software that you install something that you got knowledge for use. Or
>you'll never know that seed got to be changed. Just a hint about
>life...>
>> […](#)>
>> On September 25, 2018 3:29:25 PM EDT, EclipseFLG ***@***.***> wrote:
>Also having the same issue, cannot login to admin area, very annoying,
>anything we can try here? really need a solution to this that is user
>friendly. Thanks! -- You are receiving this because you commented.
>Reply to this email directly or view it on GitHub: [#311
>(comment)](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311#issuecomment-424471314)>
>> -- Polyna-Maude R.-Summerside>
>>
>Sorry if it came off that way, did not intend for that... As far as
>user friendly, I was looking for just a little more than the generic
>"go google it" answer, which is how i ended up here in the first
>place.. I have looked in docs, i have tried things that are listed, was
>wondering if maybe there was a file out of place or something that
>could be changed.. Simply looking for some direction, and yes im glad
>its free software and think its fantastic!!!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311#issuecomment-424479764

-- 
Polyna-Maude R.-Summerside

**Comment by EclipseFLG** [comment]
Basically, when going to the admin login, once i type the username, password and email, it looks like its doing somehting and loops back to the login page, absolutely no errors whatsoever.

**Comment by pH-7** [comment]
@Ghost173 Please let me know if this is fixed?

**Comment by Ghost173** [comment]
hi @pH-7 really thz for this   still have same problem  http://45.32.113.186/pH7Builder-14.3.0/   here just try to register :) cant register and admin login also not working if ph7 guys need my phpmyadmin and other staff ill give for fix this bug 

in console  this the error buy fire fox working fine but in documentation no need https its a http issue or my browser problem?   and @pH-7  if u need ill share admin access also 

```
This Web App has been made with http://pH7CMS.com | The Social App Builder
GitHub: http://github.com/pH7Software/pH7-Social-Dating-CMS
login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
```

**Comment by pH-7** [comment]
Please migrate your website to https in order to be safe.

**Comment by pH-7** [comment]
Please let me know if this issue is still relevant for you @Ghost173  @rimer10  @EclipseFLG

**Comment by pH-7** [comment]
Since you didn't get back to me, I assume this issue is solved by now.
Please reopen it if it isn't the case. Thanks!
