### ISSUE TITLE
admin login and register 14.0.0 ubuntu 

### ISSUE THREAD

**Issue by rimer10** [pH7Software/pH7-Social-Dating-CMS#312]
i have Ubuntu vps and php 7 apche2 

i try to install ph7 dating after install i select 1st one   then also delete install (in wizard i click delete) then i refresh page 

1.i care a new user its not store in database
2.admin login fail 
 i read same issue in git-hub but its not solve my problem so please any body can help me?

**Comment by pH-7** [comment]
Same problem as https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/312
