### ISSUE TITLE
Importing Users

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#314]
I look into it but I can't find anywhere in the documentation how it should it be the configuration of the file to import .CSV ?
Does it should be something like that:
first_name,last_name,username,email,password,sex,match_sex,birth_date,description,country,city,state,zip_code,website,social_network_site,ip
and if I have extra fields, should I create them first and them add to the CSV file ?
Cheers
I follow the affiliate link for the users database, paid for it but they only send me the .sql file, is there a ways to import without damaging my database already with users ?

**Comment by pH-7** [comment]
Hi @Mobiller 

Yes, that's right. I've made the importer to work with most of user csv files. So, the email field could be either `email` or `mail`, same for zip_code, could be also `zip`, `postalcode`, `pincode`, etc.

According to your example, please make sure the delimiter is the comma `,` then.

All the best!

**Comment by pH-7** [comment]
Let me know if everything works :)

P.S. I'm really sorry to hear what happens with the displayed link. I will remove the link then, if they provide only SQL files. It's not an affiliate link (although there is the `from` param), it was only to tell them that the software is giving them traffic (but they never got back to me).

**Comment by pH-7** [comment]
BTW @Mobiller, I have seen that they say "Profiles format: CSV, SQL" on saledatingprofiles website. Are you sure you got only SQL file format?

**Comment by Mobiller** [comment]
> BTW @Mobiller, I have seen that they mention "Profiles format: CSV, SQL" on saledatingprofiles website. Are you sure you got only SQL file format?

I got the SQL but I asked him to send me the CSV as well and he did. I am not sure about how to add the pictures in the process as well?!

**Comment by Mobiller** [comment]
> BTW @Mobiller, I have seen that they mention "Profiles format: CSV, SQL" on saledatingprofiles website. Are you sure you got only SQL file format?

And what about the passwords ? just leave it blank ?

**Comment by pH-7** [comment]
1. Please use the fake generator profiles instead if you need profile pictures
2. You don't need passwords for them. 
3. They are in `ph7_members_info` table.

Hope that helps!

**Comment by Mobiller** [comment]
> 1. Please use the fake generator profiles instead if you need profile pictures
> 2. You don't need passwords for them.
> 3. They are in `ph7_members_info` table.
> 
> Hope that helps!

If I can't use those profiles with the pictures I will rather use the fake generator already on the system. Thank you for your help

LOL anyone want it to buy 25,000 brazilian profiles ? hahaha
