### ISSUE TITLE
social dating css  not loading and anminpanlel 404

### ISSUE THREAD

**Issue by rimer10** [pH7Software/pH7-Social-Dating-CMS#315]
ph7 14.0.0 i choose 1st (social dating) that css not loading

**Comment by polynamaude** [comment]
How do you want to get help if you don't help yourself !!!

Give us logs, and what you're running on !

Do you use modsecurity-crs?

On September 26, 2018 7:44:32 AM EDT, rimer10 <notifications@github.com> wrote:
>ph7 14.0.0 i choose 1st (social dating) that css not loading 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/315

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
@rimer10  Although I already said it, can you make sure that the `.htaccess` has been correctly been uploaded to the root directory.

**Comment by pH-7** [comment]
And that Apache mod_rewrite is CORRECTLY setup https://ph7cms.com/doc/en/how-to-install-rewrite-module

**Comment by pH-7** [comment]
@rimer10 Please let me know if this issue is solved?

**Comment by pH-7** [comment]
@rimer10 Because you didn't get back to me, I assume this issue is solved by now. 
Please reopen it if it isn't the case.
