### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#316]
Hello, 
I don't know PHP but I am willing to research or pay to a coder to develop a social login (facebook, google and et cetera) for this script.
What do I need to do ?
Regards

**Comment by polynamaude** [comment]
Site offer this service but you can get varying result.

Or you can pay more and go with established consultant.

On September 26, 2018 8:54:10 AM EDT, Mobiller <notifications@github.com> wrote:
>Hello, 
>I don't know PHP but I am willing to research or pay to a coder to
>develop a social login (facebook, google and et cetera) for this
>script.
>What do I need to do ?
>Regards
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/316

-- 
Polyna-Maude R.-Summerside

**Comment by Mobiller** [comment]
> Site offer this service but you can get varying result. Or you can pay more and go with established consultant.
> […](#)
> On September 26, 2018 8:54:10 AM EDT, Mobiller ***@***.***> wrote: Hello, I don't know PHP but I am willing to research or pay to a coder to develop a social login (facebook, google and et cetera) for this script. What do I need to do ? Regards -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #316
> -- Polyna-Maude R.-Summerside

When you mean "varying result" it mean works one day and doesn't work on the other ? or once working will carry on working ?

**Comment by Mobiller** [comment]
How do the consultant/coder can have access to the files where social login are located ?

**Comment by Mobiller** [comment]
Any Developer website that you can suggest ?

**Comment by polynamaude** [comment]
....
You should take some time to think before starting to ask question...

I'm not going to give you computing class or teach you how do software development lifecycle is done.

Many years ago I used RTFM and will do so now. If you don't know what it does mean then use Google.

Where can I find developper ? First if you make some effort instead of just asking around what we took time to write in the docs then you'll get some information and learn stuff.

How do a developper access the file ? He download pH7CMS and code a module for you ! How does that sound ? Oh and you pay him for his work !

Haven't you noticed that Pierre-Henry was fast to answer in the beginning and now pretty slow with you ? Maybe he got annoyed by answering question that he wrote the answer already but that you didn't bother to read before asking.... Or he's busy !

But anyhow, act this way on a Linux Kernel forum or some other project alike and either you get ignored, banned after you continue without a nice warning or just banned because there:s rule.

Sure I know place to find developpers, so ? I'm not here to answer such question, this is a place for issue with the software pH7CMS and not a computer club. I have more than enough to do so I don't need such question that are personnal choice.

Or to answer question because people re too lazy or don't think it's worth to do some work.

What does it mean you can get bad quality work ? Problem now and later, same when your house get fixed.

On September 27, 2018 8:27:48 AM EDT, Mobiller <notifications@github.com> wrote:
>How do the consultant/coder can have access to the files where social
>login are located ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/316#issuecomment-425071638

-- 
Polyna-Maude R.-Summerside

**Comment by Mobiller** [comment]
You shouldn't waste your time and precious words with me. Just ignore my questions if you can. Or probably you have some kind of fetish on bullying people with words, that's called Trolling.

Thank you for the tip on Googling RTFM, really explanatory.

If Pierre-Henry decided to ignore me, it's is because he is doing real work instead of Trolling people.

I will be really devastated if I am banned from a Linux Kernel Forum. It will break my heart :( 

I did not understand "What does it mean you can get bad quality work ? Problem now and later, same when your house get fixed." but I don't really care.

Good Luck in life polynamaude

**Comment by polynamaude** [comment]
The day you'll really need help and finish not getting any answer you'll understand what I mean and end up paying for what you could get for free. We call it advice.

When you ask a bad plumber to do repair a leaking faucet, two things happens, first your leak start back pretty soon and later on you get problem when you upgrade.

As I get emailed everytime there's something on the gitHub, I go see if it's someone who need help or has a problem with something related.

I give chance and I try to be as nice as possible, that's what we call moderating.

If you have something real about pH7 then we'll give you a hand. But ask on the right place, like on a PHP forum if it's not related.

You seem amused when I give you the example of a serious forum with lots of high end developper. Maybe you should learn what we call community standards.

On September 27, 2018 11:59:00 AM EDT, Mobiller <notifications@github.com> wrote:
>You shouldn't waste your time and precious words with me. Just ignore
>my questions if you can. Or probably you have some kind of fetish on
>bullying people with words, that's called Trolling.
>
>Thank you for the tip on Googling RTFM, really explanatory.
>
>If Pierre-Henry decided to ignore me, it's is because he is doing real
>work instead of Trolling people.
>
>I will be really devastated if I am banned from a Linux Kernel Forum.
>It will break my heart :( 
>
>I did not understand "What does it mean you can get bad quality work ?
>Problem now and later, same when your house get fixed." but I don't
>really care.
>
>Good Luck in life polynamaude
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/316#issuecomment-425147531

-- 
Polyna-Maude R.-Summerside

**Comment by Mobiller** [comment]
> The day you'll really need help and finish not getting any answer you'll understand what I mean and end up paying for what you could get for free. We call it advice. When you ask a bad plumber to do repair a leaking faucet, two things happens, first your leak start back pretty soon and later on you get problem when you upgrade. As I get emailed everytime there's something on the gitHub, I go see if it's someone who need help or has a problem with something related. I give chance and I try to be as nice as possible, that's what we call moderating. If you have something real about pH7 then we'll give you a hand. But ask on the right place, like on a PHP forum if it's not related. You seem amused when I give you the example of a serious forum with lots of high end developper. Maybe you should learn what we call community standards.
> […](#)
> On September 27, 2018 11:59:00 AM EDT, Mobiller ***@***.***> wrote: You shouldn't waste your time and precious words with me. Just ignore my questions if you can. Or probably you have some kind of fetish on bullying people with words, that's called Trolling. Thank you for the tip on Googling RTFM, really explanatory. If Pierre-Henry decided to ignore me, it's is because he is doing real work instead of Trolling people. I will be really devastated if I am banned from a Linux Kernel Forum. It will break my heart :( I did not understand "What does it mean you can get bad quality work ? Problem now and later, same when your house get fixed." but I don't really care. Good Luck in life polynamaude -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#316 (comment)](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/316#issuecomment-425147531)
> -- Polyna-Maude R.-Summerside

Dont't worry about my questions, I won't post anymore so I won't disturb you.

If I need help I will ask somewhere. Maybe a serious forum with lots of high end developers.

au revoir
