### ISSUE TITLE
Evaluation Copy On Laptop

### ISSUE THREAD

**Issue by krossphyre** [pH7Software/pH7-Social-Dating-CMS#317]
Hello Pierre

I like your ph7Builder product.  I am considering starting a dating site and would like to install a evaluation copy of your software on my laptop. 

Before I spend a lot of time trying to do that, can you please tell me how difficult is that to install locally on a laptop?

I am in the process of installing Apache and MySQL on my laptop now.  Afterwards PHP.  

Any special instructions?

Thanks
Bruce Frcek

**Comment by polynamaude** [comment]
Hi !
Maybe you should give a look at ph7cms.com so you get more information.

I'd suggest you simply use a shared hosting or a VPS to do your evaluation.

Far from trying to discourage you, I'd suggest you look out for someone with technical knowledge as the only fact to ask such question show that it may not be what you master (system administration).

For sure you can install this thing but what about doing change on the look and feel ? Doing backups ? Managing problem that may arise ?

Yes computing gets easier but the same as having a heart attack may make you gain knowledge in cardiology, it doesn't make you a cardiologist. A running server is like the human body, everything is inter-related and it's pretty easy to make something stupid in Javascript that will allow a hacker to harvest password.

By the way, you must be praying to get "phone" spamed to put your info directly on a open site like here.

Just a bit of thought but surely that you know better than everyone as I'm used of those. And they normally don't even know about privacy and GDPR....

Also, Pierre's in UK and make this for free in free time ? You seem to be expecting maybe more than what's offered for a software that don't cost a penny. (Like pay for a oversea phone call). Too often you guys don't know nothing about open source and end up expecting a "click only" software that won't require you to edit text file and get support like if you'd be paying our mortage...

Now don't shout me an answer but instead be smart and take at least 48 hours to think about what I said. What did you do BEFORE asking here? Any research, looking into the software and attached file, looking at the docs here ??? Or you just think you'll be rich and famous ?

On September 26, 2018 10:14:57 AM EDT, krossphyre <notifications@github.com> wrote:
>Hello Pierre
>
>I like your ph7Builder product.  I am considering starting a dating
>site and would like to install a evaluation copy of your software on my
>laptop. 
>
>Before I spend a lot of time trying to do that, can you please tell me
>how difficult is that to install locally on a laptop?
>
>I am in the process of installing Apache and MySQL on my laptop now. 
>Afterwards PHP.  
>
>Any special instructions?
>
>Thanks
>Bruce Frcek
>561-451-7089
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/317

-- 
Polyna-Maude R.-Summerside

**Comment by krossphyre** [comment]
thanks for the response.  I'm going to close this one out because of the number.  I thought I had erased the  but I guess the copy you got was the original.  If you can delete it I would appreciate it.  I will open a new issue later.  thanks!

**Comment by polynamaude** [comment]
Even if you close, you'll still need to go and edit.

Btw, why do you ask if it's hard to install instead of just doing the installation.

On September 26, 2018 6:42:50 PM EDT, krossphyre <notifications@github.com> wrote:
>Closed #317.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/317#event-1869687122

-- 
Polyna-Maude R.-Summerside
