### ISSUE TITLE
GEOIP2/MAXMIND error

### ISSUE THREAD

**Issue by kirenpillay** [pH7Software/pH7-Social-Dating-CMS#318]
Hi 

I'm getting the following error and my site is broken:
`
Message: | **The address 102.132.41.119 is not in the database**.
-- | --
File: | /usr/local/share/applications/ph7cms/_protected/vendor/geoip2/geoip2/src/Database/Reader.php
Line: | 244
`
`#0 /usr/local/share/applications/ph7cms/_protected/vendor/geoip2/geoip2/src/Database/Reader.php(215): GeoIp2\Database\Reader->getRecord('City', 'City', '102.132.41.119')
#1 /usr/local/share/applications/ph7cms/_protected/vendor/geoip2/geoip2/src/Database/Reader.php(71): GeoIp2\Database\Reader->modelFor('City', 'City', '102.132.41.119')
#2 /usr/local/share/applications/ph7cms/_protected/framework/Geo/Ip/Geo.class.php(134): GeoIp2\Database\Reader->city('102.132.41.119')
#3 /usr/local/share/applications/ph7cms/_protected/framework/Geo/Ip/Geo.class.php(88): PH7\Framework\Geo\Ip\Geo::get(NULL)
#4 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Controller/Controller.class.php(190): PH7\Framework\Geo\Ip\Geo::getCountry()
#5 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Controller/Controller.class.php(50): PH7\Framework\Mvc\Controller\Controller->assignGlobalTplVars()
#6 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Router/FrontController.class.php(566): PH7\Framework\Mvc\Controller\Controller->__construct()
#7 /usr/local/share/applications/ph7cms/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter()
`

**Comment by pH-7** [comment]
Thanks for reporting this error Kiren!
 Apparently the MaxMind 's GeoIP throws now an exception if the IP address isn't found... I will update the class in order to be work with the new GeoIP version.
