### ISSUE TITLE
A suggestion not an issue: Fake Profile Generator

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#319]
Hi, 

This is not an issue but a suggestion

1) When generating fake profiles there should an option to Couples
2) The profiles are created with all lower (john smith, london, case and it would look better capitalize the first letters of names, addresses, cities and estates).

Cheers

**Comment by pH-7** [comment]
Hi @Mobiller 

This cannot be done, because the API used only offers  "male" or "female". They don't have "couple" user data. 
More info: https://randomuser.me/documentation#gender
