### ISSUE TITLE
 Class 'PH7\Framework\Core\Kernel' not found

### ISSUE THREAD

**Issue by gruvin** [pH7Software/pH7-Social-Dating-CMS#32]
_EDIT_
Having now used the pH7 home page to download the ZIP file, instead of cloning from the Git repository, I see that the file that is actually missing in the repository seems to `Kerneltmp.php`.

I suppose it doesn't really matter, now that I know about the home page zip download.
## Original issue description follows ...

Fresh install succeeded (including license key input, etc). But home page just blank. Enabled developer mode. Now I see the following error ...

`Fatal error: Class 'PH7\Framework\Core\Kernel' not found in /*****/_protected/framework/Server/Server.class.php on line 51`

I have searched the entire code base and cannot find any file containing `namespace PH7\Framework\Core\Kernel` -- though of course there are lots of files that try to `use` that class.

My installation was done using `git clone`.

I have also searched the repository on GitHub, but also cannot find the Kernel class definition anywhere. (Have not searched back through previous versions.)

Search I tried ...

```
$ egrep -r '^namespace\s+PH7\\Framework\\Core\\Kernel' *
Vista:pH7-Social-Dating-CMS
$ 
```

Sanity check ...

```
$ pwd
~/www/pH7-Social-Dating-CMS
$ egrep -r '^namespace\s+PH7\\Framework\\Core' *
_protected/framework/Api/Api.class.php:namespace PH7\Framework\Core;
_protected/framework/Core/Core.class.php:namespace PH7\Framework\Core;
_protected/framework/Core/Exception.class.php:namespace PH7\Framework\Core;
$
```

Seems like the master master branch has no record of such a namespace ever existing in the code, either ...

```
$ git log -S 'namespace PH7\Framework\Core\Kernel' -p
$
```

So, what am I missing?

**Comment by exander77** [comment]
What domains should be accessible from the PH7, it is not mentioned anywhere?

**Comment by pH-7** [comment]
hizup.net, hizup.com, ph7cms.com, appspot.com (and all their subdomains).
But normally on a proper live installation you should allow everything... that's why it isn't mentioned.

**Comment by exander77** [comment]
Thank you for the info. I am very strict to what I allow for a webpage. Usually I don't allow anything. So this probably what is causing the problem. What other pages could be contacted and why?
