### ISSUE TITLE
cash not auto clear

### ISSUE THREAD

**Issue by Ghost173** [pH7Software/pH7-Social-Dating-CMS#322]
i try to register my ph7 dating site  

i fill everything then i click register i found this is errors  ```
The following errors were found:

    Error: Invalid email or already used by another user.
    Error: Your Email must contain an email address.
```

but my mail id is 
jpirak***@gmail.com
  
and in my data base there are no email like mine    

if i refresh or ztrl+f5 my previous enter datas not clear   (name user name mail id password) its are showing

**Comment by pH-7** [comment]
Please try with "jpirak@gmail.com" without the `*` asterisks.

**Comment by pH-7** [comment]
Please let me know @Ghost173

**Comment by pH-7** [comment]
@Ghost173, because you didn't get back to me, I assume this issue is solved by now...
Please reopen it if it isn't the case. Thanks!
