### ISSUE TITLE
free-chatroulette-speed-dating  this function not working 

### ISSUE THREAD

**Issue by Ghost173** [pH7Software/pH7-Social-Dating-CMS#323]
hi free-chatroulette-speed-dating not working js enable flash player all are enabled 
1.cant select gender and  other button functions are not working

**Comment by pH-7** [comment]
This is a third-party provider. I'm not able to fix it for them. And yes, it still requires flash... :(
If you aren't happy with it, feel free to host one to your web server or use another chatroulette service. 
You can change the provider easily through your admin panel -> https://ph7cms.com/how-to-change-chat/
