### ISSUE TITLE
Briefing for the next version: pH7CMS 1.2 + Focus on "Dating" + Cleaning useless Features

### ISSUE THREAD

**Issue by pH7Software** [pH7Software/pH7-Social-Dating-CMS#33]
- [x] Change the menu bar, rewrite the design and do it responsive #21 
- [x] Decrease  the number of games. Keep only 3 per category. Currently, there are 11 categories, so 3*11= 33 games. Not more!(after all, everybody can add any games he wants through the admin panel)
- [x] Focus on profiles and relationship, less on features to do everything. Indeed, pH7CMS should focus more on "Dating Site Features Only" and less on a software that does everything even coffee, ...
- [x] Improve the "membership" feature
- [x] Remove the "mobile" module (WAP integration), because it has become obsolete. Now we focus on the same design thanks responsible design
- [x] Remove the "virtual-earth" module

**Comment by pH7Software** [comment]
- Improve the installation (make it easier) -> Done
- Use Bootstrap stylesheets

**Comment by pH7Software** [comment]
- [ ] In License form, add <span class="label label-success">Activate</span>
or if Inactivate <span class="label label-danger">Inactivate</span>
or also <span class="label label-warning">Trial License</span>

**Comment by pH7Software** [comment]
Add
´´´
 <span class="badge">42</span>
´´´ 
In Message menu notification and in content pending moderation

**Comment by pH7Software** [comment]
- [ ] Add ```<button  class="btn btn-primary btn-lg"``` In the installer

**Comment by pH7Software** [comment]
Replace the progress bar by this one in the registration user form
```
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    60%
  </div>
```

**Comment by pH7Software** [comment]
Add progress bar for the steps in the installer 
```
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    60%
  </div>
```

**Comment by pH7Software** [comment]
- [ ] Try maybe to replace the current table in the admin panel of the users with this table

```
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel heading</div>

  <!-- Table -->
  <table class="table">
    ...
  </table>
</div>
```

**Comment by pH7Software** [comment]
- [ ] For comments, textarea things, add this code (or try and see)
```
<textarea  class="well"
```

**Comment by pH7Software** [comment]
- [ ] For browse profiles, change  (or try) into the below code:

```
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x300" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>
```

**Comment by pH7Software** [comment]
- [ ] For image thumbnails, add

```
<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <img data-src="holder.js/100%x180" alt="...">
    </a>
  </div>
  ...
</div>
```

**Comment by pH7Software** [comment]
- [ ] Change alert message (the old one was in alert-msg.css)

**Comment by pH7Software** [comment]
- [x] Fix the bug wen the site in under HTTPS caused with "http://" of googleapis links

**Comment by pH7Software** [comment]
- [ ] HTTPS bug with Google map when the site is under SSL
Change "http://" by "//"

**Comment by pH7Software** [comment]
- [ ] Use/Add  ```class="thumbnail"``` for profile avatar

**Comment by pH-7** [comment]
Now, guest splash page looks like attached

![pro-social-dating-builder-solution-for-business](https://cloud.githubusercontent.com/assets/1325411/12043273/747be578-ae7b-11e5-84cb-f1724ebc969d.png)

**Comment by pH-7** [comment]
And the normal "classic" guest page

![php-social-dating-software](https://cloud.githubusercontent.com/assets/1325411/12043653/fe916352-ae7e-11e5-83e8-3296fb857325.png)

**Comment by pH-7** [comment]
The Attractive Join page showing the interested profile + avatar to the guest wanted join the social/dating site

![ph7-social-dating-cms-signup-page](https://cloud.githubusercontent.com/assets/1325411/12043681/364218e6-ae7f-11e5-9deb-b994a57de495.png)

**Comment by pH-7** [comment]
Ad (advertising, 336x280px square banner) Block on profile page

![ad-block-profile-page](https://cloud.githubusercontent.com/assets/1325411/12043718/807ad25e-ae7f-11e5-9227-f2553b044a17.png)

**Comment by pH-7** [comment]
Other new **Social / Dating ** templates made
Find them below (1.3.7 version):

![ph7cms-social-city-new-york](https://cloud.githubusercontent.com/assets/1325411/14080218/84d2f9b8-f4fb-11e5-90e2-36c139f0eb66.png)

![ph7-zendate-social-template](https://cloud.githubusercontent.com/assets/1325411/14080217/84ca02c2-f4fb-11e5-941d-dedc0354dafd.png)

![ph7cms-city-date-dating-template](https://cloud.githubusercontent.com/assets/1325411/14080219/84d3ad5e-f4fb-11e5-972c-e7c9dd229b52.png)

**Comment by pH-7** [comment]
User Browse Feature (in this case with **11,562 users**

![ph7cms-user-browse](https://cloud.githubusercontent.com/assets/1325411/14080251/b476e5c6-f4fb-11e5-825e-ddc992ba1055.png)

**Comment by pH-7** [comment]
pH7CMS 3 has several design improvements.

New screenshots for the splash homepage

**Comment by pH-7** [comment]
![screen shot 2016-10-16 at 00 45 58](https://cloud.githubusercontent.com/assets/1325411/19419476/5475b32c-93d0-11e6-9756-8e7db8df129f.png)

![screen shot 2016-10-16 at 00 46 44](https://cloud.githubusercontent.com/assets/1325411/19419477/5476b45c-93d0-11e6-823d-d293f186c0f7.png)

![screen shot 2016-10-16 at 00 48 41](https://cloud.githubusercontent.com/assets/1325411/19419479/6552402a-93d0-11e6-89ac-14c94b8b726c.png)

![screen shot 2016-10-16 at 00 47 10](https://cloud.githubusercontent.com/assets/1325411/19419481/657386a4-93d0-11e6-8eee-95deba2d30a0.png)

![screen shot 2016-10-16 at 00 48 01](https://cloud.githubusercontent.com/assets/1325411/19419480/65738a1e-93d0-11e6-9fbe-a48fa36fc53a.png)

**Comment by pH-7** [comment]
<img width="750" alt="csrf-settings-ph7cms_4" src="https://cloud.githubusercontent.com/assets/1325411/20458781/3f3c8ef4-aea6-11e6-80ec-2704a52c46eb.png">

**Comment by pH-7** [comment]
<img width="1268" alt="screen shot 2016-11-19 at 21 54 06" src="https://cloud.githubusercontent.com/assets/1325411/20458783/489aa288-aea6-11e6-9723-b44e52da45f7.png">

**Comment by pH-7** [comment]
This can be now considered as "done". After 3 years of intensive development! 😃

**Comment by pH-7** [comment]
New screenshot samples 🎉 

<img width="1304" alt="screen shot 2018-06-14 at 5 46 33 pm" src="https://user-images.githubusercontent.com/1325411/41442323-4271cd28-6ffc-11e8-9ec8-bc407113c27a.png">
<img width="1216" alt="screen shot 2018-06-14 at 5 46 15 pm" src="https://user-images.githubusercontent.com/1325411/41442324-428e2acc-6ffc-11e8-9036-83039ad91b5e.png">
<img width="1232" alt="screen shot 2018-06-14 at 5 57 45 pm" src="https://user-images.githubusercontent.com/1325411/41442376-7beab98e-6ffc-11e8-93a6-4d6a67a71991.png">
<img width="1266" alt="screen shot 2018-06-14 at 5 57 33 pm" src="https://user-images.githubusercontent.com/1325411/41442377-7c04f0ec-6ffc-11e8-83d9-fbc39c1691de.png">
