### ISSUE TITLE
Regarding self activation mail

### ISSUE THREAD

**Issue by PRINCEPANNU** [pH7Software/pH7-Social-Dating-CMS#331]
So i had enabled the feature self activation mail but no mail is getting by user after sign up what should i do

**Comment by pH-7** [comment]
Are you on local host? If so, you will need to install a SMTP server. If you are with a web host, please ask them if your SMTP server is correctly configured and check its log.

Finally, make sure the email isn't in the spam folder.

More info: https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

**Comment by pH-7** [comment]
Please let me know if this helps @PRINCEPANNU Thanks

**Comment by PRINCEPANNU** [comment]
Thansk
