### ISSUE TITLE
The problem with Russian names

### ISSUE THREAD

**Issue by uebsite** [pH7Software/pH7-Social-Dating-CMS#334]
I can not create the names of forums, files, etc. In Russian. How to fix?

**Comment by pH-7** [comment]
Do you mean that the names aren't validated and you get a form error message?

If so, please change this regex for the names https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/61c47c14f66090949fa6b33005b785ff61b6dcd5/_protected/framework/Security/Validate/Validate.class.php#L30

And concerning the forum subjects, please change this regex in the forum config file https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/forum/config/config.ini#L18

This is done to avoid junk contents added by users and keep your database clean. 
It’s a good feature for most of the languages, but obviously not for Cyrillic alphabet (and also for the non-alphabetic languages such as Chinese, Japanese, Korean, …). 
In that case, you can change it easily like how I explained.

Hope this helps 😊

And I wish you all the best with your social dating Web service! 🚀

Take care,
Pierre

**Comment by pH-7** [comment]
And if RegEx scares you, you can have a look to 
https://regexone.com/references/php
and https://www.tutorialspoint.com/php/php_regular_expression.htm

Hope it helps! 💪

**Comment by pH-7** [comment]
@uebsite In case, you don't know what it means [GitHub ★](https://help.github.com/articles/about-stars/). Please let me know if needed.
