### ISSUE TITLE
Allow multiple registrations with the same IP in a short delay

### ISSUE THREAD

**Issue by PRINCEPANNU** [pH7Software/pH7-Social-Dating-CMS#335]
While user is signup it shows that someone has already registered with same ip address how to shortoutt the problem

**Comment by pH-7** [comment]
You can change the sign up delay as simple as that -> Admin Panel -> Setting -> General -> Registration delay for Users (change the amount in minutes or enter "0" to disable it).

**Comment by pH-7** [comment]
You can change the sign up delay as simple as that -> Admin Panel -> Setting -> General -> Spam tab -> Registration delay for Users (change the amount in minutes or enter "0" to disable it).

**Comment by PRINCEPANNU** [comment]
But users are using are ip address still that same ip address problem
occurred
