### ISSUE TITLE
Upgrade instructions missing

### ISSUE THREAD

**Issue by kirenpillay** [pH7Software/pH7-Social-Dating-CMS#345]
The instructions on how to upgrade an existing installation don't seem to be documented anywhere visible. 

I need to upgrade my server now and am not sure what to do.

**Comment by pH-7** [comment]
Hey @kirenpillay! How are you?

Well... this is the doc https://ph7cms.com/doc/en/upgrade (however, everything could not work as excepted... 👌).
I'm working on something easier to update using the GitHub API, but  hasn't been released yet).

Hopefully, it can helps. And don't hesitate to give feedback/PRs 😃 Thanks!

P.S. If you downloaded it from Sourceforge, I realized that the upgrade files aren't included in the zip archive available on Sourceforge, so you will need to download them. You can download them from the master GitHub repository.

**Comment by pH-7** [comment]
On what version are you? Yes, just do a pull from master, then run the correct SQL script depending on the version you are (so, you might have a few to run if you are on a older one).

Supposing you are on 14.3.4, and you want to upgrade to 14.3.6, please run https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_repository/upgrade/14.3.4-14.3.6/data/sql/MySQL/upgrade.sql

Finally, when everything is done, don't forget to clear all caches https://ph7cms.com/doc/en/how-to-clear-caches

**Comment by pH-7** [comment]
On what version are you? Yes, just do a pull from master, then run the correct SQL script depending on the version you are (so, you might have a few to run if you are on an older one).

Supposing you are on 14.3.0, and you want to upgrade to 14.3.4, please run https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_repository/upgrade/14.3.0-14.3.4/data/sql/MySQL/upgrade.sql

Finally, when everything is done, don't forget to clear all caches https://ph7cms.com/doc/en/how-to-clear-caches

**Comment by pH-7** [comment]
I'm closing it by now @kirenpillay 

Hope it helps 😄 

Please reopen it if something wrong occurs. Thanks :)

**Comment by kirenpillay** [comment]
Hi Pierre-Henry,

Sorry, I work on this web site in my spare time, only had a chance to look at this now.

I've pulled from master and run the upgrade scripts, that was well done:)

However there are 2 issues:
1. I can't clear the cache because my admin panel is throwing an exception (because of a cache issue I think). Maybe a clear cache step before the upgrade would help?

2. A previous issue regarding GEOIP hasn't been resolved, see stack trace below. 
Trace: | #0 /usr/local/share/applications/ph7cms/_protected/vendor/geoip2/geoip2/src/Database/Reader.php(215): GeoIp2\Database\Reader->getRecord('City', 'City', '102.132.44.174') #1 /usr/local/share/applications/ph7cms/_protected/vendor/geoip2/geoip2/src/Database/Reader.php(71): GeoIp2\Database\Reader->modelFor('City', 'City', '102.132.44.174') #2 /usr/local/share/applications/ph7cms/_protected/framework/Geo/Ip/Geo.class.php(134): GeoIp2\Database\Reader->city('102.132.44.174') #3 /usr/local/share/applications/ph7cms/_protected/framework/Geo/Ip/Geo.class.php(88): PH7\Framework\Geo\Ip\Geo::get(NULL) #4 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Controller/Controller.class.php(190): PH7\Framework\Geo\Ip\Geo::getCountry() #5 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Controller/Controller.class.php(50): PH7\Framework\Mvc\Controller\Controller->assignGlobalTplVars() #6 /usr/local/share/applications/ph7cms/_protected/framework/Mvc/Router/FrontController.class.php(566): PH7\Framework\Mvc\Controller\Controller->__construct() #7 /usr/local/share/applications/ph7cms/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #8 /var/www/vegdating.co.za/pH7-Social-Dating-CMS/index.php(46): PH7\Bootstrap->run() #9 {main}
-- | --




I want to upgrade, however I

Regards
Kiren

**Comment by polynamaude** [comment]
Have you tried simply clearing the folder through your shell account (using _rm_).

**Comment by kirenpillay** [comment]
Hi

I have tried this but I'm still getting this error. Note that I'm running
off master, maybe I should switch it to the 14.3.6 tag?

I just upgraded the database using the scripts, do I still need to run
*http://YOUR-DOMAIN.COM/
<http://YOUR-DOMAIN.COM/>asset/file/Upgrade  ?*

Regards
Kiren

**Comment by polynamaude** [comment]
You have two choice : 
First one is to download the standard distribution from SourceForge and follow the instruction given.
Second one is to use a git repository but you'll have to get yourself the third party library using **composer**.

In your case it may be easier to follow the straight instruction given and go with the Sourceforge archives.

Repository on gitHub don't contain external library as there's no need to host twice the same piece of software.

**Comment by kirenpillay** [comment]
Thank you.

I managed to install the 3rd party libraries via composer, however I'm
getting an error about a method thats unknown which probably means mixed up
code in my installation.

Can I start a brand new software installation, while keeping the exact
database intact?

Regards

**Comment by polynamaude** [comment]
Hi,
From years of helping people and doing consulting, I'd give an answer as a mathematical equation.

You seem to be trying to save time or work, but what's the gain expected ? Pretty much none.

What's the advantage possible, pretty much the same answer.

What are the risk ? It should be possible, but why do so when you can simply start a clean install and be sure everything work good ?

There's a technique called the _stable state_. What it simple means is to get the system into a state that you know that everything is as it should be and work from there. For example, sometime you have to do a clean install of a software or use backup that we're done before data get corrupted. You could surely try to fix the corrupted state but you always carry the risk of having something in-between.

As I understand you didn't go over hours of configuration or anything else, at most a 15 minutes job. So where's the need to preserve what's done ? Go clean !

**Comment by kirenpillay** [comment]
I hear you, a clean install would be great except I have a live subscriber
base I want to preserve. I did the upgrade to get rid of some bugs that
where affecting me. I just don't look at this installation much, which is
why I've forgotten about the _protected folder setup :)

Pierre Henry has given me a solution which I will try today.

Regards
Kiren
