### ISSUE TITLE
function.preg-replace: Compilation failed

### ISSUE THREAD

**Issue by jay0kay** [pH7Software/pH7-Social-Dating-CMS#349]
Attached are screenshots of: -

1) Debug at the line of code which causes the exception along with the called function parameters [locals].

2) The browser output showing the error messages and call stack.

![predefined_class_php-addfunc exception](https://user-images.githubusercontent.com/44788256/48165178-abee3e00-e2dc-11e8-9a57-195b5eeaa4c1.png)
![curly-parse exception](https://user-images.githubusercontent.com/44788256/48165179-abee3e00-e2dc-11e8-8381-d3099b1be0bf.png)

**Comment by pH-7** [comment]
Hi again @jay0kay 

Please follow the instructions I gave to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/348#issuecomment-437118675

**Comment by pH-7** [comment]
Closing this one as a duplicate (https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/348).

**Comment by pH-7** [comment]
P.S. FYI, there is nothing is wrong with the `preg_replace` function. This is how the template engine works 😊

**Comment by jay0kay** [comment]
Thank you for the reply in the #348. I have zero doubt that the template functions work, but for some reason my installation is not working and the error messages are far from obvious as to the reason why.

I downloaded all the files from sourgeforce again and they matched the size/number of original installation but I started from scratch with the new download files for a clean install.

I once again created a new database with collation utf8mb4 and a user with full privileges for the d/b.

Re-installed ph7cms which completed successfully and have the identical result as detialed above. FYI during installation, I did try and move the _protected folder to the folder above htdocs but when I clicked next a blank screen was displayed in the browser so I continued with the default location.

http://localhost:8080/index.php produces a different error message to http://localhost:8080/ so I have 
provided screenshots of the debug code and variables which throw the exception plus the output.

![frontcontroller-indexfilerouter exception](https://user-images.githubusercontent.com/44788256/48279454-926a0500-e448-11e8-816e-61c39b820901.png)

![index_php exception](https://user-images.githubusercontent.com/44788256/48279380-55057780-e448-11e8-86af-c56d1040e9b9.png)

**Comment by polynamaude** [comment]
Maybe I could add that WAMP is not a production platform so the support and test is pretty limited. 
As for the error message, I think it's obvious enough that it has to do with the way Windows translate the file name and folder names. So your main index file is not being recognised.

Run a virtual machine with Linux (w/o GUI doesn't require much power) or try using XAMPP (BitNami stack). I've got more good feedback of user using BitNami that told us it work.

https://www.apachefriends.org/bitnami_for_xampp.html

In all case, Windows is not really a supported platform.
