### ISSUE TITLE
clean install, framework\Mvc\Router\FrontController.class.php exception

### ISSUE THREAD

**Issue by jay0kay** [pH7Software/pH7-Social-Dating-CMS#351]
Thank you for the reply in the #348. I have zero doubt that the template functions work, but for some reason my installation is not working and the error messages are far from obvious as to the reason why.

I downloaded all the files from sourgeforce again and they matched the size/number of original installation but I started from scratch with the new download files for a clean install with no code or template changes. And yes I checked that the templates files were there and lauout.tpl tags matched.

I once again created a new database with collation utf8mb4 and a user with full privileges for the d/b.

Re-installed ph7cms which completed successfully and have the identical result as detailed in #349. FYI during installation, I did try and move the _protected folder to the folder above htdocs but when I clicked next a blank screen was displayed in the browser so I continued with the default location.

http://localhost:8080/index.php produces a different error message to http://localhost:8080/ so I have
provided screenshots of the debug code and variables which throw the exception plus the output.

![frontcontroller-indexfilerouter exception](https://user-images.githubusercontent.com/44788256/48279937-f6d99400-e449-11e8-9321-ae55a1574711.png)

![index_php exception](https://user-images.githubusercontent.com/44788256/48279947-fd680b80-e449-11e8-9cc7-922ce9525697.png)

**Comment by pH-7** [comment]
Concerning your initial error, I'm not really sure what's happening with your installation, but something is definitely wrong with it. 
If you want to have your website running, please install pH7CMS on your live web hosting (and ditch your dev local host).

Concerning your second concern, like I said in the docBlock in the code you just posted as screenshot, please don't access to your website with `/index.php`

**Comment by pH-7** [comment]
Hopefully, you will get it working very soon. Wish you all the best.

I'm closing it by now.
