### ISSUE TITLE
500 Internal Error Hostgator/Shared Hosting

### ISSUE THREAD

**Issue by nerfthis2019** [pH7Software/pH7-Social-Dating-CMS#352]
I have uploaded pH7 to my host (Hostgator). I unzipped the files into my public_html folder. I have double checked and I am running the requirements for PHP/Mysql. I have went through a few of the other issues regarding 500 internal error with no resolve. I can't even install it, simply after I uploaded it and tried to go to install it I got a 500 Internal Error Message. Hostgator uses PHP in CGI. I'm not sure if that's whats effecting it, I went through their PHP selector and modified their PHP.ini file and all of the mods that I could fine seem to be enabled by default already. I'm just confused as to what to do if I can't even get to the install page. Thanks in advance.

**Comment by nerfthis2019** [comment]
Solution: 
Hostgator is shit

**Comment by polynamaude** [comment]
Did you really had a need to open a issue and share this with others ?

**Comment by nerfthis2019** [comment]
Well I was really pissed at Hostgator because I troubleshooted this issue
all night just to come to the conclusion that Hostgator is really on PHP
5.4. I uploaded to dreamhost, and tried on a local server and it worked
perfectly fine. So in a nutshell avoid Hostgator when it comes to pH7.

**Comment by polynamaude** [comment]
@nerfthis2019  Maybe you should read back your post. You start by saying that you checked all the requirements and that they we're good. If you would have done it properly then you would have checked the version of PHP they use.

And just to add something useless, check your control panel because you can change your PHP version ;-)

**Comment by nerfthis2019** [comment]
I'm not sure why you're so passive aggressive but you can honestly smd.
Hostgator claims to use 5.6+ when I checked what PHP version it was truly
using it was 5.4. I set it to 7.1 which they claim to offer yet it never
would work even after getting rid of the custom php.ini's. You should
really learn how to talk to people before you respond to them in a
derogatory manner. Someone might someday kick your ass and it sure could be
me.
