### ISSUE TITLE
Custom questions

### ISSUE THREAD

**Issue by bilalsammour** [pH7Software/pH7-Social-Dating-CMS#356]
Hi,
I love pH7, really I love you developer.

Can I add custom question in the profile? Also can I remove some predefined questions?

Thank you

**Comment by pH-7** [comment]
Hi @bilalsammour 
Thanks very much for your feedback. I always appreciate this kind of comment :)
Absolutely, you can do it. However, at the moment you can only change a few fields through Admin -> User/Admin -> Users -> Fields.

However, you can do much more by modifying the https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/views/base/tpl/profile/index.tpl file.
Or thif you enabled the fancy profile page,  https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/cool-profile-page/views/base/tpl/main/index.tpl

**Comment by pH-7** [comment]
@bilalsammour Psst, don't forget to Star the repository as well :)
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by bilalsammour** [comment]
Yes I got it.
So I can add just text field question? What about drop down list?

**Comment by pH-7** [comment]
Only text fields. If you want drop down list, it will involves more changes.

**Comment by pH-7** [comment]
Once this question is solved for you, please close it. In that way, it's easier for me to help and know which one is still a relevant problem..

**Comment by pH-7** [comment]
And don't forget to Star the repo @bilalsammour :)

**Comment by pH-7** [comment]
And don't forget to Star the repo as well @bilalsammour 😊
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by bilalsammour** [comment]
I have stared this great project. I am closing this ticket.
