### ISSUE TITLE
Problem on my webhost

### ISSUE THREAD

**Issue by yanpablo** [pH7Software/pH7-Social-Dating-CMS#357]
Hello, I installed ph7cms on a local server (xampp server on windows) and it works perfectly, I adapted and modified files and templates and everything works perfectly on a local server. Then i transferred the files to my host O2switch (shared linux server) and there I have problems, during the new member registering process, just after validating the step 2/3, I have the following error message :

_Fatal error: Uncaught Error: Class 'PFBC\Element\CheckBox' not found in /home/yanpablo971/public_html/_sunny/app/system/modules/user/forms/JoinForm.php:181 Stack trace: #0 /home/yanpablo971/public_html/_sunny/data/cache/pH7tpl_compile/user_cfab3e016ef07db2e5a8914a29961fcb/base/signup/step3.cpl.php(19): PH7\JoinForm::step3() #1 /home/yanpablo971/public_html/_sunny/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(401): require('/home/yanpablo9...') #2 /home/yanpablo971/public_html/_sunny/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('signup/step3.tp...', '_sunny/app/syst...') #3 /home/yanpablo971/public_html/_sunny/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(401): require('/home/yanpablo9...') #4 /home/yanpablo971/public_html/_sunny/framework/Mvc/Controller/Controller.class.php(82): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/yanpablo9...') #5 /home/yanpablo971/public_html/_sunny/app/system/module in /home/yanpablo971/public_html/_sunny/app/system/modules/user/forms/JoinForm.php on line 181_

I'm looking for where the problem is from for several days but without success.

can someone help me please ?
thanks for your advices.

**Comment by pH-7** [comment]
Welcome @yanpablo! 🎉

On line 181 (located in `~/public_html/_sunny/app/system/modules/user/forms/JoinForm.php`), I can see that you added a new checkbox field. However, you made a typo with the capitalization of class name. Please change "CheckBox" to "Checkbox". 
For your information, the class filename couldn't be found because file systems are case-sensitive with Linux servers (not the case with Windows operating systems).

**Comment by yanpablo** [comment]
Hello Pierre-Henri, thank you for your quick response, I forgot the difference between Linux and Windows, case sensitive, now, it works perfectly on both platforms.

A thousand times thank you
and God bless you.

(Je crois que vous êtes francophone, 
alors je vous le dit également en français car j'habite sur Nice :
Mille fois merci et que Dieu vous bénisse.)

**Comment by pH-7** [comment]
De rien @yanpablo! Cela me fait plaisir de vous aider ;)
Si vous avez une minute devant vous, ça me ferait plaisir si vous pouviez laisser un avis sur https://sourceforge.net/projects/ph7socialdating/ Cependant, vous devez créer un compte pour pouvoir laisser un avis (donc, je peux comprendre si vous n'avez pas le temps).

Oh Nice, très belle ville :) 🌞
