### ISSUE TITLE
Male to female, Female to male (only hetero website)

### ISSUE THREAD

**Issue by bilalsammour** [pH7Software/pH7-Social-Dating-CMS#358]
Hello,
Thank you for this lovely CMS.

I want to build a date to marriage website, in my culture the marriage is between male and female, so, the male is interested just in female and the female is interested just in the male.

I need to remove (interested in) from registration page and search page as well.

How can I do that?

**Comment by pH-7** [comment]
Hi again @bilalsammour !

Excellent question!

To do so, 

1.  Please remove the following https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/71f1f07d3c567a80df59f9f83bceed0e5cc2112a/_protected/app/system/modules/user/forms/JoinForm.php#L107-L118 in `_protected/app/system/modules/user/forms/JoinForm.php`
2. In https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/07c28b78e7fb985ada6b6da5608634dff6a2fd74/_protected/app/system/modules/user/forms/processing/JoinFormProcess.php#L105 
Please change 
```php
'match_sex' => Form::setVal($this->httpRequest->post('match_sex', Http::NO_CLEAN)),
```
to
```php
'match_sex' => ($this->httpRequest->post('sex') === 'female') ? 'male' : 'female',
```


And finally, concerning the search form (simpler 😅), please remove
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/6434bc2ab6999f1a2dcb9c879deca798f81583ad/_protected/app/system/core/forms/SearchUserCoreForm.php#L62-L73
AND
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/6434bc2ab6999f1a2dcb9c879deca798f81583ad/_protected/app/system/core/forms/SearchUserCoreForm.php#L113-L124 
 in `_protected/app/system/core/forms/SearchUserCoreForm.php`

P.S. I didn't test it, but hopefully this should do the job 🤞

**Comment by pH-7** [comment]
Oh, BTW, I was eating my dinner I realized that I forgot something concerning the search results.
Indeed, you will also have to change the line 334 https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/c86e3411ccc63426e7a26c10f4bb9e4082ed7373/_protected/app/system/core/models/UserCoreModel.php#L334 in `_protected/app/system/core/models/UserCoreModel.php`

On that line, change
```php
$bIsSex = !$bIsMail && !empty($aParams[SearchQueryCore::SEX]) && is_array($aParams[SearchQueryCore::SEX]);
```
to the following
```php
if (!$bIsMail && !empty($aParams[SearchQueryCore::MATCH_SEX])) {
    $bIsSex = true;
    $aParams[SearchQueryCore::SEX] = ($aParams[SearchQueryCore::MATCH_SEX] === 'female') ? 'male' : 'female';
} else {
    $bIsSex = false;
}
```

P.S. Once again, please note that I didn't test the code, but it should be pretty much what you need 🙂

**Comment by bilalsammour** [comment]
Thank you,

For the registration form, it works.

For search, I got 500 error in both quick and advanced search.

**Comment by bilalsammour** [comment]
I will write a new ticket to be a suggestion to help you.

**Comment by pH-7** [comment]
Please enable the development mode (Admin Panel -> Tools -> Environment Mode), and refresh the page and give me the error there.

**Comment by bilalsammour** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to PH7\UserCoreModel::getSexInClauseSql() must be of the type array, string given, called in /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/app/system/core/models/UserCoreModel.php on line 375 and defined in /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/app/system/core/models/UserCoreModel.php:1630 Stack trace: #0 /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/app/system/core/models/UserCoreModel.php(375): PH7\UserCoreModel->getSexInClauseSql('female') #1 /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/app/system/modules/user/controllers/BrowseController.php(39): PH7\UserCoreModel->search(Array, true, 0, 0) #2 [internal function]: PH7\BrowseController->index() #3 /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/framework/Mvc/Router/FrontController.class.php(614): ReflectionMethod->invokeArgs(Object(PH7 in /Users/bilalsammour/Professional/Development/Projects/Web/htdocs/p/ph7/_protected/app/system/core/models/UserCoreModel.php on line 1630

**Comment by pH-7** [comment]
Haha, my bad!

Indeed, `$aParams[SearchQueryCore::SEX]` must be an array. I updated my previous post with the correct code.

So, please update https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/c86e3411ccc63426e7a26c10f4bb9e4082ed7373/_protected/app/system/core/models/UserCoreModel.php#L334

from
```php
$bIsSex = !$bIsMail && !empty($aParams[SearchQueryCore::SEX]) && is_array($aParams[SearchQueryCore::SEX]);
```

to the following:

```php
if (!$bIsMail && !empty($aParams[SearchQueryCore::MATCH_SEX])) {
    $bIsSex = true;
    $aParams[SearchQueryCore::SEX] = [($aParams[SearchQueryCore::MATCH_SEX] === 'female') ? 'male' : 'female'];
} else {
    $bIsSex = false;
}
```

This should work! 🎉

Please let me know. Thanks

**Comment by bilalsammour** [comment]
Worked!

Thank you.

I think it should be a good idea to be a settings option.

**Comment by pH-7** [comment]
Happy to hear that @bilalsammour 
If you are happy with the software and the time I spent to build it and help, I would be really happy if you can add a review at https://sourceforge.net/projects/ph7socialdating/ (you will just have to create an account in order to write a review).
This really motivates me to continue developing the software.

Thanks for understanding :)

**Comment by pH-7** [comment]
Hi again @bilalsammour, Happy to hear that!

If you are happy with the software and the time I spent to build it and help, I would be really happy if you can add a review at https://sourceforge.net/projects/ph7socialdating/ (you will just have to create an account in order to write a review).
This really motivates me to continue developing the software.

Thanks for understanding :)

**Comment by bilalsammour** [comment]
Done

**Comment by bilalsammour** [comment]
So you will add it as an option?

**Comment by pH-7** [comment]
I really appreciate it @bilalsammour! Many thanks. At the moment, it won't be added as an option.. I will reply to your suggestion post with full details.
