### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by archmod** [pH7Software/pH7-Social-Dating-CMS#361]
Can't install mod_rewrite on my WAMP server. 
Im stuck, I dont know how to get to the console and input "sudo a2enmod rewrite"
I've tried entering it into CMD and the MySQL console

I'm very new to the scene and any help would be greatly appreciated

**Comment by polynamaude** [comment]
As you wrote "WAMP" (Windows Apache MySQL/MariaDB and PHP) then I'll make the assumption that you are running windows.

The command **_sudo_** is a UNIX command, not a windows one. Sorry but we don't offer support for the WAMP stack here. Maybe you can check at Bitnami support forum and you'll get a better chance.
If you want to do whatever more than just looking around then go with a Linux box, if you want to stick with Windows the get a BitNami base installation. It should already include the mod_rewrite module.

When you ask for help, do it at the good place. It's not a Apache support forum here, neither a WAMP support forum. An issue is a problem (bug) or a something that you want to get fixed, not general support about all computer problems.

Good luck !
