### ISSUE TITLE
not working in Chrome

### ISSUE THREAD

**Issue by zeze6** [pH7Software/pH7-Social-Dating-CMS#365]
Firefox all good but Chrome

**Comment by pH-7** [comment]
What's the problem? Please be more specific. Give as much as details as you can, otherwise I won't be able to help you.

**Comment by zeze6** [comment]
suddenly the website stopped working in Chrome, it gives me blank page with no error,  after couple of hours it stopped working in Firefox as well
i looked at log file and found out that i have to change Options -Indexes to Options +Indexes
fixed
i did not touch any file before, it was working but why this happened i don't know.
thank you for this good software, i'm testing it at moment and i might run it for long term

**Comment by polynamaude** [comment]
@zeze6 There's no such thing as "it works for Firefox but not for Chrome". A web server just does what it's name says and "serve web pages". Now if you web client (browser) does not present it properly then it's something related to your browser and not your CMS or the web server underneath it.

In all case, when such problem do arise the first thing to do is to either use a "private browsing session" or clear your cache. It will make sure that what you are looking at is not something that was held in the cache and by the same time a older version. What you described as a difference between those two is simply related to the fact that you must be using Chrome more often and the web pages are cached.

The .htaccess file does not change by itself or by the act of magic. The use of +Indexes simply says to your web server that in the case the user does not request a specific page then serve the index as configured (with the **DirectoryIndex** directive)

**Comment by zeze6** [comment]
@polynamaude cool
i'm having some server issues
thank you
