### ISSUE TITLE
The following error was found: 

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#373]
Hi i have this error (The following error was found:
Oops! Somebody has recently registered with the same IP address. You have to wait 1 day before try again.)

i replaced the code file as provided but it still shows error, Thanks
------

<?php
/**
 * @title            Form Class
 * @desc             Class offering useful methods for the management of forms.
 *                   It allows, among other display popular predefined messages to avoid duplicate text (message) similar.
 *
 * @author           Pierre-Henry Soria <ph7software@gmail.com>
 * @copyright        (c) 2012-2018, Pierre-Henry Soria. All Rights Reserved.
 * @license          GNU General Public License; See PH7.LICENSE.txt and PH7.COPYRIGHT.txt in the root directory.
 * @package          PH7 / Framework / Layout / Form
 * @version          1.0
 */
namespace PH7\Framework\Layout\Form;
use PH7\Framework\Core\Core;
abstract class Form extends Core
{
    /**
     * Launch Error Token Message.
     *
     * @return string
     */
    public static function errorTokenMsg()
    {
        return t('The security token does not exist or the security time of the token has expired. Please try again!');
    }
    /**
     * Launch Wrong Image File Type Message.
     *
     * @return string
     */
    public static function wrongImgFileTypeMsg()
    {
        return t('The file type is incompatible or too large. Please try again a smaller image with .gif, .png or .jpg extension.');
    }
    /**
     * Launch Wrong Video File Type Message.
     *
     * @return string
     */
    public static function wrongVideoFileTypeMsg()
    {
        return t('The file type is incompatible or too large. The accepted file types are: .mov, .avi, .flv, .mp4, .mpg/.mpeg, .wmv, .ogg, .ogv, .webm or .mkv');
    }
    /**
     * Launch Wrong HTTP Request Method Message.
     *
     * @param string $sMethodName
     *
     * @return string
     */
    public static function wrongRequestMethodMsg($sMethodName)
    {
        return t('The HTTP parameter must be a %0% type!', $sMethodName);
    }
    /**
     * Launch an Error Sending Email.
     *
     * @return string
     */
    public static function errorSendingEmail()
    {
        return t('Oops! Our email server encountered an internal error and the email could not be sent. Please try again later!');
    }
    /**
     * Number of connection attempts exceeded.
     *
     * @param int $iWaitTime
     *
     * @return string
     */
    public static function loginAttemptsExceededMsg($iWaitTime)
    {
        return t('Oops! You have exceeded allowed login attemts. Please try again in %0% %1%.', static::convertTime($iWaitTime), static::getTimeText($iWaitTime));
    }
    /**
     * @return string
     */
    public static function duplicateContentMsg()
    {
        return t('Oops! It seems that you have already sent the same message to prevent spam you can not send multiple same content.');
    }
    /**
     * @return string
     */
    public static function tooManyUrlsMsg()
    {
        return t('Oops! It seems that you abuse of links. Why links are that important for you...?');
    }
    /**
     * @return string
     */
    public static function tooManyEmailsMsg()
    {
        return t('Oops! It seems that you abuse of emails. Why emails are that important for you...?');
    }
    /**
     * Wait to write a new message (mainly to reduce spam).
     *
     * @param int $iWaitTime (in minutes)
     *
     * @return string
     */
    public static function waitWriteMsg($iWaitTime)
    {
        return t('Oops! You have to wait %0% %1% before you can send another.', static::convertTime($iWaitTime), static::getTimeText($iWaitTime));
    }
    /**
     * Wait to new registration (mainly to reduce spam).
     *
     * @param int $iWaitTime (in minutes)
     *
     * @return string
     */
    public static function waitRegistrationMsg($iWaitTime)
    {
        return t('Oops! Somebody has recently registered with the same IP address. You have to wait %0% %1% before try again.', static::convertTime($iWaitTime), static::getTimeText($iWaitTime));
    }
    /**
     * Get Time text.
     *
     * @param int $iWaitTime
     *
     * @return int
     */
    private static function getTimeText($iWaitTime)
    {
        $iWaitTime = (int)$iWaitTime;
        return ($iWaitTime < 2 ? t('minute') : ($iWaitTime < 60 ? t('minutes') : ($iWaitTime < 120 ? t('hour') : ($iWaitTime < 1440 ? t('hours') : ($iWaitTime < 2880 ? t('day') : t('days'))))));
    }
    /**
     * Conversion time if necessary (we do not do the conversion of minutes so you should rather take hours sharp (same thing for days).
     *
     * @param int $iWaitTime
     *
     * @return int
     */
    private static function convertTime($iWaitTime)
    {
        $iWaitTime = (int)$iWaitTime;
        if ($iWaitTime > 60) {
            $iDivide = ($iWaitTime < 1440) ? 60 : 1440;
            $iWaitTime = floor($iWaitTime / $iDivide);
        }
        return $iWaitTime;
    }
}

**Comment by pH-7** [comment]
This is to prevent flood on your website.

You can change it as simple as that.
Admin Panel -> Setting -> General -> Spam ->  Registration delay for Users, and update the number to "0" to disable it (or simply decrease the number of minutes).

**Comment by chalit9999** [comment]
Thank you very much for your help, it's a good idea to prevent from flood, should i set to 0 or any less number?  and one more question , should i activate Captcha for User Signup Form? Thanks again and merci beaucoup

**Comment by pH-7** [comment]
You are very welcome @chalit9999 

At the moment, your website probably don't get a lot of visitors, so you shouldn't bother you wasting time with this. If you really want an amount, keep "1440" (1440 minutes = 24 hours).

**Comment by pH-7** [comment]
Concerning the captcha, once again, please disable it at the moment to avoid bothering users on your website, and re-enable it once you get spam... 

P.S. Pro Tip: Be focus on marketing and see how you could drive more users on your website instead of wasting time on things that don't really matter when you don't have traction :) Hope it helps :)

**Comment by chalit9999** [comment]
Thank you so much for your support, i will definitely rate you 5 or even 6
star if possible, i really like this program, i'm not online at the moment
i just have to choose the right name for it and then i will let you know
as  soon as it's online so you can give some advice, to be honest i don't
know how to do marketing, can you suggest what i have to do ?   Thanks
again from Chalit

ในวันที่ อ. 27 พ.ย. 2018 เวลา 17:25 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:

**Comment by pH-7** [comment]
Very good @chalit9999 
Sorry, but I can't really give suggestions for your marketing. I was just an advice, but now it's much more complex, and cannot stand in a comment :) Hope you understand.

**Comment by chalit9999** [comment]
don't worry, i 'll find the way. :-)

ในวันที่ พฤ. 29 พ.ย. 2018 เวลา 15:52 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:

**Comment by pH-7** [comment]
Great @chalit9999!, buy the way, in order to help the software and to support you, don't forget to Star the repo as well 😊 And if you have time, review the project on Sourceforge https://sourceforge.net/projects/ph7socialdating/  (it takes just one minute).
You will need an account to do so, but it really helps me and motivates me a lot to continue this project :)
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
Great @chalit9999! 🎉 Good luck!
