### ISSUE TITLE
Admin Panel Missing

### ISSUE THREAD

**Issue by VisualizedStudiosOfficial** [pH7Software/pH7-Social-Dating-CMS#374]
I have installed the entire website but it seems that when i try to access my admin panel it is not there. I look for the php file labeled admin123.php and it is missing. Please someone help me with this.

**Comment by polynamaude** [comment]
Look at the documentation.
You need to rename the place the protected folder in a place out of your main web server tree, then indicate it into config.ini and at the same time give the name you want to use (and rename) for your administrator panel.

If you need more help, then get back.
https://ph7cms.com/doc

**Comment by pH-7** [comment]
The URL is YOUR-WEBSITE.com/**admin123** 
With pH7Builder, you never have ".php" extension.

More info: https://ph7cms.com/doc/en/how-to-go-to-admin-panel
