### ISSUE TITLE
Using my own background image

### ISSUE THREAD

**Issue by klaus1957** [pH7Software/pH7-Social-Dating-CMS#375]
I am new to ph7cms and i want to use my own image on website background. Is it possible to describe in detail how to get it

**Comment by chrisave** [comment]
Hello,

Apparently, according to the webdeveloper tools, with the Splash Homepage and the Background Splash Video disabled, and for the "Base" Default Theme at least, it is in a css file in templates/themes/base/css/, and after a quick investigation it is confirmed to be in common.css :
```
body {
    background: white url(../img/body_bg.jpg) repeat-x;
}
```
As you can see, the image is, in this case, in templates/themes/base/img/.
