### ISSUE TITLE
Lost on upgrade

### ISSUE THREAD

**Issue by oedo808** [pH7Software/pH7-Social-Dating-CMS#377]
I don't have any critical data yet, but I wanted to go through an upgrade to make notes for the future.  I believe I initially installed 14.0.0, or at least that's what the admin console told me.  I made www and mysql backups and then ran git pull on the web folder.  When I went to http://[hostname]asset/file/Upgrade, it lists the following information for each version down to 0.1.6, all with the same Wrong "version name/number or version build" on the button.

Version Name: pKb, Version Number: 14.8.0, Version Build: 1

Wrong "version name/number or version build"

It will be terribly easy to start over from scratch right now, I just wanted to try to get an upgrade down so that I could have documentation in case I ever get a subscriber base and need to do it with real data in the future.  

I was thinking about just running the MySQL scripts starting with https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_repository/upgrade/14.0.0-14.3.0 and each one up to the last.
14.0.0 - 14.3.0
14.3.0 - 14.3.4
14.3.4 - 14.3.6
14.3.6 - 14.7.0
14.7.0 - 14.8.0

Is there something I did wrong to break my asset/file/Upgrade page?

**Comment by pH-7** [comment]
Hi @oedo808!

Please do not overwrite the `_protected/framework/Security/Version.class.php` when you are updating the files to the latest version.

So, if your website was on 14.0.0, please update `Version.class.php` lile 37 https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Security/Version.class.php#L37 

from
```php
const KERNEL_VERSION = '14.8.0';
```
to 
```php
const KERNEL_VERSION = '14.0.0';
```

then refresh the upgrade wizard and you will see the available upgrade patches.

Don't forget to run from the oldest version to the newest one (all of the available upgrades have to be executed).

![upgrade-page-ph7cms](https://user-images.githubusercontent.com/1325411/49146247-9d88c480-f366-11e8-8382-55da09a4800d.png)


Hope this helps 🙂

**Comment by oedo808** [comment]
Thank you!  I restore /_protected/framework/Security/Version.class.php and ran the upgrade scripts.  I manually updated KERNEL_VERSION to 14.8.0, but I guess I could have just overwritten the file with the newest Version.class.php, but they're the same now.  Thank you for what you do!

**Comment by pH-7** [comment]
You're very welcome @oedo808 

Normally, the upgrade script will automatically update `KERNEL_VERSION` constant to the correct version for each upgrade patch.

**Comment by pH-7** [comment]
And if you have time to review the project on Sourceforge https://sourceforge.net/projects/ph7socialdating/ 
You will need an account to do so, but **it really helps me and motivates me a lot to continue this project** :)

**Comment by oedo808** [comment]
You got it.  I wanted to ask, is there any way to have a free trial period on paid membership while still collecting payment details?  Also is there an avenue for paying for additional features or feature development?  I saw your Patreon campaign, but it looked like maybe it was related to a retired Pro version.
