### ISSUE TITLE
How to add other logo in the social media logo link?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#381]

**Comment by chalit9999** [comment]
i like to add my logo next to those social media link in the footer left side

**Comment by pH-7** [comment]
Hi @chalit9999 

Near to the social sharing widgets, would be here https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/layout.tpl#L173 (layout.tpl, line ~173). 

Hope this helps!

**Comment by chalit9999** [comment]
thanks , will try and hope it works

ในวันที่ พ. 5 ธ.ค. 2018 เวลา 16:11 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:

**Comment by chalit9999** [comment]
one more request if you don't mind,   i would like to change default language to Thai language is it possible ?

**Comment by pH-7** [comment]
Hi @chalit9999 
At the moment, there is no translations for Thai language. 
More information to know how to translate pH7CMS to Thai https://ph7cms.com/doc/en/how-to-translate-to-another-language

The available languages for pH7CMS are mentioned on this page https://github.com/pH7Software/pH7-Internationalization#available-languages (it's the repo where they are available).

Hope this helps!

**Comment by chalit9999** [comment]
*i'm about to upload all the file in my FTP htdocs  but i'm not sure what
to name my database name , here i have a sample of the one i use with Xampp*

*** Database server hostname:
Generally "localhost" or "127.0.0.1"

*** Database username:

*** Database password:
12345  (set own password for now)

*** Database name:
    ********* *should this be ph7cms ? or i can name it as i want? *
*** Prefix for tables in database:
This option is useful when you have multiple installations of pH7CMS on the
same database. We recommend that you change the default values in order to
increase the security of your website.


ในวันที่ พฤ. 6 ธ.ค. 2018 เวลา 14:04 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:
