### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by yanpablo** [pH7Software/pH7-Social-Dating-CMS#383]
Bonjour Pierre-Henry,

J'ai vu que suite à de nombreuses mise à jour des APIs chez facebook pour le "Facebook Login", vous avez décider de ne plus maintenir l'option de connexion via Facebook (Social Media Authentification) et Google.

Envisagez-vous à court terme, de mettre à jour le module de connexion Facebook/Google 
( par la mise en place d'un correctif ou dans une prochaine version de Ph7cms ) ?

Vous remerciant pour votre réponse.

Cordialement,
Yannick.

**Comment by pH-7** [comment]
Bonjour @yanpablo 
Je vous remercie pour vos recherches préalables à ce sujet. 
En effet, pour le moment ce n'est pas dans mes priorités... Malgré qu'il soit désactivé par défaut, je le laisse dans le logiciel au cas où quelqu'un voudrait le mettre à jour pour qu'il puisse fonctionner avec les dernières APIs Google, FB, Twitter, etc. 

Enfin, actuellement, seulement "Facebook Login" a été migré vers un package composer. Les autres utilisent encore les vieilles librairie seules (https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/library/Service) et doivent aussi être supprimés et utiliser les composer packages à la place.

**Comment by pH-7** [comment]
C'est avec grand plaisir !
