### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by GigaaG** [pH7Software/pH7-Social-Dating-CMS#384]
Hi there! 

I installed pH7 today, but there are some struggles. I received a mail with confirmation the website is installed correctly, but all it does is displaying the index and on clicking buttons, it looks like the other pages aren't installed. 
Also, the admin panel is not accessible. 

Any ideas?

**Comment by pH-7** [comment]
Hi @GigaaG 

If the URLs return 404 error, it's likely that your mod_rewrite configurations aren't setup well. https://ph7cms.com/doc/en/how-to-install-rewrite-module

If you are using a web hosting service, please ask the support to investigate to the error and check the log files.

**Comment by manugarciac** [comment]
I'm having the same problem. In that link it explains who to install mod_rerewrite for apache, but the installation steps mentioned nginx. Should I set up apache instead?

**Comment by pH-7** [comment]
@GigaaG Is this solved?

**Comment by pH-7** [comment]
@GigaaG Since you didn't get back, I assume this issue can now be closed.
