### ISSUE TITLE
translation and background picture

### ISSUE THREAD

**Issue by micropuce** [pH7Software/pH7-Social-Dating-CMS#385]
Hello, I installed the French translation file, but I see that when we select French on the site, everything is not translated. how should I proceed to continue the translation? other question how to put only an image in the background instead of the video?
thanks

**Comment by pH-7** [comment]
Hi @micropuce 

1. Have you correctly transfered the .mo file and `language.php` (the files available in https://github.com/pH7Software/pH7-Internationalization)?

It's normal that not everything is translated. As mentioned on https://github.com/pH7Software/pH7-Internationalization#ph7cms-i18n---internationalization The translations aren't 100% completed. You can translate the French translation easily with POEdit. More info here https://ph7cms.com/doc/en/how-to-translate-to-another-language

It would be nice from you if you can then send your completed translation, and in that way, your translation will stay on the next further updates.

**Comment by pH-7** [comment]
**Concerning your second question**

You can disable it through the admin dashboard -> Setting -> General -> "General Settings" tab, scroll down until "Background Splash Video" option, then choose "Disable" and save it.

**Comment by micropuce** [comment]
for the translation yes what I would have done I would communicate it to you to advance the evolution ..
what I mean is that the translation is not complete, for example on the home page the text "You're at the best place for meeting new people nearby!" Chat, Flirt, Socialize and Have Fun!
Create any Dating Sites like that with pH7CMS. It's Professional, Free, Open Source, ... "does not translate when you change language and I would like to know how to do it?
and for the bottom how to put an image in place of the video?

**Comment by pH-7** [comment]
"You're at the best place for meeting new people nearby!" sentence, and others on the homepage are dynamic :) You can directly change them through the admin panel -> Settings -> Meta Tags/Homepage Texts
 
More info: https://ph7cms.com/doc/en/how-to-change-promo-texts-on-homepage

**Comment by pH-7** [comment]
Concerning the video background, I answered here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/385#issuecomment-445174924

**Comment by pH-7** [comment]
@micropuce Please let me know if this issue is now solved?

AND also, don't forget to **Star** the repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Passez un excellent dimanche @micropuce! 🎉

**Comment by pH-7** [comment]
@micropuce Please let me know if this issue is now solved?

AND also, don't forget to **Star** the repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Passez un excellent dimanche @micropuce! 🎉

**Comment by pH-7** [comment]
@micropuce Since you didn't get back, I assure this issue can now be closed.
