### ISSUE TITLE
Can't create users

### ISSUE THREAD

**Issue by manugarciac** [pH7Software/pH7-Social-Dating-CMS#387]
Whenever I try creating a user, the page refreshes without errors and the user is not created. Any ideas?

**Comment by pH-7** [comment]
Do you try to create a new user through the admin panel (User/Admin -> Users -> Add User) or on the registration form?
Do the other forms work?

**Comment by pH-7** [comment]
Hey @manugarciac 
Please let me know if this is still relevant?

**Comment by manugarciac** [comment]
Sorry @pH-7, I've been away from my computer. Yes, it is still relevant. It was the registration form. Give an hour and I'll give you more info. Thank you!

**Comment by manugarciac** [comment]
I can't create a new user because I can't log in as an admin. What other form could I try without logging in?

**Comment by Athenasoftwares** [comment]
Hello, 

Is it possible that we can use all the features added in all the 3 websites? 
Because the website we set up (Dating app), it doesn't have a lot of features in it.

Thanks

**Comment by pH-7** [comment]
> I can't create a new user because I can't log in as an admin. What other form could I try without logging in?

The admin login form for the admin dashboard https://ph7cms.com/doc/en/how-to-go-to-admin-panel

**Comment by pH-7** [comment]
> ossible that we can use all the feat

@Athenasoftwares I think you are on the wrong thread. You need to open a new issue per different problem (and btw, I'm not sure to understand what you are saying...)

**Comment by manugarciac** [comment]
@pH-7 Same problem. I also tried the reset password form. When I submit, the form clears itself as if the page was refreshed.

**Comment by pH-7** [comment]
You probably have a "session issue". Apparently the sessions cannot be saved to your web host, or the disk is full. I would suggest you to contact your web host and investigate on it

**Comment by pH-7** [comment]
Did you have a look to similar closed issues?  This issue looks similar to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/215#issuecomment-395602193

**Comment by pH-7** [comment]
@manugarciac Or even here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/289

**Comment by manugarciac** [comment]
No luck. I found where sessions are being written, and files seem to be creating OK on that dir. What other problem with sessions do you think there could be?
