### ISSUE TITLE
New Install but CSS "on and off" 

### ISSUE THREAD

**Issue by Outlines** [pH7Software/pH7-Social-Dating-CMS#388]
Hello,

I just got PH7CMS and am excited to learn about it.

I installed it, and it seems the css is rendering sometimes and not other times.  I set it on "Zendate" theme.

If you look you'll see the css issues.
[http://www.canadianbears.com/](http://www.canadianbears.com/)

Same in the back end, as attached.
![admin-css](https://user-images.githubusercontent.com/5274447/49676856-dac11680-fa38-11e8-8dd8-1011b135e8f2.jpg)

While I work with asp.net and windows servers all day long, this project is a personal one and is on a shared hosting company's server.

Thank you to all the experts for their advice.

David

**Comment by pH-7** [comment]
Hi @Outlines 

I had a look to your website. Can you try to clear the "Static Files" caches? https://ph7cms.com/doc/en/how-to-clear-caches

Then, clear your web browser's cache and retry

**Comment by pH-7** [comment]
Let me know if it did the job @Outlines

**Comment by Outlines** [comment]
Hello,

 

Thank you for the reply, and the advice.

 

I cleared the caches as per your suggestion.

 

I'm still encountering the issue with display.

 

Best regards,

 

David

**Comment by pH-7** [comment]
@Outlines Apparently, the issue is caused by your web hosting company.

All CSS/JS asset links redirect to templates.doteasy.com/ErrorPages/error404/

For example, this http://www.canadianbears.com/asset/gzip/?t=css&d=static/css/&f=bootstrap.css,bootstrap_customize.css,animate.css
redirects to http://templates.doteasy.com/ErrorPages/error404/

Please see with them.

And maybe their security system also blocks external cURL requests...

If this isn't the case, please reopen the ticket.

Thanks!

**Comment by Outlines** [comment]
Hi, 

Thanks for all the information. 

I heard from my hosting company (DotEasy) and they feel they have solved
it.  They want me to upgrade from the "basic starter hosting" I used, to
their "Business Standard" because the basic one was having issues
running PH7CMS. 

I just thought you might be interested.  Here's what he said: 

"The PH7CMS appears to be failing due to a limitation on the Virtual
memory as testing this script we have found this to be extremely Memory
heavy which is leading to the problem. 

Due to the higher memory limitations your pages are not fully formed
when being dynamically created which results in them mostly looking like
the CMS is broken, sometimes looking like the CMS is a little off, and
rarely working properly. 

From testing we can see that the Memory spikes heavily when even trying
to open or run this by itself and apepars that you would need to have a
bigger plan in order to better run this platform. 

From the requirements of the script itself and from our observations we
believe you would need at minimum one of our Business Standard Hosting
Plans: https://www.doteasy.com/business-hosting/ in order to run this
properly. Please note that because of how quickly and frequently it's
difficult to say what the upper end is at this time, but from our
observations and their listed requirements, it appears this would work."


Thanks again for your assistance. 

Best regards, 

David

On 2018-12-09 22:43, ♚ PH⑦ Soria ♛ wrote:

> @Outlines [1] Apparently, the issue is caused by your web hosting company. 
> 
> All CSS/JS asset links redirect to templates.doteasy.com/ErrorPages/error404/ 
> 
> For example, this http://www.canadianbears.com/asset/gzip/?t=css&d=static/css/&f=bootstrap.css,bootstrap_customize.css,animate.css
> redirects to http://templates.doteasy.com/ErrorPages/error404/ 
> 
> Please see with them. 
> 
> And maybe their security system also blocks external cURL requests... 
> 
> If this isn't the case, please reopen the ticket. 
> 
> Thanks! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/Outlines
[2]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/388#issuecomment-445694537
[3]

**Comment by pH-7** [comment]
Hi @Outlines 
Thanks for sharing!
Yes, pH7CMS usually needs something more than a simple hosting like WP hosting... It's not the same king of websites..

Here are a list of very cheap web hosting companies "compatible" with the software: https://ph7cms.com/doc/en/hosting (the images are broken, but you still see the alt descriptions).

DigitalOcean is also a good solution with cheap plans.

Hope this helps :) Good luck!
