### ISSUE TITLE
Homepage slideshow

### ISSUE THREAD

**Issue by chrisave** [pH7Software/pH7-Social-Dating-CMS#392]
Default Theme: Base
Splash Homepage: Disable
Background Splash Video: Disable

The _protected folder is at the same level as the public_html folder.

Hello,

I've managed to slow down the homepage slideshow's transition speed in public_html/templates/themes/base/js/splash.js:
```
//Slider Animation
    $(".img_reel").animate({
        left: -iImgRealPosition
    }, 2500);
```

But I've noticed that I have to resolve another issue: instead of the fifth image I have a white background.

I've found _protected/app/system/modules/user/views/base/tpl/main/index.guest.inc.tpl and the following code:
```
<div class="splash_slideshow">
            <div class="window">
                <div class="img_reel">
                    {for $i in [1,2,3,4,5]}
                        <a href="{url_root}">
                            <img src="{url_tpl_img}slideshow/{i}.jpg" alt="{lang 'Social Dating Web App'}" />
                        </a>
                    {/for}
                </div>
            </div>
            <div class="paging">
                <a href="#" rel="1">1</a>
                <a href="#" rel="2">2</a>
                <a href="#" rel="3">3</a>
                <a href="#" rel="4">4</a>
                <a href="#" rel="5">5</a>
            </div>
        </div>
```

Removing, for example, the fifth image occurrence from the "img_reel" class div and the "paging" class div doesn't change anything.

Thanks in advance !

Christophe

**Edit:**
![capture du 2018-12-11 01-24-40](https://user-images.githubusercontent.com/14296961/49770431-a6718280-fce4-11e8-8147-b764a37b17bd.png)

**Comment by chrisave** [comment]
![capture du 2018-12-11 01-24-40](https://user-images.githubusercontent.com/14296961/49770431-a6718280-fce4-11e8-8147-b764a37b17bd.png)
![capture du 2018-12-11 01-27-47](https://user-images.githubusercontent.com/14296961/49770393-8b067780-fce4-11e8-88b8-1950146462b4.jpg)

**Comment by pH-7** [comment]
@chrisave Except if you want to fix it (I'm sure you can find good help on Stackoverflow), this homepage version hasn't been updated for years and is buggy. 
You should probably keep the "Splash Homepage" enabled (which is the option by default).

Anyway, if you have time and fix it, I will really appreciate if you post the fix here :) And so, it will also be included to the further versions.

Sorry for this "not helpful" answer, but I really can't do more here.

Have a great day!

**Comment by chrisave** [comment]
**@pH-7** 
I've just resolved it. It has taken me not so long. I've tested several things.

Among them, I had thought of adding a sixth item:  {for $i in [1,2,3,4,5,6]}, so I've tried it out of curiosity.
Logically it has made the 5th image appear, but of course there has been an error message in the console because of the non-existent 6th image.

Then I've had the idea of testing with {for $i in [1,2,3,4,5, $i = 1]}. It seems to have solved the issue.
It also works with $i=2 up to 5.

But starting from the second image a small part of the precedent image is seen bigger and bigger.
So the solution seems to be to reduce the width (not more and not less than 588px for the current images):
.img_reel img {  
    width: 588px;

But I see that a lot of things are overlapping in "mobile" mode/view.
I'll see if I use the splash homepage or if I try to resolve other issues.

Have a nice day!

**Comment by pH-7** [comment]
Thanks very much for your very detailed solution! 🏆 Do you mind to create a pull request with your changes?

Indeed. This version hasn't been optimized for small devices such as mobile phones (especially for the slideshows).

**Comment by chrisave** [comment]
@pH-7 
I never made a pull request. Also, I don't know what would be the best way to make one in this case.

But I'm seeing other strange things in the non-splash homepage.
For example, in Chromium, in mobile view, after reloading the page, I see that the slideshow is not appearing anymore, and the carousel is static, different, and small. But there is no overlapping.
When not in mobile view (and also in Firefox), when the browser window is under a certain width (before the overlapping) and I reload the page, the slideshow is there but there seems to be a problem a little like before on larger "screens", so my "fix" wouldn't really fix it apparently.

I'm confused.

So it may be better not to change anything.

I think I'm going to stick to the "Splash Homepage" as it is (or I'm going to try to add things).

**Comment by pH-7** [comment]
Fair call :) Thanks anyway!
