### ISSUE TITLE
Homepage carousel (transition speed)

### ISSUE THREAD

**Issue by chrisave** [pH7Software/pH7-Social-Dating-CMS#393]
Default Theme: Base
Splash Homepage: Disable
Background Splash Video: Disable

The _protected folder is at the same level as the public_html folder.

Hello,

I need to reduce the homepage (user) carousel's transition speed, by half for instance.

I can't manage to find how to do it.

I've found carouFredSel.js, for example, during my quest.
I've looked a bit at its documentation.
I've also found the existence of <script>$(function(){$("#foo").carouFredSel()});</script>
Perhaps I have to put a speed option inside carouFredSel(), but I can't find where the script line is located for the moment.

I could also be completely wrong.
Perhaps it's another carousel that is used, and/or its transition speed is controlled by css transitions (but it didn't seem to be so).

Thanks in advance for your help!

Have a nice week!

Christophe

**Edit:**
![capture du 2018-12-12 02-23-22](https://user-images.githubusercontent.com/14296961/49840970-fe2bee80-fdb5-11e8-91bb-2d048188e523.jpg)

**Comment by pH-7** [comment]
Hi @chrisave 
You one you found is the right one.

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/ecf46b09de980e44d05fb5b6eb811c01dbb6f514/_protected/app/system/core/models/design/UserDesignCoreModel.php#L102
This method will be called in the view tpl file here https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/0207b9f21dcc638db5eff1289ce4e1144d3035e4/_protected/app/system/modules/user/views/base/tpl/main/index.guest.inc.tpl#L46

Try to change [the code](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/ecf46b09de980e44d05fb5b6eb811c01dbb6f514/_protected/app/system/core/models/design/UserDesignCoreModel.php#L102) to something like below:
```javascript
<script>$(function(){$("#foo").carouFredSel({duration: 2000})});</script>
```

**Comment by chrisave** [comment]
@pH-7 
Thank you!
I think I'm going to stick to the "Splash Homepage".
NB: you can see why in the issue I opened concerning the slideshow.

**Comment by pH-7** [comment]
Thank you @chrisave 
Anyway, feel free to get back to it later on if needed. I will close this issue by now then. Please reopen it if needed.
