### ISSUE TITLE
Edit / Delete Genders

### ISSUE THREAD

**Issue by Outlines** [pH7Software/pH7-Social-Dating-CMS#398]
I'd like to be able to delete "woman" from genders as this is an all-male dating site (including "couples").

That's the ideal.  Is there a fairly uncomplicated way to do that, or is it too complicated (i.e. "woman" is all through the database, or in code files that would get overwritten with any updates?

Thanks

**Comment by chrisave** [comment]
Hello,

I had removed the "couple" option in files using Searchmonkey (cross-platform). There is also Recoll, for instance (but only for Unix/Linux).
I just had a difficulty with one file, but I think it was ok.
But I didn't test everything to be sure there was no problem.
And women can still contact women, and men still contact men. I would prefer it was not the case for a specific project.

Here you can normally find solutions:
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/359
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/358

I think I will try them after an "automatic" upgrade of the software when the new stable version comes out.

**Comment by pH-7** [comment]
Hey @Outlines 
This might also help you https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Remove-the-%22couple%22-option
Instead of removing the "couple" option, remove the "woman" option. You will need to do the same for the "Looking for" field.

**Comment by Outlines** [comment]
Thank you for the suggestions - that did the trick!  (will these get overwritten by any updates?)

**Comment by pH-7** [comment]
Happy it helps!

**Comment by pH-7** [comment]
Yes, it will if you want to update your website... that's why you always have to backup your website before. In that way, you can put back your changes to the new files once updated (or see the changes done for the next version in the git history).

**Comment by pH-7** [comment]
BTW @Outlines, don't forget to Star the Github repo 😊
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
I will close this issue by now @Outlines 
If you have any further problems, please open a new issue. 

Have a great day!
