### ISSUE TITLE
people.jpg and people_bw ?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#401]
Hi i wonder what i could do with these 2 pictures, is it the static picture mode if we don't enable VDO bg?  Thanks

**Comment by pH-7** [comment]
@chalit9999 Those are legacy files. It was used as a background, but it isn't used anymore in the theme. 

Thanks for reminding me them. I will remove them...
Anyway, you can use them if you wish to... :)

**Comment by chalit9999** [comment]
those two pics might be useful in the future i will keep them, thanks

**Comment by chalit9999** [comment]
i need some advice i hope you don't mind. i'm about to ad SQL database and
i'm not sure if i should set my website name or ph7cms?  thanks

ในวันที่ ส. 15 ธ.ค. 2018 เวลา 15:12 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:
