### ISSUE TITLE
How to set SQL  database and SQL user in the real server?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#403]
i have tested the program in Xampp and now i want to upload in my root path and have to set **SQL database** and **SQL user** but i'm not sure what to do.     this is what it's done in Xampp as below

* Database server hostname:
Generally "localhost" or "127.0.0.1"
 
* Database username:
root
 
* Database password:
 12345  (set own password for now)

* Database name:
ph7cms
 
* Prefix for tables in database:
This option is useful when you have multiple installations of pH7CMS on the same database. We recommend that you change the default values in order to increase the security of your website.
ph7_
  Thanks

**Comment by pH-7** [comment]
Not really sure to understand your question//?
Do you want to transfer the existing data to your live database, or make a fresh installation to your web host?

**Comment by chalit9999** [comment]
i want to make fresh installation in the new host because i have made many
mistakes in Xampp it's not good data to transfer, i will try again slowly
step by step in my new host. Thanks for your help

ในวันที่ อ. 18 ธ.ค. 2018 เวลา 15:39 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:

**Comment by pH-7** [comment]
Oh, so that should be easy! 🙂
Like what it is said on the installer page, you should first create a database and user through your web hosting control panel. 

Most of the web hosts mentioned here https://ph7cms.com/doc/en/hosting offers easy-steps to do so.

Finally, if you don't really know how to do it, just ask you web hosting company to give a database name and database credentials (they sometimes can generate them for you).
 

https://www.youtube.com/watch?v=fFSI-AEMQwY

Hope that helps!

**Comment by chalit9999** [comment]
i'm still struggle with my sql database and unfortunately the hosting
company doesn't know what to, you are my only hope and here are what i have
done so far , i'm sorry for taking your time and i hope you don't mind.

database username = ph7cms

database password  =

database name = ph7cms

prefix        ph7ver8

and i get this result (unable to create directory /home/www/virtual/
flurt.info/htdocs/_install/data/caches/smarty_compile/0f/65/88)

and this host company does not support bin/ffmpeg   please let me know if
this is another problem or it's still ok?


Thanks

ในวันที่ อ. 18 ธ.ค. 2018 เวลา 16:48 ♚ PH⑦ Soria ♛ <notifications@github.com>
เขียนว่า:

**Comment by polynamaude** [comment]
Read back what @pH-7 wrote and you'll get answer to the questions you've asked. We already gave you a link with names of hosting provider that offer good quality / prices and support our software.

**Comment by chalit9999** [comment]
Thanks,  for your feed back i have another question,  if hosting not
support bin/ffmpeg  meaning the VDO module will not work, it this the video
background on the front page ?  if this is the case i can use static bg
background instead right?  Thanks

ในวันที่ ศ. 21 ธ.ค. 2018 เวลา 16:09 Polyna-Maude R.-Summerside <
notifications@github.com> เขียนว่า:

**Comment by chalit9999** [comment]
somehow i have lost this link or don't know how to find it, kindly provide
it one more time, apologise for the trouble, Thanks

ในวันที่ ส. 22 ธ.ค. 2018 เวลา 15:46 Chalit Wantaree <chalit9999@gmail.com>
เขียนว่า:

**Comment by polynamaude** [comment]
Sorry, but maybe you should ask yourself this question.
Look into the thread and you'll see all the messages already exchanged. You have all the history on github.com .
