### ISSUE TITLE
Groups and meta networks

### ISSUE THREAD

**Issue by CyberspaceX** [pH7Software/pH7-Social-Dating-CMS#404]
Hello, you did a very good job. But1-2 questions. did you plan a group feature? For a dating site, it's always impossible to separate your visitors into niches and groups are a good feature.
the same with meta networks... for example, I have a domain: dating.xyz
and now I like africa.dating.xyz asia.dating.xyz europe.dating.xyz and and and all with the same DB... is this possibel or i need different installations?!

**Comment by pH-7** [comment]
Hi @CyberspaceX 
Thanks very much for your suggestion. 
That kind of feature would involve several modifications, and each member in the database would have to be assigned to a specific dating niche.

However, it's an excellent idea (and niches are very good, like I suggest [here](https://ph7cms.com/start-a-dating-niche/) and [here](https://ph7cms.com/10-excluside-niche-ideas-for-your-dating-web-app/))

For the moment, it isn't possible do have a such feature. So, you will have to have different distinct installations of pH7CMS
