### ISSUE TITLE
what will happend if hosting not support bin/ffmpeg ?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#406]
many host company do not have bin/ffmpeg function , is it ok to start with or it will be bad without this function?

**Comment by pH-7** [comment]
Sure, that's not a problem.
> Video Module Requirement (only if enabled) - FFmpeg
https://github.com/pH7Software/pH7-Social-Dating-CMS#requirements

Just keep the "Video" module disabled (Admin -> Mod -> Enable/Disable Modules -> uncheck the "Video" module there).
