### ISSUE TITLE
安装这个框架后，无法正常使用，除了主页能够访问，其他页面全都是404

### ISSUE THREAD

**Issue by OneBoYun** [pH7Software/pH7-Social-Dating-CMS#408]
[After](url) installation, it could not be used normally. Except for the home page, all other pages could not be found. CSS in the home page could not be displayed normally
![image](https://user-images.githubusercontent.com/29030022/50464035-bfa74e00-09c9-11e9-8cb6-ca0aa065ea84.png)

![image](https://user-images.githubusercontent.com/29030022/50464044-c9c94c80-09c9-11e9-8723-5fa25af60d13.png)
![image](https://user-images.githubusercontent.com/29030022/50464054-d3eb4b00-09c9-11e9-90a6-6140366f3ede.png)

**Comment by pH-7** [comment]
Closing this one as a duplicate to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/409
