### ISSUE TITLE
 Administrator background cannot log in

### ISSUE THREAD

**Issue by OneBoYun** [pH7Software/pH7-Social-Dating-CMS#410]
![image](https://user-images.githubusercontent.com/29030022/50502087-9654f380-0a97-11e9-979c-c33c90c0784b.png)

I tried many times, but I still couldn't log in

**Comment by pH-7** [comment]
Hum, looks similar to those ones
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/146#issuecomment-343699495
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/215#issuecomment-395602193

**Comment by pH-7** [comment]
@OneBoYun Is this still relevant?
