### ISSUE TITLE
Logo not change

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#411]
Hi my new logo does not change, i have done all the cache manager in admin page as well as clear data in chrome, is there any things else must be done?  Thanks

**Comment by pH-7** [comment]
Do you see your new logo when you go to `http://YOUR-URL.com/templates/themes/base/img/logo.png?v=123`? (change `base` to your current template name).

If it is the case, that means your logo has been successfully updated and it was only a cache problem.

It is isn't the case, that means you have permission issues and the software doesn't have writing access to update the logo. Make sure to allow "write" for `/templates/themes/base/img/` folder (change `base` to your current template name).

Hope this helps!

**Comment by chalit9999** [comment]
Thanks

**Comment by pH-7** [comment]
Finally, in the admin panel, on the "logo" setting page (below the uploader field), what image is shown? Is it the new logo (or still the old one).

<img width="1030" alt="screenshot 2019-01-10 at 8 42 40 pm" src="https://user-images.githubusercontent.com/1325411/50953578-b5806600-1518-11e9-92a0-29397b5e78dd.png">

**Comment by chalit9999** [comment]
my new  logo is 50x40  and it shows the new logo which is a good sign but i
still can't find out why the new logo does not appear on the website, i
will keep trying. Thanks

ในวันที่ พฤ. 10 ม.ค. 2019 เวลา 14:46 ♚ PH⑦ de Soria™♛ <
notifications@github.com> เขียนว่า:

**Comment by chalit9999** [comment]
Hi   i have just done the DNS and clear chrome cache one more time it works
now. Thanks and sorry for the trouble :-)

ในวันที่ ศ. 11 ม.ค. 2019 เวลา 11:08 Chalit Wantaree <chalit9999@gmail.com>
เขียนว่า:

**Comment by pH-7** [comment]
Great! Glad it helped :)
