### ISSUE TITLE
How to generate IP API ? 

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#413]
I managed to fix google api key but the location but still point to USA, and i just found another box below  IP API:
The URL must end with a slash.  how do i generate this key is it the same?  Thanks

**Comment by pH-7** [comment]
Are you on a local host? If so, that's normal.

Local host IP is an invalid IP, so it shows a default IP, which is a US IP

More info: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/ef39ba21a67344dee3dcc1229410b808bd12f0d6/_protected/framework/Geo/Ip/Geo.class.php#L144-L147
