### ISSUE TITLE
function.preg-replace failure on fresh install

### ISSUE THREAD

**Issue by SilentSeraphim** [pH7Software/pH7-Social-Dating-CMS#415]
Hi, I just did a fresh install at http://polyamr.us and I can't get it to stop giving me this error: 

Warning: preg_replace() [function.preg-replace]: Compilation failed: invalid range in character class at offset 22 in /storage/content/39/1005439/polyamr.us/_0220/framework/Layout/Tpl/Engine/PH7Tpl/Predefined/Predefined.class.php on line 105

The installation process seems to go fine but when I try to access anything after deleting the install folder, this is what I get. I deleted the entire install and reinstalled with a freshly downloaded copy to no avail. Here's the code in the predefined.class.php that the error references:

` /**
     * Adding Function.
     *
     * @param string $sKey
     * @param string $sValue
     *
     * @return void
     */
    protected function addFunc($sKey, $sValue)
    {
        $this->sCode = preg_replace(
            '#' . $sKey . '#',
            static::PHP_OPEN . static::WRITE . $sValue . static::PHP_CLOSE,
            $this->sCode
        );
    }`

It's that final sCode that is on line 105. I've also attached a screenshot of the entire debug message. Needless to say, I'm not a programmer, so any help you guys could give me would be greatly appreciated.
![2019-01-10](https://user-images.githubusercontent.com/46569024/50978932-6fe57e00-14c3-11e9-92ec-bf21be42444e.jpg)

**Comment by SilentSeraphim** [comment]
Also, that code didn't look very helpful in the OP so here's a screenshot of the code surrounding line 105 in the predifined.class.php.
![2019-01-10- 1](https://user-images.githubusercontent.com/46569024/50979303-319c8e80-14c4-11e9-9548-5952d8eb720b.jpg)

**Comment by SilentSeraphim** [comment]
Nevermind. Figured it out myself. Apparently, the code doesn't play nice with PHP 7.3. I switched to 7.1 and it works fine.

**Comment by pH-7** [comment]
The patch is here https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/2e43a5aa7dba1738db046c34292a67bff526b5cc (in case, someone wants to run the software already now with PHP 7.3+).

Anyway, the fix will be released with pH7Builder 14.9.0

**Comment by ibacompre** [comment]
I was having the same issue and fixed it by modifying Func.class.php:
`$this->addFunc('<ph:date value="([\w\s\-/\|\.,:\\\\]+)" ?/?>', 'date(\'$1\')');`

More specifically, if you look at the pattern in this call to `addFunc()`, you'll see a '-' (dash) character, which was taken as a range symbol. I modified it with a backslash, and it fixed the issue for me.
