### ISSUE TITLE
Missing files after installation

### ISSUE THREAD

**Issue by kd2nom** [pH7Software/pH7-Social-Dating-CMS#416]
I completed my installation of pH7 on Ubuntu 18.04 server. The main page for the site displays, although it is not rendering properly (large image on top, links and text below it) and there is no login page or admin123 directory.  The last step of the installation asked to delete the _install directory which I completed. Should I try reinstalling?

Best regards,

Mark Steele
![ph7-01](https://user-images.githubusercontent.com/46572723/50985942-8267b380-14d3-11e9-9572-022616d6ebbe.PNG)
![ph7-02](https://user-images.githubusercontent.com/46572723/50985949-8562a400-14d3-11e9-9385-847346e15c38.PNG)

**Comment by kd2nom** [comment]
I did a new install with the zip file pH7Builder-14.8.9.zip - same results.

**Comment by pH-7** [comment]
Hi @kd2nom 
Don't worry, you have all files (nothing is missing). The problem looks to be from mod_rewrite. 

Please make the mod_rewrite is correctly configured https://ph7cms.com/doc/en/how-to-install-rewrite-module Please ask you web host to investigate the problem if you are with one

Can you also make sure that the .htaccess has been correctly been uploaded to the root directory.

**Comment by kd2nom** [comment]
Will do.

It's hosted on a VM here at my office for now.

Best regards,

73, Mark - KD2NOM
10-10: 77596, FHC: 5930
https://www.qrz.com/db/KD2NOM
