### ISSUE TITLE
How to remove black bg on logo image?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#417]
Hi  i have successfully changed my logo after clear cache and DNS but my new png logo shows black background instead of transparent,  is it possible to make it transparent?    Thanks

**Comment by pH-7** [comment]
Hum, looks like you uploaded a JPG image. Can you try with a PNG version with transparent background. Or just update your logo icon with this free online service: https://onlinepngtools.com/convert-jpg-to-png

Hope this helps! Good luck :smile:

**Comment by pH-7** [comment]
Did it the job? Is it working now? Please close this issue if everything is OK

**Comment by chalit9999** [comment]
it is not working yet, the black background still appearing, do you have any other way to fix?  Thanks
