### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by Mobiller** [pH7Software/pH7-Social-Dating-CMS#419]
How can I translate the "Your Content Has Been Approved" email from English to Portuguese ??

There are many pages not fully translated to Portuguese. An example is the registration Steps where you can find many English words in a portuguese PT-br website like: How old are you - Your Country - Your City. and so on.....

![engtopt-br](https://user-images.githubusercontent.com/43084373/51545765-965bcf80-1e5a-11e9-831c-04c90e4dc6c7.jpg)

Thanks

**Comment by pH-7** [comment]
Hi @Mobiller 

Those strings are new ones are aren't included in the Portuguese translation. 
You will need to add them manually in the po file like below
```
msgid "Your Content Has Been Approved" # Original string
msgstr "Seu conteúdo foi aprovado" # Translated string
```

Then, compile it with poedit to generate the mo file.

P.S. If you have time, you can update the translation https://github.com/pH7Software/pH7-Internationalization/tree/master/_protected/app/langs/pt_BR/LC_MESSAGES
and submit your updated version, so it will be included in the further versions 😄

**Comment by Mobiller** [comment]
Hello @pH-7 Thank you for your answer.

I am more than happy to translate into Portuguese no problem but I don't know how to submit the updated version for analysis.

On the example that you gave me above 
`msgid "Your Content Has Been Approved" # Original string
msgstr "Seu conteúdo foi aprovado" # Translated string`

Aint missing the line of the php code ? as in `: _protected/app/system/core/classes/UserCore.php:485
msgid "Your account has been successfully validated. You can now login!"
msgstr "Sua conta foi validada com sucesso. Agora você pode fazer login!"`

and finally what are the other new strings that I can add to the .po file ?

**Comment by pH-7** [comment]
No, this isn't necessary at all. 
The `#_protected/app/system/core/classes/UserCore.php:485` lines are just comments generated by POEdit (it's just there for informative purpose to help to know where is that string in the source file).

If you aren't familiar with git and Github to create a PR, you can just zip the files and attach it on this thread (just drag and drop it and GitHub will upload it to the post).

**Comment by pH-7** [comment]
Thank you @Mobiller !

**Comment by Mobiller** [comment]
Great. So I will work with the .po file that is already installed on my directory under /_protected/app/langs/pt_BR/LC_MESSAGES

**Comment by pH-7** [comment]
Awesome @Mobiller! 💪

**Comment by Mobiller** [comment]
Hello,

I started working on the translation but I am facing some problems on the system emails like:

When an user post a picture and it's approved he/she/it will receive an email straight away and on the email body it will read:

**Congratulation! The content you recently posted at xxxxxxx has been successfully approved by the team.**

 However I am not able to translate this. I am assuming that it is using `%site_name%`

So the string would be 

`msgid "Your content you recently posted at %site_name% has unfortunately been disapproved by our moderation team."`
`msgstr "O conteúdo que você postou no %site_name% infelizmente não foi aprovado pelo Administrador."`

But I am not able get it right, any help ?

Cheers

**Comment by pH-7** [comment]
Hi again @Mobiller!

There is a link in that string. That's why it didn't work for you because it wasn't the same as yours.

The correct version you have to add as msgid is
`"Congratulation! The content you recently posted at <a href="%site_url%">%site_name%</a> has been successfully approved by the team."`
Source: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/80c17c02371b274afe0f453018c1440fe6013c42/_protected/app/system/modules/admin123/inc/class/UserNotifierString.php#L42

And the disapproval one is
`Your content you recently posted at <a href="%site_url%">%site_name%</a> has unfortunately been disapproved by our moderation team.`
Source: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/80c17c02371b274afe0f453018c1440fe6013c42/_protected/app/system/modules/admin123/inc/class/UserNotifierString.php#L59

Finally, the message of that disapproval one (because there is also a link in the message) is
`Please feel free to post again a content at any time as long as it respects our <a href="%0%">terms of service</a>`
Source: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/80c17c02371b274afe0f453018c1440fe6013c42/_protected/app/system/modules/admin123/inc/class/UserNotifierString.php#L62

Hope it helps!

**Comment by Mobiller** [comment]
Hello and Thank you :) it did help a lot and know I think I got the gist of it.

I am struggling with a few lines though, follow just one example:

`msgid "Are you proud of using <a href="%software_website%">pH7CMS</a> brand? Are you proud to say your dating app has been made by the Leading Dating Software provider?"`
`msgstr "Você está orgulhoso por usar a marca <a href="%software_website%">pH7CMS</a>? Você está orgulhoso em dizer que seu aplicativo de namoro foi criado pelo Lider de mercado?"`

[https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/28a6e08f6f009f6a326fb9b63bab56b9a954b835/_protected/app/system/modules/admin123/forms/SettingForm.php#L80](url)

`        $oForm->addElement(new \PFBC\Element\Select(t('Show "Powered By" link in footer:'), 'display_powered_by_link', [1 => t('Enable'), 0 => t('Disable (NOT recommended)')], ['description' => t('Are you proud of using <a href="%software_website%">pH7CMS</a> brand? Are you proud to say your dating app has been made by the Leading Dating Software provider?'), 'value' => DbConfig::getSetting('displayPoweredByLink'), 'required' => 1]));`

**Comment by pH-7** [comment]
You need backslashes `\" when you use the double quote (like this `\"`).
So, try to change it to
```
`"Are you proud of using <a href=\"%software_website%\">pH7CMS</a> brand? Are you proud to say your dating app has been made by the Leading Dating Software provider?"`
```

**Comment by Mobiller** [comment]
Hello, 
I believe that I finished the translation or at least what was left to translate because the hard part was already done previously. It is a very small contribution to this wonderful project.
I tried to go into every translatable part but If any user find some part not translated or that something can be improved please let me know that I will try to fix straight away.
Please let me know if I can of any help.
All the best
[portuguese.zip](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2844273/portuguese.zip)

**Comment by pH-7** [comment]
Awesome @Mobiller!! I really appreciate it.
I will update the [i18N repo](https://github.com/pH7Software/pH7-Internationalization) then.

Thanks!

**Comment by pH-7** [comment]
@Mobiller By the way, could you also provide your updated `global.mo` compiled file. I see only the updated global.po file, but the global.mo is the old one.

**Comment by pH-7** [comment]
It's all good @Mobiller. I updated the MO file too :) Excellent job!
Cheers

**Comment by Mobiller** [comment]
Sorry @pH-7 my bad for not updating the .mo file.
It is a pleasure to help. If any improvement or further translations required to Portuguese, count on me .
Cheers
