### ISSUE TITLE
Index AVATAR  FAIL URL

### ISSUE THREAD

**Issue by gatgat1991** [pH7Software/pH7-Social-Dating-CMS#420]
Hello i use the last Git and i have a Prob my Path from Avatar on my Index is not correct  is my Server ip Oo

http://prntscr.com/map160

**Comment by polynamaude** [comment]
May I ask you to describe your problem in a readable manner ?

**Comment by pH-7** [comment]
Thank you @polynamaude! 😊

**Comment by gatgat1991** [comment]
Ok I have installed on my domain okey. And my problem is the script buse my server ip for loading the image can say me who can change this or is this right?
