### ISSUE TITLE
IP Restriction for Admin Panel Access:

### ISSUE THREAD

**Issue by bartsanchez713** [pH7Software/pH7-Social-Dating-CMS#426]
I entered my IP address and now i am not able to log in the admin panel and get the following error:
"Failed! Wrong IP address"  Is there a way to go back to change to original status and leave field it blank as per the following as it was under General Settings under Security tab that read as follows:

IP Restriction for Admin Panel Access:
By entering your IP, you will get a higher security and exclude all other people and bots that tried to login with another IP address even if the login is correct! Leave blank to disable this feature. Be careful, for using this feature you need to have a static IP (not a dynamic one). If you are not sure, please contact your ISP.
0
Would think after I would make this change as it was then I will be able to log in to Admin Panel as I was for several days, thanks for your help.

**Comment by pH-7** [comment]
Hi @bartsanchez713 

I'm really sorry for this inconvenience. I built the software to be as handy as possible (and as secure as possible), and unfortunately sometimes you have this kind of annoying problem.

Thanks for your detailed post btw. 
Are you sure your website isn't installed on your localhost, but on a real host? 
Finally, are you sure that your public IP didn't changed?

You have two options to fix it:
1. The recommend option.
https://gist.github.com/pH-7/ccfed2fba5761ebc43882ce24a5f4e90#file-reset-admin-panel-ip-restriction-sql-L16
By executing this SQL query through your phpMyAdmin or MySQL command line, you will clear the IP value you previously set, and you will again be able to log in to your admin dashboard with any IP addresses.

2. Second option This consists of installing the following Chrome extension https://chrome.google.com/webstore/detail/modify-headers-for-google/innpjfdalfhpcoinfnehdnbkglpmogdi/ 
And, add as the header name `HTTP_X_FORWARDED_FOR` and as the value, the IP you specified in pH7CMS's admin panel (if you still remember it).
Once you are logged in, you can update or remove the IP address you set in "IP Restriction for Admin Panel Access" field.

<br />
Hope it helps!

Have a great day, and good luck with your website!

**Comment by bartsanchez713** [comment]
Hello,
thanks for your reply and your recommendations to get the fix
The dating site is sitting with my hosting site, Hostinger
My public IP has not changed as I verified it on the logs when I have tried to log in the admin panel
I think my mistake was compounded when i copied and paste the IP in the field and it resulted with this:https://whatismyipaddress.com/ip/108.73.51.31 and not just the numbers in the IP.
Anyway I tried your recommended option of executing the SQL query through my phpMyAdmin:
 UPDATE pH7_Settings SET value = '' WHERE name = 'ipLogin'; and this is what I got back:
Error
Static analysis:
1 errors were found during analysis.
1.	Ending quote ' was expected. (near "" at position 58)
SQL query:
UPDATE ph7jySettings SET value = '' WHERE name = ipLogin';
MySQL said:  
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''' at line 1

**Comment by polynamaude** [comment]
@bartsanchez713 Hi !
You can use the editor to modify directly the table by simply clearing out the line where the column named "name" is ipLogin. Juste empty put a empty value.

If needed, read the phpMyAdmin manual to do so.

**Comment by pH-7** [comment]
> Hello,
> thanks for your reply and your recommendations to get the fix
> The dating site is sitting with my hosting site, Hostinger
> My public IP has not changed as I verified it on the logs when I have tried to log in the admin panel
> I think my mistake was compounded when i copied and paste the IP in the field and it resulted with this:https://whatismyipaddress.com/ip/108.73.51.31 and not just the numbers in the IP.
> Anyway I tried your recommended option of executing the SQL query through my phpMyAdmin:
> UPDATE pH7_Settings SET value = '' WHERE name = 'ipLogin'; and this is what I got back:
> Error
> Static analysis:
> 1 errors were found during analysis.
> 
> 1. Ending quote ' was expected. (near "" at position 58)
>    SQL query:
>    UPDATE ph7jySettings SET value = '' WHERE name = ipLogin';
>    MySQL said:
>    #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''' at line 1

Hey @bartsanchez713, can you please retry with 
```sql
UPDATE pH7_Settings SET settingValue = \'\' WHERE settingName = 'ipLogin';
```

Hopefully, this one will work for you

**Comment by pH-7** [comment]
@bartsanchez713, so for you, with your custom database prefix, it will be
```sql
UPDATE ph7jySettings  SET settingValue = \'\' WHERE settingName = 'ipLogin';
```

**Comment by pH-7** [comment]
If this query works, last thing you will have to do is to delete all folders located in `/_protected/data/cache/pH7_cache/db/config` 
You can do that easily with an FTP client (filezilla) or through your cPanel dashboard.

(the reason is that the value will still be cached in a static file. Indeed, to speed up your website and reduce CPU resource, pH7CMS caches most of the data from the database to static files in your web server).

**Comment by bartsanchez713** [comment]
Hello PH and polynamaude,
I fixed the problem thanks to both recommendations so was able to log in to admin panel
First I "used the editor to modify directly the table by simply clearing out the line where the column named "name" is ipLogin. Just empty put a empty value" but after this still not fixed then I used PH's
last recommendation of "last thing you will have to do is to delete all files located in /_protected/data/cache/pH7_cache/db/config/
You can do that easily with an FTP client (filezilla) or through your cPanel dashboard."
The query did not work but had the fix already but was missing deleting the caches files.
When I put the query as PH said:
UPDATE ph7jySettings  SET settingValue = \'\' WHERE settingName = 'ipLogin';
I got back the following:
Error
Static analysis:
2 errors were found during analysis.
1.	Unexpected character. (near "\" at position 41)
2.	Ending quote ' was expected. (near "" at position 75)
SQL query:
UPDATE ph7jy_settings SET settingValue = \'\' WHERE settingName = 'ipLogin'
MySQL said:  
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\'\' WHERE settingName = 'ipLogin'' at line 1

Just glad the problem is fixed now and many thanks!!!!

**Comment by pH-7** [comment]
You are very welcome @bartsanchez713! Very happy for you that it works again! 🎉
BTW, if you are happy with the software I built, could you leave a nice review on Sourceforge https://sourceforge.net/projects/ph7socialdating/ (it takes just one minute)
**It's something that really motivates me to continue the development of the software 😊** and helps the software to get better 😃 

Have a great weekend!

**Comment by pH-7** [comment]
Hi again @bartsanchez713! How are you? I hope you had a good weekend 🤞

I was wondering if you could you leave a review at https://sourceforge.net/projects/ph7socialdating/
**It really motivates me to continue the development of the software 😊** and helps the software to get better 😃 

Any further helps, just let me know at anytime 😀
Have a great weekend!

**Comment by pH-7** [comment]
Thanks @bartsanchez713! 😊 You rock! 🚀
