### ISSUE TITLE
Encart publicitaire

### ISSUE THREAD

**Issue by OsonsRever** [pH7Software/pH7-Social-Dating-CMS#428]
Bonjour,
Je ne rencontre aucun problème sur le site lors d'une connexion via un pc mais dés que l'on ce connecte via un smartphone une page publicitaire pornographique s'ouvre et bloque  l’accès à la page d'accueil, cette publicité n'est pas refermable.
Pouvez vous m'aider.
Merci d'avance
Valérie
Adresse : http://www.osonsrever.com/rencontre

**Comment by pH-7** [comment]
Bonjour @OsonsRever 
Avez-vous activé le "Adult Disclaimer" dans Admin Panel -> Settings ->  Adult Disclaimer? 
Veuillez vérifier que cette option soit désactivée, comme indiqué sur cette page.

<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">


Excellent week-end !

**Comment by OsonsRever** [comment]
Merci beaucoup pour cette réponse rapide effectivement tout vas bien.
Je profite pour vous demander si vous savez si une traduction existe en français pour le tchat et le chatroulette
Merci d'avance
Valérie

**Comment by pH-7** [comment]
Il n'y a pas de quoi. C'est un plaisir @OsonsRever 
Le chat et le chatroulette étant des services tiers, il n'y a pas de traduction possible pour le moment. Cependant, vous pouvez les changer par un autre fournisseur ou en installer un sur votre serveur.
Plus de détails ici : https://ph7cms.com/how-to-change-chat/

**Comment by pH-7** [comment]
Au passage, pouvez-vous "Star" ce dépôt GitHub ?

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Bonne chance pour le tchat !

**Comment by pH-7** [comment]
Au passage, si vous aimez le logiciel et que vous avez une minute devant vous, ça me ferait vraiment plaisir si vous pouviez laisser un avis sur https://sourceforge.net/projects/ph7socialdating/ Cependant, vous devez créer un compte pour pouvoir laisser un avis (donc, je peux comprendre si vous n'avez pas le temps).

Bonne fin de soirée !

**Comment by pH-7** [comment]
Osons, ça me ferait vraiment plaisir si vous pouviez laisser un avis sur https://sourceforge.net/projects/ph7socialdating/  😊

Profitez de votre week-end ! Bonne chance 🍀
