### ISSUE TITLE
Nearby error Special Characters Cities Names

### ISSUE THREAD

**Issue by nandosilvajr** [pH7Software/pH7-Social-Dating-CMS#429]
Hi, @pH-7 !
Recently I report a error with special characters with the Setúbal city in Portugal. I have the same problem with other cities that contains accent in their names, like to image follow.

![image](https://user-images.githubusercontent.com/32247688/52181488-5c8bb100-27ea-11e9-80d1-6ea4bfbb013d.png)

**Comment by pH-7** [comment]
Like how I said there https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/425,
Please update your line
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/cc4deaae4dc07627ed1ed9bfb832641215ef5b81/_protected/app/system/modules/map/controllers/CountryController.php#L154 
File `_protected/app/system/modules/map/controllers/CountryController.php`, line 154

To the following
```php
 substr($this->str->upperFirst(str_replace(['%BA', '%A1'], ['ù', 'á'], $this->httpRequest->get('city'))), 0, self::MAX_CITY_LENGTH)
```

I will try to find a viable fix later for a future version.

Another option (worst-case scenario...), is to just to disable the Google Maps (Admin -> Mods -> Enable/Disable Modules -> uncheck "Google Maps").

Thanks!

Enjoy your day anyway! :)

**Comment by nandosilvajr** [comment]
Okay, @ pH-7! Thank you for your help. I will try to fix it, anyway. If I can, I'll tell you.

**Comment by pH-7** [comment]
Hey @nandosilvajr 
I have a great news for you!

Please finally find the definitive solution (without dirty hacks) 
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/425#issuecomment-462023703
