### ISSUE TITLE
Quick and Advanced search shows anything

### ISSUE THREAD

**Issue by nandosilvajr** [pH7Software/pH7-Social-Dating-CMS#430]
Hi, @pH-7
When I try make a search I can't get anything results and no shows any message with error report.
I can't way to show how it happens.

Thanks,

**Comment by pH-7** [comment]
Hi @nandosilvajr!

Are you sure there were no cities/countries specified (where you don't have users in there), or maybe the age criteria is different than the age of your users?

**Comment by pH-7** [comment]
Hum, interesting. Do you have any PHP errors in your log file (at `/_protected/data/log/php_error.log`)?

**Comment by pH-7** [comment]
Okay... thanks anyway! Still weird though... :)

**Comment by githubsteef** [comment]
hi, same thing here, because the city is always filled with na placename, and bon remove and then enter it is back again
