### ISSUE TITLE
Bug Article ID 

### ISSUE THREAD

**Issue by marketing720** [pH7Software/pH7-Social-Dating-CMS#432]
The following error was found:
Error: Article ID cannot exceed 60 character(s).
* Article name:

Doesn't matter the character length - still dumps

**Comment by pH-7** [comment]
Hi @marketing720

I tried to replicate you issue, and it works like a charme. 
What PHP version do you have? Can you put "My Blog Post Test" for the "Article Name field and try again?

**Comment by pH-7** [comment]
<img width="1333" alt="screenshot 2019-02-07 at 7 00 35 am" src="https://user-images.githubusercontent.com/1325411/52362742-1793a300-2aa6-11e9-80e4-0661661abe9b.png">
<img width="1006" alt="screenshot 2019-02-07 at 7 00 23 am" src="https://user-images.githubusercontent.com/1325411/52362744-182c3980-2aa6-11e9-95ab-f53d5975edc7.png">

**Comment by pH-7** [comment]
Did you try again @marketing720?
What did you put for the "Article Name" field?

**Comment by pH-7** [comment]
Hey @marketing720, since you didn't get back to me, I assume that this issue is now solved for you and can be closed. Just let me know if this isn't the case 😃
