### ISSUE TITLE
Install redirects.

### ISSUE THREAD

**Issue by ghost** [pH7Software/pH7-Social-Dating-CMS#433]
When I go to my domain to install pH7 I get an error saying "too many redirects".  When I look at the address bar it says: http://chillpages.com/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/_install/

**Comment by pH-7** [comment]
Hi @MarkNth 
Try again to go to http://chillpages.com/_install/ on another browser or on an incognito window (or clear the cache/cookies of your web browser).

Hope that will help! 🤞

**Comment by pH-7** [comment]
Hum, I actually tried and doesn't look good...

**Comment by pH-7** [comment]
http://chillpages.com/_install/index.php?c=install&a=index fails! Maybe, you should ask your web host what's the problem in there?

With what Web hosting provider are you?

**Comment by pH-7** [comment]
[TMP Hosting](http://ph7cms.com/web/tmdhost) is usually a good place to start.
Business or Enterprise plans are good, and even better, their Cloud hosting or VPS plans!

**Comment by kevinbkk** [comment]
I also has the same issue on hostgator. Please fix the issue, i can't even go through installation and it keeps redirecting.

**Comment by polynamaude** [comment]
@kevinbkk Maybe you should ask yourself where the issue is ? Our software or your hosting provider ? Before making the affirmation that the problem reside with pH7CMS maybe you should make sure your provider does have the basic requirements for running the CMS and that you have setup your web server properly. It is not because something doesn't run "out of the box" in every situation that there's a problem.

This is not a software for "end user".

**Comment by kevinbkk** [comment]
Problem solved, they told me the _install folder permission should be 755

**Comment by pH-7** [comment]
Great! Happy to hear that! You see, like I told you, it's always good to ask your web host, because this was related to it.

**Comment by pH-7** [comment]
If you are happy with the software and the support, don't forget to Star the repo, thanks!
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

I appreciate it!

**Comment by kevinbkk** [comment]
> If you are happy with the software and the support, don't forget to Star the repo, thanks!
> ![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
> 
> I appreciate it!

Ok, before giving you 5 star for this script, would you let me know if ffmpeg is really necessary if I don't really want use videos? As hostgator doesn't provide ffmpeg on shared hosts and I don't want pay more for my host to install it. Thanks.

**Comment by polynamaude** [comment]
@kevinbkk There's one reason why we ask to make 1 Question = One opened issue. And the reason is quite simple, we don't want to answer the same question over and over.

What you asked about **ffmpeg** has already been answered more than once.
No you don't need this unless you want to use videos. So simply disable this option.

**Comment by kevinbkk** [comment]
Thanks a lot. I'm new so I didn't know about how to ask questions here. You got my 5 star, happy to work with you guys.

**Comment by MarkNth** [comment]
I tried another browser and it didn't work. I saw a comment by kevinbkk and changed the permission of the install folder and it worked. I did that along with installing in an incognito window. Thank you everyone!

**Comment by pH-7** [comment]
HI @kevinbkk  

Yes, if you don't have ffmpeg installed, just leave the "video" module disabled (Admin Panel -> Mods -> Enable/Disable Modules -> uncheck "video").

That would be awesome if you could indeed give a five star review at https://sourceforge.net/projects/ph7socialdating/reviews/ 
You just need to create an account there, but it takes max 2min! I promesse). This really motivates me to continue the software. Thanks!
