### ISSUE TITLE
Changing the Adult Warning pop-up

### ISSUE THREAD

**Issue by MarkNth** [pH7Software/pH7-Social-Dating-CMS#436]
My site is for gay men and I would like to know how to change the background of the adult warning popup. Thank you.

**Comment by polynamaude** [comment]
@MarkNth Did you take some time to read the documentation before asking this question ??????? !!!!!
The "Adult Warning Popup" is a external service or third party if you prefer. Why do you contact us about this?

Do you ask the guy who sold your stove what to do when there's a power outage ? This is pretty much the same here.

**Comment by MarkNth** [comment]
Did you have any proper home training? I would not have asked had I known. Yes, I did a search before asking the question. Sorry to have bothered you. Is it because it's  <whisper> gay </whisper>?

**Comment by MarkNth** [comment]
You let people like @polynamaude give advice/help?

**Comment by polynamaude** [comment]
Let me get it right ? You didn't notice that it's an external service when it is said directly on the configuration page (where you enable this option).

Oh, just like that, I founded a LGBTQ Defense organisation so I have big doubt on your complains. Maybe you should stop being a victim and act on your destiny ;-)

**Comment by MarkNth** [comment]
You still have the manners of a cow. The gay thing was more of a joke, hence the "whisper". I saw your picture and I have no doubt you fit the LGBTQ spectrum in some way. Blocking you now. I deleted the script anyway.
