### ISSUE TITLE
Change Logs, Update Option?

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#437]
I just installed this script yesterday and did a lot of customization and today the new release came out, now my question is how to update it to new version? Should I delete everything and begin installing new version every time new update comes out? I couldn't find any change logs file in new downloaded version

**Comment by polynamaude** [comment]
Why don't you take the time to read the docs before asking such question ?
https://ph7cms.com/doc/

**Comment by pH-7** [comment]
Hey @kevinbkk 

Have you been to https://github.com/pH7Software/pH7-Social-Dating-CMS/releases/tag/14.9.0?
The change logs can be found here https://github.com/pH7Software/pH7-Social-Dating-CMS/compare/14.8.9...14.9.0 (210 commits, 141 files changed. It's really huge. You won't be able to update it manually, except you cloned the repo, then you could just do a `git pull`... (however, if you did changes in the files, it won't be that easy...).

The upgrade instructions are mentioned on the "Update alert box" on the admin dashboard https://ph7cms.com/doc/en/upgrade

Anyway, don't worry. This version isn't a security update, so you could avoid it to avoid more problems. That's a good option too :) If you aren't on PHP 7.3, you won't have any problems with pH7Builder 14.8.9

**Comment by kevinbkk** [comment]
Thanks for great answer

**Comment by pH-7** [comment]
You're very welcome 😊
