### ISSUE TITLE
What should i do with _protecetd file?

### ISSUE THREAD

**Issue by chalit9999** [pH7Software/pH7-Social-Dating-CMS#438]

**Comment by chalit9999** [comment]
Hi i have forgotten what to do with this file _protecetd ?   should i delete it or just change the file name? Thanks

**Comment by pH-7** [comment]
Please, don't delete it. It contains all "server" files. Without it, you have only the "fontend" static files.
Only for security reasons it is advisable, however if you use Apache (I think you do), there is a .htaccess in it that protects everything inside and denies every requests made from outside, so it's safe to say that you can just leave it as it is.

**Comment by chalit9999** [comment]
thank you so much

ในวันที่ พ. 13 ก.พ. 2019 เวลา 13:42 ♚ PH⑦ de Soria™♛ <
notifications@github.com> เขียนว่า:
