### ISSUE TITLE
hello my members aren't getting email, what should i do

### ISSUE THREAD

**Issue by D4rkkking** [pH7Software/pH7-Social-Dating-CMS#443]
hello my members aren't getting email, what should i do

The following error was found:
Oops! Our email server encountered an internal error and the email could not be sent. Please try again later!

**Comment by pH-7** [comment]
Hi @D4rkkking 
Welcome! How are you doing today?

Are you on local host? If so, you will need to install a SMTP server. 
If you are with a web host, please ask them if your SMTP server is correctly configured and check its log.

Finally, make sure the email isn't in the spam folder.

More info: https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

Hope this helps 🤞

Thanks

**Comment by D4rkkking** [comment]
Do you have a video?
