### ISSUE TITLE
remove rollover effect on profile search result 

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#446]

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by samit78** [comment]
When we do search , it shows all profile images but i want to remove rollover effect on profile image as now when take mouse on it , its moving all the time.

**Comment by pH-7** [comment]
@polynamaude Great work on the wiki page you created! :tada: I really appreciate your help on it!!!

**Comment by pH-7** [comment]
@samit78 
Please edit `templates/themes/base/tpl/browse_user.inc.tpl`, around line 30
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/browse_user.inc.tpl#L30

And change
```smarty
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, true) }}
```
to 
```smarty
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, false) }}
```

then, save the file and retry.

Hope this helps! Good luck

**Comment by pH-7** [comment]
BTW @samit78 
It would be also nice if you could Star this Github repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Let me know if you need any further helps :)

**Comment by samit78** [comment]
Thanks its working but the image size became small , i madeit before size 125*125 but now it become small
Regards,
 

 

    On Friday, February 22, 2019, 2:56:48 AM GMT+7, ♚ PH⑦ de Soria™♛ <notifications@github.com> wrote:  
 
 
@samit78
Please edit templates/themes/base/tpl/browse_user.inc.tpl, around line 30
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/browse_user.inc.tpl#L30

And change
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, true) }}
to
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, false) }}
then, save the file and retry.

Hope this helps! Good luck

**Comment by samit78** [comment]
When i added CSS on image.avatar width 125px and height 125px , it looks perfect on home page and search result page but on latest user : its stretching the image



Regards,
 


    On Friday, February 22, 2019, 2:56:48 AM GMT+7, ♚ PH⑦ de Soria™♛ <notifications@github.com> wrote:  
 
 
@samit78
Please edit templates/themes/base/tpl/browse_user.inc.tpl, around line 30
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/browse_user.inc.tpl#L30

And change
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, true) }}
to
{{ $avatarDesign->get($user->username, $user->firstName, $user->sex, 64, false) }}
then, save the file and retry.

Hope this helps! Good luck

**Comment by polynamaude** [comment]
@samit78 Have you looked with the _page source_ option of your browser ?
It should give you some hint about what to change.
