### ISSUE TITLE
Since new update(pH7Builder-14.9.0), these functions stopped working

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#447]
No longer receiving any emails either for user and admins.

Such email examples for admins are: user registration email, user manual approval emails....
Such email examples for users are: welcome email, profile approved email, picture approved email...

There are also other bugs:
1. Users can login **immediately** after registration even tough the manual user approval activated.
2. There's no option to delete/edit forum replies. (delete option is only available for forum topics)
3. Google Maps showing New York by default for all profile locations.

**Comment by kevinbkk** [comment]
_As emails work well on PHP 5.6 I will stop using php 7+. But it seems that the script is not fully compatible with php 7+_

**You didn't say anything about the other issues. Please don't answer if you think those issues are not important, but I think they are related to theme's functioning that the support team can take a look.**

Here are the issues:

1. Users can login **immediately** after registration even tough the manual user approval activated.
2. There's no option to delete/edit forum replies. (delete option is only available for forum topics)
3. Google Maps showing New York by default for all profile locations.

**Comment by polynamaude** [comment]
@kevinbkk I think you didn't read the link about asking for help.

First of all, without your PHP logs, I can't do nothing other than presume. Is it because some modules are not compiled in your PHP distribution ? are not activated ? your configuration is different ?

Also, no there's no **support team** as you think there is. PH did 99.9% of the coding and I give him a hand at support when I have time off from work.

Also, none of what you are mentioning is related to theme issue. Theme don't build Google Maps query or has something to do with the user approval process.

**Comment by polynamaude** [comment]
@kevinbkk If you want to do the "you answer in half" than maybe I should get back with the already posted question I gave you ;-)

Btw, there's some documentation on email problem. Have you looked into it??

**Comment by pH-7** [comment]
> * There's no option to delete/edit forum replies. (delete option is only available for forum topics)

Hi @kevinbkk 
There were no changes in the features you mentioned from 14.8.9 and 14.9.0, so I doubt it comes from it... I will try to replicate those issues for you however.

Concerning the email issue with the PHP version, please ask your web host company, this problem should be caused from their side.

Finally, concerning the Google Maps. "New York" is the default location (before, it used to be Paris). Maybe it isn't configured correctly. Google did recent changes. Make sure your account where you used your API key is correctly setup
https://developers.google.com/maps/documentation/geocoding/usage-and-billing
And the API key has to go in Admin Panel -> Setting -> General -> API -> Google Maps API Key

Please also check this related post https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/412#issuecomment-453609431
Let me know if you figured it out.

**Comment by kevinbkk** [comment]
> user approval process is not related to theme
As I said it's better you let the real coding staff to look at my questions. Thanks btw

**Comment by pH-7** [comment]
I just tested for you the "Manual Activation by Administrator" with 14.9.0 and I cannot login if my account hans't been approved by an admin. There is probably wrong on your side or files you may edited which might cause your actual problem. 

Good luck anyway with your website! And enjoy your weekend :)

**Comment by polynamaude** [comment]
@kevinbkk I'll take your suggestion and I'll answer you exactly for this reason.

Templates only deal with the way the data is presented on your screen. It has nothing to do with the processing of those data. The back end will serve the same stream of data whatever different theme is given. And that's the exact goal of using theme, that is to separate presentation from processing.

**Comment by kevinbkk** [comment]
> I just tested for you the "Manual Activation by Administrator" with 14.9.0 and I cannot login if my account hans't been approved by an admin. There is probably wrong on your side or files you may edited which might cause your actual problem.
> 
> Good luck anyway with your website! And enjoy your weekend :)

Once a user register it will automatically redirected to login page. Did you login exactly after registration without closing the window? after the user login, It will alert (Oops! You are already connected.) that you're already logged-in even tough I activated the user manual approval.

**Comment by kevinbkk** [comment]
> @kevinbkk I'll take your suggestion and I'll answer you exactly for this reason.
> 
> Templates only deal with the way the data is presented on your screen. It has nothing to do with the processing of those data. The back end will serve the same stream of data whatever different theme is given. And that's the exact goal of using theme, that is to separate presentation from processing.
