### ISSUE TITLE
Design Profile

### ISSUE THREAD

**Issue by nerfthis2019** [pH7Software/pH7-Social-Dating-CMS#448]
Seems as though the Custom wallpaper option for users doesn't work. When you upload a wallpaper it does save it to the correct directory. However it doesn't display on the user page. I do have some custom CSS but that's mainly for the top navigation/header.

**Comment by pH-7** [comment]
Can you try to clear your browser's cache or visit the profile page with incognito mode?

**Comment by pH-7** [comment]
Don't have any issue for me with the default themes. Probably something from your modification. Maybe you used `!important` in your CSS rules. 
The best would be to play with your browser's inspector tool.

**Comment by nerfthis2019** [comment]
I'll take a look, I truly appreciate the fast and positive response!

**Comment by nerfthis2019** [comment]
Hmmm not sure why it's not working tried all the above and nothing. Maybe a clean reinstall is in order?

**Comment by polynamaude** [comment]
@nerfthis2019 I'll ask the same question (again) as PH did as it could be part of your problem. Did you clean the cache ?
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by pH-7** [comment]
On a fresh installation, it works like a charm for me... Strange. Like I told you, try to play with the Inspector tool of your Web browser and CSS rules in there.

**Comment by nerfthis2019** [comment]
Update: I reinstalled and still doesn't work. I installed the latest version as well. Not sure what it could be. However I just went ahead and deleted the link to "Design Profile" for all users. Wasn't that big of a deal for me. Thanks for all the help as well! One more thing though, where can I find a How-to or guide on making mods for Ph7?
