### ISSUE TITLE
We are new

### ISSUE THREAD

**Issue by marketing720** [pH7Software/pH7-Social-Dating-CMS#449]
IS this app - running with WordPress - I mean you do you need or should you use this app with a wordpress plug in ??

**Comment by zeerprettiggestoord** [comment]
This isn't a wordpress plugin. Its a standalone program.

Op za 23 feb. 2019 21:55 schreef Marketing 720 <notifications@github.com>:

**Comment by marketing720** [comment]
Thank you zeer

**Comment by marketing720** [comment]
We uploaded 14.8 a couple of weeks ago - and just saw there is a new release 14.9 - how does one update the program files - sorry for the stupid question

**Comment by polynamaude** [comment]
@marketing720 
Why don't you look at the Wiki instead of making people waste time answering "stupid questions" as you say yourself ?

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

https://ph7cms.com/doc/

You are running straight into a RTFM.

And in the end, possibly that people simply won't answer the day you'll have a real useful one ;-)

**Comment by marketing720** [comment]
Has to be a liberal - possibly because I didn’t know about it  
    	
    	

    	Get Outlook for iOS
    
  




On Sat, Feb 23, 2019 at 5:28 PM -0800, "Polyna-Maude R.-Summerside" <notifications@github.com> wrote:












@marketing720

Why don't you look at the Wiki instead of making people waste time answering "stupid questions" as you say yourself ?


https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help


https://ph7cms.com/doc/


You are running straight into a RTFM.


And in the end, possibly that people simply won't answer the day you'll have a real useful one ;-)

**Comment by polynamaude** [comment]
There's a simple rule about life, try something before reaching out for help.
Right on the landing page there's a link to the ph7cms web page and documentation. The README.md is not made for duck, dogs, cats and other kind of domestic or wild animals.

**Comment by polynamaude** [comment]
@marketing720 When you see on the bar of a gitHub project the tab **wiki** it's a little hint about the fact that there's one.

**Comment by pH-7** [comment]
@marketing720 Please create a new thread for each different question. THanks

**Comment by pH-7** [comment]
If you want to update to the newest version, this post will probably help you https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/437
