### ISSUE TITLE
Add Bitcoin gateway

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#45]
People like to be anonymous on Dating sites and pay through Bitcoin is an excellent solution and will will increase easily the retention rate!

**Comment by ghozzt** [comment]
This one should be easy to integrate (it uses the Restful API)

https://bitpay.com/developers <https://bitpay.com/developers>
https://github.com/bitpay/php-bitpay-client <https://github.com/bitpay/php-bitpay-client>

Best regards,

Nico
