### ISSUE TITLE
Cannot login as admin, cannot register as a new user

### ISSUE THREAD

**Issue by ppiznal** [pH7Software/pH7-Social-Dating-CMS#452]
Hello.

I have a problem - after fresh installation I cannot sign in as admin (path /admin123) - when i post form, the page just refresh (301).
It does the same when I try to register as a new user.

I did installation on vps with Docker at Debian.
On one container there are PHP and Apache with uploaded files from Sourceforge zip, exposed port is 8100. Second container is MySQL.

I did installation like this:
I uploaded files from Sourceforge zip
Leaved folder path _protected as it was originally because this installation is only temporary.
Setted proper chmod for folders and files
Installed all required php extensions and modules as there were in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/Dockerfile
Enabled rewrite_module at Apache.

Changed https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/sample.htaccess to .htaccess and added

"<IfModule mod_security.c>
   SecFilterEngine Off
   SecFilterScanPOST Off
</IfModule>"

to disable mode mod_security

The installation went ok, MySQL tables were created, page can get assets, there is one administrator account in ph7_admins table.
What i see is - when i try to login into /admin123/main/login there is doubled PHS7SESS cookie in response.
Also there is no entry in ph7_admins_attempts_login
I tried to clear cache of browser and login from mobile phone.

I've read related issues, some of them seems to be similar, but with no clue what the problem might be
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/275
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/211
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/192
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/215
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/311

You've written there that there may be some session config problem so i enabled session_cookie_module and session_module at Apache, but i don't know it was needed (I'm newbie to Apache).

Do you think that problem may be somewhere in the Apache configuration?

I provide config files and logs:
config.ini https://pastebin.com/txrYiF2E
apache logs when trying to login to http://mysite.com:8100/admin123/main/login: https://pastebin.com/rHJZWCUf
apache logs when trying to sign up a new member http://mysite.com:8100/signup: https://pastebin.com/st40xh52
request and and response headers from browser: https://pastebin.com/DVCEULvv

I've edited domain name, ips in logs and some data in config to keep my privacy.

Regards
Przemek

**Comment by polynamaude** [comment]
Have you checked the documentation ?
https://ph7cms.com/doc/

I always suggest a simple thing and it's keep it simple when you are new to something. Basic rule of life.

I'd suggest you start by doing a standard install on your **localhost**.  That is, no docker or containers, a Linux box with apache, installing the CMS in a folder, using MySQL/MariaDB as a normal installation. That's quite straight forward to do.

Once you get it working in a somewhat standard configuration you can try to play with more exotic installations. And when something stop working you'll have a existing base to compare.

**Comment by polynamaude** [comment]
@ppiznal I give you a simple example about what I just said (and after taking a really quick look at your logs). Some of the URL are built using standard ports number, so when you install something on port 8100 it can cause problem. And this is not exclusive to pH7CMS. There's a reason why we use 80 for HTTP and 443 for HTTPS ;-)

And this may be part of you problem right now.

**Comment by polynamaude** [comment]
@ppiznal Yes container based solution are useful but in the situation described here, they are more a configuration overhead than anything else.

**Comment by ppiznal** [comment]
Oh yes, I've changed exposed port in container from 8100 to 80 and now it works :D
Thank you for help :)
