### ISSUE TITLE
problems with installation of new created language

### ISSUE THREAD

**Issue by ungoliant235** [pH7Software/pH7-Social-Dating-CMS#453]
Hello,

tried to install a new language i translated myself but it dont work..
Maybe there is a problem in my Code but i cannot find it...
if i upload de folder de_DE in my langs directory it shows up in the Admin panel but if i activate it the text stil appears in english...

Thanks for helping!
[de_DE.zip](https://github.com/pH7Software/pH7-Social-Dating-CMS/files/2900438/de_DE.zip)

**Comment by gatgat1991** [comment]
das prob kenne ich ich kann nicht alles übersetzen  wirt dann nicht übernehmen und Hardcodet kann man es ja ändern aber is ja nicht so doll

**Comment by ungoliant235** [comment]
problem still exits; 
but we moved to another system.. (WP Theme:Datebook)

**Comment by ungoliant235** [comment]
problem still exits;
but we moved to another system.. (WP Theme:Datebook)
