### ISSUE TITLE
Emails on PHP 7+ Not Working But Works on PHP 5.6 (on major host provider: HostGator)

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#454]
I should tell again that **emails work on PHP 5.6** but **not work on any versions of PHP 7+** on Hostgator. 
Already double checked with different members of Hostgator supports. 
Configurations, SMTP, PHP Logs all are fine. They told me this problem is definitely from the script.

Here is the full list of their host software properties:
https://support.hostgator.com/articles/what-software-and-program-versions-does-hostgator-offer

**Note:** This problem is not only for pH7Builder 14.9.0 but for older versions too.

**Comment by nerfthis2019** [comment]
Hostgator sucks for Ph7 I tried it months ago and had so many issues. I installed on Dreamhost with no issues at all.

**Comment by polynamaude** [comment]
@kevinbkk Thanks for remind us of what you already told us and that we did answer.

https://ph7cms.com/doc/en/hosting

@nerfthis2019 Thanks for your intervention. Cheap hosting ain't always a goo deal.

**Comment by polynamaude** [comment]
@kevinbkk If you can give me some proof that the email problem is related to PHP 7 then I'd be happy to lok into it. But only based on something like "It runs on PHP 5.6 and not on PHP 7" does not make a direct link. If it was related to incompatibility then you'd get something in your PHP error / warning logs.

**Comment by kevinbkk** [comment]
> Hostgator sucks for Ph7 I tried it months ago and had so many issues. I installed on Dreamhost with no issues at all. It can't be PHP 7.x because I installed it with no issues on 7.x. I'm telling you I went down this road with hostgator. If you want to run a site with Ph7 get a different host like Dreamhost.

Thanks for confirming the issue but I don't have other issues with HostGator. As I said the problem only happens for emails and it's only on PHP 7+. It works 100% fine on PHP 5.6 on HostGator.

Hostgator is the largest and most popular web host provider in the world. It definitely worth if the guy behind PH7CMS take a look at this issue on HostGator by opening an account with them as the host comes with no question asked refund policy.

**Comment by nerfthis2019** [comment]
Considering this is a free script to the public and the creator takes donations for development of this. I wouldn't think he'd be willing to buy Hostgator hosting just to test this. But if it's the emails you're having a problem with. Have you tried making an email through Hostgator for your website, such as admin@example.com? Have you updated the email inside of ph7?In the general settings there should be an email tab and you set the email to whatever you want.

**Comment by kevinbkk** [comment]
> Have you tried making an email through Hostgator for your website, such as [admin@example.com](mailto:admin@example.com)? Have you updated the email inside of ph7?In the general settings there should be an email tab and you set the email to whatever you want.

I tried your suggestion and changed the email tabs setting to domain name emails but that doesn't help.

**Comment by polynamaude** [comment]
@kevinbkk We have made some suggestions of hosting provider that we do know they work goods. Be it you think that Hostgator is the most popular in your world and think we should be trying it out. We'd surely accept donation from yourself if you want to give us a hosting account.

In other case, like I said, you already have a list of hosting provider that do work good and there's many others that work too (Namecheap for example). The only thing Hostgator may be popular is for cheap hosting and this is one reason why there's problem with software that pushes the use of PHP.

Like @nerfthis2019 and I did repeat it too many time (again, again, again). This is something we do as volunteer so maybe if you have expectation of the type (should definitively buy a hostgator account to try it out) then maybe you should stick with commercial software.

**Comment by kevinbkk** [comment]
> We have made some suggestions of hosting provider that we do know they work goods. Be it you think that Hostgator is the most popular in your world and think we should be trying it out. We'd surely accept donation from yourself if you want to give us a hosting account.

Hold on! You're not a part of this script. Don't use the word "we"... Scum!
