### ISSUE TITLE
Not Interested button on Profile Page

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#457]
If you go to another profile and press “not interested”, you will land on another page that is different every time you press “not interested”, it changes the gender, looking for gender etc,

**Comment by pH-7** [comment]
Hey @samit78 
Not sure to understand your problem here

**Comment by pH-7** [comment]
That's the URL when you click on "Not Interested"
You can change the GET variables in there if you want different options from the search results.
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/32ddb2d38c1e7482b6759cfc27187f3ad7d5162f/_protected/app/system/modules/cool-profile-page/views/base/tpl/main/interested_buttons.inc.tpl#L5

It's part of
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/core/models/UserCoreModel.php#L322-L338

**Comment by pH-7** [comment]
By default (with the current params), the genders and the country on the search results will be the same than the current profile the user was on.

**Comment by samit78** [comment]
my profile is man and looking for woman
now i do quick search and select looking for woman,search results are correct all girls. now when i click on one girl profile and click not interested.New page shows with results of man and woman which is wrong as i am looking only for woman so why man profile is showing
