### ISSUE TITLE
Smtp

### ISSUE THREAD

**Issue by D4rkkking** [pH7Software/pH7-Social-Dating-CMS#459]
hello my members aren't getting email, what should i do

**Comment by polynamaude** [comment]
@D4rkkking 
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

You should start by looking at the docs before asking questions we already answered !
Or your risk RTFM
