### ISSUE TITLE
Add Stripe Gateway

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#46]
Get https://github.com/stripe/stripe-php

**Comment by pH-7** [comment]
Example of usage
https://gist.github.com/boucher/1750375
https://github.com/stripe/wilde-things
https://github.com/chadsmith/OpenVBX-Plugin-Stripe

http://michaelbudd.org/tutorials/view/7/stripe-payment-gateway-tutorial-php

**Comment by pH-7** [comment]
https://stripe.com/docs/checkout could also help...

**Comment by ghozzt** [comment]
Nice find!

I have been looking for a replacement for the webcam chat module, that does not require a FMS or ffmpeg as that requires a VPS or dedicated server.

I’m using http://codecanyon.net/item/vi2u-cambox-private-webcam-chat-webrtc-/9096544 <http://codecanyon.net/item/vi2u-cambox-private-webcam-chat-webrtc-/9096544> which is based on webrtc (using peer.js), as webrtc support will be included in Spartan/Edge on windows and already works with Firefox and Chrome, it’s quite cheap (10 euro)

Demo on http://walv.is <http://walv.is/>

**Comment by pH-7** [comment]
Done!
