### ISSUE TITLE
Where can I edit the text of emails that the users getting for registration, approval and new messages?

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#460]
Where can I edit the **text of emails** that the users getting for registration, approval and new messages?
I think you forget to include this in your docs.

**Comment by polynamaude** [comment]
https://ph7cms.com/doc/en/how-to-change-email-template-design

https://ph7cms.com/doc/

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Layout/Html/Mail.class.php

Here you go !

This will change the styling of your emails, you'll have to either put the whole CSS in this file or add them to your template + refer  to it in this file.

I wouldn't say that some part of the documentation got forgotten, I'd say more that the documentation come as a extra gift for the price you paid.

**Comment by polynamaude** [comment]
@kevinbkk If you want to change the text then you do so with a editor for the GNU Gettext library (.PO) file as those are translated like most other strings.

**Comment by kevinbkk** [comment]
Looks like you're the only one that answer here so Ill try to understand you. 
I'm not talking here about styling. Are you sure the .PO file is the only file that contains **the text of the emails**?
I'm asking this because I already edited the .PO text for welcome to the users but the welcome email that users get is still the same and didn't change. There should be another file for **text of emails**.

**Comment by polynamaude** [comment]
Run **_fgrep_** with the string you want to change and you'll find where it is
