### ISSUE TITLE
self activation email does not have activation link in it

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#463]
hi,
i got the email for email activation but it does not have any links inside to activate. what should be link so i can put in email template

**Comment by polynamaude** [comment]
Hi !
Thanks for you interest in the pH7CMS.

If you want to use something as such, then you cannot use the same link on every email. It is quite obvious that it will be needing a different link generated for every user, plus store the link in the database so it can be compared later on so it can activate the actual user.

Those functions will require you do to some coding.

I'd suggest you take some time to read this post.

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

https://ph7cms.com/doc/en/code-convention

**Comment by samit78** [comment]
Hi,
actually my mistake , I delete the content in that email template in admin section. is it possible to get the content
Regards,
 

 

    On Friday, March 1, 2019, 7:41:48 PM GMT+7, Polyna-Maude R.-Summerside <notifications@github.com> wrote:  
 
 
Hi !
Thanks for you interest in the pH7CMS.

If you want to use something as such, then you cannot use the same link on every email. It is quite obvious that it will be needing a different link generated for every user, plus store the link in the database so it can be compared later on so it can activate the actual user.

Those functions will require you do to some coding.

I'd suggest you take some time to read this post.

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

https://ph7cms.com/doc/en/code-convention

**Comment by polynamaude** [comment]
How about simply getting the file you erased from the distribution archive ?

**Comment by pH-7** [comment]
Hi @samit78 
Not sure why you didn't see any hyperlink in the email. Maybe a problem with the webemail software.

FYI, the link is generate here for the email content: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/ec2b2867d51156c9a25ff6e71bd4e10fd32f2ab4/_protected/app/system/core/classes/RegistrationCore.php#L135

**Comment by pH-7** [comment]
@samit78 
The content of the email to put back through the admin panel is
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/global/views/base/tpl/mail/sys/mod/user/account_registration.tpl

**Comment by pH-7** [comment]
Hope it helps! And if you appreciate the software, don't forget to review it on https://sourceforge.net/projects/ph7socialdating/ (it just takes one minute to create an account and leave a review).
This really motivates me to continue my hard work on the software 😄

**Comment by pH-7** [comment]
@samit78  Hope it helps! And if you appreciate the software, don't forget to review it on https://sourceforge.net/projects/ph7socialdating/ (it just takes one minute to create an account and leave a review).
This really motivates me to continue my hard work on the software 😄
