### ISSUE TITLE
PH7CMS 15 Installation Issue

### ISSUE THREAD

**Issue by justin4444** [pH7Software/pH7-Social-Dating-CMS#464]
Hi, I'm trying to install your new update but it says the third party library is not installed. I download the PH7CMS 15 from sourceforge.

**Comment by polynamaude** [comment]
Have you already installed pH7CMS before and this is only an update ?

https://ph7cms.com/doc/en/requirements

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

If you make a _screenshot_ then you'll make it easier for us to understand what you are reporting.

Make sure you have the minimum requirements.

**Comment by justin4444** [comment]
Here's the screenshot the error I got on installation PH7CMS 15:
https://prnt.sc/ms4vv7

I had no issue with installation of previous versions.

**Comment by polynamaude** [comment]
run **_composer install_** from your installation root folder

maybe the package had a problem with the build script from Sourceforge has it does happen once in a while. I work on the development of other CMS and we did have some problem with the automatic packaging.

Look to make sure you have a folder name **__protected/vendor_** and under this you should have all the external dependencies.

If you need more help about composer https://getcomposer.org/doc/

**Comment by justin4444** [comment]
Unfortunately I'm not familiar with the composer installation. The error says it's because you downloaded the github version of PH7CMS and when I look at the script files it has a GitHub folder which was not included in previous versions of PH7CMS. Are you sure you uploaded the right version of PH7CMS on sourceforge? Why it should have github folder in sourceforge?

**Comment by polynamaude** [comment]
Read back what I just said ! It's quite plain easy English.

And I'll add a scoop here...

Your problem maybe related to Sourceforge not building properly the download package as it should run by itself the **_composer install_** before making the archive.

I just told you what to do so you get your problem fixed. The only difference between the Sourceforge archive and the gitHub version is that the SF one already include dependencies.

There's no such thing as "uploading" archive to Sourceforge. You supply the repository and the hooks to call for building on new release.

If it does have the .github folder not removed then it's mostly SF that has problem with their archive building script (again). I had the same problem with Tiki CMS about a month ago.

So download the release from here https://github.com/pH7Software/pH7-Social-Dating-CMS/releases/tag/14.9.0

and run **_composer install_**

Or just run **_composer install_** from your actual installation.

If you don't have composer then I gave you the link for the site. By the way, if you have any interest in using any type of PHP software then you'd better learn how Composer work.

https://getcomposer.org/

**Comment by polynamaude** [comment]
@justin4444 I have just downloaded the file from SourceForge and it does contain a **__protected/vendor_** folder. Could you have removed or renamed this folder ?

https://sourceforge.net/projects/ph7socialdating/files/14.9/pH7Builder-14.9.0.zip/download

**Comment by justin4444** [comment]
> @justin4444 I have just downloaded the file from SourceForge and it does contain a **__protected/vendor_** folder. Could you have removed or renamed this folder ?
> 
> https://sourceforge.net/projects/ph7socialdating/files/14.9/pH7Builder-14.9.0.zip/download

I'm talking about the version 15 not 14.9. The version 14.9 works like a charm. No issue with that.

**Comment by polynamaude** [comment]
@justin4444 If you look at version 15 then you'll see there's the word **_BETA_** in it. So this means that there may still be some problem using it and by virtue of logic, shall be used by persons who either have in depth knowledge of the inner working of PHP or that is willing to take some risk.

Alpha - Beta - Release Candidate (RC) - Release

**Comment by justin4444** [comment]
OK thanks, just wanted to report this issue here so you or whoever admin is can fix it in newer versions. Thanks for great support.

**Comment by polynamaude** [comment]
It's noted, thanks for letting us know.
I'll look if the package was built properly.
Still, I'd suggest you stick with the release version if you want stability. When you go with Beta version, there's not guarantee that there won't be any breaking changes in the future or that you'll always be able to make a update to the latest version.
Beta are for testing and are published for the exact reason of getting feedbacks.

Thanks

**Comment by polynamaude** [comment]
@justin4444 I've just downloaded and looked at the archive.
The folder is missing (as I believed it was). If you want to use the 15 version then simply run composer as I said. If you are unable to do so then let me know what OS you are on and I'll build you a archive.

**Comment by polynamaude** [comment]
@justin4444 If you like the software then could you please **_star_** the repository in gitHub and / or make a **_review_** on Sourceforge.

**Comment by pH-7** [comment]
@justin4444 Please bear in mind that the version you mentioned is still in beta https://github.com/pH7Software/pH7-Social-Dating-CMS/releases/tag/15.0.0-beta1

Concerning your problem, please read https://github.com/pH7Software/pH7-Social-Dating-CMS#-installation (you need to run composer). Because, on GitHub, the dependencies of the software aren't committed.

**Comment by pH-7** [comment]
The best option would be to use pH7Builder 14.9.0

**Comment by pH-7** [comment]
Hope it helps  @justin4444  and don't forget to STAR the repo 😉 
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
