### ISSUE TITLE
Want to take a photo of yourself directly with your webcam?

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#465]
when click this link it goes to payment when it must open webcam and let user take photos. 
One more issue when user upload full photo we cant see it on website , it must auto crop or let user crop his or her face so it can be visible . how to do these both issue please let me know

**Comment by polynamaude** [comment]
I don't understand exactly what you are saying here. Can you be more precise please ?

Are having some problem with the software or is it that you are asking for how to add some specific function ?

You seem to have opened many issues as I see.
