### ISSUE TITLE
My Database password has been changed, how to update it in your script?

### ISSUE THREAD

**Issue by justin4444** [pH7Software/pH7-Social-Dating-CMS#468]
I changed my database password and want to know how can i change it for your script.

**Comment by polynamaude** [comment]
Have your looked inside your configuration file (config.ini) ?

**Comment by polynamaude** [comment]
May I ask you to please "star" the repository if you like the software ?
<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/53856715-2a17d400-3fa1-11e9-8e26-d91ac4349d4d.png">
