### ISSUE TITLE
search box does not show anything due to a standard filled in city or placename

### ISSUE THREAD

**Issue by githubsteef** [pH7Software/pH7-Social-Dating-CMS#471]

**Comment by githubsteef** [comment]
In my search box there's a name of a city filled in that byou can't remove for a search without a placename specified.

**Comment by jilinos** [comment]
I too would like to know ?!

**Comment by githubsteef** [comment]
[23-Feb-2019 09:55:28 Europe/Amsterdam] PHP Fatal error:  Namespace declaration statement has to be the very first statement or after any declare call in the script in /home/vlamica212/domains/datingvoorons.nl/public_html/_protected/app/langs/it_IT/language.php on line 9

You asked on the other post for php error? well, this was on my log

**Comment by polynamaude** [comment]
@githubsteef Thanks for reporting the error but it is not related to your actual problem.
What version of PHP are your using ?
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by pH-7** [comment]
> In my search box there's a name of a city filled in that byou can't remove for a search without a placename specified.
> Is that enough specific? first timer...

That's actually a feature.
You can actually get rid off by removing the following highlighted here https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/ffeb4807a7599abd1fc09f0890997500854961f4/_protected/app/system/core/forms/SearchUserCoreForm.php#L254

**Comment by pH-7** [comment]
Hope it helps :)

**Comment by githubsteef** [comment]
7

Op vr 8 mrt. 2019 03:59 schreef Polyna-Maude R.-Summerside <
notifications@github.com>:

**Comment by githubsteef** [comment]
Ik use php7 andere Will try your solution today.

**Comment by githubsteef** [comment]
@pH-7 sorry for my late respons. Im ill and awaiting a treatment in hospital.
Im trying your sollution and will study on how to ask for help. im sorry for any inconvinience and thanks for your patience
