### ISSUE TITLE
Browse members sidebar is not showing in mobile displays

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#475]
Browse members sidebar is not showing in mobile displays. Probably the reason you removed it is because there's not much space in mobile displays. What I see others do is using top sidebars instead left sidebars. This was just a suggestion to improve your UI.

**Comment by pH-7** [comment]
Thank you for the suggestion @kevinbkk! I appreciate it. I will see how I could improve it for the next versions :)
