### ISSUE TITLE
Don't have config.ini

### ISSUE THREAD

**Issue by Romesar** [pH7Software/pH7-Social-Dating-CMS#478]
I've just installed ph7CMS. But neither the browser nor me can find **config.ini**
The directory **~/_protected/app/configs/** is empty. Is it supposed to be like that or I made a mistake somewhere?

**Comment by pH-7** [comment]
Hi @Romesar !

Did you install it with Softaculous? If so, please contact them or with your web hosting comapny. There is probably a problem when they install the software to the server.

If you installed the software with the normal installation ziward, probably there was an issue with the permissions of your folders, and the config.ini file couldn't be saved in _protected/configs.
Please check the permissions of the directories, or see with your web hosting company to do it for you...

See http://ph7cms.com/doc/en/install for further details.


Thanks!

**Comment by pH-7** [comment]
Finally, will you "Star" the repo? :)

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by Romesar** [comment]
Oh, yeah, bro! Of course! Thank you!

________________________________
