### ISSUE TITLE
No Option to Disable Photo Watermarks

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#479]
The photo watermark is a really unnecessary feature and we can't even disable it. Could you please make it optional to use watermark feature in new versions of PH7CMS?

**Comment by polynamaude** [comment]
You don't think that your user would like to be protected from getting their picture harvested on your website ?

**Comment by kevinbkk** [comment]
No. You should take a look at Facebook, Tagged, DateinAsia and many other social media and dating websites. Think like pros. This is not a school project.

**Comment by polynamaude** [comment]
FYI - Facebook does tag picture using EXIF. You just don't see it ;-)

Also, I don't think no one would invest as many hours in a "school project" and as you say, if you consider this a "school project" then maybe you should contribute too as a team work instead on taking only the benefit of others work.

**Comment by kevinbkk** [comment]
and what is your contribution here? Killing questions?

**Comment by pH-7** [comment]
Hey @kevinbkk 

Good question! This feature should be added soon :)
Don't forget to become a patreon, today :) https://www.patreon.com/bePatron?u=3534366

**Comment by kevinbkk** [comment]
Thanks mate for fixing it. About your business plan I would suggest you to build mobile app based on your script and I'll be the first one to purchase it. You can easily sell the mobile app for $79. But keep the desktop version free. It's the best business plan I can think about your script.

**Comment by polynamaude** [comment]
There's already a Android version.
https://github.com/pH7Software/Social-Dating-Android-App

**Comment by pH-7** [comment]
@kevinbkk I understand! If you want to help me having more time developing a React mobile app or so, that would be very grateful from you to become a Patreon from today. The sooner, the sooner it will be delivered.

**Comment by pH-7** [comment]
@polynamaude I think Kevin doesn't want a webview app, but a real one...
