### ISSUE TITLE
ads banner Issues 

### ISSUE THREAD

**Issue by hykelauncher** [pH7Software/pH7-Social-Dating-CMS#482]
Pls how use image as my banner instead of (728x80)

**Comment by polynamaude** [comment]
You have to edit the template files.

**Comment by hykelauncher** [comment]
Pls I tried everything possible but I haven't succeeded in it

**Comment by polynamaude** [comment]
Please what ?
The templates are either in the base for the common files or in the respective folders.
_**/templates/themes/base/tpl**_

**Comment by pH-7** [comment]
Concerning the ads, just go to the Banner module through the admin panel 
**Admin -> Setting -> Ad Banners** and edit them there. You can create nice images with you favotite image editor software and the wanted size available for pH7CMS, then, upload the images somewhere and add the img url there.
