### ISSUE TITLE
Payment module problem

### ISSUE THREAD

**Issue by walnad** [pH7Software/pH7-Social-Dating-CMS#483]
when member buys one of my memberships, it won't update his membership status.After payment is made i get an error "token expired" any idea?
Thanks for any help

**Comment by pH-7** [comment]
What payment gateway did you use? Is the sandbox enabled.

Are the API key of the payment gateway you enabled is correctly configured at Admin -> Mod -> Billing -> Gateways Configuration?

Can you provide a screenshot of the "token expired" page, so I can see better from where it is.

**Comment by walnad** [comment]
Hi,
I'm using built in PayPal with sandbox disabled. Where do I put the API? 

Thanks,
Walter
![FireShot Capture 055 - Configure Payment Gatewa_ - 1](https://user-images.githubusercontent.com/48806517/54860560-1d9db600-4cd9-11e9-8439-e18c74c30cec.png)

**Comment by pH-7** [comment]
pH7Builder (pH7CMS) doesn't use PayPal Express, but just "PayPal Standard", so it's just your PayPal email address. That's all.

**Comment by pH-7** [comment]
Concerning the screenshot, like I said, could you provide a screenshot of the "token expired" page, so I can see better from where it is. Thanks for the details! :)

**Comment by walnad** [comment]
I'm using only my email address for Paypal.This is the msg I get after payment is made to upgrade my membership.BTW, membership never gets updated even after payment.Its always "Free" see attached
![FireShot Capture 056 - Provider Not Foun_ - https___polishdatingsite com_payment_main_process_paypal](https://user-images.githubusercontent.com/48806517/54879829-e7f0ee00-4dfa-11e9-9d19-242bba137613.png)
 screen shot

**Comment by pH-7** [comment]
This issue has been fixed in [pH7Builder, v15.0.0](https://github.com/pH7Software/pH7-Social-Dating-CMS/releases/tag/15.0.0)

Related ticket https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/507#issuecomment-482691122
