### ISSUE TITLE
he requested URL /admin123 was not found on this server.

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#484]
Good Day

I did go through posts before logging this issue. Hope you can help me out here.

For testing I did everything on my localhost (Xampp) and it worked fine. Then I decided to install the script on my hosting provider. The install process went without any problems, but after the installation I am unable to go to the admin123 backend.

I did run your script to check the Mod Rewrite and it told me " Well done mate! Rewrite Mod works well ;-)"
I also went through the process to rename the folder to BACKEND and edited the constants.php file just to see if that will help but the problem is still there.

Please let me know if you require more info / testing on my side and I will be happy to do so

Regards

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
https://ph7cms.com/doc/
https://ph7cms.com/doc/en/requirements

**Comment by pH-7** [comment]
Hi @Nigrini 

If the URLs return 404 error, it's likely that your mod_rewrite configurations aren't setup well. https://ph7cms.com/doc/en/how-to-install-rewrite-module

Please also make sure that the .htaccess has been correctly been uploaded to the root directory.


Other solution could be to use WampServer instead of XAMPP (or directly use a web hosting provider) -> https://ph7cms.com/doc/en/hosting

**Comment by pH-7** [comment]
Other post that might help you too https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/255#issuecomment-410202843

**Comment by pH-7** [comment]
Is this still relevant @Nigrini? Please let use know :)

**Comment by Nigrini** [comment]
Thank you very much - the htaccess file was missing. Once I uploaded it, everything seems to be working so far.

Regards

**Comment by pH-7** [comment]
Nice! Happy to hear that @Nigrini!
If you appreciate the software and my work, don't forget to review it on https://sourceforge.net/projects/ph7socialdating/ (it just takes one minute to create an account and leave a review).
This really, really motivates me to continue my hard work on the software 😄
