### ISSUE TITLE
fake proliles generator

### ISSUE THREAD

**Issue by alealo92** [pH7Software/pH7-Social-Dating-CMS#485]
hi, sorry my english but im italian. Its possible generator fake profiles for Italian?

**Comment by pH-7** [comment]
Hi @alealo92 

Hope everything is OK for you in Italy 😊

Unfortunately, at the moment RandomUser API doesn't offer Italian users (you have Spanish though...).
More info: https://randomuser.me/documentation#nationalities

However, in pH7Builder, v15, you will have another tool called "Profile Generator", accessible through Admin Panel -> User/Admin -> Users -> Generate Bulk Members where you will be able to generate Spanish users (however, unlike the other tool, this one won't generate profile photos).

**Comment by pH-7** [comment]
By the way @alealo92, could you Star this GitHub repository? I appreciate it 😊

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
