### ISSUE TITLE
"pH7Builder 15.0.0 Beta 3" Bugs Detected

### ISSUE THREAD

**Issue by kevinbkk** [pH7Software/pH7-Social-Dating-CMS#487]
Hi, I installed "pH7Builder 15.0.0 Beta 3":
**Bug1:** Still no option for disable watermarks, **PLUS the old settings for text and size of watermarks gone!**

**Bug2:** Number of unread mails remains same after deleting the unread message.

**Comment by polynamaude** [comment]
Thanks for reporting....
As you can note, a "beta" release may still have some problem.

**Comment by pH-7** [comment]
Thank you very much @kevinbkk for testing the beta versions. Like I said on the releases descriptions, I publish BETA versions for testers to let me know any potential problems.

Please note that there would not be an option to disable the watermark. As it says on the Setting form, you will have to leave that field blank.

The "Watermark Text" and "Watermark Field" fields would be hidden if the "Picture" module is disabled. Please check this in Admin -> Mod -> Enable/Disable Modules

**Comment by kevinbkk** [comment]
OK then just the bug2 is still there. I would suggest you to fully remove the trash box.

**Comment by polynamaude** [comment]
@kevinbkk Have you tried emptying the trash ? Most E-Mail manager (K-9 Mail on Android, Thunderbird, etc) will still count the unread in the trash box in the "global" unread count.

**Comment by kevinbkk** [comment]
If the goal is to have a UI which is easy for users then you have to fix this. Also dating websites never use trash box, instead they have only 3 boxes.

unread
inbox
sent box

For example one of the best websites I ever seen is Thaifriendly. They have one of the best UI I ever seen.  You can get a lot of ideas from them. Back in 2010 they just needed 6 months to be number 1 dating website in Thailand. They are still far bigger than other competitors.
