### ISSUE TITLE
IIS8 Install - Unable to render website

### ISSUE THREAD

**Issue by mrowe819** [pH7Software/pH7-Social-Dating-CMS#488]
http://2.ecitrix.com

I have tried numerous install attempts on our server (which runs many php applications fine) however this one has me stumped. Install steps work fine, however the final site doesnt render the css & js. I installed this using;

composer create-project ph7software/ph7cms --prefer-dist ph7cms

I have tried numerous URL rewrite rules based on the provided htaccess file. Ive also tried to disable gzip as files served via gzip seem to be the issue. When I apply the rewrite rules from the htaccess file I get a 404.3 error to do with not a valid MIME type, currenly the site served on the link above is fresh off a vanilla install and no rewrite rules anywhere.

Server details;
Windows Server 2012R running on AWS EC2 instance
PHP v7.2.7
MySql v 5.7.17

Any help would be greatly appreciated!

**Comment by polynamaude** [comment]
https://ph7cms.com/doc/en/requirements
Sorry but Windows IIS server is not supported as is. (ie You're on your own).

**Comment by mrowe819** [comment]
On the project page it says that it is?

**Comment by mrowe819** [comment]
also - in your link it sas that windows and IIS is supported :)

**Comment by polynamaude** [comment]
You might have to change some pieces of code and change the URL rewriting to make it work.
Should work, means we haven't tested it. We don't have such infrastructure installed.

**Comment by mrowe819** [comment]
what code items are being reffered to here though? you must have something in mind for this? Rewrite rules I can do, but if there is a specific piece of code or config elsewhere in the app that needs updating that you think would be the cause then I would appreciate  some input

**Comment by polynamaude** [comment]
I don't know about IIS. You can look around in the closed issue because we had some similar problem with Apache that we're solved by editing the htaccess file.

Else, maybe PH-& have better knowledge than I do but as far as I know, he's on a Mac
