### ISSUE TITLE
logo link

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#490]
1. Once login as profile and click on logo link on left it land in middle of the page when it must show the top part. how can i do it.
2. When search we have city field but it does not show the list same as country. it very difficult for user to know exact spelling of city name , how can i show all cities under that country?

**Comment by pH-7** [comment]
> 1. Once login as profile and click on logo link on left it land in middle of the page when it must show the top part. how can i do it.

Could you be more specific here? Not really sure what you mean here...? Or maybe if you could provide a screenshot, that would be awesome!

**Comment by pH-7** [comment]
@samit78 Let me know if this is still relevant. If so, could you be more specific here? Not really sure what you mean here...? Or maybe if you could provide a screenshot, that would be awesome!

**Comment by samit78** [comment]
here is the screen shot
Regards,
 
Samit Dhekane
Managing Director
Siddhartha Software Solutions Co.,Ltd
TRAVELERS FREE Magazine The Map Hua Hin | Cha Am | Pranburi | Kanchanaburi | Bangkok  
www.sidhusoftwares.net
+66 89 209 7664
 

    On Wednesday, April 3, 2019, 11:49:56 AM GMT+7, ♚ PH⑦ de Soria™♛ <notifications@github.com> wrote:  
 
 
@samit78 Let me know if this is still relevant. If so, could you be more specific here? Not really sure what you mean here...? Or maybe if you could provide a screenshot, that would be awesome!

**Comment by polynamaude** [comment]
There\s not screenshot here !

**Comment by samit78** [comment]
Regards,
 

 

    On Friday, April 5, 2019, 1:32:17 PM GMT+7, Polyna-Maude R.-Summerside <notifications@github.com> wrote:  
 
 
There\s not screenshot here !
