### ISSUE TITLE
i have update theversion fron 12.9.8   to  14.9.0

### ISSUE THREAD

**Issue by tendoryu** [pH7Software/pH7-Social-Dating-CMS#491]
but the site is stil in Site Maintenance
www.2date.be

i have change the 
After installation, please edit ~/home/tend21/domains/2date.be/public_html/_protected/app/configs/config.ini file and find the code:
"environment = development ; production or development"
and replace it with the code:
"environment = production ; production or development"

but stil nothing

can you help me

**Comment by pH-7** [comment]
Hi @tendoryu 

Probably an issue occurred during the Upgrade wizard and your website wasn't set to "Online" status after it.

Can you please go to your admin panel, log in into it, go to Setting -> General and change "Site Status" to "Online".

Hope it helps :)
