### ISSUE TITLE
A LOT of questions from a newbie

### ISSUE THREAD

**Issue by UnitedThreeways** [pH7Software/pH7-Social-Dating-CMS#492]
Hello, 
I'm hoping that experienced ph7cms user are be able to help me with those. I'm writing in bulletpoints to make reading easier:)

- Can I set up a bot that will occasionally send users opening messages and the user would need to purchase premium subscription to see them?
- Can I use outsourced payment gates, such as RocketGate?
- Can I create my own landing pages/heavily modify the existing home page?
- Is it possible to use geolocation on the landing page? For example, on the landing page there would be a carousel with womens' photos and names and location of them would change depending on the location of a user.
- can I autopopulate site with pre-made profiles? Call them Love Stars, as it is on other dating/hookup sites

Thank you veery much for your answers:)

**Comment by polynamaude** [comment]
Why don't you start by reading the docs instead of asking already answered questions ?
Maybe then will you don't get a RTFM

http://ph7cms.com/doc/
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki

**Comment by polynamaude** [comment]
And the most important of all...
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

If you like the software than could you create a Sourceforge and write a review please.

**Comment by kevinbkk** [comment]
Did you read the documentation? There it says your users can actually use browse feautures but they can still play games online. My favorite one is: Angry Birds.

Finally if you loved this script please give a 5 star.

**Comment by pH-7** [comment]
Great list @UnitedThreeways!

This isn't possible by default. Those requirements are quite specifics...

To have those custom features you metioned, you will have either to find a great software developer to develop them for you into your pH7CMS's website. You can find great PHP developers on Toptal or Upwork (mention on your job description that is to develop some modules/features for pH7CMS. Mentioning this will make your task easier).

Other solution could be to wait and become a good Patreon or support the project, so if it reaches 1 month or so of salary, I could take some weeks/month off and create and build those features into the software for you.

Finally, if you don't have much money..., you could even create a good Kikstarter compaign saying you are making a revolutioning online dating service and you need to levreage $$$$ for several special customization based on pH7CMS engine.


Hope this helps! :) 

All the best! I like all your ideas! This is already a great start :) You look really motivated, and that's the right mindset. 


Good luck!
Pierre
