### ISSUE TITLE
issue with porn popups

### ISSUE THREAD

**Issue by webbyhull** [pH7Software/pH7-Social-Dating-CMS#493]
hello, i need some help, i have installed ph7cms and love it however everything works fine on the normal site via chrome, however when accessing the mobile version i keep getting redirects to porn sites - i havent installed any mods or extras just a straight version from softaculas  - could you offer any help?

**Comment by webbyhull** [comment]
hiya, yes you are right, i have edited that and now working as expected
many thanks :)

**Comment by pH-7** [comment]
Thanks @polynamaude!

Great to hear that @webbyhull 
<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">

**Comment by pH-7** [comment]
BTW @webbyhull, don't forget to Star this GitHub repo
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Thanks!
