### ISSUE TITLE
After installing the script the changes i make in admin panel are not saved. 

### ISSUE THREAD

**Issue by clochenberg** [pH7Software/pH7-Social-Dating-CMS#494]
I did a new installation. When setting up my site in admin panel, it does not save the changes. When i click save it just defaults back to where it was. I tried different browsers and cleared my cache

**Comment by polynamaude** [comment]
I'd suggest you check this with your hosting provider. Most people who had this problem got it solved by asking their hosting provider. I can't exactly tell you what did change because people are hungry to ask for help but aren't nice enough to give us the feedback once they get the problem solved.

**Comment by clochenberg** [comment]
Thank you for your reply. I called my hosting company and they resolved the issue, It is sad however that no one comes back and notify other people on how to resolve the issue.

So here goes:

1. Go to your C-Panel of your hosting
2. Look for the Security tab
3. Under Security click on MOD security
4. Disable MOD security

Problem resolved
![image](https://user-images.githubusercontent.com/20343464/55480500-beb53680-5620-11e9-84ff-94674a7a742a.png)

**Comment by polynamaude** [comment]
Hi,
If you look into the docs of pH7CMS you would see that we clearly say that ModSecurity can cause many issue with pH7CMS.
   

**Recommended:**

    _JRE (Java Runtime Environment) - 1.6 or higher (used for compressing static files. The option is disabled by default and uses our homemade compressor instead. However, if you have Java installed on your server, it would be nicer to enable that option).
    Apache mod_security/mod_security2 disabled - pH7CMS may not work correctly if enabled, so it's advisable to disable it for your domain (just ask your Web host or do it through cPanel)._

If you like pH7CMS could you give us a star on gitHub and write a nice review on sourceforge ?
<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/55482151-e80a9e00-55f1-11e9-8502-24e57f1d21b0.png">

If you problem is solved, you can close the issue.
