### ISSUE TITLE
Static pages and menus

### ISSUE THREAD

**Issue by webbyhull** [pH7Software/pH7-Social-Dating-CMS#497]
Hi, sorry if that has been covered, but I want to create static pages and have menu items linking, is this something I can easily do?

**Comment by polynamaude** [comment]
@webbyhull You need to edit the source code, I'd suggest you create a module and add a link into the template.

https://ph7cms.com/doc/en/create-your-module

**Comment by pH-7** [comment]
Hey @webbyhull!

You will have to edit the [top_menu.inc.tpl](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/top_menu.inc.tpl) file (from "base" theme) and add manually some new links in there.
