### ISSUE TITLE
can't login or set recaptcha via chrome

### ISSUE THREAD

**Issue by juicelink** [pH7Software/pH7-Social-Dating-CMS#498]
I made a fresh install, can login as admin or create an account via edge but not with chrome.
While edge redirect to main/index after posting admin login form, chrome redirect (301) to the same login page. No error in chrome console and server logs. Cleared chrome caches and tryied in private window with no success.
Same behavior with account creation process, working in edge but not in chrome. 
While trying to reset password, I've noticed that it was impossible to have a valid code in the recaptcha field when I use chrome  (get a 200 response but with a 0 status). work well in edge.

the app run on ubuntu 18.04 with:
apache2 2.4.29
php 7.2
mariadb 10.1

 security mod isn't installed

Can't figure out what can make it working well in edge and not in chrome...

**Comment by juicelink** [comment]
after debugging it seems that there is no session whem the client is chrome.
After comparing cookies in edge and chrome, I can notice that session cookies haven't the same name:
in edge: PH7SESS
in chrome: PHPSESSID

**Comment by juicelink** [comment]
was requesting website by ip address.
Seems that chrome doesn't set cookies if domain's cookie is an ip address.
Everithing is working by requesting a domain name instead of ip address. I had to delete cache in _protected/data

**Comment by pH-7** [comment]
> Seems that chrome doesn't set cookies if domain's cookie is an ip address.

Maybe Chrome does that for security reason or was set in your Chrome settings.

**Comment by pH-7** [comment]
Really happy for you it works now :tada: And thank you for posting your solution! This might help others in the same case as you :)

**Comment by pH-7** [comment]
BTW @juicelink, do you mind to Star this GitHub repo?
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Thanks! 🥇
