### ISSUE TITLE
in search city field need ajax

### ISSUE THREAD

**Issue by samit78** [pH7Software/pH7-Social-Dating-CMS#499]
in search we have city field

i need it must show all  cities in that country selected as AJAX
as well as if city is not selected it must show all members in that country

how can i do that

**Comment by polynamaude** [comment]
What do you mean ?
You need to code it in PHP.
If you want we can tell you where to look for but we won't be writing code for you.
You can hire a developer.
You can contribute https://www.patreon.com/bePatron?u=3534366 and maybe you'll get a chance to get your feature added.
If you like the software, it would be appreciated that you give us a star on gitHub and make a nice review on Sourceforge.

<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/55607722-e7d1e600-574a-11e9-8233-e5e33c1ea622.png">

**Comment by pH-7** [comment]
Hey @samit78 

I would suggest to find someone good at Toptal, Upwork or similar service or dev friend to make this happening. 
I totally understand that it can be frustrating for you, however, you have to know that everything here I do is for free, during my free time and I really can't make any custom feature/suggestion requests from users happening. This is totally impossible for me. 

All the best with your social dating website!! :tada:
