### ISSUE TITLE
Email settings

### ISSUE THREAD

**Issue by webbyhull** [pH7Software/pH7-Social-Dating-CMS#500]
Hi, I am struggling to find where I can edit the settings for my email settings. The install is via a cpanel install but it's not sending out emails. Checked the help file and it said to check the ini file but I have failed to find its location and the ones I have found don't contain any smpt email settings any help would be great :)

**Comment by polynamaude** [comment]
Why don't you start by reading the documentation. It will prevent from asking question that we already took time to answer.

http://ph7cms.com/doc/
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

The configurations are either in the config.ini file ( _protected/app/system/config/config.ini ) or stored in the database and edited through the administrative interface.

**Comment by webbyhull** [comment]
Many thanks for your reply,

I did read the document and under the section for why it can't send emails
it just says to check the php.ini file, but it didn't say where that would
be located hence my question.

I did search for the file but no email settings are in the file so will
check the database

It maybe worth updating the email section of the help file as it says
php.ini and not config.ini

I appreciate you taking the time to reply

**Comment by polynamaude** [comment]
@webbyhull First of all maybe you should learn some basics about PHP before trying to run an online service.

The **php.ini** file and the **config.ini** file are two different thing. The first one (**php.ini**) is file used by the PHP interpreter and that will be common to every application. The **config.ini** file is used only by pH7CMS.

As we say :
_**This means there is an incorrect configuration on your host side and/or with the "php.ini" file."**_

We cannot enumerate all the possibilities relating to email sending problem, may it be a missing module in your PHP, an incorrect configuration option in pH7CMS, a network problem with your firewall and/or SMTP server refusing the connection.

Solving problem is never a straight line of "do this, do that, then do this".
If you look at one of the link I've sent you (before complaining that we shall update our help) then you'll get some hint about what do to if you want to get something useful as help. And this start by giving enough information so we can have some idea about where may the problem reside.

For now we can't do more.

**Comment by polynamaude** [comment]
@webbyhull You can also use SendGrid SMTP services : https://sendgrid.com/
You'll get a guaranteed working SMTP server that doesn't filter based on your originating IP.

**Comment by pH-7** [comment]
Is this still relevant @webbyhull?

**Comment by palmdoc** [comment]
In my case it only partially works and I am also trying to figure out any setting to tweak but 

This contact form works
https://mysite/contact

but when I try another mail method to a user on the site eg
https:/mysite/mail/compose/userid
 this does not work

forgot password function also cannot send mail
https://mysite/forgot/user

Appreciate more guidance. 
Sorry I read the docs but equally lost.

**Comment by palmdoc** [comment]
> @webbyhull You can also use SendGrid SMTP services : https://sendgrid.com/
> You'll get a guaranteed working SMTP server that doesn't filter based on your originating IP.
> 
> Or use MailGun
> https://www.mailgun.com/

oHOw does one set the sendgrid SMTP in ph7CMS? I can't find a link to the instructions in the wiki

**Comment by polynamaude** [comment]
@palmdoc You'll get the good answer if you ask at the right place. This is not the SendGrid support group, this is pH7CMS. A SMTP is simply an SMTP server, so you replace the information you'd set for your own server by the one used by SendGrid / MailGun or whatever service you use (your own, your providers, etc).

https://sendgrid.com/solutions/smtp-service/

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Also, by using others already opened issue for problem unrelated or that you think related but may not be is just causing a mess around here ! Something like getting into other peoples conversation.

Open a issue clearly indicating your problem. Go read the wiki pertaining to how to ask for help. And people should get back to you.

Or maybe I could write twenty two different list of "to do" and "try this", possibly only one will be good but why not waste some time here ! When you go to the doctor, he does lab work ? Blood test ? Same goes for the computer world. So maybe if you'd take the time to look into your logs (it would show us that you have the basic knowledge of operating an online service and some debugging aptitudes).

**Comment by kevinbkk** [comment]
I had the same issue, but after downgrading to PHP 5.6 all emails start working. However I'm talking about version 14.9. I didn't update to 15 yet.

**Comment by polynamaude** [comment]
@kevinbkk It's not only about gettings it working but to find out why.
You should try to compare your logs between PHP 5.6 and PHP 7.1  when sending emails. The version 5.6 of PHP is going out of support soon.

**Comment by palmdoc** [comment]
> @palmdoc You'll get the good answer if you ask at the right place. This is not the SendGrid support group, this is pH7CMS. A SMTP is simply an SMTP server, so you replace the information you'd set for your own server by the one used by SendGrid / MailGun or whatever service you use (your own, your providers, etc).
> 
> https://sendgrid.com/solutions/smtp-service/
> 
> https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
> 
> Also, by using others already opened issue for problem unrelated or that you think related but may not be is just causing a mess around here ! Something like getting into other peoples conversation.
> 
> Open a issue clearly indicating your problem. Go read the wiki pertaining to how to ask for help. And people should get back to you.
> 
> Or maybe I could write twenty two different list of "to do" and "try this", possibly only one will be good but why not waste some time here ! When you go to the doctor, he does lab work ? Blood test ? Same goes for the computer world. So maybe if you'd take the time to look into your logs (it would show us that you have the basic knowledge of operating an online service and some debugging aptitudes).

I'm not asking about how to use Sendgrid, simply asking where on earth if there are at all the SMTP settings for mail within ph7CMS.
I see code for Swftmailer within the protected files but I am not a PHP programmer. I am a mere mortal user asking for help. 
Is it possible at all to tweak within the ph7CMS application how it sends out mail? i.e. use a hosting smtp service with login/password? 
Or are we doomed to just use php mail?
