### ISSUE TITLE
Edit user profile page

### ISSUE THREAD

**Issue by spike99** [pH7Software/pH7-Social-Dating-CMS#501]
Where I find the user page?
site.com/@peter22#p=general
I want to edit this page, I mean its look

Please help me!

**Comment by pH-7** [comment]
Once that user is logged in, it has the option to edit its profile Settings -> Edit Profile
 
Another option as an admin, is to go to your admin panel -> User/Admin -> Users -> Browse -> edit.

Hope it helps. Enjoy!

**Comment by spike99** [comment]
I want to edit the html page. I do not find that .tpl

**Comment by polynamaude** [comment]
@spike99 You have to look inside the modules. Not all of the files are in the template, they follow the MVC pattern rules and will override by the template if one's available.

For example
**__protected/app/system/modules/user-dashboard/views/base/tpl/main/index.tpl_**

**Comment by polynamaude** [comment]
@spike99 If you like the software then would you please make a nice review on Sourceforge ?

<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/55679620-af621180-58dc-11e9-8035-0600ab39cf55.png">

**Comment by spike99** [comment]
Thanks for the help!

**Comment by polynamaude** [comment]
@spike99 Thanks for the review ;-)
