### ISSUE TITLE
Button add friend does not disappear

### ISSUE THREAD

**Issue by spike99** [pH7Software/pH7-Social-Dating-CMS#503]
When a user sends a friend request, the button is still there.

```
{if $is_friend_enabled AND $is_logged AND !$is_own_profile}
<button href="{befriend_link}" type="button" class="btn btn-success btn-sm">{lang 'Add Friend'}</button>
{/if}	
```
I need a variable, which when the request for friendship was sent, the button will not be there anymore

**Comment by pH-7** [comment]
Thanks for mentioning it @spike99 :tada:

I've fixed it. Patch: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/a9023557bbb4860538e2d3bd4c50b74fd499b09f

**Comment by spike99** [comment]
If user X send friend request to user Y, and user Y does not respond to the request of friendship and enter to user X profile, he have "add friend" if user Y send a request. they will be friends 2 times in friends list

**Comment by spike99** [comment]
> Thanks for mentioning it @spike99 🎉
> 
> I've fixed it. Patch: [a902355](https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/a9023557bbb4860538e2d3bd4c50b74fd499b09f)

can it be repaired?

**Comment by pH-7** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/504#issuecomment-481679899
