### ISSUE TITLE
Is there a demo? 

### ISSUE THREAD

**Issue by samayo** [pH7Software/pH7-Social-Dating-CMS#505]
I can't find any live working demo. They are all images. Is there a demo somewhere to log in and see the features? 

Also, I have been watching this repo for years, glad it is still active. Planing to become patreon soon :)

**Comment by polynamaude** [comment]
@samayo No there is no demo available. You can always do a local installation to try it out. It's free !

**Comment by pH-7** [comment]
Hey @samayo 

Thanks very much for your nice message. Unfortunately, I had to shut down the demo, because some people were abusing of it, and it was difficult to maintain..  In brief, too much work for what it was...


Anyway, you could still have a look to the Softaculous demo at https://www.softaculous.com/softaculous/demos/pH7CMS However, they also got people abusing of it, so please use it reasonably (and admin dashboard isn't available for demo there).

**Comment by pH-7** [comment]
And yes, the best option is obviously to download the latest version and try it. If you web host has cPanel and Softaculous, you could also install it in one-click :tada:

**Comment by pH-7** [comment]
@samayo That would be AWESOME if you could be a Patreon :+1: 

And by the way, don't forget to Star the repo :) Thanks!

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
And by the way, don't forget to Star the repo @samayo  :) Thanks!

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
Hey again @samayo 
By the way, if you enjoy my software, do you mind to Star this GitHub as mentioned below on my screenshot?

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

Enjoy your day! 😎Thanks

**Comment by samayo** [comment]
Hey, yes. I read that the first time. I only star repos I like or i intend to use later, you can see I don't even like my repo enough to star them. Anyway, the demo link you gave me didn't work, it kept loading and loading until it got me tired. I will check it out some other day and likely will star it then

**Comment by polynamaude** [comment]
@samayo The softaculous infrastructure is not something under our control.
Like I already said, it's a 10 minutes (at most) job to do the installation.

Any website you operate will require work on customisation so there's not much use with a demo anyway.

Have fun
