### ISSUE TITLE
Bug domain link

### ISSUE THREAD

**Issue by spike99** [pH7Software/pH7-Social-Dating-CMS#509]
![Capture](https://user-images.githubusercontent.com/41783544/55952884-52ab8180-5c63-11e9-81ca-daf768ad290e.JPG)

Some photos do not appear
In inspect element is https://nextq.xyz/ this is not mine
 
`<img src="https://nextq.xyz/data/system/modules/user/avatar/img/ticklishlion287/3-64.jpg" alt="Ticklishlion287" class="avatar">
`
why did that domain appear there?

**Comment by pH-7** [comment]
Hi @spike99 
Did you transfer your website from one to another domain before?

Can you please try to clear the "Database and Other Data" cache https://ph7cms.com/doc/en/how-to-clear-caches

**Comment by spike99** [comment]
I not changed domain.
that domain was my server's ns but it was not assigned to the server

**Comment by pH-7** [comment]
Did it work by clearing the cache?

**Comment by spike99** [comment]
yes

**Comment by spike99** [comment]
but I don't want to repeat this

**Comment by polynamaude** [comment]
What's the problem ? You made some changes that needed the cache to be cleared, your problem is soleved. What do you want more?
