### ISSUE TITLE
Country not available in currency

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#510]
How do I add the South Africa Rand (R) as a currency

**Comment by polynamaude** [comment]
@Nigrini Could you please give me more precision ? Are you talking about PayPal ?

**Comment by Nigrini** [comment]
Yes - In Currency Code South Africa is not available

**Comment by polynamaude** [comment]
@Nigrini Have you made sure you can have this currency available in PayPal ?

**Comment by polynamaude** [comment]
@Nigrini I see that there's a configurable option in the "General settings" in the Admin interface. You can access it on the "edit membership" form.

**Comment by Nigrini** [comment]
Yes - Paypal is available in South Africa

So when I go to Mod - Billing - Gateway Configuration There is no option to pick South Africa from the Currency Code dropdown list

**Comment by polynamaude** [comment]
@Nigrini Then you can edit the following file
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Layout/Form/Engine/PFBC/Element/Currency.php

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/1f09ea64015aa1bab748aa715cfba3b3091d95df/_protected/framework/Layout/Form/Engine/PFBC/Element/Currency.php#L15

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/1f09ea64015aa1bab748aa715cfba3b3091d95df/_protected/framework/Layout/Form/Engine/PFBC/Element/Currency.php#L41

You can search through the source code by doing the following command from the folder
**_fgrep -r -i 'currency' . | less_**

**Comment by polynamaude** [comment]
If you like the software then a review on Sourceforge and a nice Star on gitHub would be appreciated.

We all work on this volunteer and we aren't many to do so !

**Comment by Nigrini** [comment]
Thank you - Will try the edit part, and let you know if I require more assistance.

I always give you guys a Star - You are Great ! !

**Comment by polynamaude** [comment]
@Nigrini Thank's, it's always a nice reward to have our works appreciated. I don't do much coding, at least for this software. It's PH that did nearly everything but I do give some support when I can.

**Comment by graceryfolad** [comment]
i love the functions of this script and like use it for my personal
project, how can i edit the look and feel and give it a nice frontend.
Thanks
Folarin Daniel
*07062746793, **08124488435*
Software Developer (PHP, SQL, C#, Laravel, Codeigniter, Vue JS)

**Comment by polynamaude** [comment]
@graceryfolad What's the link between what you just wrote and the subject of this issue ??

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
http://ph7cms.com/doc/

If we all start writing unrelated information everywhere and we don't take a minute to do basic research before asking out question then we'll be taking time for useless purpouse.

If I look at the signature you wrote (PHP, SQL, C#, Laravel, CodeIgniter, Vue.JS) then I'm surprised you haven't noticed a folder named template.

**Comment by pH-7** [comment]
Thanks @polynamaude

**Comment by pH-7** [comment]
Thanks @polynamaude! That's right!

**Comment by pH-7** [comment]
@Nigrini 

Indeed, please add `ZAR` in `CURRENCY_CODES` array https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/1f09ea64015aa1bab748aa715cfba3b3091d95df/_protected/framework/Layout/Form/Engine/PFBC/Element/Currency.php#L15 

Then, add `ZAR => 'South Africa Rand',` in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/1f09ea64015aa1bab748aa715cfba3b3091d95df/_protected/app/langs/en_US/language.php#L315
