### ISSUE TITLE
Database not correct working

### ISSUE THREAD

**Issue by githubsteef** [pH7Software/pH7-Social-Dating-CMS#513]
After upgrade to version 15 with softalicious, it's not possible to retrieve the old database.
I put in the right number and prefix, several time in the passed six hours, but no members, no logo etc like een new install. But fixing the database entries in the installations instructions, did not help

**Comment by TGHepburn** [comment]
Hello;
New here, so I can only add that when I used Softalicious to install NEW install it worked well.  I did note that Softalicious said it was installing 14.7 (I think) and was surprised to see it had installed v15 (admin menu tool > info > software)
