### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by Wetalya** [pH7Software/pH7-Social-Dating-CMS#515]
`docker-compose up`
error:

> Creating network "ph7-social-dating-cms_default" with the default driver
> Creating ph7-social-dating-cms_db_1 ...
> Creating ph7-social-dating-cms_php_1 ... error
> Creating ph7-social-dating-cms_db_1  ... done
> ERROR: for ph7-social-dating-cms_php_1  Cannot create container for service php: b'invalid mode: /var/www/'
> 
> ERROR: for php  Cannot create container for service php: b'invalid mode: /var/www/'
> ERROR: Encountered errors while bringing up the project.

hosting: digitalocean
Ubuntu 16.04.6 x64 
![image](https://user-images.githubusercontent.com/20833318/56214112-ed420100-6065-11e9-85f8-5f9e97453d3c.png)

**Comment by pH-7** [comment]
Hum... interesting... Indeed, the Docker implementation is not a stable one. Do you mind to try with these changes done here https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/472

**Comment by yarekc** [comment]
Same BUG here on a brand new Debian distribution: 

```
Starting ph7_db_1
Creating ph7_php_1

ERROR: for php  Cannot create container for service php: invalid mode: /var/www/
ERROR: Encountered errors while bringing up the project.
```
