### ISSUE TITLE
After clean version 15

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#517]
I deleted the 14.9 version and installed version 15 on a clean system with a clean database today 17/04/2019

1.	General settings -> Registration -> Default Membership Group is set to Regular(Free)
2.	Mod -> Billing -> Membership List is Enabled and I edited the profile to be able to browse    the website without being able to do mush

![3400504d-42cf-495b-a458-e814af20f9e6](https://user-images.githubusercontent.com/43742116/56249092-ca860b80-60aa-11e9-9e9d-d7796956630a.jpg)
![a1](https://user-images.githubusercontent.com/43742116/56249177-146ef180-60ab-11e9-8d86-5e88482e41ea.PNG)
![a2](https://user-images.githubusercontent.com/43742116/56249201-2d77a280-60ab-11e9-8ed2-9f33a9e7b6d0.PNG)
![a3](https://user-images.githubusercontent.com/43742116/56249268-70397a80-60ab-11e9-9b35-5a1a330778b6.PNG)
My problem is when I sign up as a new user, went through the email verification and then login with the newly created user, the system takes me to a page telling me that I need to upgrade my subscription.
I want the newly registered users to be able to scout out the site first at least before being forced to upgrade.
The only way I can get back to the login page is to clear by browsers cache

**Comment by Nigrini** [comment]
Deleted everything / redo everything and now it is working :)

**Comment by pH-7** [comment]
Awesome @Nigrini 🥇You rocks!
Really happy for you!! Enjoy your website then! 🌴
