### ISSUE TITLE
Add a donation button?

### ISSUE THREAD

**Issue by Aiaboseacabo** [pH7Software/pH7-Social-Dating-CMS#519]
Hi guys, since I plan to make the site completely free and no-profit, I need to implement a donation button somewhere, in the home or in a section, how can i do? It is possibile, for example to add a section in the top row and how? Thanks

**Comment by pH-7** [comment]
The the layout.tpl file probably :) If you are not comfortable with coding, the best would be to hire a dev on Upwork or Toptal. Both are good for what you need and it wouldn't cost more than $100 for what you need to do. 
By the way, do you mind to become a Patreon https://patreon.com/bePatron?u=3534366 today and support the further updates and features of the software you love?

**Comment by pH-7** [comment]
Hi again @Aiaboseacabo 

Let me know if you found my answer was helpful for you..? I'm sure you will find quite easily a great freelance who will be willing to implement a beautiful donation button on your social dating website.

If the question is solved for you, would you be kind to close it?

**Comment by Aiaboseacabo** [comment]
Thanks for the answer! Actually i can't use that money cause i'm a student
and my budget is very limited, maybe in the future.. that's a pity i don't
know how to implement the code in the files, i studied programming at the
high school but not javascript, if only i will find the time to learn...

Il giorno sab 4 mag 2019 alle ore 04:16 ♚ PH⑦ de Soria™♛ <
notifications@github.com> ha scritto:
