### ISSUE TITLE
ph7cms language

### ISSUE THREAD

**Issue by gatgat1991** [pH7Software/pH7-Social-Dating-CMS#524]
i have a question the language is working or not the front page cannot translate

**Comment by polynamaude** [comment]
@gatgat1991 The language work very good. But not all of the text are made into string that translate. If you want to have a truly multilingual site then you will have to use different template and translate them.

**Comment by polynamaude** [comment]
@gatgat1991 https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by gatgat1991** [comment]
okey thx for the info

**Comment by polynamaude** [comment]
@gatgat1991 Maybe if you'd make a little bit of effort in the way you write messages then people will be more interested in helping out. It ain't very much more time consuming to write "Thanks for the information" versus "thx for the info".
