### ISSUE TITLE
2checkout Gateway Config

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#525]
I have a 2checkout account. I can fill in the Vendor ID without any problem, but the Secret Word that I was given consist of alphanumerical characters and for some reason the field only accepts numerical characters.

My secret word that was given to me is 0L8GUb@yM|Be2H#uW3E]  when I copy and paste it into the field it only display 008e23E, and when I try to submit it, I get a popup saying please enter a number
![aaa](https://user-images.githubusercontent.com/43742116/56881855-100ae700-6a62-11e9-91bc-81f850bad7ba.PNG)

**Comment by Nigrini** [comment]
Putting the Secret word in " " did work but I am not sure the Vendor ID is correct because it still gives me the Up/Down arrows on the right hand side instead of the green tick mark.

NB - The vendor ID is **numerical only**

![cc](https://user-images.githubusercontent.com/43742116/56964107-c8b45180-6b5a-11e9-871f-6ca3d454e9d1.PNG)

**Comment by pH-7** [comment]
Thanks @Nigrini 

That field is automatically set as "number" HTML5 field, because it contains only digits. 
I know, it doesn't make sense to have  Up/Down arrows for vendor ID, but those form fields are dynamically generated, so it doesn't always fit very well for all of them :)
