### ISSUE TITLE
Changing or moving the _protected folder 

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#527]
My hosting company installed the software for me from Softaculous. I'm circling back and going through the install steps. Step #3 talks about renaming or moving the _protected folder. 

When I changed the _protected folder to _spring, the site does not load in the browser and returns a HTTP Error 550. Also, if i leave the folder name as _protected but moved it out of my public_html folder, again the site does not load in the browser and returns a HTTP Error 550. 

        a. What other folders or files do I need to change, when I change the "_protected" folder to "_spring" or simply move the _protected folder out of my public_html folder, so that my website works properly without error?

**Comment by polynamaude** [comment]
@CooperAshley2 Why don't you do a complete install from the distribution file ?
You'll need to move your **__protected_** folder AND set the new name in your configuration file.
This last step (set the new location of the **__protected_** folder is done by the installation wizard.
I'd suggest you to follow those step.

You have some link bellow for more information.
We are not related to Softaculous so we don't know how do they work.
You can also look inside the **__constant.php_** for the location of the _protected folder.

https://ph7cms.com/doc/en/install
https://ph7cms.com/doc/
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki

Doing a clean installation is the first part in building a website (and if you can't do it then maybe you should pair up with someone who has the knowledge). Installation is only the first part !

Good luck

**Comment by CooperAshley2** [comment]
Thank you for the quick response. Whether the files are uploaded via Softaculous or the distribution file my issue is the same regardless. It's been a headache following the install instructions and making changes to a file then having to search through thousands of webpages, forums and Qs & As to learn that you also have to edit additional files for your changes to work. The links to the install and doc, those are great reads for general information but both are useless when you have very specific problems and issues. Thank goodness for Github and you guys who offer your time to help us out. I do appreciate it tremendously. 

Now, I can make the changes to the config file, I just need to know what files to change and where it's   located.  Is this it: /_protected/app/configs/* ?

**Comment by pH-7** [comment]
Hi @CooperAshley2 

Great question! You will have to edit the `_constants.php` file located in the root folder of your website.
On line 50, change 
```php
define('PH7_PATH_PROTECTED', '/SERVER_PATH/_protected');
```
to your new path. 

Let me know, if this works

**Comment by CooperAshley2** [comment]
> @CooperAshley2 
> You'll need to move your **__protected_** folder AND set the new name in your configuration file.

What's the path to the config file, please?

**Comment by CooperAshley2** [comment]
> Hi @CooperAshley2
> 
> Great question! You will have to edit the `_constants.php` file located in the root folder of your website.
> On line 50, change
> 
> ```
> define('PH7_PATH_PROTECTED', '/YOUR_CURRENT_SERVER_PATH/_protected/');
> ```
> 
> to your new path.
> 
> Let me know, if this works

This did not work unfortunately. I changed the names (if folder is left in root) and paths (when i moved folder outside of the root) and site will not load. I had to leave the _protected folder in the root for now.

**Comment by pH-7** [comment]
> > Hi @CooperAshley2
> > Great question! You will have to edit the `_constants.php` file located in the root folder of your website.
> > On line 50, change
> > ```
> > define('PH7_PATH_PROTECTED', '/YOUR_CURRENT_SERVER_PATH/_protected/');
> > ```
> > 
> > 
> > to your new path.
> > Let me know, if this works
> 
> This did not work unfortunately. I changed the names (if folder is left in root) and paths (when i moved folder outside of the root) and site will not load. I had to leave the _protected folder in the root for now.

What PHP error did you get? Or in your log? 

If you specify the FULL path to your new protected folder (with trailing slash at the end, it should work)

**Comment by pH-7** [comment]
Please also make sure you don't have any UNIX permission problems with the new location of the `PROTECTED` folder. You might ask your web host company to check for you.

In my case, it works well (I tried to replicate your exact issue in order to help you better).

**Comment by pH-7** [comment]
Anyway, having `_protected` folder located in your root folder is totally fine too.
There are many other security precaution in there such as .htaccess `all denied` in that folder, so don't worry about it :)

**Comment by pH-7** [comment]
Finally @CooperAshley2, Would you be able to Star the GitHub repo? :)

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
