### ISSUE TITLE
Fake profile generator: Remove or disable user website and social network site profile questions

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#528]
In earlier versions of PH7 there used to be an option in the admin panel where you can select the profile questions you want the new user to complete when they join your site. I'm not finding where I can do that in the admin panel in v15, am I overlooking it?

I want to remove these 2 fields and your suggestion is: You can comment this highlighted L159 line in _protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.phpfile." 

        a. I don't understand "comment". Do yo mean to delete that line, or simply change the wording from "user website" to something else? 

            1. If i make any changes to this .php file, what other files will I need to change for the site to correspond and work properly?

        b. Can't I just delete the entire field?

        c. Can't i simply disable that field so it doesn't show in the profile questions? If i can simply disable it, I won't need to bother with editing the .php file.

**Comment by pH-7** [comment]
You right @CooperAshley2 

I will add the ability to remove them for the next release (v15.1) 😄

**Comment by pH-7** [comment]
BTW, don't forget to Star the GitHub repo :)

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
BTW @CooperAshley2, don't forget to Star the GitHub repo :)

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
I added the ability to remove more fields in order to give more flexibility to the software.
The changes will be shipped in the next release (pH7Builder v15.1.0).
