### ISSUE TITLE
Fake profile generator: Ooops, fake profiles are all gone

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#529]
So I generated about 50 profiles with pictures. Then i did a bulk generator of about 250 profiles, no pictures, etc. Once i realized the profiles had the "website" and "social media" questions, I went through and deleted ALL of the profiles I generated because i don't want those options to be included when new users are completing a profile. (not everybody has a website and not everyone even wants to reveal their social profile publicly, so why are they even in there anyways, and apparently those questions cannot be removed?? I'd love to know how others have dealt with this issue.)

When i tried to generate fake profiles again, i get this message:

" Internal Server Error
The server encountered an error. This is most often caused by a scripting problem, a failed database access attempt, or other similar reasons.

If you are the administrator of the site, please go to your admin panel -> Tools -> Environment Mode and set to "Development", then go back here to see the details of the error. "

Which I did, and the error is:

" Message: | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'middleName' in 'field list'
-- | --
File: | /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php
Line: | 752
Trace: | #0 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(752): PDOStatement->execute() #1 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(718): PH7\UserCoreModel->setInfoFields(Array) #2 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(52): PH7\UserCoreModel->add(Array) #3 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/AddFakeProfilesForm.php(21): PH7\AddFakeProfilesFormProcess->__construct() #4 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/admin123_15f5f0903451a8aa7294045e7e214a26/base/user/addfakeprofiles.cpl.php(19): PH7\AddFakeProfilesForm::display() #5 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #6 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('user/addfakepro...', '/home/cooperas/...') #7 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #8 /home/cooperas/public_html/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/cooperas/...') #9 /home/cooperas/public_html/_protected/app/system/modules/admin123/controllers/UserController.php(108): PH7\Framework\Mvc\Controller\Controller->output() #10 [internal function]: PH7\UserController->addFakeProfiles() #11 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(660): ReflectionMethod->invokeArgs(Object(PH7\UserController), Array) #12 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(618): PH7\Framework\Mvc\Router\FrontController->runController() #13 /home/cooperas/public_html/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #14 /home/cooperas/public_html/index.php(46): PH7\Bootstrap->run() #15 {main} "

Can you please tell me which folder or files (and the path to get to it) I should re-upload to get the profiles back in order to regenerate fake profiles with pictures?

Thank you.

**Comment by pH-7** [comment]
Hey @CooperAshley2 

THanks very much for your message.
Can you please try to update your `_protected/app/system/core/models/UserCoreModel.php` file to these changes below  
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/270a4c51ff1fcee6a9c271545792c377fc38249f

It should work again :)

**Comment by pH-7** [comment]
Oops, sorry. I meant this changes https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/a0d98bd91fb35473ceca87e19d661eeeba9cd427

**Comment by pH-7** [comment]
Hey @CooperAshley2 

THanks very much for your message.
Can you please try to update your `_protected/app/system/core/models/UserCoreModel.php` file to these changes below  
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/a0d98bd91fb35473ceca87e19d661eeeba9cd427

It should work again :)

**Comment by CooperAshley2** [comment]
Hello, thanks for responding. I replaced the lines in my file with those in your file and now it's showing this error:


Message: | SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
-- | --
File: | /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php
Line: | 754
Trace: | #0 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(754): PDOStatement->execute() #1 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(718): PH7\UserCoreModel->setInfoFields(Array) #2 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(52): PH7\UserCoreModel->add(Array) #3 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/AddFakeProfilesForm.php(21): PH7\AddFakeProfilesFormProcess->__construct() #4 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/admin123_15f5f0903451a8aa7294045e7e214a26/base/user/addfakeprofiles.cpl.php(19): PH7\AddFakeProfilesForm::display() #5 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #6 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('user/addfakepro...', '/home/cooperas/...') #7 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #8 /home/cooperas/public_html/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/cooperas/...') #9 /home/cooperas/public_html/_protected/app/system/modules/admin123/controllers/UserController.php(108): PH7\Framework\Mvc\Controller\Controller->output() #10 [internal function]: PH7\UserController->addFakeProfiles() #11 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(660): ReflectionMethod->invokeArgs(Object(PH7\UserController), Array) #12 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(618): PH7\Framework\Mvc\Router\FrontController->runController() #13 /home/cooperas/public_html/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #14 /home/cooperas/public_html/index.php(46): PH7\Bootstrap->run() #15 {main}

**Comment by pH-7** [comment]
> Hello, thanks for responding. I replaced the lines in my file with those in your file and now it's showing this error:
> 
> Message:	SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
> File:	/home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php
> Line:	754
> Trace:	#0 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(754): PDOStatement->execute() #1 /home/cooperas/public_html/_protected/app/system/core/models/UserCoreModel.php(718): PH7\UserCoreModel->setInfoFields(Array) #2 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(52): PH7\UserCoreModel->add(Array) #3 /home/cooperas/public_html/_protected/app/system/modules/admin123/forms/AddFakeProfilesForm.php(21): PH7\AddFakeProfilesFormProcess->__construct() #4 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/admin123_15f5f0903451a8aa7294045e7e214a26/base/user/addfakeprofiles.cpl.php(19): PH7\AddFakeProfilesForm::display() #5 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #6 /home/cooperas/public_html/_protected/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('user/addfakepro...', '/home/cooperas/...') #7 /home/cooperas/public_html/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/cooperas/...') #8 /home/cooperas/public_html/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/cooperas/...') #9 /home/cooperas/public_html/_protected/app/system/modules/admin123/controllers/UserController.php(108): PH7\Framework\Mvc\Controller\Controller->output() #10 [internal function]: PH7\UserController->addFakeProfiles() #11 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(660): ReflectionMethod->invokeArgs(Object(PH7\UserController), Array) #12 /home/cooperas/public_html/_protected/framework/Mvc/Router/FrontController.class.php(618): PH7\Framework\Mvc\Router\FrontController->runController() #13 /home/cooperas/public_html/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #14 /home/cooperas/public_html/index.php(46): PH7\Bootstrap->run() #15 {main}

Very good! You are almost there. Could you also add this changes in that file?
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/270a4c51ff1fcee6a9c271545792c377fc38249f

**Comment by pH-7** [comment]
So, remove
```php
$rStmt->bindValue(':middleName', (!empty($aData['middle_name']) ? $aData['middle_name'] : ''), \PDO::PARAM_STR);
```
in `_protected/app/system/core/models/UserCoreModel.php`, line 742

**Comment by CooperAshley2** [comment]
It worked beautifully! Thanks again!!
