### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by shutterflypro** [pH7Software/pH7-Social-Dating-CMS#53]
Would really like to be able to use this software.  It looks very promising however after completing the install all I am getting is blank pages on both the regular website and the admin side.

Hoping this is a simple issue to fix

**Comment by pH-7** [comment]
This error is caused because the requirements of your server doesn't meet with the software.
Please set the development mode to see the error http://ph7cms.com/doc/en/how-to-set-the-development-mode

And requirements: http://ph7cms.com/doc/en/requirements

**Comment by shutterflypro** [comment]
Well this definitely shows the level of support that this software is giving.   Had to wait a week just to be treated poorly.  And you actually want to get someone to pay for this.

**Comment by pH-7** [comment]
Firstly, The software is 100% open source. Please be gentle.
Secondly, You are not a client, so answer is not guarantee at all.
Thirdly, this is not a bug and you should see the documentation before, so you shouldn't even get an answer. That kind of issue wastes time on people who really deserve.
