### ISSUE TITLE
Deleting duplicate fake profiles

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#531]
During the fake profile generator of 25 men, there are profiles with the same picture. How can i delete those profiles with the same picture so visitors don't see the same picture on several different profiles, because it's a clear giveaway that the profile is fake.

When i try to delete the profile, a warning message comes up:

Are you sure you want to do this?
WARNING, THIS ACTION IS IRREVERSIBLE!

If i select yes, then i've screwed up my /UserCoreModel file again. If i select no, I have a site with hundreds of duplicate photos/different profiles. I wanted to upload 25 profiles at a time and go through to delete the ones with the same photos.

**Comment by pH-7** [comment]
Can you tell me what error exception message from UserCoreModel comes up?

**Comment by CooperAshley2** [comment]
Actually, no error message is coming up now, only the warning message and I am able to delete profiles so this is considered solved and I'll close this issue.
