### ISSUE TITLE
Delete/disable profile heading?

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#532]
How can we either remove or delete the profiles header: 

" A Man of 52 years, from United States, York Rhode island" 
" A Woman of 33 years, from United States, Witchita Kansas"

**Comment by pH-7** [comment]
Please delete this line `_protected/app/system/modules/user/controllers/ProfileController.php`, L81-L82 -> https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/90b7ad361287ceb00b0d90d8c0c3a13b041a2048/_protected/app/system/modules/user/controllers/ProfileController.php#L81-L82 

Or this one `_protected/app/system/modules/cool-profile-page/controllers/MainController.php`, L62-L63 -> https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/90b7ad361287ceb00b0d90d8c0c3a13b041a2048/_protected/app/system/modules/cool-profile-page/controllers/MainController.php#L62-L63 if the "Dating-Style Profile Page" module is enabled.
