### ISSUE TITLE
Regarding How to remove pH7CMS.com website on generated fake profiles

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#533]
Your response in 2018 was "Since pH7Builder 14, the "https://ph7cms.com" website is automatically added to the generated fake profiles as a dummy (sample) data.

If you wish to get rid of it,

You can edit the generated profiles easily (from Admin -> User/Admin -> Users -> Browse) and change/remove the website on the generated profiles OR

You can comment this highlighted L159 line in 

_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php file."

I don't understand when you say "comment this highlighted L159 line". Do you mean to delete the line, or edit the line... not sure what that means, please clarify. Thanks.

**Comment by pH-7** [comment]
Comment a PHP line means adding `//` at the beginning of the line. (more info: https://www.php.net/manual/en/language.basic-syntax.comments.php)

Anyway, better for you to just delete that line :)
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/9dbb82f81df74bc4dcffc4da508900847c63c908/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php#L161
