### ISSUE TITLE
Adding More Genders?

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#534]
If we want to add additional genders such as F2M or M2F transgenders, would it be the opposite of the suggestions here: 

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Remove-the-%22couple%22-option

We would add a line in the forms instead of removing them?

**Comment by pH-7** [comment]
Unfortunately, this would also involve database ENUM update. 

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql#L86

At the moment, the ENUM only contains "male", "female", "couple". So, if you manually add some additional genders in the PHP form dropdown fields, it won't work as the current ENUM won't match with them.

It will also require some PHP modifications such as in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/core/classes/GenderTypeUserCore.php
