### ISSUE TITLE
Deleting pages

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#535]
Within my _protected/app/system/modules/page/views/base/tpl/main folder, I deleted certain pages that I don't need such as the Affiliate Terms, Links, Jobs and Partners page so they do not show up on the homepage at all, but the links to the Jobs, Links and Partners pages still show up and when clicked on, on the live site:

This comes up for the Jobs page: 

![image](https://user-images.githubusercontent.com/50240615/57204446-f26bdf00-6f85-11e9-9d3a-46b4e585dcca.png)
 
This comes up when the Links page link is clicked on: 

![image](https://user-images.githubusercontent.com/50240615/57204559-9b1a3e80-6f86-11e9-82dd-d12ac0ea1f75.png)

And this comes up when the Partners link is clicked:

![image](https://user-images.githubusercontent.com/50240615/57204547-7aea7f80-6f86-11e9-893d-354089b621d3.png)

What other file(s) do i need to edit so these links do not appear on the homepage?

Thank you.

**Comment by CooperAshley2** [comment]
Any suggestions on other files I need to edit so these link are not visible on the homepage? Thanks.

**Comment by pH-7** [comment]
You will also have to edit the bottom menu.
For instance, removing this line for the "Jobs" page https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/tpl/bottom_menu.inc.tpl#L21

**Comment by CooperAshley2** [comment]
Thanks for responding, that worked perfectly! Thank you.

**Comment by polynamaude** [comment]
@CooperAshley2 You can also use the **_fgrep_** command on a shell prompt. It will allow you to search through all the source file. You just run this command with the _**-r**_ option from the root folder or your CMS.

**Comment by polynamaude** [comment]
@CooperAshley2 Ex: **_fgrep -r 'Jobs'_**
