### ISSUE TITLE
Bug - Membership Expiration Days 

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#538]
I created a new membership group that I want to be the VIP group that will have access for a whole year (365 days). However the system display 255 days

**Comment by pH-7** [comment]
Thanks for the bug report @Nigrini!

Please execute the following through your phpMyAdmin or MySQL command line
```sql
ALTER TABLE ph7_memberships MODIFY expirationDays smallint(3) unsigned NOT NULL;
```

Replace the "ph7_" by your database prefix you set during the installation.  It can be viewed in ~/_protected/app/configs/config.ini -> [database] prefix
