### ISSUE TITLE
IM Module

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#539]
Is the IM module still under development?

* IM does not pop up on the user you want to interact with screen. It seems that the user must go to live chat before the popup appears.

* Messages between the two may or may not reach their target

**Comment by pH-7** [comment]
Related to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/138

**Comment by Nigrini** [comment]
I went through #138 a couple of times but I am still unsure regarding this. The current IM is so unreliable on all of my installations (Test Lab) that for the one site that I am working towards going live with I am going to disable the module entirely simply because it is just not reliable.

It is quite difficult to explain because each installation of pH7Builder so far gives me different results. But so far none of them was anywhere near reliable enough to go live with. In a nutshell what I get a combination of the following:

IM does not always pop up on the user you are trying to interact with screen.
When it does pop up there is no message displayed
IM pop up with the message but the reply does not reach the person who initiated the IM chat
IM reply reach the person who initiated the IM chat only in parts. There is a huge amount of text lost
IM reply reach initiator hours after the reply was sent.
