### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by shutterflypro** [pH7Software/pH7-Social-Dating-CMS#54]
Since you locked the last thread I will just have to start another one.

Firstly, The software is 100% open source. Please be gentle.
Secondly, You are not a client, so answer is not guarantee at all.
Thirdly, this is not a bug and you should see the documentation before, so you shouldn't even get an answer. That kind of issue wastes time on people who really deserve.

The above quote from you.  Here is the answer.  Yes the software is 100% open source, but a big deal is made going through it about purchasing from you.  I WAS someone that would have been more than happy to pay you fee to become a client.  I am glad this has taken place though because it shows your real integrity and shows off what I would have gotten for my money.  Thirdly as far as your documentation goes, I read through its limited scope and guess what even with everything you said it requires turned on and verified the white screen persists, that screams bug to me.  So when you get off your high and mighty horse and decide to provide good customer serviceI think everyone should be able to see your true colors and what they will get when they pay you.

So go ahead and lock this thread and mark it irrelevant and let your true colors fly!

**Comment by ghozzt** [comment]
Maybe it’s time that you get off your horse and do what advised, or at least, to provide a proper description, along with relevant log files and the output you get when putting the site in development mode?

I get a ‘blank page’ isn’t exactly something that allows anyone to isolate the root cause.

Nico (happy customer and user of PH7)

**Comment by shutterflypro** [comment]
@ghozzt I will gladly get off a high horse.  I just have major issues when he so nonchalantly locks the thread because he doesn't want to help.  He was quick to label it as invalid and then locked the thread.  Instead he should have asked what I have tried.  He would have found out that I enabled the developer switch as per his links and docs.  He would have also found out that I have had my server company verify that all required modules and specs are met.  Guess what still get a white screen with nothing. So what am I am supposed to say now.  

Yeah he pissed me off, there are to many keyboard pirates out there that think this is fun.  Customer service should be a priority not something that is just brushed aside.  You may have had good service but that doesn't really help the situation here.

**Comment by pH-7** [comment]
@shutterflypro 
Concerning your ticket #53 As I knew it wasn't a bug and as your last comment wasn't related to the question, I locked the conversation. 
Please remember that Github tickets are not for that kind of comments you just wrote here.

You have to use the contact form instead. Thank you!
