### ISSUE TITLE
Freichat integration

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#541]
** NOT URGENT**

The current chat will do for now but for an experiment I want to try and integrate the Freichat software (https://freichat.com/). 

Using the following youtube video as guide https://www.youtube.com/watch?v=6MLySOm345g will the ph7CMS database allow the "integration" or am I on the wrong path with this one

The idea is to ultimately have the URL submitted to the API section in the admin panel, but I want the user to be authenticated by the ph7CMS database

**Comment by pH-7** [comment]
Thank you for the suggestion!
However, this wouldn't replace the chat, but the IM. 

I looked to the license (and strangely, was hard to find it...), but the free version looks to be also under a priority license which doesn't allow me to distribute it with the software and isn't compatible with pH7CMS's GPL v3 license.

Finally, the software looks quite new, and the code doesn't look very good (it won't meet the code's quality standard required for pH7CMS).

Thanks anyway!

**Comment by pH-7** [comment]
Anyway @Nigrini, you could still [ask them](https://freichat.com/contact_us) for an integration, so you could use it if you like their chat :)

They already have several several integrations, https://freichat.com/integration_list so, pH7CMS could be the next one if you insist to them...

**Comment by pH-7** [comment]
Hope it helped @Nigrini :)
