### ISSUE TITLE
Social Network Sharing

### ISSUE THREAD

**Issue by CooperAshley2** [pH7Software/pH7-Social-Dating-CMS#546]
When I try to share on Pinterest, the preview shows correctly:

![image](https://user-images.githubusercontent.com/50240615/57576703-92b57e00-7434-11e9-8a48-67fd2319edd2.png)

When I try to share on Facebook, the preview shows this, and I have no idea where the wording came from. How do i change it to show what the Pinterest is showing OR what file do i edit:
![image](https://user-images.githubusercontent.com/50240615/57576718-bed0ff00-7434-11e9-8a4a-bf7d5db4384d.png)

Mobiller asked a similar question in #303 but I don't have the US country blocked. 
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/303 

I'm referencing #303 because before today, the Facebook preview was blank. It only showed the word "Home" and nothing else. I cleared my browser cache and now it's showing the above, what i stated.

**Comment by polynamaude** [comment]
@CooperAshley2 You should take a look at **_https://developers.facebook.com_** . You will find all the information about what meta tags do facebook uses and how do they build the preview.

You'll have to understand that we don't offer advice on building website, on how does the Facebook social network architecture work or everything related.

We do support for the pH7CMS. Not your whole compute ecosystem.

It's like calling the company that made a screwdriver to ask how to open a microwave.

Again, the same technique as I gave you (**_fgrep_**) will allow you to search through the source code and find where do the words in the preview come from which file.
