### ISSUE TITLE
Default User Bug 15.1.0

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#547]
After the upgrade (But I notice this on a clean install as well), the default membership group is set to Visitor (not visible), and you cannot change that. Although you are able to select a different group when you save your changes the Visitor (not visible) is still the default membership group.
![Capture](https://user-images.githubusercontent.com/43742116/57695378-6bd29400-764e-11e9-82d6-1cc17b99c8a6.PNG)

**Comment by pH-7** [comment]
Great catch @Nigrini That was a bug indeed 👍
