### ISSUE TITLE
Suggestion: Add allow="microphone; camera"

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#548]
I was having problems with the webcam in the Chatroom (I have the paid version) where Chrome and Opera browsers would not allow the cam and mic functions but Firefox and Edge were working fine.

To fix this I edited the following file _protected/app/system/modules/chat/views/base/tpl/home/index.tpl

I added     **allow="microphone; camera"**

<iframe src="{chat_room}" frameborder="0" scrolling="no" height="500" width="100%" allow="microphone; camera"></iframe>

**Comment by pH-7** [comment]
Thanks for the suggestion! 🎉

**Comment by pH-7** [comment]
For further information: https://www.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
