### ISSUE TITLE
Use SCSS (SASS V3) for templates

### ISSUE THREAD

**Issue by pH7Software** [pH7Software/pH7-Social-Dating-CMS#55]
This would be a new feature:
Use SCSS (SASS V3) for templates (.scss extension), then comple it with Compass (http://compass-style.org/) to a main.css file (or like that).

That feature will make easier to build new CSS files and optimize even a bit more the HTTP requests (only one file) so one HTTP request and the "@import('')" CSS will not use another HTTP request anymore thanks SASS as it will compile all in the same file.

**Comment by pH-7** [comment]
Not applicable anymore. I will close it as things change fast and I might use a different approach.
