### ISSUE TITLE
Color Changes

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#553]
I an trying to do away with the Pink throughout the website.

In the image "Browse Members" and "My Dating WebApp" cannot be changed through the Admin panel, but is is possible to change the "Meet new People" by changing the Text option in Design (Color). 

![q](https://user-images.githubusercontent.com/43742116/58314451-cec2e880-7e0f-11e9-871c-81178b14cf51.PNG)

I did a Grep search and in the following file **color.css** you specify some colors regarding Pink.
I changed the color code to  #922b21 but it did not change the outcome. I see that the new value is propagating since you made it a class, because I did a Grep after the value change and it is reflecting in the other files. 

![v](https://user-images.githubusercontent.com/43742116/58314781-822bdd00-7e10-11e9-810b-cbea07cb1fc1.PNG)

I can't seem to find the place where you specify this

**Comment by polynamaude** [comment]
@Nigrini Have you tried using the **_inspector_** (in Firefox developper tools) or a similar tool in another browser. It will allow you do get the properties of the objects you are interested in. From there, you can compare between where changes happens and where they don't.

Not sure if what I said make sense (as English ain't your primary language).

**Comment by pH-7** [comment]
This is where the class is used https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/68ad351919352bd7b4bda08e12f2754f50d19d60/_protected/app/system/modules/user/controllers/BrowseController.php#L61

**Comment by pH-7** [comment]
And in the color.css stylesheet
-> https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/css/color.css#L67-L69

And the hover, https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/templates/themes/base/css/color.css#L87-L90
