### ISSUE TITLE
Possible Bug when registering

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#555]
After a clean install

When you register as a user you get to the stage where you can add a photo or skip the process.
If you skip the process you are taken to the screen where you can login.

If you pick upload a picture the system does not proceed with the option, but instead takes you to the login screen as well.

**Comment by pH-7** [comment]
I guess, the size of the photo was too big... or maybe a wrong extension.

**Comment by Nigrini** [comment]
Nope - The moment you click on the browse button, it kicks out and takes you to the login page.

**Comment by pH-7** [comment]
What web browser is it? Strangely never got this problem before...

**Comment by Nigrini** [comment]
Safari - You are right, it was the browser cache that was causing the problem. After clearing this the problem was solved.
