### ISSUE TITLE
Unknown Number

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#556]
On the landing page I have an unknown number in the top left corner of the page.
![zz](https://user-images.githubusercontent.com/43742116/58367498-5d9f3600-7ee0-11e9-83c0-d0db852d10a8.PNG)

On a Grep search it finds the code here:
./_protected/data/cache/pH7_cache/db/design/static/83f0d057ba6b488def5157cfed383a3df9f6fe43.cache.php:s:14:"UA-140787018-1"; ./grep.php:$command = "grep -ri 'UA-140787018-1' ./*"; Grep job over.

I did not notice it before, because it is difficult to see with the splash video enabled, therefore I don't know if this is normal behavior. As far as I can see it does not affect the functionality of the site in a negative way.

**Comment by pH-7** [comment]
I guess that's your Google Analytics ID. Maybe, you pasted it outside of the `<script></script>` tags somewhere, by mistake... 
Have a look in Admin -> Setting -> Analytics Code to see if everything is fine there...

**Comment by pH-7** [comment]
FYI @Nigrini, in Admin -> Setting -> Analytics Code,
It has to be the full given analytics tracking code (not just the UA ID).
