### ISSUE TITLE
Bug: Page Refress ?

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#557]
When browsing the users for the first time I will get the "full" image. Like this
![abc](https://user-images.githubusercontent.com/43742116/58434483-2dac8a00-80bc-11e9-88bf-36e4a39c7d15.PNG)

When I browse again I will get this

![xxx](https://user-images.githubusercontent.com/43742116/58434502-49179500-80bc-11e9-804c-0841bb695a99.PNG)

You constantly need to Crtl+F5 to fix this

**Comment by polynamaude** [comment]
@Nigrini Hi ! This seem to be related to a cache meta tag that tell the browser to cache some image in a wrong way. You can create an account at Ngrok (free). This will allow you to examine requests and responses.

Good luck in your investigation.

**Comment by Nigrini** [comment]
I manage to sort this one out - Maybe it will help other people. 
When you have https, then you must force it in the htaccess file. Some users visiting the site and registering a user on http will cause problems for you once the ssl is in place. By using a check of your site like https://www.whynopadlock.com/ it will tell you that some images were uploaded to your site that cannot be verified.

And the only way to fix that then is for you as the admin to upload another profile pic for the affected users. 

Jeeeez, I hope this makes sense to you guys
