### ISSUE TITLE
Can't upload video

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#561]
First at all I want to say thanks for the great job you guys have done. It's a phantastic site and helps me a lot to get into this dating business.
I'm actually programmer of CAD SW using Visual Studio C++, but I have no experience with PHP. For me it's a nice opportunity to upgrade my knowledge. Maybe in future, after I've learned my lesson, I can also contribute to the project.

Everything is working fine, except one problem which I could not yet solve. I wanted to test the video upload feature, but without success. As testing environment I use **XAMPP v3.2.2**.
ffmpeg.exe is installed and **app\configs\config.ini** > **handle.ffmpeg_path** is initialized.

I performed the test with the **1_vid.mp4** which came with the software. The size is 4.76MB.
I just copied the file to **Test.mp4**.
When I want to upload this video as a Regular video with the following settings ...
![UploadVideo1](https://user-images.githubusercontent.com/51194360/58626467-1ad5c780-82ff-11e9-8f36-5b736af9896e.jpg)
I get the message that the file was too large or the type was incompatible ...
![UploadVideo2](https://user-images.githubusercontent.com/51194360/58626583-5a9caf00-82ff-11e9-8fb2-4944d1dc0faa.jpg)

Does anybody have an idea what could be the reason?
Thanks already in advance

**Comment by Nigrini** [comment]
You must find out from your ISP if your hosting plan caters for ffmpeg. I know for me personally I will have to upgrade to a much more expensive plan to be able to use that function. That may / may not be tea reason, but it will be my best guess, and the first thing I will get clarification on.

**Comment by dimuller** [comment]
Thanks for your quick response. Appreciate!
But no, this can't be the reason. I work locally on my PC in a test environment as localhost via **XAMPP** and ffmpeg.exe is installed on my computer.
But you are right. As soon as I go public I will have the same problem. My ISP enabled ffmpeg.exe as a PHP module, but I don't know yet if this will work with pH7. Maybe it does, but certainly not without code change.

**Comment by Nigrini** [comment]
Please let me know if you find a solution. I will have the same exercise regarding the video module in about a month or so. 

Currently on my system I disabled the video module not because I don't find it useful, but because I am building the site without fake profiles. That in itself is a challenge because it is difficult getting people to register on a site when there is only 20 users.

But I will most definitely upgrade the ISP hosting plan and enable the module once I reach the 200 mark or so.

**Comment by dimuller** [comment]
Ok, I will keep you informed. As soon as I have a solution I will let you know.
Yes, it's indeed a challenge to get started. I'm more lucky. My wife is in this business already for a while and she can add her stock of ladies before we open the site for the public. What I do now is just to test all the features locally on my PC so that everything is working well once we go public.
Anyway! Wish you good luck!

**Comment by Nigrini** [comment]
Great - And Good Luck.

It is really stunning software, and with a little tweek here and there can be No 1 in my book.

**Comment by dimuller** [comment]
Sorry guys, I made a mistake.
The error message that **the file was to large or the file type wrong** came up after I made some changes in the code. With the original code the system tells me that I have to choose the video type.
I selected **Regular (from device/computer)** and then I selected the file **Test.mp4** video as you can see in the upper screenshot.
After a click on Upload the following screen came up:
![UploadVideo3](https://user-images.githubusercontent.com/51194360/58742209-1ddece00-844d-11e9-8f6c-ca5aea702080.jpg)
I tried to investigated the problem and found out that the the variable **$_FILES** was not initialized correctly. **type** and **tmp_name** were not set ...

![$_FILES](https://user-images.githubusercontent.com/51194360/58742839-e540f380-8450-11e9-8480-41aa87e2a1b9.jpg)

on construction of the **VideoProcessForm**.

![VideoFormProcess-construct](https://user-images.githubusercontent.com/51194360/58742872-a495aa00-8451-11e9-85af-4b864a5afb10.jpg)

At line 95, where an empty **tmp_name** was found, the system run into the upper mentioned error.

Does anybody have an idea why the **$_FILE** array is not initialized correctly?

As I mentioned! I'm new in PHP and pH7, so there are still many things not yet clear for me.
Assistance would be very much appreciated. Thanks already in advance.
