### ISSUE TITLE
Suggestions: Mass mail / Modal Popup

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#562]
The ability for admin to send a mass mail to all the users. This may be problematic if there is lets say 2000 users for argument sake, because your IP and/or domain may get registered for spamming ?? 

Alternative (Safer Option I think)

Ability for Admin to place a temporary Modal Popup message to be displayed once the user login, to relay information deemed necessary or important by Admin to the site users

**Comment by pH-7** [comment]
Thanks for the suggestion @Nigrini! Yes, something like sometimes FB or others do for privacy or other warning or informative messages users have to know. However, users have to log in to your website in order to see that message.

**Comment by Nigrini** [comment]
Ohh Yes for sure - The popup only to be displayed for the registered users

**Comment by Nigrini** [comment]
Something like this perhaps ?

https://github.com/dinbror/bpopup/
