### ISSUE TITLE
Force profile picture

### ISSUE THREAD

**Issue by arize99** [pH7Software/pH7-Social-Dating-CMS#563]
I want to enforce uploading of profile pictures before user can do anything. After sign up, some users don't upload a picture and it makes the site look unserious.

**Comment by dimuller** [comment]
Did you set **Settings > Registration > Require photo to be uploaded:**  to **Yes**?

**Comment by Nigrini** [comment]
The best you can do currently is:

On the Admin Panel -> General Settings -> Registration there is an option to say Yes / No for Require Members to upload a profile photo during sign up.

However - A user can still upload a cartoon pic, or any other image for that matter. I don't think there is a way to automate the process of forcing a user to upload a genuine face pic. You will have to approach all the users without a profile pic, or an image that is undesirable by your definition individually.

About limiting functionality of the software based on a profile pic - The system cannot do that, and like I said, a user can always change their profile

**Comment by pH-7** [comment]
Hope @Nigrini  and @dimuller answers helped 🎉 

An alternative answer could be found here https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/307#issuecomment-423111435
