### ISSUE TITLE
can't disable 2co gateway (sorry any gateways)

### ISSUE THREAD

**Issue by CharleeHan** [pH7Software/pH7-Social-Dating-CMS#564]
Hi,

I am using ph7cms 15.1.
I can't disable the 2CO gateway. Please advice.

Thanks,
Charlee

**Comment by Nigrini** [comment]
Are you able to make any other changes ?

You must disable MOD security on your hosting environment. I remember from my own experience that if this is not done, you will have problems saving your settings. 

Also make sure your files and folders have the the correct permissions. See the documentation regarding that.

**Comment by CharleeHan** [comment]
Yes, I am able to make any other changes.
It is hosted on my own virtual centos 7 server.

Thanks,

**Comment by CharleeHan** [comment]
SELINUX=disabled

**Comment by pH-7** [comment]
I tried to reproduce your issue and was working perfectly fine for me. 
Are you sure that the `_protected/app/system/modules/payment/config/config.ini` has writing permissions (or ask your web host to check it for you).

**Comment by pH-7** [comment]
Finally, the issue @CharleeHan got might be caused by a bug introduced in 15.1.0, but fixed in 15.1.6.
The patch can be found here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/7e5531410c2e37bfc8478754e5d0796c1b7d8e28
