### ISSUE TITLE
The meet-people system module is not found

### ISSUE THREAD

**Issue by mimmort88** [pH7Software/pH7-Social-Dating-CMS#565]
hi support I have a problem that I don't know how to solve
I entered the work environment mode
and when I search from the second page onwards of any nation
gives me this error:
Message: The meet-people system module is not found.
File: /home/mixeyqwe/meetsexyourcity.com/_protected/app/system/modules/meet-people/
or the config.ini file is not found.
File: /home/mixeyqwe/meetsexyourcity.com/_protected/app/system/modules/meet-people/config/config.ini
File: /home/mixeyqwe/meetsexyourcity.com/_protected/framework/Mvc/Router/FrontController.class.php
Line: 893
Trace:
# 0 /home/mixeyqwe/meetsexyourcity.com/_protected/framework/Mvc/Router/FrontController.class.php(208): PH7 Framework PVC Router FrontController-> notFound ('The meet-peo ...' )
# 1 /home/mixeyqwe/meetsexyourcity.com/_protected/framework/Mvc/Router/FrontController.class.php(131): PH7 Framework MVC Router FrontController-> simpleRouter ()
# 2 /home/mixeyqwe/meetsexyourcity.com/_protected/framework/Mvc/Router/FrontController.class.php(119): PH7 Framework MVC Router FrontController-> launchNonRewritingRouters ()
# 3 /home/mixeyqwe/meetsexyourcity.com/_protected/framework/Pattern/Singleton.trait.php(31): PH7 Framework PVC Router FrontController -> __ construct ()
# 4 /home/mixeyqwe/meetsexyourcity.com/_protected/app/Bootstrap.php(97): PH7 Framework PVC Router FrontController :: getInstance ()
# 5 /home/mixeyqwe/meetsexyourcity.com/index.php(46): PH7 Bootstrap-> run ()
# 6 {main}

I am also attaching a photo of the error page
https://meetsexyourcity.com/error.png
please help me

**Comment by pH-7** [comment]
Can you try to clear the cache? https://ph7cms.com/doc/en/how-to-clear-caches

Maybe you changed the language and somehow the URI cache didn't get generated.

Finally, did you change something in [routes/en.xml](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/configs/routes/en.xml)...?
