### ISSUE TITLE
Suggestion: Private Album/Photos

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#568]
I see this issue was requested way back in 2014. It is possible to revisit this request. By having the Community option during installation, the focus is not so much on dating ?

**Comment by pH-7** [comment]
Related to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/14

**Comment by pH-7** [comment]
Unfornutately, at the moment I don't have enough free time to add this feature.
However, you could hire a GOOD PHP dev to create it for you... (or even friends, etc).
Create an ad on Toptal, AngelList or Upwork mentioning pH7CMS and see if some folks out there have some experience with the software.
