### ISSUE TITLE
Off Screen

### ISSUE THREAD

**Issue by Nigrini** [pH7Software/pH7-Social-Dating-CMS#573]
When working in the admin panel User/Admin the options under Action keeps moving offscreen 
![xxx](https://user-images.githubusercontent.com/43742116/59673868-5955f800-91c2-11e9-93a4-4483f4fc1d95.PNG)
 
You need to scroll down the page to the bar below, to navigate right in order to get everything
![bb](https://user-images.githubusercontent.com/43742116/59673968-8b675a00-91c2-11e9-97af-7d620a1bac0a.PNG)

Is it possible to make the gap between the Avatar and the IP smaller perhaps so that everything will fit in properly without scowling to the right.

This is not because of my monitor size.

**Comment by polynamaude** [comment]
@Nigrini You can actually edit yourself the template file. It's a pretty simple thing to do.
The CMS use responsive design for the display of pages so the size of the objects are not set but computed by the browser rendering the page.
PM
