### ISSUE TITLE
template 

### ISSUE THREAD

**Issue by linducip2208** [pH7Software/pH7-Social-Dating-CMS#576]
HI, i want to buy new template for ph7cms.
where i must buy?

thankyou
Lindu

**Comment by pH-7** [comment]
Hi @linducip2208 

This project is 100% free and open source. There aren't any templates to buy. 

If the 4 templates already included in the software don't suit you, you could find/hire a great designer to create one for you [based on the ones already there](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/templates/themes).
