### ISSUE TITLE
different ph7cms free vs ph7cms pro

### ISSUE THREAD

**Issue by linducip2208** [pH7Software/pH7-Social-Dating-CMS#577]
hi, we want to know whats is the different between ph7cms free vs ph7cms pro

and for ph7cms pro, one time payment ? no monthly
whats is the different payment 10 usd/month 30 usd/month etc

thanks 
Lindu

**Comment by polynamaude** [comment]
@linducip2208 Hi,
Again, I'm going to go simple...
https://ph7cms.com/doc/

I don't know why you are talking about payment as the software is OpenSource (aka Free).
For sure you can give a contribution through Patreon and PH will be more than happy about this.

**Comment by linducip2208** [comment]
oke thank you

Pada tanggal Sen, 8 Jul 2019 05.55, Polyna-Maude R.-Summerside <
notifications@github.com> menulis:

**Comment by pH-7** [comment]
pH7CMSPro has been discontinued a while ago by now and isn't available anymore.

The current version available on [GitHub](https://github.com/pH7Software/pH7-Social-Dating-CMS/) (and [SourceForge](https://sourceforge.net/projects/ph7socialdating/) is the recommended one.
