### ISSUE TITLE
membership level management

### ISSUE THREAD

**Issue by linducip2208** [pH7Software/pH7-Social-Dating-CMS#579]
Hi

we want membership level management like skadate. there is features at ph7cms?

![membership-level-management](https://user-images.githubusercontent.com/49618141/60771868-272c1c00-a118-11e9-9fe4-8191da1cb18a.png)

chat can used by premium member

**Comment by polynamaude** [comment]
@linducip2208 Hi,
Thanks for your interest in pH7CMS.
Yes there is possibility to implement membership level.
As the software is Free, I'd suggest you give it a try and get answer to many of your questions.

**Comment by linducip2208** [comment]
hi

i try for ayotaaruf.com but didn't find membership level management.
chat only at premium member


Pada tanggal Sen, 8 Jul 2019 05.52, Polyna-Maude R.-Summerside <
notifications@github.com> menulis:

**Comment by polynamaude** [comment]
@linducip2208 I don't understand what you are saying here.
Simply install your own instance and customize it to your needs.

**Comment by linducip2208** [comment]
customize with code?

Pada tanggal Sen, 8 Jul 2019 09.42, Polyna-Maude R.-Summerside <
notifications@github.com> menulis:

**Comment by polynamaude** [comment]
@linducip2208 Do you speak english ?
Or should I say, do you understand english ?

Let me think... you're expecting something that work out of the box and that you'll get rich without much work ?

**Comment by polynamaude** [comment]
@linducip2208 Do some reading about what's a CMS, learn PHP whatever, have fun !

**Comment by pH-7** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/540

**Comment by dimuller** [comment]
I believe it would be worth to consider it as future feature. It would be very useful.
My idea is to not only to enable and disable modules, but to add a membership level to each module.
This should not be too difficult. What do you think?
Maybe that could be my first contribution to the SW ;-)

**Comment by polynamaude** [comment]
@dimuller This is an OpenSource software (FOSS), everyone is welcome to customize and modify to suit one's own need.

Here's some starting point
https://ph7cms.com/doc/en/code-convention
https://ph7cms.com/doc/
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki

**Comment by polynamaude** [comment]
@dimuller I don't know how much experience you've got in programming but you'll need more than just modify the form in the administration panel. You'll need to do some validation on the controller and routing level to validate if a module is available depending on the user level (when the call is made to display the specific page). You will also need to do some modification to ensure that links that the user can't use aren't displayed.

**Comment by polynamaude** [comment]
@dimuller Take time to read the discussion related to some issue. This will save time on useless talk.
That's mainly a one-man project (PH) with me giving some time. So there won't be much discussion wit a development team.

**Comment by dimuller** [comment]
> 
> 
> @dimuller This is an OpenSource software (FOSS), everyone is welcome to customize and modify to suit one's own need.
> 
> Here's some starting point
> https://ph7cms.com/doc/en/code-convention
> https://ph7cms.com/doc/
> https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki

@polynamaude thanks for your response and comments.
I digged already well into the code-conventions and the docs, but I've not yet seen the wiki, which actually is very helpful.

**Comment by dimuller** [comment]
> 
> 
> @dimuller I don't know how much experience you've got in programming but you'll need more than just modify the form in the administration panel. You'll need to do some validation on the controller and routing level to validate if a module is available depending on the user level (when the call is made to display the specific page). You will also need to do some modification to ensure that links that the user can't use aren't displayed.

@polynamaude I got some experience. I started with Firmware software for Intel's second generation microprocessor 4040 end of the 70ties. My main job is CAD software in C++, but I have no experience at all with Web based software. So I have to catch up a lot. It's not only a new language, the whole programming environment is different.
Yes, I know that it's not done with the form, but I think it would be a relatively simple way to get this feature. Or do you have a better idea?
I will definitely dig into it as soon as I get some time because I really need it to manage the difference of the user levels.

**Comment by dimuller** [comment]
> 
> 
> @dimuller Take time to read the discussion related to some issue. This will save time on useless talk.
> That's mainly a one-man project (PH) with me giving some time. So there won't be much discussion wit a development team.

@polynamaude IC, so I'm talking already with the right person. That makes things even easier ;-)

**Comment by dimuller** [comment]
Hi @linducip2208,
Membership levels are already implemented. I don't know what you are missing.
It just does not work with a table like you recommended.
As Admin you just go to **Mod > Billing > Memberships List**
There you **edit** the level which you want to control.
Then a form opens where you can define the features which should be available for this level.

**Comment by linducip2208** [comment]
hi

i mising module membership level . module chat for premium member not free
member

thank you

Pada tanggal Min, 21 Jul 2019 12.05, Dieter <notifications@github.com>
menulis:

**Comment by dimuller** [comment]
Yes, this is available when you follow my link.
You login as Admin, then you open **Mod > Billing > Memberships List**
There you choose edit you can choose which modules are available for this level.
So in case of Regular members for example you can disable chat, but you can make it available for Premium members.
