### ISSUE TITLE
Ph7CMS admin general settings doesn't save

### ISSUE THREAD

**Issue by Smizzie** [pH7Software/pH7-Social-Dating-CMS#580]
Ph7CMS admin general settings doesn't save. I change the theme and everything. I tap save. Everything returns the way they were.

    Version: 15.1.6
    Version Name: ABSOLUTE™
    Version Build: 1
    Release Date: 06-01-2019

**Comment by Nigrini** [comment]
Turn Off ModSecurity on your hosting environment

**Comment by pH-7** [comment]
Hi @Smizzie, hope @Nigrini's answer helps you.
I will close it by now since I didn't hear from you.
Please feel free to reopen it at any time if the problem persists :)
