### ISSUE TITLE
Problem when you login as both admin and user.

### ISSUE THREAD

**Issue by AKNightHawk** [pH7Software/pH7-Social-Dating-CMS#584]
It seems to be a minor issue. But an annoying one. Whenever I run my site. And login as both an admin and my user profile. The links at the top of the page. On both the admin and the user side at the top. Sometimes Disappear. All except the people drop-down menu. It seems to happen randomly and suddenly. And I never know when.  It makes it hard when you're trying to work in the admin section. Or testing stuff in the front end. Just thought I would pass this along here.

**Comment by pH-7** [comment]
Hey @AKNightHawk 
Thanks very much for pointing this out!

What web browser do you use? And what screen resolution is it? Or maybe, could you just send here a screenshot when the problem occurs?

**Comment by AKNightHawk** [comment]
Your welcome @pH-7 I am currently using Firefox and my Resolution is 1366 x 768 soon as I get time to take a pic I will post it here. Thanks so much. :)
