### ISSUE TITLE
Pictures showing up sideways

### ISSUE THREAD

**Issue by AKNightHawk** [pH7Software/pH7-Social-Dating-CMS#585]
I uploaded a few pictures of mine to an album on my site. And all the pics that I posted except save one. Was sideways. What is that about?

https://assaultknights.biz/user/album/ak_nighthawk/just-me/1

**Comment by polynamaude** [comment]
@AKNightHawk Use a image editor program to rotate your picutres. It's simply because they are in the wrong orientation.
Some site do automatic transformation but pH7CMS does not to preserve image integrity.

**Comment by pH-7** [comment]
Unfortunately, at this time the software doesn't allow to rotate the photos. This would be a great feature though

**Comment by pH-7** [comment]
Just added a suggestion issue here: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/588

Hopefully, it will soon be done if I (or someone else) have enough of time for this issue :)

**Comment by AKNightHawk** [comment]
> 
> 
> @AKNightHawk Use an image editor program to rotate your pictures. It's simply because they are in the wrong orientation.
> Some site do automatic transformation but pH7CMS does not to preserve image integrity.

When I uploaded them they were in the right orientation. Then they come out like that.  Honestly, the site should not even mess with the orientation. Or resize the pic unless it is making a thumbnail.

**Comment by AKNightHawk** [comment]
@pH-7 Thanks for suggesting that. Would be a nice feature for sure. :D

**Comment by dimuller** [comment]
Another nice feature would be the ability to drag the picture on upload to the best position in the avatar square.
Most pictures are rectangular. With center alignment many times the head gets cut off. Unfortunately not all website users are capable to crop the picture before uploading it.
I changed already from center alignment to top alignment what gives a slightly better results, but not in all cases.
