### ISSUE TITLE
getting 404 error just after installation

### ISSUE THREAD

**Issue by noorbakerally** [pH7Software/pH7-Social-Dating-CMS#586]
WASTE OF TIME !!!!!!!!!!!!!!!!!

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Maybe if you'd give more information than "I did everything as supposed and it didn't work. Oh by the way, I installed that thing on a computer running an operating system" we'd be happy to give you a hand.

For sure, without any log we can give plenty of good answer that will all fail !

http://ph7cms.com/doc/

Make sure you ain't running modsecurity.

**Comment by polynamaude** [comment]
No there's no **_asset_** folder, this is why we use mod_rewrite !

**Comment by noorbakerally** [comment]
mod_rewrite in `on`, some lines in the log that appears to be linked with this:

```
[Sat Jul 20 11:12:06.787055 2019] [mpm_prefork:notice] [pid 7602] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Jul 20 11:12:07.907624 2019] [suexec:notice] [pid 7940] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sat Jul 20 11:12:07.930542 2019] [auth_digest:notice] [pid 7940] AH01757: generating secret for digest authentication ...
[Sat Jul 20 11:12:07.931202 2019] [lbmethod_heartbeat:notice] [pid 7940] AH02282: No slotmem from mod_heartmonitor
```

**Comment by polynamaude** [comment]
And what makes you think this is related ?
Anyway, sorry dude... Don't have time to waste... when you get the time to read the little link I've gave you then maybe you'd get something back.

How do you think that I can get any idea when you throw out 4 lines out of no-where ? That I don't have a clue about what you are running on ?

Help yourself and maybe god will do is part too ;-)

**Comment by polynamaude** [comment]
High Five ! I'll give Donald Trump a vote.
