### ISSUE TITLE
I have issue with the cache and mobiles 

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#590]
Okay I will keep this very simple this time. I have the site running perfectly on my server but I am getting a few issues between devices/browsers, for example I sign in with chrome and change a static page like contact us and its all fine in chrome.

I look at the site via firefox and its the old page still. Same with my mobile, only I dont know why but I can not access site on mobile via url I have to put IP address, this maynot be related.

The clear cache links in admin panel are not doing anything and yes I have cleared cache in browsers, still shows me the old pages. I have googled the problem and have looked on here so this is not a repeat question. 

Thank you.

**Comment by polynamaude** [comment]
@Undefined-Variables I'll make it simple. Give enough information so we can reproduce what you report. That's the basis of bug report.

**Comment by Undefined-Variables** [comment]
okay the cache will not clear using the buttons and i have different versions of a website all coming from the same server!

**Comment by Undefined-Variables** [comment]
problem is the buttons are javascript and I dont understand js! Not at all.

**Comment by Undefined-Variables** [comment]
I have figured out what was happening and I feel a bit silly, I have a server running one site and my laptop running another development site but both had the same cookie ID set and the same site setting in php.ini was empty so and I had been jumping between the two using the same browser! 

The cache buttons are still not clearing cache so I have disabled the HTML cache, that is fine for now but if/when I get traffic on the site this will cause the site to lag im guessing? Where are these buttons coded? Please don't say the Jquery file cos that is hard work!

PH-7 I would just like to say thank you for going open source and for all the work you have clearly put in to this, its amazing honestly, if this takes off for me I will one million percent become a patron.   :)

**Comment by pH-7** [comment]
> PH-7 I would just like to say thank you for going open source and for all the work you have clearly put in to this, its amazing honestly, if this takes off for me I will one million percent become a patron. :)

Thanks very much for your very nice message @Undefined-Variables! I really, highly appreciate it! 😊

P.S. If you like the software and appreciate the time I spent to build the software, I will be really happy if you could add a review at https://sourceforge.net/projects/ph7socialdating/ (you will just have to create an account in order to write a review).
This really motivates me to continue developing the software!

**Comment by Undefined-Variables** [comment]
Yes of course I will write a review :) Could you point me in right direction to sort these http links out, I have working SSL certificate and it works fine on Desktop but apple wont allow a secure connection cos there are http elements on the page! If you view page source it has 4 links that are using my ip address and not the domain name! Like http://1.1.1.1 the links are images, female no picture and ta few of the pages in about us menu are the same?

I will go and write this review now :) Keep up the good work...

**Comment by Undefined-Variables** [comment]
Dont worry I figured it out, the pictures in question were on accounts created over a http connection so I just uploaded new images and it works!!!! :) Very happy now and I have left you a review :)
