### ISSUE TITLE
ph7_settings missing, disable strict mode?

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#591]
After install I get the ph7_settings missing error that I have seen before in old posts.

There conclusion was to disable strict mode on mysql.. 
Is this the solution still?

**Comment by pH-7** [comment]
Hi @rondlite!

Are you sure you install pH7CMS on a new fresh database?

If this isn't the case, can you create a new database through your phpmyadmin and run the following files (in the same order)
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_SchemaGame.sql
* https://raw.githubusercontent.com/pH7Software/pH7-Social-Dating-CMS/master/_install/data/sql/MySQL/pH7_Core.sql

And let me know here what you get as error :)

**Comment by rondlite** [comment]
yes, dropped database after fail and tried again with fresh db, 
it missed quite a few tables (basicly everything after settings)
After copy paste of the raw sql file in mysql (with first editting the ph7_ prefix to my own), it worked.

**Comment by pH-7** [comment]
Did you get an error message while running those SQL files?

**Comment by pH-7** [comment]
Just curious, did you get any errors while running those SQL files as mentioned above? If so, do you remember them?

This information could help me to improve the installer.

**Comment by rondlite** [comment]
No errors like that, tried several times to reinstall and got same result.
Switched to apache2 (for rewrite reasons... nginx config not complete) and gave it another try.. 
Same result still..

I am using latest MariaDB is that is a clue.

**Comment by rondlite** [comment]
Apart from ph7_settings.. everything that comes after in the sql is also skipped.
Page refreshes back to the installer to the page i just submitted with the error about missing settings on top.. resubmit will not help due to duplicates being inserted (and that obviously fails)
