### ISSUE TITLE
Sign up Error

### ISSUE THREAD

**Issue by abuaslad** [pH7Software/pH7-Social-Dating-CMS#592]
The following error was found:

    Oops! Somebody has recently registered with the same IP address. You have to wait 1 day before try again.

When new user is trying to register. He face above error.

**Comment by pH-7** [comment]
As the message says, it means that you already have a user registered with the same IP address as him within the last 24 hours.

You can change this as simple as that.
Admin Panel -> Setting -> General -> Spam -> Registration delay for Users, and update the number to "0" to disable it (or simply decrease the number of minutes, as you wish 😁).

**Comment by pH-7** [comment]
Last thing @abuaslad, don't forget to Star the GitHub repo :)
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by abuaslad** [comment]
Thanks.... Issue has been resolved.
