### ISSUE TITLE
Unintentional commenting in Bootstrap.php

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#593]
The asterisk on the end of this line causes a few lines to get commented, I think this is unintentional.

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/96eaeea6207f3b6908f04f14920b196d06e84de0/_protected/app/Bootstrap.php#L131

**Comment by pH-7** [comment]
This is a single-line comment. The asterisk has no consequence on it. No worries, there is no bug in there :)

Thanks anyway!

**Comment by rondlite** [comment]
ok, it must be my shell and sublime since the coloring says the next block is comment due to the /*
