### ISSUE TITLE
File Location to remove Paypal & Card and Add new Payment method Image

### ISSUE THREAD

**Issue by abuaslad** [pH7Software/pH7-Social-Dating-CMS#594]
![payment-location](https://user-images.githubusercontent.com/53337420/61990394-959c3400-b05d-11e9-8527-14981f63686f.jpg)

Please help me to get the file location to remove Paypal and Card button from front end and back-end also.
Add another payment gateway image from front-end and back-end also as shown in attached image.

**Comment by pH-7** [comment]
Hi @abuaslad 🎉

The PayPal button in the view is located here: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/8a5eceaf111daac5b3537e79b953d37b0fc8d96c/_protected/app/system/modules/payment/views/base/tpl/main/pay.tpl#L31-L35

Finally, the payment gateway buttons are generated in this PHP class: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/payment/inc/class/design/PaymentDesign.php


Hope this helps! 🚀

Good luck! 😊

**Comment by pH-7** [comment]
P.S. concerning the PayPal gateway, you can simply disable it through the Admin Panel.
Admin -> Mod -> Billing -> Gateways Configuration -> Paypal Enabled, and set it to "Disable".

**Comment by pH-7** [comment]
Let me know if it helped @abuaslad, so I know if this issue can be closed. Thanks :)

**Comment by abuaslad** [comment]
Thanks.....Issue has been resolved!!! :)

**Comment by pH-7** [comment]
Awesome @abuaslad 🎉

I wish you all the best then!! 🚀
