### ISSUE TITLE
addfakeprofiles not generating profiles

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#596]
When using Add Fake profiles, I get a green bar with amount of users added.
However, nothing is added.
Checking console/network shows addfakeprofiles (cancelled) in red.
No error in apache log. 

The bulk version does work, however they are from random countries even when I specify a country.

What could I be doing wrong

**Comment by polynamaude** [comment]
@rondlite Could you please either give me more explanation on what you called "Checking console / network shows addfakeprofiles (cancelled) in red" ?

You can always use phpMyAdmin to bulk modify your profiles to make then the country you want.

**Comment by rondlite** [comment]
I mean the developer console in chrome under F12, section Network. The 2nd request to addfakeuserprofiles gets cancelled (no status code, no 200,no 404, just cancelled)

I don't use phpMyAdmin, and understand how to bulk change countries, however those towns are not in these countries. 
I can goto randomuser.me myself and copy paste all the details but that was not the intention here.

**Comment by polynamaude** [comment]
@rondlite I'm going to make a second and last try.
If you'd like to help then we need to know what you are using as a system.
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Could you also take a screenshot so I can see exactly the situation.

**Comment by polynamaude** [comment]
@rondlite If you want to write a better Fake Profile generator that does take in consideration city then we'll be more than happy to merge it into the pH7CMS source code.

**Comment by rondlite** [comment]
Problem was in the profile checker, just before insert in database.
I commented it, and now it works. Will have a look at the function to see why  it fails.

**Comment by pH-7** [comment]
Hi @rondlite 
Sorry, just to see your message know. Glad to hear you found the problem! I just did some changes to give error messages in case it fails, otherwise, it's confusing like what you got with the success message and no generated users.

**Comment by pH-7** [comment]
@rondlite Is it this function you commented? https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php#L184


Maybe, the API gave wrong/invalid email addresses and so `$this->oValidate->email($sEmail) ` was returning FALSE.
...Or maybe, all emails generated by RandomUser.me already existed in your database, and so `$this->oExistsModel->email($sEmail)` returns FALSE...?

**Comment by rondlite** [comment]
It indeed is the function I commented.
The database had no members and I tried several times (about 10 times), so suspect it to be something else.
Will try again and trace what happens..  when commenting the function, all goes well and got no odd email addresses in my db.

**Comment by pH-7** [comment]
Hey @rondlite 
I just found the reason for this. The bug was introduced in v15.1.7.
Just remove the `@example.com` from the _protected/app/configs/banned/email.txt file https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/ba388c926dbc9c17964606ba6d933ac5a4270c32

Thanks again for pointing it out :)

**Comment by rondlite** [comment]
That makes a lot of sense. ty
