### ISSUE TITLE
Warning: DOMDocument::loadXML() [domdocument.loadxml]: Extra content at the end of the document in Entity, line: 3 in /var/www/***/public/_protected/framework/Mvc/Router/Uri.class.php on line 67 

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#597]
Apache2
PHP7.2
Dedicated Debian 9
Chrome

I get this error on top of splash, in production mode I get on cached page and not on reload.
Development mode gives it at all times on top of splash page.

**Comment by rondlite** [comment]
Ah, this is on all pages, but on other pages hidden behind top menu

**Comment by rondlite** [comment]
the only content in $sContents is "</routes>"

**Comment by rondlite** [comment]
ok, this was caused by i18n and missing es.xml routes..

**Comment by polynamaude** [comment]
@rondlite Hi !
Great, can I consider it's solved ?
If so, I'll create a page in the documentation explaining this type of error and that it's related to missing language.

Or maybe I'm not getting right what you said ?

Thanks for reporting.

**Comment by rondlite** [comment]
It is right, the doc should state to add/copy the lang.xml file..
