### ISSUE TITLE
User image

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#598]
Can't quickly find how to get the user image in script, can you please point me in the right direction?

**Comment by polynamaude** [comment]
@rondlite Can you explain a bit more what you mean ?

**Comment by polynamaude** [comment]
@rondlite Do you mean the entry point for image upload in the script ?

**Comment by rondlite** [comment]
Sorry I overlooked since was checking profile without image (something messed with my head obviously) .. 
Was looking for this:
```
     $oUserModel = new UserCoreModel;
     $oUser = $oUserModel->readProfile($this->session->get('member_id'));
     $avatar=$oUser->avatar;

```     
There must be routine already converting this to /data/system/modules/user/avatar/img/username/6-size.jpg which is what I am looking for now

**Comment by rondlite** [comment]
Ok.. found what I needed... 

Was getUserAvatar

Don't want to re-invent wheel so takes a bit longer sometimes ⏲
