### ISSUE TITLE
Some help needed with routing

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#600]
Trying to add an extra page which I want under the payments module.
I created tpl for it in the tpl folder of the module.
Next step would be edit routes/en.xml, I presumed.. 

However there is only payment/edit/   as route in there.

Am I overlooking another place/way to add route?

**Comment by rondlite** [comment]
figured it out, was at controller level

**Comment by Undefined-Variables** [comment]
Sorry missed this question and could have answered too.
