### ISSUE TITLE
Upload logo removes alpha

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#601]
This was posted before #417 and #411
When I download the heart form DateLove and re-upload it as my logo, it gets a black background.
Same result with indexed png that has alpha.

Something is done to the image on upload most likely.

**Comment by rondlite** [comment]
Can confirm it happens on upload, uploading the same image over FTP and it has alpha mask.

**Comment by pH-7** [comment]
> Can confirm it happens on upload, uploading the same image over FTP and it has alpha mask.

If you upload (replace) your logo manually through FTP (with the correct size), you shouldn't have this issue anymore.

Try to upload it to `/templates/themes/base/img/logo.png` (please change `base` to the template name you use such as `datelove`, `zendate`, `cartoon`).

Then, don't forget to clear the cache. Admin Panel -> Tool -> Caches -> Caches Manager -> Static Files.
And your Web browser's cache.

Visit http://YOUR-URL.com/templates/themes/base/img/logo.png?v=123 (again, change `base` to the template name you currently use such as `datelove`, `zendate`, `cartoon`).
And check if the new logo looks good.

Hopefully, this will help! 🎉 Good luck!

**Comment by rondlite** [comment]
> uploading the same image over FTP and it has alpha mask.

I figured this already, only posted so you know it does not work from the backend.

**Comment by pH-7** [comment]
I will soon publish a patch to fix this issue with transparent images and GD.
It should be released in the v15.1.8 version.
