### ISSUE TITLE
Remove and Update Home Page Heading and Footer Links

### ISSUE THREAD

**Issue by abuaslad** [pH7Software/pH7-Social-Dating-CMS#605]
**Issue 1:**
I am unable to find the location of following heading present in admin section or which file to update it on homepage:

**🚀 Meet amazing people near Mumbai! 🎉**

Especially I am looking to change **Mumbai** but I am unable to find anywhere. 

**Issue 2**

I am unable to find Footer file to update following homepage footer links:

About Nookors | Help | Newsletter | Invite | Site Map

From where I can change it i.e admin or Footer file

**Issue 3**

Home Page is not SEO Friendly:

Heading Tag H1, H2, H3 are not placed properly:
H1 - 2 Times => Wrong SEO practice
H2 - 🚀  Meet amazing people near Mumbai! 🎉  =>Wrong  Place

Please let us know from where we can change Heading of Home Page.

Website:- http://www.nookors.in/
![nookers-home 1](https://user-images.githubusercontent.com/53337420/62438928-4cd43180-b767-11e9-9da3-20054db3e768.jpg)

**Comment by Undefined-Variables** [comment]
The word Mumbai is a variable! This variable is determined by the current users IP address location so if the user was in Madrid it would say Madrid not Mumbai. 

The links are found in the themes folder /public/templates/themes/base/tpl/bottom_menu.inc.tpl 

But again these are not hard coded words they are variables and to change them is not that simple, you will have to make changes in many places or your site will simply break! 

The pages are not hard to find if you have a good text editor that has a search function (that's my tip of the day)

**Comment by polynamaude** [comment]
@abuaslad 

Here's some link for more information...

https://ph7cms.com/doc/

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-edit-the-Terms,-Privacy,-Legal-Notice,-About-Us-pages%3F

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-remove-the-left-link-in-the-footer-of-the-site%3F

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

The last one is pretty important, unless you feel like getting on the ignore list.

The source code is well commented so shouldn't be too hard.
If you want to change to name of the city to a static one, you simply have to edit the main controller and set the variable to a static string. That's pretty easy and fool proof.

Regarding what you consider as SEO acceptable practice, feel free to change it suiting your own needs. That's the goal of GPL and this is not meant to be a universal, out-of-box solution. Unless you still believe in Santa Claus.

You'd be nice if you could give a star on gitHub and / or make a nice review on Sourceforge.
<img width="1030" alt="star-repo" src="https://user-images.githubusercontent.com/21186871/62439780-27213b00-b71b-11e9-875d-88185d003c4d.png">

**Comment by Undefined-Variables** [comment]
You never asked me to give you a star!!!

**Comment by polynamaude** [comment]
@Undefined-Variables You mind just keeping quiet when needed ? If you are waiting to get a real banned, then you are getting pretty close. Get it ?

**Comment by abuaslad** [comment]
> The source code is well commented so shouldn't be too hard.
> If you want to change to name of the city to a static one, you simply have to edit the main controller and set the variable to a static string. That's pretty easy and fool proof.

@polynamaude 
From which file I will get the 

> Location Variable

Please help me I am tired of finding it.

IP based location changing Variable is not working. Its is BUG. Need to resolve it because I have checked with many different proxy site of US, UK and many other country but everywhere it is showing MUMBAI.

I want to remove following heading permanently until BUG is not resolved permanently.

🚀 Meet amazing people near Mumbai! 🎉

**Comment by polynamaude** [comment]
@abuaslad Use **_fgrep_** to search inside the files. You can use this tool to find any type of string.

**Comment by polynamaude** [comment]
@abuaslad Nothing prevent you from completely removing the line if you prefer.

**Comment by Undefined-Variables** [comment]
> > The source code is well commented so shouldn't be too hard.
> > If you want to change to name of the city to a static one, you simply have to edit the main controller and set the variable to a static string. That's pretty easy and fool proof.
> 
> @polynamaude
> From which file I will get the
> 
> > Location Variable
> 
> Please help me I am tired of finding it.
> 
> IP based location changing Variable is not working. Its is BUG. Need to resolve it because I have checked with many different proxy site of US, UK and many other country but everywhere it is showing MUMBAI.
> 
> I want to remove following heading permanently until BUG is not resolved permanently.
> 
> 🚀 Meet amazing people near Mumbai! 🎉

Its not a bug it works for me! the file you are looking for is here

_protected/app/system/user/views/base/tpl/main/user_promo_block.inc.tpl

all the pages are found here

**Comment by abuaslad** [comment]
Thanks @Undefined-Variables 

Finally I have removed  it permanently from following  file location:
_protected/app/system/modules/user/views/base/tpl/main/user_promo_block.inc.tpl

Thanks a lot....
