### ISSUE TITLE
Please enter a correct phone number with area code

### ISSUE THREAD

**Issue by abuaslad** [pH7Software/pH7-Social-Dating-CMS#607]
What is the format to add Phone no in India for user profile.

I am adding following format but it showing error:

+91-9100000000

Getting following error:

> 
Please enter a correct phone number with area code

**Comment by polynamaude** [comment]
Take off your dash and plus sign. Give this a try

**Comment by pH-7** [comment]
Hi @abuaslad 
How are you?

The phone RegEx prior to pH7Builder v15.1.8 is `(\+|00)[0-9]{1,3}[0-9]{5,14}(x.+)?`
Since v15.1.8, the calling area code is optional. So, `(\+|00)?[0-9]{1,3}[0-9]{5,14}(x.+)?`

You can change the RegEx pattern in your config file (`_protected/app/configs/config.ini`; Line 48).

Hope this helps! 🎉

**Comment by pH-7** [comment]
> Take off your dash and plus sign. Give this a try

Yes, the dash is definitely causing a problem there. 
@abuaslad will have to update the RegEx in his `_protected/app/configs/config.ini` file in order to allow it.

**Comment by pH-7** [comment]
FYI, I posted a similar issue, which might be useful as well here: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/282#issuecomment-418605253

**Comment by Undefined-Variables** [comment]
Although I didnt include India, this is what I was trying to address in the pull request I made. My example included United States, United Kingdom, France and Spain. I couldn't include anymore locations simply due to being unable to add the correct language translation. I only studied french and Spanish in school!

**Comment by polynamaude** [comment]
@Undefined-Variables This type of validation should be front-side validated. The constraint validation when inserting in the database being something different.

**Comment by Undefined-Variables** [comment]
Okay fair enough! Maybe I will try again soon I’m not well at the moment,

**Comment by abuaslad** [comment]
Thanks everyone for suggestion:
I have tried following FORMAT of mobile no. It is working
0091XXXXXXXX
i.e - 009112345678

According to my suggestion, there should be no condition placed on Phone section because we need this information. User should not frustrate while adding their phone no or we can provide phone no hint below the text box.

**Comment by Undefined-Variables** [comment]
> Thanks everyone for suggestion:
> I have tried following FORMAT of mobile no. It is working
> 0091XXXXXXXX
> i.e - 009112345678
> 
> According to my suggestion, there should be no condition placed on Phone section because we need this information. User should not frustrate while adding their phone no or we can provide phone no hint below the text box.

You need to go to the file in /_protected/app/configs/config.ini and change the formula of the regex standard expression, if you don't understand what that means this software is beyond your capability!

**Comment by Undefined-Variables** [comment]
Replace this in /_protected/app/configs/config.ini

        phone.pattern = "(\+|00)[0-9]{1,3}[0-9]{5,14}(x.+)?"

With this 

         phone.pattern = "^[0][1-9]\d{12}$|^[1-9]\d{12}$"

This allows the phone number to be 12 digits only, now you could get more specific like only allowing the number to start with a zero or must start with 0091 all you have to do is change the rules in this expression

**Comment by pH-7** [comment]
Looks you found the correct RegEx by now @abuaslad 🎉

**Comment by pH-7** [comment]
By the way, @abuaslad, if you appreciate the software and the hard work to develop it, reviewing the software at https://sourceforge.net/projects/ph7socialdating/ will help a lot! (it takes 1 minute to create an account). Thanks very much in advance @abuaslad
