### ISSUE TITLE
Add banners

### ISSUE THREAD

**Issue by simon1967** [pH7Software/pH7-Social-Dating-CMS#608]
Hope this is in the correct place The add banner panel only has one add banner in it and it had a set.
Please how do i correct this and put the add banners back so i can use more 
Thanks

**Comment by simon1967** [comment]
So what i am saying is I have deleted all the banners and now I need them back, Please bare with me as I am just learning code, So what i am asking is there a file i can swap to put the banners back please..Thankyou

**Comment by polynamaude** [comment]
@simon1967 Hi !
First of all, we are all volunteers here so there's no need to ask over many time the same question with the hope of pushing us to answer. At most, you'll win a **_ignore_** on the long run.

Great to see you have interest in the software.

All the data that are fed to the system during the installation are mostly inside the **__install/data/sql/MySQL/pH7_Core.sql_** file.

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql

If what you did was to erase the banners information from the administration panel then you can simply copy back the part you'll find in the file above.

You can always use a tool like **fgrep** to search inside the repository for specific string when you are searching something.

If this wasn't you question then be more specific.

This is not a programming sandbox and we don't teach programming. There's level of knowledge and type of project adapted to learning. If this is your case then maybe you shall look somewhere else or contact someone on a platform like UpWork.

**Comment by simon1967** [comment]
Thank you for your help
Simon

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
