### ISSUE TITLE
Fix video embed

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#610]
Fixing the video embed is as easy as changing the  youtube url to /embed and add it to the list of regex too.. 

Now ppl get offered a SWF for download

**Comment by pH-7** [comment]
Not sure to understand @rondlite 
Could you be more specific?
And with what video platform do you get this?

**Comment by Undefined-Variables** [comment]
@rondlite How are your users downloading the YouTube video? I really don't understand :~/

**Comment by rondlite** [comment]
in the youtube class there is:

const PLAYER_URL = 'https://youtube.com/v/';

That causes the swf download since it is not the embed url.
Is known problem from years ago when Youtube changed the url
