### ISSUE TITLE
Whoops big no-no

### ISSUE THREAD

**Issue by rondlite** [pH7Software/pH7-Social-Dating-CMS#611]
```
$aMeta = [
    'title' => Core::SOFTWARE_NAME . ' | ' . Core::SOFTWARE_COMPANY,
    'description' => Core::SOFTWARE_DESCRIPTION,
];
?>
<!-- Begin Header -->
<?php $oDesign->usefulHtmlHeader($aMeta, true); ?>
<!-- End Header -->
```

This is what you are looking for if you find your site being called different in various search engines. 
Terrible SEO practice or intentional grey hat.

**Comment by Undefined-Variables** [comment]
LOL

**Comment by pH-7** [comment]
Do you have an internal server error somewhere...? It should give 500 HTTP code status anyway.. This shouldn't be crawled by search engines.
 
On what page of your website do you get this? Have you blocked your website for USA IPs (which is Googlebot one)?

**Comment by rondlite** [comment]
I didn't get this on any page, I got this when checking a Yandex. 
The title of my site is as described in above code.
I take it that this goes for error 500 as well.
Even if I block my site for any search engine, that doesn't make that search engine a FFA backlink engine.

**Comment by Undefined-Variables** [comment]
@rondlite you about? Do me favour please drop me an email... I want to ask you something but its private! Nothing to worry about, nothing to do with this project. I just want your opinion on something

admin@totalbutterflies.com
