### ISSUE TITLE
Live webcam chat is almost impossible for a large user base?

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#612]
I have some concerns regarding offering a live webcam chat service, this is made to look doable by the way it has been presented though out this project and is even somewhat suggested that it is included within this software, truth is that there is no code to support this feature. There is simply a blank page asking for someone to develop it. This has not stopped you from advertising it as a feature and it is even been put into the meta tags as if its working...

The issue is not implementing it, this is fairly straight forward, it requires a LOT of dependencies and   a small miracle to get these different parts to work together smoothly but it can be done, I've had a demo running a few days ago. 

The problem comes down to bandwidth and the number of participants you can realistically hope to achieve. Here is a few lines that explain the situation better than I could ever hope to

`HTTP Web and RTMP Streaming on same server: required for solutions that involve conversion of video archives, streaming of uploaded videos, scheduling playlists, restreaming IP cameras and similar advanced features that require both web and rtmp to have access to certain files.
RTMFP hosting (optional, for enabling P2P connectivity) - Not recommended for most projects.
Get a free rtmfp address by registering with Adobe Cirrus .Using RTMFP will not replace RTMP requirements (RTMP hosting is always required).
P2P is often used on free chat roulette type sites but is not as reliable as streaming trough the RTMP relay server. P2P video streaming is great for users in same network or having dedicated IP address and high speed upload but will fail or produce huge latency for most users with regular connections.
Clean Domain Nameservers
If you use a name server optimizer (ex. CloudFlare) certain protocols, ports and services may not work with default settings, including RTMP. You can use rtmp addresses based on IP to fix this or configure exceptions for RTMP (TCP port 1935). 
Additionally, such services may alter output or force cache for scripts that communicate with flash applications, which can break parameters and functionality.
Session Control requires streaming server to make requests to web server and these are disabled by default CloudFlare setup. 
Other malfunctions from such services can occur in form of timeouts, restrictions on uploads, disabling certain requests or site features, showing site as offline when is online, showing outdated output or wrong formats for adaptive interfaces, extra latency on requests (including visible delays for interactions and chat).
Such services are designed for static content and often cause malfunctions for live content sites, when using default plans and settings. 
VideoWhisper recommends against using such services that add an extra point of failure, extra latency and malfunctions for live content features.
WebRTC - Some solutions implement streaming using WebRTC protocol for compatibility with HTML5 browsers that lack Flash plugin support. WebRTC streaming is done trough media server, as relay, for reliability and scalability needed for these solutions.
Conventional out-of-the-box WebRTC solutions require each client to establish and maintain separate connections with every other participant in a complicated network where the bandwidth load increases exponentially as each additional participant is added. Broadcasters need server grade connections to live stream to multiple users and using a regular home ADSL connection (that has has higher download and bigger upload) causes real issues. These solutions use the powerful streaming server as WebRTC node to overcome scalability and reliability limitations.
For most integrations that involve video recording and archiving, HTTP and RTMP must be hosted on same physical server so web scripts have access to the video files saved by rtmp server for management and conversion.

Server Software / Hosting F.A.Q.

Can I use a different RTMP streaming server type with Videowhisper solutions?
Solutions involve RTMP side functionality (managing interactions, stream info, session control, chat, users list) that is only available as extra module for listed servers. 
Most advanced features like RTMP Session Control required to manage other stream sources and transcodings are only available for Wowza. 
Some other streaming servers may allow implementing such rtmp side features but that involves custom development.
Can I run solution on current web host that does not meet the requirements?
Only if using a remote RTMP hosting service for plain videochat and live streaming functionality based on VideoWhisper web apps configured to connect to remote RTMP server.
For most advanced features site needs to be fully deployed on a compatible host that includes all requirements. Some features require specific tools on web hosting server and some other features require the web scripts to interact with files (videos, streaming configuration files) on streaming server.
Is there any other option to run solution with advanced features, other than moving my existing site to compatible hosting?
You can point a subdomain using A records to a compatible hosting plan where solution can be deployed. In example video.yoursite.com . You can then link or embed features from existing site (live streams, video conferencing rooms).
Why not use P2P?
As standard WebRTC implementations utilize peering networks, there still has to be a nearby node to help distribute the stream to other local hosts. Peering across a global network can be incredibly difficult.
Broadcasters would need server grade connections to live stream to multiple users and using a regular home ADSL connection (that has has higher download and bigger upload) causes real issues.
While testing with 2 or few users works fine in demos and small load trials, WebRTC limits often show in production mode: becomes unusable when many users are watching same HD stream and broadcaster connection is regular.
All startups hope their streaming applications will become a huge success, with thousands of viewers watching. A performer streaming a full hd video at 6-8 Mbps directly to 100 viewers in various world locations would require up to 600-800Mbps upload connection which is unlikely to achieve for a retail home connection. A streaming server in a well connected datacenter will do the job. Above average home ADSL connections have under 100Mbps upload allowing streaming such video to a maximum of 12 users.`

As you can see unless you own a server farm like Facebook the most you can ever hope to achieve is 12 users online at one time and that is at the cost of your website having a melt down! For 100 users you need at least 600-800Mbps upload speed and that is some serious connection, the most you can get here is 200Mbps and thats download so upload would be closer to 70Mbps!!!  

Is there something I am missing here because this seems like it is impossible unless you are one of the big players in this field! Is this why its not been coded yet?

**Comment by rondlite** [comment]
i got an idea.. hook up html5chat as the example shows and you get video chat, chatroulette and all this for 1000s of ppl.. 
it is in the script for those that look.

**Comment by polynamaude** [comment]
@rondlite Hey Ron ! What a genius are you... Ain't you telling me here that we have a world of possibility in front of us ?

Am I also discovering that software development is a bit more complicated than just using library and trying to make everything get together ? Something like a need of planning and learning before doing ?

**Comment by Undefined-Variables** [comment]
@polynamaude hello mate, can I pick your brain for two minutes? I don't want stress I am sitting in a hospital, been here with laptop a lot over last few days and had a lot of time to code, I have been putting a new template together, I will push it once its ready, its not far off, just got one last bug to fix.

I have used Cloud flares popper.js script to control various features in the template, everything works except on one page. The meet-people page, it seems to be clashing with tiptip.js. My main goal here was to create an entire new layout to Ph7cms but with the following restrictions. 

I have ONLY touched the /templates/ folder and nothing else on the latest version of the software, I have done it in such a way that any user can simply replace that one folder and still be able to switch between the default, love and my new one freely and not need to make any other changes anywhere else. 

I am quite happy with what I have managed and I have written a  README and I will push it to the main repository once ready, I want to give something back to you guys and all I've been doing for last 4days is sitting here. I think even you will be impressed.

The bug is not a major problem but it stops it from being perfect. it stops the menus from reacting and I think the reason is the word pop is being picked up by both scripts. Have you ever heard of this problem?

**Comment by Undefined-Variables** [comment]
Yes that is what I ment a pull request! I was just doing to put it in my repository as a template for the code. Is that allowed? I wasn't trying to annoy anyone I was just bored and started it as something to do as couldn't access my server from here so just cloned a new copy to a vm. 

I have sent cloud flaire an email but they are known for taking weeks to reply as they almost own the internet now and always so busy! Just thought it was worth asking. No worries thanks for the answer

**Comment by Undefined-Variables** [comment]
Ok sounds good, I wasn't sure and didn't want to upset anyone any further, thank you, despite everything I can see you are a decent person and I more than appreciate your time.

**Comment by Undefined-Variables** [comment]
I have and it all works the same apart from it looses all the functions that make it what it is. It turns back to a static navigation system. the script i used is this 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>`

but think it clashes with /templates/themes/base/css/js/jquery/tipTip.js

Because @pH-7 PH-7 makes this note in his code 

`// "bIsDataPopup" checks that only for links that do not possess the attribute "data-popup", otherwise not the title of the popup (colorbox) cannot appear because of the plugin (tipTip)`

I find myself getting lost on JavaScript and just seems strange that its only one page! must be something to do with the images on that page.

**Comment by Undefined-Variables** [comment]
I have been trying to learn it, I joined HackerOne and have been reading the courses on javascript.
