### ISSUE TITLE
Database issue any ideas how this happened?

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#613]
I'm not saying this is connected to the software but my database has been seriously messed up, look at the screen shot, it won't accept passwords and only way I can access it is via CMD line...

Its not a problem I have a back up but I have not touched it for hours! maybe 4hrs or so. 

![Screenshot (1)](https://user-images.githubusercontent.com/52648055/63393183-c6982c00-c3b1-11e9-92ff-2a108e7f795d.png)

**Comment by Undefined-Variables** [comment]
I dont even know who DABZL869412 is

**Comment by polynamaude** [comment]
@Undefined-Variables Why don't you look on a support forum for database ? As you say, it's not related to this software.

https://stackoverflow.com/

**Comment by Undefined-Variables** [comment]
Im not bothered I will uninstall and install again but is this from Ph7CMS? I have not seen this code before 
![Screenshot (2)](https://user-images.githubusercontent.com/52648055/63393541-7326dd80-c3b3-11e9-8efa-c409f1eb4402.png)

**Comment by Undefined-Variables** [comment]
its all over the cmd output

**Comment by polynamaude** [comment]
@Undefined-Variables No it's because of a Youtube JavaScript hack that steals your information. You've got hacked my friend.

**Comment by Undefined-Variables** [comment]
yeah! Okay shame there is fuck all worth hacking really aint it! 

I ask a serious Q and get this again! I am only trying to prevent it  repeating...

**Comment by Undefined-Variables** [comment]
Good to see you have a sense of hummer though

**Comment by polynamaude** [comment]
@Undefined-Variables Maybe you are not asking at the good place ? The only forum you seem to know is here.
The word you look for is called **humor** and what I'm doing is called **sarcasm**.

**Comment by Undefined-Variables** [comment]
No I am part of a few forums but as I am working on this and its somewhat related this seems like the logical place to ask! But I am not making huge guessing leaps anymore so that's progress! 

Yes I was being sarcastic! Sorry thats not normally like me! Trying to make sense of this page of randomness, it seems to be some sort of codex, it refers to 

`clsid:D27CDB6E-AE6D-11cf-96B8-444553540000`

This is a flash embedded applet if my memory serves me right! Dont you think js just looks dodgy? why would it be so encoded? Like

 `{var a,b,c,d,e,f,g=arguments[0]||{},h=1,i=arguments.length,j=!1;for("boolean"==typeof g&&(j=g,g=arguments[h]||{},h++),"object"==typeof g||n.isFunction(g)||(g={}),h===i&&(g`   

Just looks like its hiding something don't it. Why jump though the hole alphabet defining to and throw if it is legit? This is why is scared me last time but to be honest I am past caring!
