### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by byyz** [pH7Software/pH7-Social-Dating-CMS#618]
I have been looking trough the Issues, open and closed but didnt find an answer for my question. Is it possible to make quick search option have all countries and no cities? I have been looking here protected/app/system/core/forms/SearchUserCoreForm.php If somebody could point me in the right direction

**Comment by polynamaude** [comment]
@byyz Like I wrote as an answer in many issues. You will have to code such functionality by yourself.
I don't have time and don't want to start this either so no I won't write down all the step to do so.

If you have a specific question regarding the CMS then we'll be more than happy to answer.

You can find someone on Upwork to do the job...

**Comment by byyz** [comment]
@polynamaude I was not asking you to do it for me. Just wanted be pointed in the right direction. Maybe it was as easy as adding gender to the forms in previous question :) but I have to start learning PHP I think

**Comment by Undefined-Variables** [comment]
@byyz  What are you trying to do?  You  have to understand how the code works,  it is set out using the MVC pattern, this stands for Model, View, Controller. 

Until you understand how it works you will not be able to add anything. 

The page you see is the View. This is html and in the html you will see variables being called using tags that look like this `{$is_some_thing}`  that variable is defined in its controller and if the data required is in the database the controller will use the corresponding model to fetch the data.

 So you can't just make a single change in one file you have to make changes in all the files involved in the process. With forms this will also include validation of user supplied input.

 I think you should look at learning the basics of php first.

**Comment by polynamaude** [comment]
@Undefined-Variables You shall apply this yourself.

**Comment by polynamaude** [comment]
@byyz What you are trying to do is not related to the MVC pattern whatsoever.

It just require some change (around 10 lines of code) in the processing of the query.

I can give you some guidance but you'll have to wait a bit of time because I'll have to dive in the code and take a deeper look.

I'm busy at work for the next week but I'll try to take time this weekend.

**Comment by Undefined-Variables** [comment]
That is what I have been doing, I know the basics of PHP and can code quite well in the classic way, as in  having the php and html all on a single script, it was the mvc I was finding difficult. 

Sorry I couldn't look at the page he was talking about, I wiped everything this morning so assumed he had found the view.

**Comment by byyz** [comment]
I totally agree with you. I need to understand the basic of PHP. I worked a little with html in 2003. Thats my level. I am the first to admit it aint much but we all have to learn and start somewhere. I appreciate all your help so far
@polynamaude thanks in advance. I will try learn this php. I have no interest in running a dating site without knowing at least a little about what is going on

**Comment by Undefined-Variables** [comment]
> I can give you some guidance but you'll have to wait a bit of time because I'll have to dive in the code and take a deeper look.
> 
> I'm busy at work for the next week but I'll try to take time this weekend.

You feel alright? That has to be the nicest comment I've ever seen for your keyboard! @polynamaude

**Comment by Undefined-Variables** [comment]
@byyz Great answer!

**Comment by polynamaude** [comment]
@Undefined-Variables I wasn't talking to you.

**Comment by polynamaude** [comment]
I'm always happy to help out when people are respectful and this ain't the case for @Undefined-Variables . He only waste our time and don't even take time to read what we write. He doesn't understand what it means to be off topic or that there's a place for each type of questions.

**Comment by Undefined-Variables** [comment]
Yeah! I do understand and I read what you say but you are know where near as helpful or straight forward with me, you called me a liar and that REALLY pissed me off! I can't stand liars and if nothing else I will always be straight with you no matter how bad or the consequences so that properly offended me!

**Comment by byyz** [comment]
Pls don't fight here. Life is to short for that :) I'm here to learn and so far I have already learned a lot. 
I like to keep things simple and I'm kinda "if it ain't broke don't fix it" guy. So I will not look for many changes but I think there should be a difference in the options between quick and advanced search. Im planning to run my dating site international. That's why I would like to have the default settings for quick search is set to all countries and the Field city disabled, age set to 18-60 default, so the user only choose gender. That makes sense for me in a quick search.
