### ISSUE TITLE
Translation in spanish

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#619]
I have reviewed all the .po and .mo files and they are correct, however texts that are not translated appear on the front page.
The only way I could change these texts has been in the file \ _protected \ app \ system \ modules \ user \ forms \ joi but then the text changes to Spanish in all languages.

I am doing something wrong?

**Comment by polynamaude** [comment]
@aquaskualos It's possible some of the strings are static. You can add your own to the language file. Show me which one you are talking about.

**Comment by aquaskualos** [comment]
There are many words and strings that seem not to be defined in variables.
If you go to http://xcitame.com and start the user registration you will see that almost the entire area is without translation.
Even so, I don't lose my job, the script is impressive, I'm still investigating all the possibilities.
Thank you!!
(the review is already posted on sourceforge.net)

Jaume Ubach
652478601
[cracked-facebook-logo]<https://www.facebook.com/jaume.ubach.3>

De: Polyna-Maude R.-Summerside [mailto:notifications@github.com]
Enviado el: jueves, 22 de agosto de 2019 23:15
Para: pH7Software/pH7-Social-Dating-CMS
CC: aquaskualos; Mention
Asunto: Re: [pH7Software/pH7-Social-Dating-CMS] Translation in spanish (#619)


@aquaskualos<https://github.com/aquaskualos> It's possible some of the strings are static. You can add your own to the language file. Show me which one you are talking about.

**Comment by aquaskualos** [comment]
Uuuups !! I have responded to the email and my data and my phone number appear here now ... LOL

**Comment by aquaskualos** [comment]
There is also a problem with the names of the populations .. for example, Palamòs is displayed as Palamós!

This word appears in the file \ _protected \ framework \ geo \ ip \ geolite2-city.mmdb

**Comment by polynamaude** [comment]
@aquaskualos There may be a problem with some extended character. Concerning the name of cities, this is a external library named Geonames.

**Comment by aquaskualos** [comment]
If yes .. it is for special characters, and for coding. I'll see if I find how to fix it. It is not good to see rare characters on a website.

**Comment by aquaskualos** [comment]
No. Is ensught.
Too many mistakes and poor help.

**Comment by aquaskualos** [comment]
20 days after... For nothing. LOL
