### ISSUE TITLE
Advertiment adult redirect to porn page

### ISSUE THREAD

**Issue by aquaskualos** [pH7Software/pH7-Social-Dating-CMS#620]
If advertiment for aduts is on, redirect to porn page (only on mobile)

**Comment by pH-7** [comment]
Hi @aquaskualos!

Thanks for this!

Indeed, when you enable the Adult Disclaimer (which is disabled by default), it uses a third-party service and  it may give some kind of adult ads/redirection **as mentioned in the Settings Page**.

<img width="950" alt="screen_shot_2018-07-30_at_4_07_51_pm" src="https://user-images.githubusercontent.com/1325411/43402450-0b5edb38-9413-11e8-9b02-e498fe94d963.png">

You can always keep it disable, and use another adult disclaimer of your choice by adding its javascript code through Admin Panel -> Settings -> JavaScript

Hope it helps. And really sorry for any inconveniences
