### ISSUE TITLE
templates and defining variables globally.

### ISSUE THREAD

**Issue by The-Dragon-Queen** [pH7Software/pH7-Social-Dating-CMS#622]
Hello again. 

I have two really simple questions, so I thought asking them together would be best, if I am wrong please tell me and I will edit this one and post the second separately.

1. I would like to add a template .inc.tpl file to add to the existing LoveDate template but when I do the new file is rejected because its not defined. Where do I define the new file name so it will load with the others and not course a fatal error?

2. I need to make a few variables that are in the user controller global. How is the safest way to do this? I am sure I could manage to do it with $_SESSION but I am not confident this would be safe and secure. How would you recommend I go about this? 

Thank you. I have spent quite some time reading all the issues, updates and code you have written and I can see the amount of work and time spent supporting and updating. You should be proud of yourselves, I am blown away by your level of commitment and technical skill. Great script.

Is there somewhere I can write a review for you? I think that is the least I could do.

**Comment by polynamaude** [comment]
@The-Dragon-Queen I don't understand what you are saying here when you say that the file your tried to include is rejected because of not being defined. Could you either post **_log_** or **_stack trace_** ? Where did you put your new file and how did you include it in the template ?

For your other question, this question is a general programming question. You should ask on StackOverflow or another support forum.

You can make a review on Sourceforge and star on Github.

Thanks

**Comment by The-Dragon-Queen** [comment]
Sure I will explain in more detail, the template files for DateLove are located 

`templates/themes/datelove/tpl/`

these refer back to

`templates/themes/base/tpl/`

The core is exactly the same for all templates, the difference is the css and js files.  The files are parts
that make up the template for example bottom_menu.inc.tpl, top_menu.inc.tpl these contain the bones of the template engine. These in turn are brought together in the layout.tpl file (in the same directory) and each part is included using the following syntax `

`{main_include 'bottom_menu.inc.tpl'}`  

This is a template engine and works by converting back to native PHP in the framework (think its layout from top of my head), my problem comes when I add a new part, for example if I create a file called right_menu.inc.tpl and then include it in the layout.tpl in the correct way using 

`{main_include 'right_menu.inc.tpl'}`

When PHP tries to build the page I get a very long list of errors that trace back throw many framework controllers including 

`_protected\framework\Layout\Tpl\Engine\PH7Tpl`
`_protected\framework\Mvc`

And many more (I am at work on lunch right now, I will update with the output later) It basically says that the new part I've added is not defined and courses a fatal error. I need to know where the parts to the templates are defined and allowed to be included in the template.

Maybe I didn't express my second question properly, I will try again.

If I define some of the variables globally in the traditional manner using 

`$username = $_SESSION['user_name']; `

Will doing this with a handful of variables courses any unintended security problems in the preexisting code? I don't need basic coding guidance I need to know is there anything about the code as it stands that will create problems if I take this route? Only the person who wrote the code can answer this question with full conference.  

Thank you, I will update with the requested output later and of course I will right you a review.

**Comment by polynamaude** [comment]
@The-Dragon-Queen I didn't ask you to explain to me how the pH7CMS template engine work. This I already know. What I did ask you is simple....

Show me the error you get when you try to include your file into the template.

**Comment by polynamaude** [comment]
@The-Dragon-Queen There's no need to give me incomplete answer. You can simply wait until you have the time to do so.

**Comment by polynamaude** [comment]
@The-Dragon-Queen I will repeat myself (again), for your question regarding the uses of variables go ask this question on StackOverflow. It is not a question that ONLY THE PERSON WHO WROTE THIS FRAMEWORK CAN ANSWER but a general programming question.

**Comment by polynamaude** [comment]
@The-Dragon-Queen There's something we call override in Object Oriented design philosophy.
So at first it will check in the templates own folder, if the file is not found then it will look into the base folder.

If you get an error about something not defined, it's because you don't include the file properly. There's no such thing as a list of specific defined files that go into the template.

This is the base Controller object (**view** is called to display the template).

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Mvc/Controller/Controller.class.php

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/bb5776083eac6db84d93e245fed4205d1afc8eab/_protected/framework/Core/Core.class.php#L44

It extends the **core** class.

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Core/Core.class.php

You can see all of the syntax in the code here.
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Layout/Tpl/Engine/PH7Tpl/Syntax/Curly.class.php

The view property of your controller is set to a PH7Tpl object.

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php

**Comment by The-Dragon-Queen** [comment]
This is the output/trace.

Message:	/www/dpublic/templates/themes/datelove/tpl/left_menu.inc.tpl file does no exist.
File:	/www/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php
Line:	342
Trace:	

#0 /www/_protected/data/cache/pH7tpl_compile/user-dashboard_72f7e784aae67210e3db7284887274b5/base/mainlayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('left_menu.inc.t...', '/www/Publ...')
#1 /www/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/www/_pro...')
#2 /www/_protected/data/cache/pH7tpl_compile/dpublic_main/datelove/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/www/Publ...')
#3 /www/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/www/_pro...')
#4 /www/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/www/Publ...')
#5 /www/_protected/app/system/modules/user-dashboard/controllers/MainController.php(38): PH7\Framework\Mvc\Controller\Controller->output()
#6 [internal function]: PH7\MainController->index()
#7 /www/_protected/framework/Mvc/Router/FrontController.class.php(660): ReflectionMethod->invokeArgs(Object(PH7\MainController), Array)
#8 /www/_protected/framework/Mvc/Router/FrontController.class.php(618): PH7\Framework\Mvc\Router\FrontController->runController()
#9 /www/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter()
#10 /www/dpublic/index.php(46): PH7\Bootstrap->run()
#11 {main}

**Comment by The-Dragon-Queen** [comment]
The file has been included in the base/layout.tpl file as I explained yesterday:

            {main_include 'left_menu.inc.tpl'}

This is the correct way to include it into the template, the files already included are done in the same way and clearly they work.

Other things I have done:

I have traced back though the above files and all the files that are related to the above files to see if I could see where the problem is.  I have tried adding my new code to the end of an existing .inc.tpl file and it works but I don't want it to be part of what is already there, I need some separation so a new file is the only choice, I tried using the page_nav.inc.tpl file that is already there then searched the code and replaced every 

`{main_include 'page_nav.inc.tpl'}`

With 

`{{ $design->pagination($total_pages, $current_page) }}`

This works great but feels the wrong way to go about it and goes against what I was taught in school and want to fo this in the right way by adding a new .inc.tpl file. 

I sent Undefined an email asking him to help me, but he explained about his mum and advised me to open issue here!  

I have not just tried failed and opened a ticket I have put a lot of effort into finding a viable solution myself.

**Comment by The-Dragon-Queen** [comment]
![bitch](https://user-images.githubusercontent.com/53600116/63705952-2b2a0f80-c826-11e9-9314-51967fc0165d.jpg)

**Comment by The-Dragon-Queen** [comment]
Okay this final reply is the answer to the question for anyone else looking for this answer. 

To add a new .inc.tpl file to a template you need to add it to the template and to the base, for example if you want to add left_menu.inc.tpl to the DateLove template you need to add it to /templates/DateLove/tpl/left_menu.inc.tpl and also add it to /templates/base/tpl/left_menu.inc.tpl 

In the DateLove.inc.tpl add this 
`{def_main_auto_include}`

And write your code in the  /templates/base/tpl/left_menu.inc.tpl file. It will now load and be included in the template. 

I have been reading thousands of lines of code trying to figure this out and finally found what I was looking for buried deep in the code. This has been a long morning looking for the answer to this, as you can see the support here is as useful as a chocolate fireguard, so I have come back to share my findings in case someone else problem.

**Comment by The-Dragon-Queen** [comment]
@polynamaude Thank you for trying to help but please read the reply you type and think if it will come across as rude. I am not the only person who has said you are rude. When multiple people say the same thing there must be some truth to it.

**Comment by Undefined-Variables** [comment]
Glad you figured it out @The-Dragon-Queen. Sorry I couldn't help you earlier, I have had a really shit couple of days and just got home. Great work though 👍 

I see you have met @polynamaude she can be a little blunt at times but I think it comes from frustration, the questions she has to deal with would drive anyone to be this way! Catch up soon though promise.
