### ISSUE TITLE
Cron Problem #1

### ISSUE THREAD

**Issue by ghost** [pH7Software/pH7-Social-Dating-CMS#624]
I am using Plesk Web Host Edition and I can run crons and see the output immediately.

In Plesk I am able to: (i) run a command, (ii) fetch a URL, and (iii) run a PHP script.

When I 'run a command' this is the output: No such file or directory.

When I 'fetch a URL' this is the output:
Status: 403
Output:

<title>403 Forbidden</title>

You don't have permission to access /asset/cron/24h/Birthday/ on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

(the permissions for 24h & 96h are both set at 705 and tried 755 also).
When I 'run a PHP script' this is the output:
Could not open input file: https://mywebsite.co.uk/asset/cron/24h/Birthday/?secret_word=*******
When I put the URL into a browser there doesn't appear to be a problem:
24h shows 'cron has already been executed'
96h Database shows 'Deleted 0 temporary messages...OK! Optmizing tables...OK! Done! The Jobs Cron is working to complete successfully!'
96h General shows 'Chmod file... OK! Done! The Jobs Cron is working to complete successfully!'

I can only think this is a server issue.

Can anyone help?

**Comment by pH-7** [comment]
Hi @AndrePhP-tech 

Thanks for this!

> In Plesk I am able to: (i) run a command, (ii) fetch a URL, and (iii) run a PHP script.

It should be the option 2, " fetch a URL"


> When I 'run a PHP script' this is the output:
> Could not open input file: https://mywebsite.co.uk/asset/cron/24h/Birthday/?secret_word=*******

These cron jobs shouldn't be run by PHP, but by cURL. More information here: https://www.ph7cms.com/doc/en/cron


> When I 'fetch a URL' this is the output:
> Status: 403
> Output:
> <title>403 Forbidden</title>

**Apparently, something from your website (maybe the `.htaccess`...) blocks cURL to run the cron on your website, which gives back the 403 error.** Usually, for security reasons.

Can you ask your server to investigate this? And give them all the information you can find on this page?

A very similar issue was: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/182 Maybe it could help you or your web host...


Finally, some URLs that might be useful for you :)
- https://www.ph7cms.com/doc/en/cron
- https://www.ph7cms.com/doc/en/cron-list

**Comment by pH-7** [comment]
It should be something like below. Hopefully, this will help you or your web host:

---
crontab -e
```
0 0 * * *  GET "https://mywebsite.co.uk/asset/cron/24h/Birthday?secret_word=REPLACE_BY_YOUR_SECRET_WORD"
```

Hope it helps 💪

**Comment by pH-7** [comment]
> It should be something like below. Hopefully, this will help you or your web host:
> 
> crontab -e
> 
> ```
> 0 0 * * *  GET "https://mywebsite.co.uk/asset/cron/24h/Birthday?secret_word=REPLACE_BY_YOUR_SECRET_WORD"
> ```
> 
> Hope it helps 💪

@AndrePhP-tech Let me know if this is still an issue... Thanks!

**Comment by AndrePhP-tech** [comment]
Deleted user-agent 'curl' bad bot found in .htaccess file. All URLs ie birthday etc are now fetched however status still showing as 403 with output: 'This cron has already been executed'. Also no notification sent to my email address.
Can anyone shed some light?

**Comment by polynamaude** [comment]
@AndrePhP-tech It gives a 403 because the job was already done.

**Comment by AndrePhP-tech** [comment]
Thanks polynamaude. 
Should I still be notified when output shows 'cron has already been executed'?
I am running this through Plesk and want to be notified but I am not.

**Comment by polynamaude** [comment]
@polynamaude First of all, I'm not going to repeat again what I already wrote many time, this place is not an open bar for questions of all type. We answer to issues relating to problem with the pH7CMS. Yes we can sometime go over the edge and give some extra information to help in specific case.

That said, I don't have any instance of Plesk. I've used in the past Plesk and it's friend cPanel. Part of your question can be answered in a better way by the guys at your hosting or at Plesk.

You shouldn't get any error 403 saying the job was already done unless you run more than once in the specified period.

**Comment by AndrePhP-tech** [comment]
Firstly, @polynamaude - either be polite on here or don't bother! 
The webmail 403 cron error continues regardless of running it more than once in the specified period!
The 403 could also be related to a continued error log I have had since running Plesk which currently uses 2.4 (the syntax used in the .htaccess file I downloaded was 2.2)
The error shows: AH01797: client denied by server configuration: /var/www/vhosts/mywebsite.com/httpdocs/index.cgi/pl.
Plesk is aware of this problem and their resolution is to add a hashtag to all .htaccess files on the server (obtainable through SSH) before the directives containing the word 'deny'. However they do not advise regarding the .htaccess (2.2) file under httpdocs. 
Has anyone been in this situation and can shed some light.

**Comment by zeze6** [comment]
i had the same issue, it's misconfiguration in the htaccess file, i solved this issue by deleting everything in the htaccess file and put the following code
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```
this will fix your cron issue and other issues like 500 error but it might cause other problems, try it..
the script has many bugs.or misconfiguration

**Comment by Undefined-Variables** [comment]
Think you will find most errors you are getting are down to your server configuration and not the script! It’s not the developers fault if you are unable to configure a basic web server and blaming his work to explain your own short comings is not the right pasta to take!
