### ISSUE TITLE
Support for RTL languages?

### ISSUE THREAD

**Issue by Keemaaa** [pH7Software/pH7-Social-Dating-CMS#625]
Hello,
I'd like to know if the script supports RTL languages like Arabic?
Thanks

**Comment by pH-7** [comment]
Hi @Keemaaa 
Thanks very much for the suggestion!
Unfortunately, at the moment, Right to Left languages aren't supported.
If any developers here are interested to implement it, I would be more than happy to review their PR 😄

**Comment by Keemaaa** [comment]
Hi @pH-7 
Thanks for the reply.
Can you give me more information like certain files to work on "other than translation files which I already working on" like CSS or whatever...
I will get some assistance from a developer and this will make it easier for us.

Thanks in advance,

**Comment by daredevil120** [comment]
Hi, 
i need a German language for pH7Software
