### ISSUE TITLE
I am not able to make change in the home page

### ISSUE THREAD

**Issue by AtharvaNikam** [pH7Software/pH7-Social-Dating-CMS#630]
![Capture](https://user-images.githubusercontent.com/54904025/64270616-7a282100-cf59-11e9-8e4f-eeabc71a1092.JPG)

**Comment by AtharvaNikam** [comment]
I can't able to remove the city name Hugo

**Comment by pH-7** [comment]
Hi @AtharvaNikam!

This one should help you https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/259#issuecomment-410524511 🚀

> Yes, you can do it (a little) through your admin panel -> Setting -> Meta Tags/Homepage.
> 
> https://ph7cms.com/doc/en/how-to-change-promo-texts-on-homepage
> 
> And add CSS/JS code; Admin -> Setting -> CSS Style / JavaScript
> 
> Finally, if you really want to change things deeper, you can edit [~/_protected/app/system/modules/user/views/base/tpl/main/index.guest_splash.inc.tpl](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/views/base/tpl/main/index.guest_splash.inc.tpl) file.
