### ISSUE TITLE
Hide from public view:Make user contents visible only for logged in users

### ISSUE THREAD

**Issue by rthuey** [pH7Software/pH7-Social-Dating-CMS#634]
Hello. It is my understanding that one can hide modules like forum from public view. I would like that non members who visit the site not see the conversations. I know they can not add. I don’t want them to even see the threads. 

What folder would I look in to change the public to private settings for the different modules?

Please and thank you for any direction you can give

**Comment by pH-7** [comment]
Hi @rthuey!

The easiest modification would allow you to have all profile pages private (only for "logged in" members).

In file `_protected/app/includes/classes/ProfileBaseController.php`
Change: 
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/90b7ad361287ceb00b0d90d8c0c3a13b041a2048/_protected/app/includes/classes/ProfileBaseController.php#L114
```php
if (!$this->bUserAuth && $oPrivacyViewsUser->privacyProfile === PrivacyCore::ONLY_USERS) {
```
TO
```php
        if (true) {
```

However, this won't make comments and forum threads private.

**Comment by pH-7** [comment]
Now, if you want all contents posted by users to be visible only by logged in users, you will need to update the Permission.php file of each module needed.

For example, if you want the comment module to be accessible only by logged in users, change
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/f284b66cd37aa67ce5185587e178e9d283e86f41/_protected/app/system/modules/comment/config/Permission.php#L21
```php
if ((!UserCore::auth() && !$bAdminAuth) && ($this->registry->action === 'add' || $this->registry->action === 'delete')) {
```
TO:
```php
if ((!UserCore::auth() && !$bAdminAuth)) {
```

**Comment by pH-7** [comment]
Same for the **Forum module**,

Change:
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/f284b66cd37aa67ce5185587e178e9d283e86f41/_protected/app/system/modules/forum/config/Permission.php#L26
```php
        if ((!UserCore::auth() && !$bAdminAuth) && ($this->registry->action === 'addtopic' || $this->registry->action === 'edittopic'
                || $this->registry->action === 'deletetopic' || $this->registry->action === 'reply' || $this->registry->action === 'editmessage'
                || $this->registry->action === 'deletemessage')) {
```
to just the following:
```php
        if ((!UserCore::auth() && !$bAdminAuth)) {
```

P.S. I haven't tested the code, but it should work (or be something very similar :)).

Hope it helps Thomas 😃
