### ISSUE TITLE
Photos tilted

### ISSUE THREAD

**Issue by Keemaaa** [pH7Software/pH7-Social-Dating-CMS#636]
**Describe the bug**
I uploaded a profile pic but it shows tilted.

**To Reproduce**
1. Upload a profile pic
2. Check it

**Expected behaviour**
Shows normally.
![Capture](https://user-images.githubusercontent.com/52850940/64673652-07460b00-d46f-11e9-8ec3-2df4b151c827.PNG)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52850940/64673675-162cbd80-d46f-11e9-8236-0c279b51f12d.PNG)

**Comment by Undefined-Variables** [comment]
I have tried to reproduce this and my pictures upload and display as expected. 

Have you tried another photo? Try another photo and if this happens again try to use a photo from a different source, download a image and see if you get the same result.

**Comment by polynamaude** [comment]
@Keemaaa Open your picture in GIMP and you will get option to rotate your picture.

It's not a problem with this CMS but your picture that's on the wrong orientation.

**Comment by Keemaaa** [comment]
Ok, It's resolved.
But another problem is that part of the photo is trimmed
![snip](https://user-images.githubusercontent.com/52850940/64675615-e338f880-d473-11e9-816e-4f993974c557.PNG)
Original
![bloom-blossom-dahlia-60597](https://user-images.githubusercontent.com/52850940/64675647-f2b84180-d473-11e9-9049-3e264ffaa3aa.jpg)

**Comment by Undefined-Variables** [comment]
Its because the CMS is setup to make images square so height and width are equal.
