### ISSUE TITLE
Email Confirmation 

### ISSUE THREAD

**Issue by abusayed0206** [pH7Software/pH7-Social-Dating-CMS#639]
Sorry for writing here!

I'm a Newbie. 

Confirmation email doesn’t arrive to user email!
How can I set it up for email registration link confirmation?
I dont know how can I set up!

Clarification : I have valid email with site domain. And I can't set it up...please help me.

**Comment by pH-7** [comment]
Hi @abusayed0206 
Have you checked your spam folder as well?
Can you see with your web hosting company if they can see in your SMTP email log to see if the email was delivered from your side?

**Comment by pH-7** [comment]
This might also help you/your web host company =>
https://ph7cms.com/doc/en/why-pH7CMS-can't-send-emails

**Comment by pH-7** [comment]
Hopefully it helps @abusayed0206 
Please let me know if this is still an issue. Hopefully, your web host will figure it out with you!
