### ISSUE TITLE
Theme probleme for site and admin panel

### ISSUE THREAD

**Issue by tototony76** [pH7Software/pH7-Social-Dating-CMS#644]
Hello,
I installed ph7cms but that if apparently does not take the themes, I try to change the theme but nothing ... I do not see where the problem comes from.
can you help me ?
sorry for my english, i'm french
cordially

**Comment by pH-7** [comment]
Thanks for opening the issue! 
In order to help me understanding better your issue, can you upload a screenshot of the current design of your website?

**Comment by pH-7** [comment]
And finally, what theme are you trying to change to?

**Comment by pH-7** [comment]
Just let me know if this is still accurate @tototony76 

Have a great Friday!

**Comment by Undefined-Variables** [comment]
@tototony76  Wow that is a dodgy username.... tony76 is not something you want in your username, trust me!

**Comment by polynamaude** [comment]
@Undefined-Variables Looking for the comment you wrote about the limits of help forum, your experience with pH7CMS and that it's not for beginners. Can't remember where you wrote it and found it could help @Simon1967 who opened a issue lately.

Thanks @Undefined-Variables

**Comment by Undefined-Variables** [comment]
Think this is what you are looking for mate...

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/643#issuecomment-535330628

**Comment by polynamaude** [comment]
@Undefined-Variables Yes that is exactly what I looked for.
