### ISSUE TITLE
Brakes up then 500 error after short period

### ISSUE THREAD

**Issue by simon1967** [pH7Software/pH7-Social-Dating-CMS#649]
Ok I am say thanks first, Please be aware I am learning code slowly, I have spent a week reading various articles trying to help my self first. I am a patreon of ph7 cms . I am willing to pay for help as I love the software and the skill set that has been applied.
I host with TMDhosting
The site will run a couple of days perfect but then starts breaking up
If i go to admin and clear the cache i can keep it going longer but then it will break up and read page not found but display as a text like page no background all text down the left had side then it will http 5000 error. I keep restoring and loosing my Data base this has been going on for a while, I have attached a screen shot of how it looks seconds before it falls over.
Greatful for your help and support with this. also I will pay to have it running perfect if need be.
Simon
![11](https://user-images.githubusercontent.com/52609146/66597606-38f9e100-eb97-11e9-87ef-b26645fae095.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by pH-7** [comment]
Hi @simon1967 
your issue seems similar to https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/284#issuecomment-418615641

**Comment by pH-7** [comment]
I have just checked your website and looks working well by now...
<img width="1237" alt="Screenshot 2019-10-11 at 10 09 51 am" src="https://user-images.githubusercontent.com/1325411/66606812-5ec2cc80-ec0f-11e9-992f-3d0552de2522.png">

**Comment by pH-7** [comment]
However, when I go to the "Browse" link, it doesn't work well. Could you try to clear the static cache? Admin Panel -> Tool -> Caches -> Caches Manager -> Static Files.

**Comment by simon1967** [comment]
I have just noticed that the host had it on php5.6 would this have done it
please.
Can i say thanks for your time
Simon

**Comment by simon1967** [comment]
Ok i have cleared them now but i have to keep clearing them. The host has
this set on php 5.6 extensions not php 7

**Comment by pH-7** [comment]
Really sorry, please ignore my previous answers (now, removed). I haven't read your entier message. Looks very weird it redirects to "index.php/..." 

Were you able to see the error message behind the 500 error?
Anything found in  /_protected/dada/log/*

I would suggest you contact TMDhosting and see with them if there is nothing breaking it.

**Comment by pH-7** [comment]
> extensions

Great news! What extension was it?

**Comment by simon1967** [comment]
it was on 5.6 they are going to change it I found it my self . I am so
grateful for your valued time and continue to support you.
Do you think this was the problem cause ?

**Comment by simon1967** [comment]
No it did the same if i clear cache in admin it works . what is wrong I
keep clearing it every 5 mins

Simon

**Comment by simon1967** [comment]
I clear the cache and it remains the same , can anyone give me any ponters please.
I host with TMD PHP7.2 on the server
I have read now for a week or so many articles but found no resolve.
Please can I say I am learning code slowly
Also the sight will fall over and give error 500 after a while and TMD have to restore.
I am asking as I am stuck and need some giudance
I want to say I appreciate all help in this matter I am a patreon of this.
Kindest
Simon

**Comment by Undefined-Variables** [comment]
Have you cleared your browsers cache? 

You can manually clear the cache by going to _protected/data/cache/ and delete the four folders here. You will likely have to do 

    chmod 777 -R /var/www/_protected/data/cache 

to allow you to delete them. To delete in terminal use 

    rm -R /var/www/_protected/data/cache/pH7_cache

Do this for each folder then load your website and the folders will be created automatically.

Hope that helps.

**Comment by polynamaude** [comment]
@simon1967 Why do you need to repeat yourself with the same question?  The issues ARE MONITORED and you already got some base for answer. The script ain't meant for beginners and there's no use to shouting you're on Patreon like thousands. This just give me the feeling you are pushing for answers.

Thanks

**Comment by simon1967** [comment]
polynamaude Thankyou for your comment, I understand but I have been looking at this for over a week, and after reading your comments to others " very similar to this one" i decided to read the articles of which I have, I could find no resolve and if you read I offered to pay for help. So I am not just walking away from this I am stcking with it and working the problem. Once you have the feeling you have exhausted all avenues you understand you then ask for help and thats where I feel I am
Thanks
Simon

**Comment by Undefined-Variables** [comment]
I have given you the answer... Why are you having so many issues with the cache? Are you making changes to the site? If so you should disable the cache until you are happy with everything.

**Comment by simon1967** [comment]
Undefined I am just trying it now and will report back. I thansk you for your help 
I have made no changes to the site.
Thanks
Simon

**Comment by polynamaude** [comment]
@Undefined-Variables could you link your comment related to your own experience. About the fact we do so for free and there's no link between paying on Patreon and getting something back (at least from myself).

I think this guy forgot we ain't UpWork or that we work at over 100 euros per hours.

**Comment by Undefined-Variables** [comment]
@polynamaude Yes I am not afraid to admit I had a few issues with the cache myself but I learned a great deal from the time I spent working with the code. 

Sorry I wasn't trying to step on your toes I am online doing some coursework and saw the question pop up in a gmail notification. How are you doing anyway?

**Comment by simon1967** [comment]
Hi Guys, I would like to report Undefined-Variables was perfect, Thank you so much.
This was obvious to you guy's but not to me. 
It is now
Thanks for all your effort and imput into solving this I am learning as I said.
Thanks
Simon

**Comment by Undefined-Variables** [comment]
@simon1967 Glad i could help you!

**Comment by simon1967** [comment]
@Undefined-Variables I hope to build my knowledge with help like yours it guides me and I now see why that was all it took. Bid thanks Can I be rude and ask is the cache likley to create me any more problems.
Simon

**Comment by Undefined-Variables** [comment]
I can't answer that with any certainty. Hopefully not but if it does you know how to fix it now.

**Comment by simon1967** [comment]
Oh dear it ran for 3 logins then did the same again any more ideas please

**Comment by Undefined-Variables** [comment]
When you say the same what do you mean? explain the problem a little more.

**Comment by simon1967** [comment]
Hi thanks, At the top of this post I put a screen shot, I can log on perfect then when i go to anything else it appears as the screen shot at the top of this page.
One big thanks

**Comment by Undefined-Variables** [comment]
Right do the same as before and clear the cache. Then login as admin and go to cache manager and disable every cache. Once you have disabled everything clear the cache again.  

Now you can enable them one at a time and find out which is causing the problem.

**Comment by simon1967** [comment]
Will do thanks I will report back
Simon

**Comment by Undefined-Variables** [comment]
What browser are you using? I am on your site and have no problem.

**Comment by polynamaude** [comment]
@Undefined-Variables You don't step on anyone's toe. You are more than welcome to contribute with hints and knowledge.

**Comment by simon1967** [comment]
Firefox and chrome 2 different machines

**Comment by simon1967** [comment]
Ok i have 1 at a time dissabled 1 at a time and deleted cache each time just to make sure and there are no changes the page still breaks up thanks

**Comment by Undefined-Variables** [comment]
Disable them all (at the same time) Then clear the cache. 

When you reload only one folder should be generated. 

Then turn them on one at a time and login etc and try to recreate the problem. Its no good turning one off and having 3 on. That tells me nothing.

**Comment by simon1967** [comment]
Ok thanks will do and report back

**Comment by simon1967** [comment]
With all 4 dissabled it came up the same broken. I did as you said a deleted Cache first completely then dissabled all 4 and tried my first login this broke up instantly and appeared as the screen shot at the top of the page. I did clear my browser on 2 macines and try the same

**Comment by Undefined-Variables** [comment]
I don't think the problem is with the software. I think the problem is the way you have set your server up. I have just spent a few minutes looking over your site and I have to be honest with you by saying your server is not set up correctly. You don't have a SSL certificate, you have not thought of security and I can see some serious holes that I could take advantage of very easily. Your set up is not even checking for same-origin. Security is the most important thing. Read this, you should have all these in place.  (except mod-security as the software handles this aspect already).

    https://geekflare.com/apache-web-server-hardening-security/

There are things that you simply can not afford to mess up. Do you have access to a php.ini file? And what have you set up?  Your server is set with the following... 

    

    Cache-Control = no-store, no-cache, must-revalidate

Who are you hosting with? Do you have SSH access?

**Comment by simon1967** [comment]
I am with TMD Hosting I will get ssl certificate now I did read this last week and it was on my list.
I will sort SSL out now and I allowed TMD to install so i was working on the server would be ok as they came recomended with the software, "I assumed" that made a fool of me. 
Regarding Cache-Control = no-store, no-cache, must-revalidate should these be set to yes
Thanks so much can I say thanks thanks your knowledge has been so gratefully recieved .

**Comment by Undefined-Variables** [comment]
I feel like I was harsh on you in that last reply but the truth is the internet is full of people who will take  advantage of any weakness and they will do so without second thought. You can not expect users to join your service via unencrypted http. 

The software provides its own cache so no leave them as no. setting them to public or even private opens up more problems with security. 

I can't help you with your server set up as only you have the access, with the code its different as we all have a copy. My advice is to concentrate on setting your server up correctly before doing anything else.

**Comment by Undefined-Variables** [comment]
If all else fails pH-7 offers hosting services that are tailored to the software. This might be your best bet.

**Comment by simon1967** [comment]
Ok i have just requested ssl and no you was not harsh. And how do i pick up that hosting please to eliminate this. I just took the top one from the recomended hosts with the software .
If i new more about the server set up i would stay with TMD they have benn really good to me.
Simon. Id there any fact sheets on the server set up for this software please. Oh and ONE BIG THANKS

**Comment by Undefined-Variables** [comment]
https://www.interserver.net/apps/ph7cms-hosting.html?gclid=EAIaIQobChMIx7j5mLqZ5QIVjq_ICh07IQ_SEAAYASAAEgK5CfD_BwE

Thats his hosting service and no there is no cheat sheet for setting up a server, it comes with experience and by learning from mistakes.

Best of luck.

**Comment by simon1967** [comment]
Just to say you have been fantastic thanks so much. I will not take anymore of your time this has been amazing help. Well done and thanks for working through these problems with me" self created"
it has been a great afternoon for me
Thanks
Simon

**Comment by polynamaude** [comment]
@simon1967 You have the requirements for the server in the pH7CMS documentation website and also in the Wiki.

Don't expect website development to be a top down approach with lists and flowchart of what to do.

Moat of it is based on experience and investigation.

**Comment by simon1967** [comment]
Thanks I am learning and reading fast . I am grateful guys very.
And thanks for your reply

Simon

**Comment by simon1967** [comment]
Thanks so much guy's this helped me a lot pointing me in a direction. Ok i have had https applied and I have been in touch with TMD Hosting all is good on the server apart from URL rewriting extension module - Apache, nginx, lighttpd, LiteSpeed and the tutorial for litespeed on here is missing. I am hoping it is simple can anyone point me too it i have been scouring for the tutorial.
Big thanks Awesome
Simon

**Comment by Undefined-Variables** [comment]
https://google.com

**Comment by simon1967** [comment]
Just to update: I have taken the oppertunity to move to VPS server as this can be configured for the perfect install. There were lots of server config problems inc LiteSpeed etc. Guy's it was you that sent me looking in this direction.  So thanks. I could have been another month looking so your input was fanatstic. I think this can be closed now. It will move accross shortly to vps.
Simon

**Comment by Undefined-Variables** [comment]
Install apache2.4, php-7.3 and mariadb-server. 

I know apache a lot better than nginx or LiteSpeed so it will be simple when you need help :)

**Comment by simon1967** [comment]
Thank you once again. I should be moving forward now I have lost 150
members at the first fall over but I will learn of course.
You have been amazing for me thanks for the guidance

Best wishes
Simon

**Comment by Undefined-Variables** [comment]
You don't have to lose your members you can dump your database in to a text file and import it into your new one, your URL will be the same so they will soon find you.

 sudo   mysqldump --all-databases > dump.sql

**Comment by simon1967** [comment]
Thanks i tried this before and lost them I used admin area and sql file but
i kept getting syntax error maybe it was the old server config again.

Thanks
Its a good job your not my next door niegbour

**Comment by Undefined-Variables** [comment]
Do it from terminal, the file will be were ever you are when you run the command. So do 

    cd ~

First so you are in your home directory then run the dump. Thats a lot of users to just throw away!

**Comment by simon1967** [comment]
Thanks I owe you

Simon " in learning mode"

**Comment by polynamaude** [comment]
@simon1967 Don't use sudo in the command. You won't get root access on your shared account. A simple mysqldump to save your DB

**Comment by Undefined-Variables** [comment]
Oh shit I forgot he is on a shared server. I just sudo -s and do everything as root and set permissions with chown as I need to.  A shared box should have sudo disabled though shouldn't it? 

Its been awhile since I used shared hosting sorry my bad, good catch :)

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables could you link your comment related to your own experience. About the fact we do so for free and there's no link between paying on Patreon and getting something back (at least from myself).
> 
> I think this guy forgot we ain't UpWork or that we work at over 100 euros per hours.

@polynamaude  I totally misread this earlier I linked the comment in the other thread so you can use it for the next person. That other guy really irritated me with the way he was talking at you like you are a paid employee, that is why he got my honest opinion. Then he thought he was being smart replying in spanish! 

You do a great job here responding to every single message. I'm sure pH-7 knows how much you do for the software. He has a lot less stress and time thanks to you, he knows that and I'm sure he does okay with all the support the software gets... He is a exceptionally clever guy. 

Just goes to show if put enough time and effort into something eventually it could be worthwhile. He is an inspiration and although I've barely spoken to him the amount I have learned from studying his work is astonishing. I owe him a great deal.

Also I am loving learning Javascript, I'm really enjoying it.  I didn't realize how much like PHP it is in many ways and yet so different in many others. Amazing language the possibilities are literally endless. 

Keep up the good work and I will always chip in if I see a problem I know something about.

**Comment by polynamaude** [comment]
@simon1967 Maybe you should take this as a reading...
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/643#issuecomment-535330628

@Undefined-Variables You shoudn't use **sudo -s** that's a bad habit. You shall modify your **sudoers** file instead. By allowing full root access by sudo you open your box to easy compromise as soon a user password is leaked. For example when I worked for a big telco we allowed specific users to specific applications in a limited fashion. We had to justify every adds we did to the **sudoers** file.

**Comment by Undefined-Variables** [comment]
Yeah I do agree it's not ideal this way but I only do it while developing. On a production server changing the user "root" to something else is probably a wise move. 

I just love the ease of not typing sudo a million times and direct access to mysql is lovely to. It uses unix socket to authenticate when the user is root so no -u user -p and no password to type :)  Adding a user to the sudoers file does not give the exact same privileges it just allows you to use sudo and enter a password.  That being said there are some things you would never want to do as root.

**Comment by Undefined-Variables** [comment]
I have just pulled undefined-variables.com offline and switched to CodeIgniter 4, going to see how it compares to CodeIgniter 3. This new version has API capability out of the box so sounds interesting.

**Comment by Undefined-Variables** [comment]
@polynamaude I really don't like what they have done to CodeIgniter, I gave it a good go and could use it if I had to but they have made it effort to use, things that made sense have been moved and odd little changes to things that already work. 

90% of it is version 3 and has changes that feel like they have been done just to make it slightly different. I like the idea of including REST API but its not worth the awkwardness when I could just add it myself and have the comfort of knowing where to look for things.

**Comment by simon1967** [comment]
Hello to all you guy's. First i would like to say a big thanks to @Undefined-Variables and to @polynamaude these guy's have been really good to me in helping and giving me some understanding and lots to read, I can not praise you enough for giving your free time to this project your knowledge and guidance. Thanks... Just to update I have moved to vps server and for now all seems to have settled down. I supplied TMD Hosting with the configuration list for the server so in theory it was set up correctly. So at this moment in time I am learning reading and playing. I have set up another site so i can play with the software and learn as I go without killing what is running. I think i need to set up a server at home on my spare desktop in order to do this from home.
Guys you are the best. I hope I can learn enough to help others in time Thanks
Simon

**Comment by Undefined-Variables** [comment]
The easiest and most practical way you can develop a site is to install a program called xampp. 

xampp runs on your everyday machine and has Apache, PHP, MySQL all running quietly in the background. This is what xampp is for PHP development. 

https://www.apachefriends.org/

 would suggest the one with PHP-7.3 but they will all will serve your requirements.

**Comment by simon1967** [comment]
Thanks so much will organise that now. I have learned one thing, Once you get in to this you can not leave it alone I look at the clock sometimes at its 1 am . and as many I have work . But it is the only way to learn
Cheers 

Simon

**Comment by Undefined-Variables** [comment]
Yes I can totally relate to that! I often find myself thinking about something programming related when I shouldn't be.  Sometimes I even dream about it. Now that is really really sad.  What is worst I wake up and try what I can remember!

**Comment by simon1967** [comment]
Dam large error log has just come back. I have placed a new htaccess file I
have cleared cache here we go its a 8 line error log going to have to look
deeper now

[14-Oct-2019 07:02:28 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/gd.so' - libX11.so.6:
failed to map segment from shared object: Cannot allocate memory in
Unknown on line 0
[14-Oct-2019 07:02:28 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/gd.so' - libX11.so.6:
failed to map segment from shared object: Cannot allocate memory in
Unknown on line 0
[14-Oct-2019 07:53:47 UTC] PHP Fatal error:  Out of memory (allocated
2097152) (tried to allocate 4096 bytes) in
/home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php
on line 152
[14-Oct-2019 08:53:54 UTC] PHP Fatal error:  Out of memory (allocated
2097152) (tried to allocate 4096 bytes) in
/home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php
on line 152
[14-Oct-2019 12:00:39 UTC] PHP Fatal error:  Out of memory (allocated
2097152) (tried to allocate 4096 bytes) in
/home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php
on line 152
[14-Oct-2019 12:24:36 UTC] PHP Fatal error:  Out of memory (allocated
2097152) (tried to allocate 4096 bytes) in
/home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php
on line 152
[14-Oct-2019 13:25:03 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/imap.so' -
libaudit.so.1: failed to map segment from shared object: Cannot
allocate memory in Unknown on line 0
[14-Oct-2019 13:25:02 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/ldap.so' -
libplc4.so: failed to map segment from shared object: Cannot allocate
memory in Unknown on line 0
[14-Oct-2019 13:25:09 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/intl.so' -
/opt/cpanel/ea-php70/root/usr/lib64/php/modules/intl.so: failed to map
segment from shared object: Cannot allocate memory in Unknown on line
0
[14-Oct-2019 13:25:09 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/mbstring.so' -
/opt/cpanel/ea-php70/root/usr/lib64/php/modules/mbstring.so: failed to
map segment from shared object: Cannot allocate memory in Unknown on
line 0
[14-Oct-2019 13:25:11 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/json.so' -
/opt/cpanel/ea-php70/root/usr/lib64/php/modules/json.so: failed to map
segment from shared object: Cannot allocate memory in Unknown on line
0
[14-Oct-2019 18:57:07 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/enchant.so' -
libenchant.so.1: failed to map segment from shared object: Cannot
allocate memory in Unknown on line 0
[15-Oct-2019 02:01:14 UTC] PHP Warning:  PHP Startup: Unable to load
dynamic library
'/opt/cpanel/ea-php70/root/usr/lib64/php/modules/bcmath.so' -
/opt/cpanel/ea-php70/root/usr/lib64/php/modules/bcmath.so: failed to
map segment from shared object: Cannot allocate memory in Unknown on
line 0
[15-Oct-2019 19:40:04 UTC] PHP Fatal error:  Out of memory (allocated
2097152) (tried to allocate 4096 bytes) in
/home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php
on line 152

**Comment by simon1967** [comment]
Something to work on for me

SIMON

**Comment by polynamaude** [comment]
@simon1967 First thing, don't start an issue and go with something else. You make the title useless and searching the issues problematic. We call that being off topic. 

2nd This ain't a general support to everything related to web hosting. And for this it's your server running out of resources.

**Comment by Undefined-Variables** [comment]
Misconfiguration is more likely 4096mb is a ridiculous amount of memory.

The answers are found in you php.ini file. 

You have not even included the extensions required.

**Comment by simon1967** [comment]
Woops Sorry
Simon

**Comment by polynamaude** [comment]
@Undefined-Variables When you run out of resources, individual allocation fail so 4096 bytes is the size of one variable not the whole PHP

**Comment by Undefined-Variables** [comment]
I will give you a hint...  

    gd.so

All of the above with .so are missing extensions, some are included with php (these are regarded to as the common group) Others are not and are installed using 

    apt-get install php7.3-json (json is one ext not in the common group, you can add as many as you like separate with a space)

Have you installed and ran composer?

**Comment by polynamaude** [comment]
@Undefined-Variables Nothing to do with Composer

**Comment by Undefined-Variables** [comment]
@polynamaude I see, I have never even come close to running out of resources. That sucks!

@simon1967 How much ram does your vps have included in the deal?

**Comment by Undefined-Variables** [comment]
@polynamaude Yeah I know I was asking cos I can see 

    /home/clubhou1/public_html/_protected/vendor/composer/autoload_static.php

Everywhere. 

Oh I understand the cache is controlled by third party software so clearing it triggered the autoload and there is no memory available for it. Sorry I didn't think about it.

**Comment by Undefined-Variables** [comment]
@simon1967 I have to agree with @polynamaude you are asking us questions that are not related to the software. Also this is not something I fully understand myself. 

So for those reasons im out!

**Comment by simon1967** [comment]
Cheers thanks I have found my php.ini file is empty 0

Simon
ps bought some books today

**Comment by simon1967** [comment]
Now closing this . I have I think resolved the issues. Guys thanks for the ponters in the direction I needed to look. 
Thanks for all your support simon
