### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by shawnus** [pH7Software/pH7-Social-Dating-CMS#651]
Hi, had a query that maybe someone here could answer?
I'm looking at dating site functionality and want to make use of it but not for dating. 
I want to use it to link mentors with trainees in healthcare, so a doctor who wants to mentor can create a profile with some bio info and what their specialties are, and trainees can register and look for mentors by region and what specialties they can provide mentorship for. The trainees shouldn't be able to browse all the members, just run a search and the results are appropriate mentors. Mentors won't need to browse trainees.
Once a trainee has a mentor they want to contact, they can use a contact form within the mentors profile, and the mentor will get an email of that form.
Also, no monetisation in this service, this is a free service to link mentors and trainees. All that side of things would be stripped out and the regulatory body will host the site.
Now I'm a project manager, not a Dev, so if this is a viable customisable product my next step would be finding the freelance developer resource to do that. But right now...in your opinion, could this product be customised to meet this need? Of not, any recommendations? Thanks for your time.

**Comment by simon1967** [comment]
Just to add here is TMD's report
 Staff

Hello,

Thank you for contacting TMDHosting Technical Support Team.

The reported error is related to the website's script using all of the allocated system memory. The PH7 requirements linked above specify 128MB of PHP memory_limit. Currently, the VPS is set to 1024MB PHP memory_limit. Thus, the script consumes nearly all of the available memory on the VPS. What we could assist with, as Hosting-related is to set up Swap space on the VPS, by using 2 or 4GB of the Disk Space on the VPS to be used as virtual memory. As you currently have 29GBs available, this should not be an issue.

**Comment by Undefined-Variables** [comment]
There are purpose built applications for this sort of thing. 

Taking this software and converting it in to what you are describing would take a lot of work and it would be fair easier to start your project from scratch. Technically you could convert this (or any other) software in to anything you like but it would be fair simpler just installing fresh framework and starting over. Any freelancer will tell you the same. 

Have a look at the applications listed here:

https://en.wikipedia.org/wiki/List_of_open-source_health_software

**Comment by WASasquatch** [comment]
Take a look at the HumHub Open Source Social Network Platofrm. It's geared towards employee networks.
