### ISSUE TITLE
Search Result Page Not Found

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#659]
I have been looking trough open and closed Issues looking for somebody who reported a problem with the **Quick** and **Advanced Search**, but I could'nt find any.
My problem is, that in case that I get more than one page of search results of a **Quick** or **Advanced Search**, the navigation buttons point to a non existing page, for example **_.../meet-people/1&p=2_**.
If I use the option from the menu **People>Browse** the navigation buttons are working well e.g. **_.../meet-people/?p=2_** and open the page correctly.
Any idea what is going wrong?
Oh, by the way! I made the test with an unmodified 15.1.7

**Comment by dimuller** [comment]
In the meantime I investigated this issue in depth and I was able to localize the source of the problem.
It's in the file "**_protected\framework\Navigation\Page.class.php**".
The function **getUrlSlug** just returned a number instead of the parameter section of the url.
I replaced the function with the following code:

```
    private static function getUrlSlug($sCurrentUrl)
    {
        $sParams = '';
        $iPos = strpos($sCurrentUrl, '&amp;');
        if ($iPos !== false) {
            $sFrag = strrchr($sCurrentUrl, '?');
            if ($sFrag !== false) {
                $sParams = str_replace('&amp;', '&', $sFrag);
            }
        }
        return $sParams;
    }

```
I also had to modify a statement in the function **cleanDynamicUrl** as follows:

`$sCurrentUrl = str_replace('&amp;amp;', '&amp;', (new HttpRequest)->currentUrl());`

As I'm still a php beginner I don't oversee yet possible implications on other parts of the site.

**Comment by pH-7** [comment]
Hi @dimuller 

Good catch!!  I REALLY appreciate that you posted the solution you found here. Well done! 🎉
I will have a deeper look in there and let you know if there is something else to do in order to fix this annoying issue.

**Comment by pH-7** [comment]
In the meantime, since this URL is rewritten, you could try to remove the following line in _protected/app/configs/routes/en.xml
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/configs/routes/en.xml#L24

Then, clear the "Database and Other Data" cache https://ph7cms.com/doc/en/how-to-clear-caches 

This "might" also fix the problem (as a temporary fix).

**Comment by dimuller** [comment]
Welcome! It's my pleasure if I can also give and not only take ;-)

By the way! Do you mean to remove the line

`<route url="meet-people" path="system/modules" module="user" controller="browse" action="index" />`

in the upper mentioned file?

I think that's not a good idea! If you remove this line **Browse Members** in the **People** Menu will not be redirected anymore resulting in a page not found error.

**Comment by dimuller** [comment]
Hi and thanks for looking into this problem.
I applied your changes, but unfortunately they don't work properly for me.
Ok, I show you what happens with your modifications.

I made a quick search and I got the following result:
![SearchResult Page 1](https://user-images.githubusercontent.com/51194360/67735134-ceb9bb00-fa35-11e9-965d-b1deed420990.jpg)

Next I clicked on the Page 2 button and I got this page:
![MeetPeople Page 2](https://user-images.githubusercontent.com/51194360/67735195-fa3ca580-fa35-11e9-90c0-1eb1dd6f2839.jpg)

But this is the normal Browse People Page 2. As you can see are there 5 pages shown and not 2.
Additionally the Quick Search settings are reset to their default values.

All this comes because your navigation buttons point to the Browse People page:
`http://localhost/Im-Cupid/meet-people/?p=2
`

With my solution you will get this result:
![SearchResult Page 2](https://user-images.githubusercontent.com/51194360/67735439-bb5b1f80-fa36-11e9-9c16-2b612cc1c3ad.jpg)

This is because my navigation buttons contain the following link:
`http://localhost/Im-Cupid/meet-people/?submit_search=form_search&age1=20&age2=40&state=&p=2`

To achieve this result I changed the **getUrlSlug** and the **cleanDynamicUrl** functions. Of course I don't know yet if the modifications result in other problems. Up to now they work for me.

```
    public static function cleanDynamicUrl($sVar)
    {
        // 191025 Mdi
        // Remove double appearance of amp; > don't know where it comes from
        $sCurrentUrl = str_replace('&amp;amp;', '&amp;', (new HttpRequest)->currentUrl());
        $sUrl = preg_replace(self::REGEX_URL_QUESTION_MARKS, '', $sCurrentUrl);

        if (preg_match(self::REGEX_URL_PARAMS, $sCurrentUrl)) {
            // check if $sVar already exists
            $iPos = strpos($sCurrentUrl, '&amp;' . $sVar . '=');
            if ($iPos != false) {
                // remove $sVar parameter
                $sCurrentUrl = substr($sCurrentUrl, 0, $iPos);
            }
            return $sUrl . self::getUrlSlug($sCurrentUrl) . '&amp;' . $sVar . '=';
        }

        return $sUrl . self::trailingSlash($sUrl) . '?' . $sVar . '=';
    }

```

```
    private static function getUrlSlug($sCurrentUrl)
    {
        // 191025 Mdi - returned 1 instead of parameters
        $sParams = '';
        $iPos = strpos($sCurrentUrl, '&amp;');
        if ($iPos !== false) {
            $sFrag = strrchr($sCurrentUrl, '?');
            if ($sFrag !== false) {
                $sParams = str_replace('&amp;', '&', $sFrag);
            }
        }
        return $sParams;
    }

```
