### ISSUE TITLE
Private profiles

### ISSUE THREAD

**Issue by 1tense** [pH7Software/pH7-Social-Dating-CMS#664]
Hello,

I do not want all profiles to be accessible to visitors (and google).

I tried this 

```
if (!$this->bUserAuth && $oPrivacyViewsUser->privacyProfile === PrivacyCore::ONLY_USERS) {
To the following:
        if (true) {
```

from https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/634

But profiles are still accessibles when I'm unlogged.

Thanks

**Comment by Undefined-Variables** [comment]
Users have the option to make there own profile visible to who they wish. They can set this by going to "edit Profile -> Privacy"

**Comment by 1tense** [comment]
Thanks for your answer. Yes, I see this option but I want this by default, globally. The user must not have a choice.

**Comment by Undefined-Variables** [comment]
So you want to make all profiles hidden from everyone else by default? Or only selected ones?

**Comment by 1tense** [comment]
Yes : hide all profiles by default when I'm not register.

**Comment by 1tense** [comment]
Hello,
I'm still interested to know how to make all profile private by default. 
Thanks

**Comment by loryel** [comment]
How about this?

./_protected/app/system/modules/cool-profile-page/controllers/MainController.php

```
40:            // The administrators can view all profiles and profile visits are not saved.
41:            if (!AdminCore::auth() || UserCore::isAdminLoggedAs()) {
42:                $this->initPrivacy($oUser);
43:            }
```

```
40:            // The administrators can view all profiles and profile visits are not saved.
41:            if (!AdminCore::auth() || UserCore::isAdminLoggedAs()) {
42:                $this->initPrivacy($oUser);
43:                if (!UserCore::auth()) $this->displayPageDenied();
44:            }
```
