### ISSUE TITLE
Improve male/female search

### ISSUE THREAD

**Issue by 1tense** [pH7Software/pH7-Social-Dating-CMS#665]
Hello,

I want, when the user choose a sex (male looking for female or female looking for male) that the quick search or advanced search automatically search the sex is looking for.

I tried this
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/358#issuecomment-439288256

But when I have a user male, looking for female, I still see all other male profiles.

Two possibilities :
1 - only display members of the opposit sex
2 - only display members with the sex the member is looking for when he registred

Thanks

**Comment by Undefined-Variables** [comment]
You have just opened 3 issues that could have all been part of one. If you have more to say please use the same issue as before!

**Comment by 1tense** [comment]
Sorry I thought it was a good pratices to open 3 issues for 3 subjets. Thats how I work usually with other tools. If other ph7cms have one of the 3 issues it will be easier for them to find an answer ?

**Comment by Undefined-Variables** [comment]
Generally speaking it is but this is normally on different occasions. Let me have a look into the questions  you have asked. I have to get a copy running for the questions you require answers to so please be patient and allow me some time to look into one question at a time :)

**Comment by 1tense** [comment]
Ok thank you for helping, I'm patient. :) it's not urgent but the 3 issues are important for me. I have many ideas of improvements, specially on SEO, but I know my limits...

**Comment by Undefined-Variables** [comment]
Can I ask why you are using an account that was only created an hour ago? I am happy to help anyone I can but normally users who create a brand new account just to ask a question are not serious about the questions they are asking and I don't like wasting my time. 

For this reason I'm only going to answer your first question for now!

**Comment by 1tense** [comment]
I'm not new on github, I have another "pro" account (I work with prestashop cms), for ph7cms it's new for me, it's not connected to my professional activity so I create a new account. I'm not a ghost ^^

**Comment by Undefined-Variables** [comment]
Okay fair enough :)

**Comment by pH-7** [comment]
> Hello,
> 
> I want, when the user choose a sex (male looking for female or female looking for male) that the quick search or advanced search automatically search the sex is looking for.
> 
> I tried this
> [#358 (comment)](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/358#issuecomment-439288256)
> 
> But when I have a user male, looking for female, I still see all other male profiles.
> 
> Two possibilities :
> 1 - only display members of the opposit sex
> 2 - only display members with the sex the member is looking for when he registred
> 
> Thanks

Hey @1tense 

Looks like you forgot to apply the comment below the one you mentioned (which is the second part).
=> https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/358#issuecomment-439311149

Sorry for that unclear information :)

**Comment by dimuller** [comment]
The problem goes far beyond the search. Also Birthdays, Hot or Not, Videos, Photo gallery, etc. should also only show the match sex.

**Comment by 1tense** [comment]
Thanks for your help but I already do the change

```
$bIsZipCode = !$bIsMail && !empty($aParams[SearchQueryCore::ZIP_CODE]) && Str::noSpaces($aParams[SearchQueryCore::ZIP_CODE]);
        if (!$bIsMail && !empty($aParams[SearchQueryCore::MATCH_SEX])) {
    $bIsSex = true;
    $aParams[SearchQueryCore::SEX] = [($aParams[SearchQueryCore::MATCH_SEX] === 'female') ? 'male' : 'female'];
} else {
    $bIsSex = false;
}
        $bIsMatchSex = !$bIsMail && !empty($aParams[SearchQueryCore::MATCH_SEX]);
```
And I have still both sex on a search.

**Comment by pH-7** [comment]
> The problem goes far beyond the search. Also Birthdays, Hot or Not, Videos, Photo gallery, etc. should also only show the match sex.

Good point @dimuller I understand your concerns. I will see to implement it also for the "Birthdays" feature.

Concerning the Hot or Not module, it already filters genders https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/ab3ac00633efeee5c65895a0e70a6ead822582e1#diff-04710f22fcaafa0047b4b12e1005e64d
It was done in May 2nd of this year.

**Comment by WASasquatch** [comment]
Sorry to jump in here, but I wanted to touch basis on gender exposure. I've been doing research in dating websites for a couple years after doing statistics monitoring on a few platforms. One thing that seems to drive away users the most is unwanted gender exposure. You'll see this on any commercial systems, where you simply cannot view "Males" with an account setup as interested in Females unless you were on desktop with a direct link. 

We confirmed this with one of our biggest loss of user points, which was summarized to be exposure to wrong criteria, around 25% (23.4%) of new users would simply leave the session hanging, or log-out after performing searches. This was compared against the search result lengths to ensure the user was simply not satisfied with variety. Another 5% of users would deactivate/delete their accounts.

We suggest this was due to the search systems (we were specifically diagnosing) and being exposed to irrelevant results (to the user). 

Looking forward to checking out this platform though. I've got everything ready for a install tomorrow on a fresh server.

**Comment by 1tense** [comment]
I'm still interested :)

**Comment by Undefined-Variables** [comment]
> Sorry to jump in here, but I wanted to touch basis on gender exposure. I've been doing research in dating websites for a couple years after doing statistics monitoring on a few platforms. One thing that seems to drive away users the most is unwanted gender exposure. You'll see this on any commercial systems, where you simply cannot view "Males" with an account setup as interested in Females unless you were on desktop with a direct link.
> 
> We confirmed this with one of our biggest loss of user points, which was summarized to be exposure to wrong criteria, around 25% (23.4%) of new users would simply leave the session hanging, or log-out after performing searches. This was compared against the search result lengths to ensure the user was simply not satisfied with variety. Another 5% of users would deactivate/delete their accounts.
> 
> We suggest this was due to the search systems (we were specifically diagnosing) and being exposed to irrelevant results (to the user). To add to what dimuller posted, this included users statuses and image shares (no videos were used on the platform). We solved this with using the interested string as a flag (male|female|either) which what used to check against content rendering.
> 
> Looking forward to checking out this platform though. I've got everything ready for a install tomorrow on a fresh server.

This is very interesting and something that should be thought about more. The software doesn't separate sex in this way and you see both male and female profiles even when your profile states what you are interested in... Great food for thought!
