### ISSUE TITLE
Who wants to install these new languages on my  pH7 installation

### ISSUE THREAD

**Issue by Mike-B** [pH7Software/pH7-Social-Dating-CMS#666]
I need that if you live in Brasil or Portugal it automatically translates the website language to Portuguese, the same if it's in Spain (to spanish) or France (to french) or any countries that speak a different language.

**Comment by Undefined-Variables** [comment]
Why would you need to mix location so dramatically on a dating site? Your users will have serious difficulties and not only with communication, they will have to plan vacations just to meet in person. 

Also it is not as simple as automatically translating in to every language. You need somebody who speaks each language to sit down and type each sentence out. The file containing English is  16,670 lines long. Have a look at it...

    _protected/app/langs/en_US/LC_MESSAGES/global.po

To do this in one language would take days and require some serious concentration. I wouldn't take that task on for all the gold in Egypt! Monumental task!!!

**Comment by Mike-B** [comment]
Ok I guess I'll just stick a translator on top of the site
