### ISSUE TITLE
cURL issue? - Can't access Admin / Themes Broken

### ISSUE THREAD

**Issue by WASasquatch** [pH7Software/pH7-Social-Dating-CMS#671]
**Describe the bug**
I cannot access the admin panel, and the main site theme is broken, all links point to 404s. 

**To Reproduce**
Install pH7Builder on vanilla Ubuntu 18.04 LAMP stack
1. Follow the links provided by **Installation of pH7CMS - Step 7/7** page
2. See errors

I was able to confirm that cURL is running using a basic curl check
http://rsdating.com/ph7/curl.php
```<?php echo 'Curl: ', function_exists('curl_version') ? 'Enabled' . "\xA" : 'Disabled' . "\xA"; ?>```

**Comment by polynamaude** [comment]
@WASasquatch Hi !
Your problem may be caused by your website not being hosted on the root of your domain 
 http://rsdating.com/ph7 . You will need to edit your .htaccess file and add a RewriteBase directive.

For more information I'd refer you to the Apache HTTPD documentation website.
https://httpd.apache.org/docs/2.4/en/

Sincerely,
PM

**Comment by WASasquatch** [comment]
Turns out my FTP wasn't configured to upload ".htaccess" files, so it simply wasn't there (I never used `ls -al` to actually check if it was there and just assumed it was)

**Comment by pH-7** [comment]
> Turns out my FTP wasn't configured to upload `.htaccess` files, so it simply wasn't there (I never used `ls -al` to actually check if it was there and just assumed it was)

Glad you figured it out! Indeed, pH7CMS cannot work properly without the .htaccess files uploaded. Unfortunately, FTP clients aren't always configured to upload .htaccess file.

**Comment by WASasquatch** [comment]
Right. I could have just used SFTP or `cp` from my home system, but I was making sure FTP was working. Which it was, I just forgot about that specific niche of my client. Thanks for the support @polynamaude , and @pH-7 .
