### ISSUE TITLE
Technical expert ism needed

### ISSUE THREAD

**Issue by samuelkinyanjui** [pH7Software/pH7-Social-Dating-CMS#679]
Hi Team,
i am looking for expert who can customize PH7software to my need 
1.publish android app
2.add subscription
3.allow real men/women to respond to clients request
example
https://invisiblegirlfriend.com/
my email is sax80kinya@gmail.com

**Comment by hykelauncher** [comment]
I can do it

**Comment by samuelkinyanjui** [comment]
what will be the cost?time it will take?

**Comment by hykelauncher** [comment]
What's ur budget, but it will take up to a month

**Comment by samuelkinyanjui** [comment]
i have few additional features
Dating site combined with these features
what i mean is one can select real man/woman or select virtual
men/women/girls
Real men the clients  can meet face to face or chat one on one
virtual men are only for chat/advice(one virtual man can advice many women
and viseversa)
Virtual men/women are configured by visitors customizing the look and feel
virtual men can have categories-  business /professionals /businessmen
/teachers/doctors etc
clients pay for prescription monthly like 1 USD and billed for text SMS
sent maybe one dollar for 20 sms/text  to the phone
The payment gateway need to be able to accept card/mobile money etc(I can
provide code for mobile money)
If prescription expire one get text message to renew and account is locked
after 3 days expiry
For text SMS/text one have to buy in advance and will not receive text/SMS
if depleted

**Comment by hykelauncher** [comment]
the software has all this features in it

**Comment by samuelkinyanjui** [comment]
OK name the cost?your charges
i have no specific budget  as it is just an idea i want to tryout

**Comment by polynamaude** [comment]
@samuelkinyanjui Hi there !
I don't feel like you know what's a software development project. A budget is needed ahead so we can define the limits we'll be having.

For example if you give a 10 000$ budget to develop a text editor then I'll be able to take some part of the budget for bug finding. If you only give me 1 000$ then I will probably be extending an existing text editor to suit your need.

I'd suggest you start by making a established list of what you want and how you want it. How much you can afford, the priority of each elements. When you do software development there's always surprise down the  road so the fix priority ahead is a good thing. This way the developer will know what to choose if he's short on budget.

This only prevent confusion later on.

The more serious you will look in your request, the more chance you will get to have someone serious do your job. Only some hints so you don't waste your money,
