### ISSUE TITLE
Issues with Universal Login

### ISSUE THREAD

**Issue by coedxx** [pH7Software/pH7-Social-Dating-CMS#686]
Hello!!

I want to let you know that I totally love this project, it's excellent
I'm having 1 issue however
Concerning the universal login module
I have disabled everything but Facebook

It won't work, the OAuth URI needs a specific address
I have set up another site with Facebook login, so that I know how it should be done
The issue however seems to be

Use Strict Mode for Redirect URIs
Only allow redirects that use the Facebook SDK or that exactly match the Valid OAuth Redirect URIs. Strongly recommended.

The issue however is, if I'm right, I need a callback URI such as this one (that works)
https://aloha.painkill.guru/m/facebook_connect/login_callback  

And I don't know this URI
Do you?
Or do you anticipate any other issue being the culprit?

Even worse, I can't disable the the "Strict mode"

Would you please help me solve this?
I'll give you screenshots, whatever you need

Sidenote: The site of this software is found at https://bull.painkill.guru  

Many thanks and best regards from
Albin

**Comment by Undefined-Variables** [comment]
The Connect module needs updating after Facebook changed the way they handle this feature on their site.

It is a known issue and will be rectified in the future I’m sure. Facebook have made a habit out of making big changes that effect other people at a moments notice and once it’s working again they will likely do it again.

**Comment by coedxx** [comment]
I see, please let us know when the module is ready and functional

Best regards
Albin

**Comment by coedxx** [comment]
Maybe DOLPHIN-api could help you guys? Such as the one I referred to...
It's a open source projects, I have mine working just fine at https://aloha.painkill.guru

**Comment by coedxx** [comment]
The only real difference is that dolphin has a "login callback oauth uri" the one I told you about
https://aloha.painkill.guru/m/facebook_connect/login_callback

**Comment by Undefined-Variables** [comment]
Intersting thanks
