### ISSUE TITLE
Ever seen this?

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#690]
We seem to have a intermittent error on login/registration. 

    The following error was found:
    The security token does not exist or its lifetime has expired. Please try once again

This is proving to be hard to reproduce when needed, it happens completely by random and finding the course is proving difficult when it happens completely by random.

The main trigger seems to be when a user submits part 1 of the registration form, part 2 fails to load and shows the progress bar but not part 2 of the form!

This has me puzzled!

**Comment by polynamaude** [comment]
@Undefined-Variables Use a tool like W3AF and do some further testing. The same tools used to test security of web applications.

**Comment by Undefined-Variables** [comment]
I have used Burp to have a good look at the headers/cookies/tokens that are being used and everything is as it should be but like I say its so random its hard to get it when its happening. I go to bed and wake up with emails telling me the site is broken but when I try it everything works. I have seen screenshots though so I know its happening I just cant catch it. 

There is nothing in any of the logs either. Just thought it was worth asking in hope someone may have some idea!

**Comment by polynamaude** [comment]
@Undefined-Variables I'm not talking about headers, cookie and such.

The error is random then use a fuzzing tool to supply hundreds of requests with data. Look where it fails and try to find some common ground to the errors raised.

**Comment by Undefined-Variables** [comment]
Right that is not a bad idea... I will give that a go. Thank you :)

**Comment by Undefined-Variables** [comment]
The problem traces back to the use of XMLHttpRequest (33 times though out the code). This is a depleted for very good reason. It is unreliable, gets confused between object types and in some cases poses a catastrophic security risk! If you have a few minutes take a look at this...

[(url) https://xhr.spec.whatwg.org/]

If you fail to set your server up properly using same origin policy and not all the options are safe like it will cause unexpected behaviour with Access-Control-Allow-Origin: so safely using API's is almost impossible. By doing a Access-Control-Allow-Origin: * you are forfeiting your rights granted to you by web browsers for that page. This has major security implications. You will not be able to protect your self from CSRF using tokens. A capthca slightly mitigates this problem, also checking the referer might also help (it will be blank if the origin is HTTPS). Also read the CSRF prevention cheat sheet.

The risks here are rather high so trying not to highlight the worst but this needs to be addressed and soon. The current situation makes me worry!

**Comment by Undefined-Variables** [comment]
The problem was the wait between registrations from the same IP address, if you use whatsmyip on a production site you will very quickly become blacklisted from using there API. When this happens everyone is logged as 127.0.0.1 the standard fallback IP address that is normally used for looping connection as the local IP of your machine. You need to upgrade to a commercial service to increase the usage available. 

This was incredibly hard to find as no errors are left in any log anywhere on the server! The thought came to me randomly and it was what was wrong!
