### ISSUE TITLE
pH7CMS installation stops at 28,6%

### ISSUE THREAD

**Issue by ab2211** [pH7Software/pH7-Social-Dating-CMS#691]
Hello,
while installing the newest pH7CMS it stops as soon as it reaches 28.6%. Another use had this problem too (reporting it here), could fix it but without describing what he did to solve it.

**Comment by Undefined-Variables** [comment]
You most likely need to increase a couple of settings in your servers php.ini file.

max_execution_time = 2500
max_input_time = 2500

If you are on a shared server you can create a file in the public_html folder called php.ini and add the lines in this file. If you are on a dedicated or personal server edit these values in your php.ini its in /etc/php7.3/apache2/php.ini on most Linux Debian based systems.

**Comment by ab2211** [comment]
Thanks, I'm on a shared server, but this does not work.

**Comment by Undefined-Variables** [comment]
If you use Cpanel you have to do it using the php.ini editor from the cPanel adding the file manually has no effect.

**Comment by ab2211** [comment]
I wrote the values at the htaccess, that is ok for me.

**Comment by Undefined-Variables** [comment]
Yes there are many ways to skin a cat, what ever works for you. 

Problem solved?

**Comment by ab2211** [comment]
Problem solved!

**Comment by hykelauncher** [comment]
Try editing your php.ini, in your Apache folder
