### ISSUE TITLE
Links not working correctly. 

### ISSUE THREAD

**Issue by walnad** [pH7Software/pH7-Social-Dating-CMS#693]
None of my links are working correctly. When I press on any given link for example FAQ page, this text is added to the link <index.php/static/legal/legal/user/birthday-people/help/faq> for FAQ's page. 
Any help would be greatly appreciated.

**Comment by Undefined-Variables** [comment]
Yes this seems to be a recurring problem that I keep seeing here, I have had this problem in the past, it doesn't happen as often as you think, it happens once then the cache keeps the issue repeating. 

The way I finally stopped this from happening was to remove 

    data-load="ajax"

from the anchor tags in /templates/themes/base/tpl/bottom_menu.inc.tpl

You will also need to clear your sites cache before you try loading a page again.

**Comment by walnad** [comment]
Still the same problem. What's really interesting one of my domains works fine, and other 3 are having the same issue. This is a problem ever since I have started testing this script (about a year ago). And another note....The cache has horrible management interface. I have to clear the cache literally every few hours. Would this ever get fixed?

**Comment by Undefined-Variables** [comment]
Yeah I agree with you but this is open source and anybody who has the time is welcome to fork a copy and make improvements with the cache. 

There are ways around having to manually empty it all the time, you could set up a cron job with 

    0 * * * * rm -R /FULL/PATH/TO/_protected/data/cache/* 

This will clear it automatically every hour (Set timing to your liking)

What cache settings have you got active?

**Comment by Undefined-Variables** [comment]
I think the problem is in the following class

    _protected/framework/Layout/Html/Design.class.php

I just don't have the time at the moment I am snowed under with paid work!

**Comment by Undefined-Variables** [comment]
Been thinking about what you said about one domain not working and others that do... There must be something different, a php extension not installed etc 

It’s funny cos we never got it to stop until we moved to a different hosting company! I would start comparing the two setups! That file I told you about earlier is a bit of a mess! I am going to go though it and tidy it up when I can.
