### ISSUE TITLE
Mobile version forwards to porn site.

### ISSUE THREAD

**Issue by chyandour5** [pH7Software/pH7-Social-Dating-CMS#695]
Hi,
I just installed via Softaculous. The desktop site works as expected, but when viewed on a mobile device the home page comes up, and then you are immediately redirected to m.xvideos.fr  Do you have any ideas as to why this is happening? The site had only been up ten minutes when I discovered this, there are no affiliates or members as yet, just me as admin. https://date-n-meet.com

**Update:** Answer found. The domain was out of use for some time, on checking the host records in my registrars admin panel, 91.226.182.128 had been added (not by me) to the records.

**Comment by smartersolutions-ohio** [comment]
I have the exact same issue. Could explain further? How did you find your answer?

**Comment by chyandour5** [comment]
In my case it was a rogue entry in the DNS records of my domain registrar 91.226.182.128, as it states in the 'update' above, It had nothing to do with the pH7 software.
