### ISSUE TITLE
Code map cheat sheet

### ISSUE THREAD

**Issue by piotrfx** [pH7Software/pH7-Social-Dating-CMS#696]
Hi guys! :)

I'm no expert in coding yet but I would like to try to add a module that I want to build from scratch.

I don't know how others, but if there would be a map pointing which file leads to which file and all dependencies, that would save a lot of time if you don't know well the structure of the whole app.

Do you know if such a thing exists? If no, I'm happy to help and create it. Would be anybody who thinks this might have sense and would like to join me?

There is an example module, but this is not great help for me. Why? I still don't understand after checking it how I can use the code to build a new module. Maybe I'm too stupid yet, but, this is a great software to start more advanced coding with.

Thanks :).

**Comment by hykelauncher** [comment]
Yeah...that's a great idea, and I would like join you
