### ISSUE TITLE
How to translate the terms/privacy/legal pages without the {lang} tags ?

### ISSUE THREAD

**Issue by crolidge** [pH7Software/pH7-Social-Dating-CMS#698]
Hi folks,

I just started out translating ph7-CMS for my soon-to-be dating website, and I want to know how can I translate the terms/privacy/legal pages?

Their lang strings are not present in the "global.po" file, so how can I generate translations besides changing the their text in the Admin templates?

The problem is my website will be multilingual, and I need PT, ES besides the EN version.

Should I generate and include lang strings in the "global.po" file, and then include {lang} settings in the Admin texts, in order to allow translating them?

I really cannot see any other option.

Thanks to advise,

**Comment by crolidge** [comment]
I am amazed no one has raised this issue before, at least according to the forum history.

**Comment by Undefined-Variables** [comment]
the pages such as privacy/terms/about/partners are static pages and can be edited though the admin area using templates files editor or you can find them in the following folder

_protected/app/system/modules/page/views/base/tpl/main/***pages are here***

**Comment by crolidge** [comment]
Thanks for the answer but that doesn't work. These pages such as **privacy.tpl** anrd **terms.tpl** are not translatable here, because the strings miss any translation tags, such as {lang} or t(...) !!
So how can you build a multilingual site if you cannot translate the legal pages??

Anytime you save their content in the Admib dashboard, it becomes static across all languages present, no matter the chosen interface language.
Please help me with this.  Thanks

**Comment by polynamaude** [comment]
@crolidge I think that Mr @Undefined-Variables already gave you the answer. And you wrote it here yourself.

That is, re-write the pages using {lang} tags.

Yesterday I was reading a forum regarding Wekan Kanboard software. Really useful for managing projects.
I found a great definition about what's the most annoying on a developer forum. Let me share it with you. May I remind you that this is a developer community and as such, it means that you shall have some minimal knowledge about building software. If you did read some posts on the forum then you surely already know this. You shall also know that, as everything is free then it would be more than rude to put pressure upon us to do anything. So take what it is and if you dislike then you ain't tie up to here (contrario of a vendor lock-in).

```
Etiquette
Why am I called a troll?
You want a feature, but you add thumbs down emoji reactions
You are adding image reactions
You want priorities changed. Current priorities are:
High priority: security issues and high severity bugs
Medium priority: Import/Export
Others. Actual roadmap will be updated later.
You write that you are providing constructive criticism
You think that free software includes free implemented features
You are adding something other than:
Thumbs up reactions to existing posts
Feature specs
Technical details
Links to related documentation
Links to example code to get a feature implemented
Pull requests
Why am I called a spammer?
You are adding new comments that have only content like:
+1
+1 I can confirm this
+1 It would be great to have this
+1 This is the only feature for preventing my company to move to Wekan
You are adding something other than:
Thumbs up reactions to existing posts
Feature specs
Technical details
Links to related documentation
Links to example code to get a feature implemented
Pull requests
```
**Extracted from...**
https://github.com/wekan/wekan/wiki/FAQ

**Comment by crolidge** [comment]
Hi Polyna & team,
Thanks for the neat answer... sorry if I trolled a bit.... I don't want to move to Wekan yet... lol !!!
This is FOSS so I definitely understand some features are lacking, and even if they lack, we shouldn't press the developers for solutions!

Although I have a minimal knowledge of software and FOSS, I must confess I was amazed how come no one seems to have reported the omissio in these legal pages/tags before. In the age of GDPR and privacy accountability, it is critical to have the ability of translating the legal pages!
No one up to date built a multilingual website with these pages? Ok...

Moving forward, I will do as you suggest : edit the global.po (never done it before, but I'll find out how) with POEDIT, hack some tags into it, match them in the pages, and see the outcome to share with you folks asap.
Of course I also though about hacking the less-used pages, such as jobs.tpl. That would be a solution.
I really wanted to avoid hacking any pages to prevent any automated future upgrade of the same (are automatic upgrades implemented?).

Let me hack it and revert. Cheers. thanks.
