### ISSUE TITLE
website icons is missing

### ISSUE THREAD

**Issue by zeze6** [pH7Software/pH7-Social-Dating-CMS#700]
hello 
greetings for you all
first of all big thanks for the team of ph7cms script
i'm using nginx and was able to set it up, everything seems to work fine..
there is little issue i have which is
photos icon not showing, photo icon for members who doesn't have photos, i mean the default icons in homepage and inside website too
uploaded photo explain what i mean
![Screenshot from 2020-02-11 04-00-53](https://user-images.githubusercontent.com/45097078/74206695-2b5b8180-4c85-11ea-8245-c71612b965b0.jpg)
also admin setting for  homepage SEO text is not showing in the admin page, can't edit or change it, blank white in the SEO text section

**Comment by Undefined-Variables** [comment]
Why are you using Nginx? As it says in the documentation you may have to add more rules to your nginx configuration to get this to work properly. I have very little experience with nginx so unable to elaborate!

**Comment by zeze6** [comment]
> Why are you using Nginx? As it says in the documentation you may have to add more rules to your nginx configuration to get this to work properly. I have very little experience with nginx so unable to elaborate!
thank you for your quick reply @Undefined-Variables 
i'm using nginx due to its light-weight resource utilization

**Comment by zeze6** [comment]
@Undefined-Variables good evening, i tried with apache server i get 500 internal error just after uploading files to root, i checked your docs and make sure i have my files permissions set right
and PHP config set right, where i can check error log? i can't find anything in apache log, what do you suggest? 
thank you

**Comment by zeze6** [comment]
the fix for my issue was deleting everything in htaccess file and put the following code
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

**Comment by Undefined-Variables** [comment]
@zeze6 Yeah I was just thinking as I read your post an initial 500 is normally to do with .htaccess file! Most of the rules in the example supplied for your convenience should be in your apache configuration (httpd.conf or apache2.conf depending on version you are running) it’s more efficient to have them in apaches configuration as the rules are read and set upon apache start.

Having them in the .htaccess means they are called on every single request! This quickly consumes resources when 100 users are all browsing the site! 

Unless you have experience using nginx and fully understand the way the rules are applied I’d recommend sticking with Apache as the software has been developed and tested with it! When problems arise you have more chance of getting help. 

I’m glad you worked it out and thank you for coming back and sharing your solution, this helping and getting help is a two way street :) 

By the way @pH-7 is the led developer on this project, I simply help out with issues as a way of saying thanks for all his work...give and take!

**Comment by zeze6** [comment]
@Undefined-Variables thank you so much for explaining this to me
i have another issue, sometimes when users clicks on one of the pages for example, *browse* or *photo* a new tab opens and redirect to domain name IP like this www.xxx.xx.xxx.xxx/photo-gallery x is the IP for my domain, not domainname.com 
it doesn't happen always but it happens a lot, any suggestions?

**Comment by Undefined-Variables** [comment]
You can use a rewrite rule to stop this. Something like...

`RewriteCond %{HTTP_HOST} ^xxx.xxx.xxx.xxx$
RewriteRule ^(.*)$ https://your-real-domain.com/$1 [R=301,L]`

This should solve your issue, as for the course... Its down to your servers configuration.

**Comment by zeze6** [comment]
@Undefined-Variables thank you the issue still not solved

**Comment by Undefined-Variables** [comment]
This rule is perfect for the problem you have... Is mod_rewrite installed? 

![Annotation 2020-02-14 063648](https://user-images.githubusercontent.com/52648055/74507481-6dd6c580-4ef4-11ea-9e69-d702ef3c9a3e.jpg)

Open terminal type this...

    sudo a2enmod rewrite

then 

    sudo service apache2 restart

**Comment by zeze6** [comment]
@Undefined-Variables thank you i forgot to restart apache it works now, but website still open new tab whenever this happens

**Comment by Undefined-Variables** [comment]
I’m pleased it works but I am going to leave you to solve this one :)

**Comment by zeze6** [comment]
@Undefined-Variables haha brother i'm not coder by any means, i just know the basic things and since i have unmanaged VPS with no support included i learned from internet and from great people like you how to fix everything by my self, don't leave me please

**Comment by Undefined-Variables** [comment]
@zeze6 Try removing the L from the rule I gave you.

```RewriteRule ^(.*)$ https://your-real-domain.com/$1 [R=301,L]```

To 

```RewriteRule ^(.*)$ https://your-real-domain.com/$1 [R=301]```

There are more redirects ahead in the file so the L is not required yet!

**Comment by Undefined-Variables** [comment]
> the fix for my issue was deleting everything in htaccess file and put the following code
> 
> ```
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteRule ^index\.php$ - [L]
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule . /index.php [L]
> </IfModule>
> ```

Plus you have removed half the rules you need in the htaccess file. I would upload the complete one and add the rules above and if you get a 500 remove one rule at a time, if its still giving 500 replace the rule and try the next one!

**Comment by zeze6** [comment]
@Undefined-Variables thank you for your suggestion, i put back the htaccess file and i removed the following code and kept the one i put earlier, no errors
```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>
    Options +FollowSymLinks

    RewriteEngine On

    ## Uncomment the below "#RewriteBase /" (remove "#") if pH7CMS is installed in a folder, and add the folder name after the slash "/"
    ## Example: If pH7CMS is installed in "/public_html/ph7cms/", then it should be "RewriteBase /ph7cms/", however it may depends of your Apache configuration.
    ## If you need, please ask your hosting company or check the Apache doc: http://httpd.apache.org/docs/current/mod/mod_rewrite.html

    # RewriteBase /
</IfModule>
```

**Comment by Undefined-Variables** [comment]
Wonderful :) If you issue is solve you can close this issue :)

**Comment by zeze6** [comment]
@Undefined-Variables ok i will but i have question please, suddenly i can't login in admin panel and can't reset password *not receiving email* is there a way to change or view the password? 
thank you so much brother

**Comment by zeze6** [comment]
@Undefined-Variables i tried with chrome and i was able to login but couldn't do it on firefox

**Comment by Undefined-Variables** [comment]
Absolutely not!!! Passwords are hashed then stored in the database! Any other way is just asking for problems! Sounds like Firefox is not allowing cookies, I don't have the time to look right now! But that is where I would start looking...

**Comment by zeze6** [comment]
oh i see, but now it won't let me be able to solve the Captcha for admin and users too

**Comment by zeze6** [comment]
also i haven't set cron job yet :) i tried to do so i get 403 error

**Comment by zeze6** [comment]
the Captcha worked when i used windows 10 but did not work on Ubuntu :) ok my man @Undefined-Variables when you come back please tell me what are the correct settings for cron, have a good night

**Comment by Undefined-Variables** [comment]
This is the 4th issue now on this ticket, we are not here to provide step by step support for every issue you see and you are asking for help with things that are explained in the documentation

    https://ph7cms.com/doc/

Your cron tab should look something like this

``` 
0 0 * * * curl "https://your.domain.here.com/asset/cron/96h/Database/?secret_word=your_secret_string_here"
0 0 * * * curl "https://your.domain.here.com/asset/cron/96h/General/?secret_word=your_secret_string_here"
0 0 * * * curl "https://your.domain.here.com/asset/cron/96h/Banned/?secret_word=your_secret_string_here"
```

I am busy im sorry I can't help further :)

**Comment by zeze6** [comment]
when i try to put GET http://domain.com/assets/cron/96h/Database/?secret_word=mysecretword
i get 403, i looked at htaccess and found out there was some lines cause this error lines are
```
</Limit>

ErrorDocument 400 /error/http/index?code=400
ErrorDocument 401 /error/http/index?code=401
ErrorDocument 402 /error/http/index?code=402
ErrorDocument 403 /error/http/index?code=403
ErrorDocument 404 /error
ErrorDocument 405 /error/http/index?code=405
ErrorDocument 500 /error/http/index?code=500
ErrorDocument 501 /error/http/index?code=501
ErrorDocument 502 /error/http/index?code=502
ErrorDocument 504 /error/http/index?code=504
ErrorDocument 505 /error/http/index?code=505

# URL Rewrite
```
when i remove these lines and put the same cron job, it works! i don't know if this is misconfiguration in the script or bug

are these all the cron list? in this link https://ph7cms.com/doc/en/cron-list

**Comment by zeze6** [comment]
sorry @Undefined-Variables i just saw your comment, and yes i read the doc but i thought maybe the docs were old i just want to make sure, thank you so much for being so helpful i really appreciate that

**Comment by Undefined-Variables** [comment]
Not a problem, close this ticket and open a new one for any future problems, this helps others find issues in the future. Best of luck!

**Comment by zeze6** [comment]
@Undefined-Variables ok Sir :)
