### ISSUE TITLE
Sorting a localized list of countries

### ISSUE THREAD

**Issue by crolidge** [pH7Software/pH7-Social-Dating-CMS#701]
Hi there folks,

I need to sort alphabetically the localized list of countries in the search forms,  but I don't know how to do it.
Changing the order of the 2-letter country codes in the language.php file doesn't work, because the order of the countries in every form drop-down list remains English-based, no matter which language I choose in the language selector (I am sure there must be some PHP code to solve this 🙂). Can someone help me?
Cheers,

**Comment by Undefined-Variables** [comment]
If cURL is installed and working as it should they default is automatically set using the geo location of the users IP address.

Can't think of a simple way to do this manually... Not with out rewriting the module!

**Comment by polynamaude** [comment]
@crolidge Use Javascript to sort the list in the front-end.

**Comment by crolidge** [comment]
Thanks for the tips. After many trials, I was able to find a way to always sort the countries dropdown list, using JQuery, and working around diacritics! Here goes:

```
<script>
window.addEventListener("load", function () {
    $("#str_country").html($("#str_country option").sort(function (a, b) {
	return a.text.localeCompare(b.text)
    }))
}, false);
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
```

Thanks a lot for the guidance!
