### ISSUE TITLE
XSS fail

### ISSUE THREAD

**Issue by randomtech2** [pH7Software/pH7-Social-Dating-CMS#709]
Hello I noticed that the cms has important XSS failures so I looked on the internet and I found this https://cxsecurity.com/issue/WLB-2019040120
How to solve this fail?

**Comment by Undefined-Variables** [comment]
Thank you for bringing this to my attention! I will look in to this and get back to you ASAP!

**Comment by polynamaude** [comment]
@randomtech2 I'd first suggest you take a look at the version before reporting stuff and make sure it hasn't changed since. That's a good start ;-)
What you are showing here is nearly a year old that is v14.9.0 and we are now at v15.3.0.

Have you tried it against the last version ?

**Comment by Undefined-Variables** [comment]
Yeah tested and no longer possible :)

**Comment by polynamaude** [comment]
@Undefined-Variables Now you are starting to get why I'm not giving my limited energy to people who only have very limited knowledge and think (foolishly) that they'll get rich with this system without much effort or brain work.

You now seem to be repeating the same words I already said, that is, this software require knowledge to be used and also require some work before you can really do something useful about it.

**Comment by Undefined-Variables** [comment]
@polynamaude Absolutely! I can totally see where you are coming from! I give a general example that any developer would get first time and be able to adjust to there needs but sadly the more you give the more they want and to be fair it’s exhausting!

**Comment by polynamaude** [comment]
@Undefined-Variables Did our dude that was reluctant to share his log with us finally solved his problem ?
Maybe he had in mind something related to fireplace !

Like I told you, beware of people who only have one issue and they opened their Github account the same month.

**Comment by Undefined-Variables** [comment]
@polynamaude  Haha god only knows!!! He never came back to us but pretty certain I have the answer for him should he wish to continue what he started :/ 

Reluctant is an understatement... I do wonder what he has to hide! 

Yeah I’m implementing a one issue rule so if help is needed make sure it’s really not something solvable alone! I don’t mind helping solve a single issue but I’m not here to build an entire website for people!

**Comment by polynamaude** [comment]
@Undefined-Variables You now seem to be repeating the exact same pattern I did about a year ago. And at that time, it was you that came mad and in a furry against me.

Hope you understand why now...

**Comment by Undefined-Variables** [comment]
Yeah I totally understand! I was asking to much and didn’t realise the amount of time you had given to helping people. It’s not just that either people come and ask for help, you help them and they don’t even come back and say thanks! 

I’m sorry I gave you such a hard time, I see things differently now!

**Comment by pH-7** [comment]
Thanks, I appreciate your issue @randomtech2 :)
However, this has already been fixed a while ago here, https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/6b95281dd34ba56036595ee3dfa6423e38c36a7c
