### ISSUE TITLE
Fatal error: generators cannot return values using "Return"

### ISSUE THREAD

**Issue by platindev** [pH7Software/pH7-Social-Dating-CMS#71]
Hello, I just tried to install the script. but getting this error. 
Fatal error: Generators cannot return values using "return" in /home/****/public_html/demo3/_protected/framework/File/File.class.php on line 665
The error 1st displayed on under URL and after that also on frontend URL
example.com/_install/?a=config_site

**Comment by pH-7** [comment]
Hi @platindev 
I don't have access to my server here. Can you replace this file https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/framework/File/File.class.php#L665
by 
`if (!($rHandle = opendir($sPath))) yield false;`

And let me know

**Comment by pH-7** [comment]
I will fix the bug soon and it will throw an exception next time. Please watch the repo to be awared to those changes

**Comment by pH-7** [comment]
And PLEASE let me know if that works now

**Comment by platindev** [comment]
Yeh sure I am going to replace now.

**Comment by platindev** [comment]
That's worked but I did something this.

from line 665 
        if (!($rHandle = opendir($sPath))) yield false;
 return;

and from line 641
        if (!($rHandle = opendir($sPath))) return false;

 return;

now it's working. Thanks for help out. Will give you further updates. Now going to make further steps

**Comment by pH-7** [comment]
Nope, you don't have to change anything line 641 because it doesn't use `yield`.
Concerning your internal error, that looks strange to me. Can you set the development mode http://ph7cms.com/doc/en/how-to-set-the-development-mode and then tell me what you see. Also please check your log file located in` _protected/data/logs/`

**Comment by platindev** [comment]
getting same with development mode

**Comment by platindev** [comment]
You can access code from here.
ftp details:
site: meriwall.com
user: demo3@meriwall.com
pass: 987654321

**Comment by pH-7** [comment]
Do you have a screnshot. Maybe it's not the internal server error message from pH7CMS but the internal server error from Apache. If so the error is from your Apache configuration. You should check your Apache log.

**Comment by platindev** [comment]
You can look the error here.
demo3.meriwall.com

**Comment by platindev** [comment]
and in log folder there is no error log. just empty default files

**Comment by pH-7** [comment]
I don't have  internal server error page. 

I got only the following:
`
Fatal error: Generators cannot return values using "return" in /home/meriwalldotcom/public_html/demo3/_protected/framework/File/File.class.php on line 656
`
Can you please change `return false;` by `yield false; return;` in 656 line

**Comment by platindev** [comment]
Yes that is the error. Because i just change the code as you said. As error page was due to my code as I wrote you before. 
And now your is updated in _protected/framework/File/File.class.php

**Comment by pH-7** [comment]
OK, your server doesn't seem the best for I fixed the initial problem.

The problem was from the Gettext library that wasn't working on your PHP installation. Constructors PHP 4 weren't called. Now I fix it in your site and works well for me.
