### ISSUE TITLE
Admin locked out due to 2-step authentication.

### ISSUE THREAD

**Issue by crolidge** [pH7Software/pH7-Social-Dating-CMS#710]
Hi there,
While testing the 2-step authentication in my site, I accidentaly activated it without scanning the QR code or saving the backup recovery code.

So now I got my Admin ID locked out of my site! Basically I cannot due anything. Arghh!
Yet I have FTP access to the site. I tried manipulating some PHPs, enable some Admin menus on a regular-user ID, logged on by that user, but any Admin features/menus always lead to an Admin login prompt, so I really cannot do anything.

Is there a way to recover my Admin login, or disable internally the 2-step authentication?
Thanks in advance for any tip!

**Comment by Undefined-Variables** [comment]
You need to access the database though PhpMyAdmin you can disable it from there.

**Comment by Undefined-Variables** [comment]
Table  Admins change isTwoFactorAuth from 1 to 0 The mysql cmd from terminal is 

````mysql -u <USER> -p 
<PASSWORD>

use <DATABASE NAME>


UPDATE `<TABLE PREFIX>_admins` SET `isTwoFactorAuth` = '0' WHERE `<TABLE PREFIX>_admins`.`profileId` = 1;

**Comment by crolidge** [comment]
Thanks a lot dear @Undefined-Variables !!!
You saved my day! (and nights as well... lol)

My previous experience with phpMyAdmin and dealing with MySQL databases was close to zero, so this was really a useful insight! Have to learn more about it.
Cheers!
