### ISSUE TITLE
Installer 

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#711]
Just done a fresh install using the latest version and the installer failed to create the admin account and the random users so had to add the admin manually in the database. Just letting you know there is a little problem is all. 

Love the updated user generator with photos that is extremely useful for development purposes :)

**Comment by crolidge** [comment]
When I made my install of the latest version back in January, I didn't experience any troubles. Agere the user generator is really useful, easy to go through and practical!

**Comment by polynamaude** [comment]
@crolidge May I ask what version you installed back in January ?
Sometime there's delay before updating the application on Sourceforge...

**Comment by polynamaude** [comment]
@Undefined-Variables Sorry to be "off-topic" but I'll erase my message afterward.
Did you try to install Open Web Analytics for your site ? It's pretty useful as it gives you good stats and can even do some lookup of GeoIP.

Cheer

**Comment by Undefined-Variables** [comment]
@polynamaude yes love open web analytics :)
