### ISSUE TITLE
FontAwesome loading and not loading in same page

### ISSUE THREAD

**Issue by crolidge** [pH7Software/pH7-Social-Dating-CMS#712]
Hi folks,
I love implementing FontAwesome (FA) icons in my test site (using FA 4.4 for the time being).
However, there are cases where the icons load and don't load in the same page, (which I think is a bit strange), depending on the CSS classes used.

FA never loads inside **.alert** Bootstrap classes, but at the same it loads inside **.pfbc-error** dialog boxes!
The icons are the same and the associated tags too (i/em/span).
I analyzed all the CSS and can't find any apparent conflict. Is this related to JQuery somehow?
Any tips would be welcome.

**Comment by crolidge** [comment]
I also tried Glyphicons, and the same error happens - you can't use them inside .alert classes.

**Comment by Undefined-Variables** [comment]
The version of font awesome used is not the current one. Think the current is 4.7 and the installed version is 4.4 (of the top of my head) so only some of the icons work! I’ve never tried using one in an alert class but was under the impression you could use them anywhere html can be used as they live inside <i></i> tags.

**Comment by Undefined-Variables** [comment]
iPhone can’t do back ticks stupid phone!

**Comment by crolidge** [comment]
Yes, fontawesome latest version is 5, but I am using some old icons to ensure backward compatibility.
