### ISSUE TITLE
Module not found when chang language at Pswd Rest

### ISSUE THREAD

**Issue by crolidge** [pH7Software/pH7-Social-Dating-CMS#713]
Hi folks,

When I try changing the language at the Password Reset page, I get a dialog error "Module Not Found", and the user is forwarded to the Home page.
It's the only time this behaviour happens, but I still don't know the reason.
The alternate links in the header seem well applied, so really cannot figure this out.
Any hints out there?
Cheers,

**Comment by Undefined-Variables** [comment]
@crolidge Sounds like you are missing something... Put the site into development mode and it will give you the full trace. If you copy and paste that here I will tell you the problem...

**Comment by crolidge** [comment]
@Undefined-Variables Thanks my friend. I just did it but where do I retrieve the error logs? I cannot find it anywhere on screen or in the Admin menus.
When I reproduce the same error I cannot see anything different. The only difference is the development sentence in the footer.

**Comment by Undefined-Variables** [comment]
So you have site in development mode and sign in as admin then call the reset password URL while you are signed in!

**Comment by crolidge** [comment]
It doesn't work. I signed in as a Admin, but when I paste the reset URL on the browser (http://amorzito.com/forgot/admin123), I am routed to the Admin index page.... and a dialog box says "You are already logged in".

**Comment by Undefined-Variables** [comment]
I don’t see what the problem is I just tried it! 

Very neat looking site though mate, good job! 
![947B2BF5-2F0A-4FE1-A62C-D051767C46B7](https://user-images.githubusercontent.com/52648055/75605964-fe5dfa00-5adf-11ea-8be8-1b1f1d5a6850.png)

**Comment by Undefined-Variables** [comment]
I would change admin123 to something obscure though!

**Comment by crolidge** [comment]
Thanks for the nice words but my site is far from completed. :-) but the error creeps coming in whenever I switch languages on the reset page.
I thought maybe ity has to do with my routes setup.
Currently I have these:

` 
<route url="forgot/([a-zA-Z0-9_-]+)" path="system/modules" module="lost-password" controller="main" action="forgot" vars="mod" />
<route url="reset-password/([a-zA-Z0-9_-]+)/(.+)/(.+)" path="system/modules" module="lost-password" controller="main" action="reset" vars="mod,mail,hash" />
`

The canonical alternate URLs in the header look fine.
In all other pages, the site adds the suffix **?l=(any language)** correctly.
The problem is it appears in a crucial page for the users - the pwd reset.

The debut blue box doesn't show up as well. :-(

**Comment by crolidge** [comment]
Wait.... I just obtained this log when typing the web page without the user after "forgot/":

![image](https://user-images.githubusercontent.com/60101029/75607003-a24ca300-5aea-11ea-9eb0-be5cb887494a.png)

Does it give us some clues?

**Comment by Undefined-Variables** [comment]
Yeah I know building a website is a journey of ups and downs and just when you think you are close something will pop up and put you back a few steps... I am a perfectionist when it comes to style and I love playing with CSS too so end up spending hours on little things, but if something is worth doing its worth doing right. Also spending the extra time now will save headaches later on... Trust me on that :) 

According to this trace you are missing /_protected/app/system/modules/forgot module or the config.ini that is found  /_protected/app/system/modules/forgot/config/config.ini its an empty file but must be in place, however I am skeptical as you have had it working on occasions. Just check and make sure they are there and the permission is correct. 

Also if /amorzito.com is your root directory move _protected up a directory then make the change in  /_constants.php (at the root) there are many reasons why this should be done. Don't leave _protected in a web accessible location or you will regret it...

**Comment by crolidge** [comment]
Thanks but  I have no module folder called "forgot". Only the "lost-password". I created a new module folder called "forgot", added a subfolder "config", added confi.ini empty or equal to the one inside "lost-password", and it doesn't work. Same error!
It's a pity.

**Comment by Undefined-Variables** [comment]
You see the lost-password module has a Lang file inside it? Can you not use this to do what you want? I’m not sure as never had to convert before!

**Comment by Undefined-Variables** [comment]
Has your lost module got all this inside?

![Capture](https://user-images.githubusercontent.com/52648055/75611922-ad1d2d00-5b16-11ea-8f4c-d5ded7ed7972.PNG)

**Comment by Undefined-Variables** [comment]
and the view has a config too

![Capture](https://user-images.githubusercontent.com/52648055/75611928-ccb45580-5b16-11ea-9926-dfc043e54b8c.PNG)

**Comment by crolidge** [comment]
I copied all those subfolders but it just creates a new feature "resend activation email" on the login page. I think I'm gonna forget it and just disable the language chage in this page.
Thanks for your support!!!

**Comment by Undefined-Variables** [comment]
Personally I would have downloaded a new copy and used the files from there! 

No worries anytime:)

**Comment by crolidge** [comment]
Hi Undefined-Variables.
How can I send you a private message? Can you disclose some contact please? Thanks in advance.

**Comment by Undefined-Variables** [comment]
hey@undefined-variables.com
