### ISSUE TITLE
error after 5/7 installation page

### ISSUE THREAD

**Issue by clefsauvard** [pH7Software/pH7-Social-Dating-CMS#714]
receive 

HTTP ERROR 500

avec validate Admin details on 5/7 page
why ????????

try again and with several web browser but without success

**Comment by polynamaude** [comment]
@clefsauvard It would help your own self if you'd start by looking at the logs and sharing them with us here.
At least, would show that you have some basic knowledge about what's going on...

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Apache-Server:-Internal-Server-Error-500-after-installing-%5BHow-to-solve%5D

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

**Comment by polynamaude** [comment]
@clefsauvard Web browser have nothing to do with any type of HTTP Error code (404/403/500/...)

**Comment by Undefined-Variables** [comment]
@clefsauvard your question is lacking the basics! Can you explain how you coursed the error and how we can reproduce it, also your server log would be helpful. 

I have to say though that a 500 error is an internal server error and is most likely down to your servers setup.

**Comment by clefsauvard** [comment]
Hi
Thank you for your reply

Success to install after 2 things


First is with .Htaccess file. Need to delete the option FollowSymLinks with
my provider Online.net.



Second I installed 15.2.0 instead 15.3.0 because else never installer add
admin profile on the database with 15.3.0.

Regards
