### ISSUE TITLE
More of a question?

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#716]
Why is the software using outdated packages obtained from composer? Image says a thousand words...

![Screenshot from 2020-03-01 22-27-25](https://user-images.githubusercontent.com/52648055/75635232-4a0dc200-5c0c-11ea-9493-c7eeb4fd7595.png)

**Comment by polynamaude** [comment]
@Undefined-Variables We already had this discussion...
Not every library is backward compatible.

There's nothing bad in using an older release of a library. Unless you really need some newest possibility offered or there's a bug that's bothering you. When you depend on something you rarely want to use the latest version. It's better to deal with bugs already known (and that you can manage to get along with) than to discover new ones introduced by new change that haven't got used widely (even testing doesn't always find everything).

You'll learn those thing by either reading books on SDLC or by gaining experience...

**Comment by Undefined-Variables** [comment]
@polynamaude yes I can see what you are saying and please don’t take my question the wrong way I am by no means an expert and I am asking questions in the process of learning. 

I am currently learning in depth about sessions, cookies and authentication, in particular how applications handle manage and how to avoid problems that arise in this area! I read something about a vulnerability in an older version of one of these out dated libraries and the advice was to keep all of composer packages up to date. 

I installed a session/cookie framework that can be easily used on multiple sites and makes the use of shared session and cookie in software installed in sub domains simple and secure, I used composer and saw that almost all the libraries/packages are old versions no longer supported by the authors who created them, this can be just as bad as new unknowns. 

I was just shocked that almost all are outdated. The day you think you know everything is the day to give up because nobody will ever know everything it’s just not possible. I am really enjoying learning new things and sometimes asking questions is the most efficient way of learning. 

You have more experience than me and I take what you think seriously and apply it to my own work:)

**Comment by polynamaude** [comment]
@Undefined-Variables I think it's more a lack of time or something like this that caused the library not to be updated. There's nothing preventing you from updating them one by one and testing if they do any breaking change. If so you just revert the last one and go forward to the next.

**Comment by Undefined-Variables** [comment]
Yeah I am going to as I read the documentation for composer from start to finish and that is exactly what they recommend doing but to allow some time between updating them as not all problems are immediately apparent, sometimes it can take a certain set of events to see there is an issue! 

Time is the only thing we all have the same amount of and there is so much to do and limited time to do it. 

I have also been learning the ins and outs of ffmpeg conversation and video players, another fascinating area if you have the time. It’s one area that could use some love in the software for sure :)
