### ISSUE TITLE
Dynamic fields

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#718]
I have seen that there are a bunch predefined dynamics fields and the possibility to add own.  

How to enable them so the user can fill in the fields (and other user see them)?

Does the advanced matching use these fields?

Regards
Digiloo

**Comment by Undefined-Variables** [comment]
You can create custom fields in the admin panel. You will see the options under the user drop down menu, add fields to add and field list to see your current set up! 

As for the search no not unless you make some changes in the code. Search parameters are in _protected/app/system/core/classes/SearchQueryCore you would need to define them as constants there and then add them to /_protected/app/system/core/forms/SearchQueryCoreForm.php 

A basic understanding of PHP would be required for the latter.

**Comment by digiloo** [comment]
Wow. Thank you for superfast answer.  I have already found the possibility in admin panel. But these dynamic fields (predefined or custom)  are not visible then creating a new user. 

Regards
Hakan

**Comment by Undefined-Variables** [comment]
Yeah just good timing as at my Desktop. 

Yes you are correct they are added to the user profile and not to the registration form. To do this you would have to make some more complicated changes to the user module/user/signup/ in here you need to add the input html attributes to the view, add logic to the controller and also add to the insert sql statement in the model also you need to make sure the database has the correct setup to by adding the fields to the user info table

**Comment by digiloo** [comment]
Ok. Thanks. Perhaps this can be a suggestion to later versions?

Regards

**Comment by Undefined-Variables** [comment]
Yeah sounds like a useful addition :)
