### ISSUE TITLE
Problems with e.g City:  in Quicksearch

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#719]
If the city (fetched from GeoLite2-City.mmdb) e.g contains the nordic letter ö (o with dots) it is displayed (and searched) wrongly and no match is found in the database.

The fetched information is (according to my understanding) UTF-8 encoded. And hence no need to encode again.

Regards
Hakan

**Comment by digiloo** [comment]
```
public static function getCity($sIpAddress = null)
    {
        try {
            // Encode to UTF8 for Latin and other characters of the GeoIP database are displayed correctly
            $sCity = utf8_encode(static::get($sIpAddress)->city->name); <==  Remove the encode here to get "Linköping" correct
           
            // TODO: When support PHP 7.1, specify multiple exceptions using "|" pipe
        } catch (AddressNotFoundException $oE) {
            $sCity = '';
        } catch (InvalidDatabaseException $oE) {
            $sCity = null;
        }

        return $sCity;
    }

```

**Comment by pH-7** [comment]
Thanks for tying to debug that one. Encoding can be a big nightmare. Do you mind to open a Pull Request with your working fix?

**Comment by digiloo** [comment]
Thanks, WIll do!

**Comment by pH-7** [comment]
> Thanks, WIll do!

Awesome. Can't wait to see it! 😊

**Comment by pH-7** [comment]
Was fixed here: https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/734
