### ISSUE TITLE
500 Internal server error on Installation

### ISSUE THREAD

**Issue by aquilax** [pH7Software/pH7-Social-Dating-CMS#72]
After step `Install of pH7CMS - Step 4/8`, when I press Next, I get 500 Internal Server Error

Testing on Ubuntu 14.04.2 LTS

```
192.168.33.1 - - [07/Feb/2016:06:26:40 +0000] "POST /_install/?a=config_site HTTP/1.1" 500 416 "http://192.168.33.10/_install/?a=config_site" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
```

**Comment by pH-7** [comment]
Hi @aquilax 
First of all, can you check if you have a log file in /_install/data/logs/ ?
Then, can you check your server log (Apache log) as it seems to be a server error...?

**Comment by aquilax** [comment]
The log contains multiple:
```
[07-Feb-2016 00:33:22 America/Chicago] PHP Fatal error:  Call to undefined function ph7\is_internet() in /var/www/html/_protected/framework/Loader/Autoloader.php on line 68
```

**Comment by pH-7** [comment]
This modif was really new and didn't check the installer (as this Github repo is dev place, some time you get bugs). Thanks for your help!

Here is the bugfixed: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/857a89704fcbd2899de1220eb701072aadb6e3a6
You can fix it by uploading this file again.
