### ISSUE TITLE
Import users from csv file don't seem to work

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#721]
This seems to loop forever ...

while ($this->aFileData !== false) {
                $sEmail = trim($this->aFileData[$this->aTmpData['email']]);
                if ($oValidate->email($sEmail) && !$oExistsModel->email($sEmail)) {
                    $this->setData($iRow);
                    $oUserModel->add(escape($this->aData[$iRow], true));
                    $iRow++;
                }
            }

**Comment by digiloo** [comment]
while ($this->aFileData !== false) {
                $sEmail = trim($this->aFileData[$this->aTmpData['email']]);
                file_put_contents("hakan.log", "RUN2 " . $sEmail . " " . $iRow . "\n", FILE_APPEND);
                if ($oValidate->email($sEmail) && !$oExistsModel->email($sEmail)) {
                    $this->setData($iRow);
                    $oUserModel->add(escape($this->aData[$iRow], true));
                    $iRow++;
                }
                $this->aFileData = fgetcsv($this->rHandler);  <== Add this
            }

**Comment by pH-7** [comment]
Thanks for pointing this out @digiloo! I will investigate :)

**Comment by digiloo** [comment]
Thanks!

**Comment by pH-7** [comment]
Code:
https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/2fb2fa99508783a7afef34898d2e00a68a95612a/_protected/app/system/modules/admin123/inc/class/ImportUser.php#L286-L293
