### ISSUE TITLE
Errornous display (No one has seen "Search")

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#723]
```
No one has seen "Search"
No one has visited the profile.
```
I guess that **Search** above shall be the name of the logged in user 

It seems like **Search** is picked from the URL (./user/visitors/search/)

/ Hakan

**Comment by Undefined-Variables** [comment]
Yeah I know this is an issue and I will be investigating soon as possible.

I will update this issue once I have more information.

**Comment by digiloo** [comment]
Thank you!

**Comment by pH-7** [comment]
> ```
> No one has seen "Search"
> No one has visited the profile.
> ```
> 
> I guess that **Search** above shall be the name of the logged in user
> 
> It seems like **Search** is picked from the URL (./user/visitors/search/)
> 
> / Hakan

Yes, you're right. That happends when you specified "Search" as the user name in the URL.
FYI, it's right here: https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/10cbc8ececd8b6404c0c8479fe709ef81663742d/_protected/app/system/modules/user/controllers/VisitorController.php#L98

**Comment by digiloo** [comment]
Hmm, I hav'nt specified "search" it gets in the path by itself in some circumstances

**Comment by digiloo** [comment]
Hi, Too see above issue just do:

1) Login
2) Account->Who See Me->Find Visitor(s)

/ Hakan

**Comment by pH-7** [comment]
> Hi, Too see the above issue just do:
> 
>     1. Login
> 
>     2. Account->Who See Me->Find Visitor(s)
> 
> 
> / Hakan

Cheers! I will have a look to it
