### ISSUE TITLE
Suggestion for dynamic fields

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#726]
Hi,

I have the following suggestion for dynamic fields to make them look more like a standard field:

DynamicFieldCoreForm.php:

 ```
 default:
     $sLangKey = strtolower($this->sColumn);
     $sLangKey = ucFirst($this->sColumn) . ":"; <== Add this
     $sClass = '\PFBC\Element\\' . $this->getFieldType();
     $this->oForm->addElement(new $sClass(t($sLangKey), $this->sColumn, ['value' => $this->sVal]));

```

**Comment by pH-7** [comment]
This is a great suggestion! However, not all form labels are separated with colon in pH7CMS. I believe this shouldn't be hardcoded in there. Instead, you should add the colon (`:`) in the language.php translation file. 

In that way, the colons ":" can always be removed or added (like what it is currently the case thanks to the Gettext translations).

**Comment by digiloo** [comment]
Yes. But my idea was that **always code** with ":" and possible remove in gettext/language.php/Lang.js/...
