### ISSUE TITLE
Google Analytics Question 

### ISSUE THREAD

**Issue by ultra-pool** [pH7Software/pH7-Social-Dating-CMS#729]
Iv signed up for Google Analytics and trying to find out how to get the tracking code to add to the Analytics setting in the dating site.

**Comment by Undefined-Variables** [comment]
This is a question for google support!

**Comment by Undefined-Variables** [comment]
It is given to you when you sign up. Its the block of code in script tags they tell you to copy!

**Comment by Undefined-Variables** [comment]
Why are you asking questions you could put into google.com?

**Comment by ultra-pool** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4G0ZGEBHTJ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'your-code-here');
</script>`

This seems to work. Took 24+hrs.
