### ISSUE TITLE
Command line installer

### ISSUE THREAD

**Issue by aquilax** [pH7Software/pH7-Social-Dating-CMS#73]
Command line installers are very useful for development or hosting companies trying to automate the deployment process.

Some good examples: Prestashop: http://doc.prestashop.com/display/PS15/Installing+PrestaShop+using+the+command+line
Magento: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

**Comment by pH-7** [comment]
Not spend time to develop  something that 10% of users will maybe use it.

**Comment by pH-7** [comment]
Might be implemented in the near future. I will reopen it and see if I will get time to add that
@aquilax

**Comment by pH-7** [comment]
Happy day @aquilax! 🎉 Better late than never, I'm creating a command line installer => https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/949

It will be available in the next release 🙂
