### ISSUE TITLE
Paid membership question

### ISSUE THREAD

**Issue by ultra-pool** [pH7Software/pH7-Social-Dating-CMS#730]
If a user clicks on a paid membership does this automatically move the member from free to paid after payment has been sent or does this have to be manually?

**Comment by Undefined-Variables** [comment]
Yes if the payment was successful they are automatically upgraded. 

Then the time of membership expires they are automatically downgraded! 

I’d advice you to fully test each payment method by completing a real transformation before you go to full production.

**Comment by ultra-pool** [comment]
The only use full one I see is paypal. The others Iv never heard of. But ill test it once ai get to that point.

**Comment by Undefined-Variables** [comment]
Yes PayPal is one option and the most known and easiest to set up but PayPal will make you jump though hoops and hold money just because they can! The others are just as well known how ever you probably don’t know they are involved in taking your payment as online retailers will take visa, MasterCard etc directly though there checkout but these companies are processing the payment on the behalf of the company you give your card number to. 

They all require you to register an account with them with the exception of bitcoin but looking at your profile I don’t think I need to explain this to you!

**Comment by Undefined-Variables** [comment]
![gateways](https://user-images.githubusercontent.com/52648055/78728935-9dbcab00-7930-11ea-869c-ea4e80b64d45.PNG)

Braintree, Stripe, Paypal TwoCheckOut are all payment gateway merchants that handle card payments... 

![braintree](https://user-images.githubusercontent.com/52648055/78729253-89c57900-7931-11ea-80cf-6ef990aeac66.PNG)
![2check](https://user-images.githubusercontent.com/52648055/78729256-8c27d300-7931-11ea-80cc-505c9d6a28c9.PNG)
![stripe](https://user-images.githubusercontent.com/52648055/78729264-8e8a2d00-7931-11ea-91b1-4e1a55586560.PNG)

This is basic stuff where transactions are involved using credit or debit cards and if you do own a bitcoin pool like you claim you would easily be able to install bitcoind on your server and use json-rpc to generate wallet addresses if your user wished to use btc to pay for your service. This is the best option on paper as tiny fees and no third party holding your money but in reality trying to get someone to pay for legal services with concurrency when they have a visa in their pocket is a fools erred. 

Paypal will find a reason to hold your money then suspend your account and by the time you have gone thought all their bullshit you will have waited months for money that is yours. Worst company in history, avoid them like Coronavirus!

**Comment by ultra-pool** [comment]
Yes I own my own mining pool along with other web sites and services crypto related. I do plan adding crypto payments to it. Along with other stuff. I was also going to look into adding google pay and apple pay as options. Maybe adding square payment for CC and debit cards.
