### ISSUE TITLE
The AlbumController controller of the video module is not found.

### ISSUE THREAD

**Issue by mchir** [pH7Software/pH7-Social-Dating-CMS#732]
**Describe the bug**
Hello guys,
I have not found on the internet a solution for the issue.
My installation on LAMP seems to be working in general but after I upload a video or try to access a video album as a user I get:

The AlbumController controller of the video module is not found.File: /var/www/html/tandem/_protected/app/system/modules/video/
--
File: | /var/www/html/tandem/_protected/framework/Mvc/Router/FrontController.class.php
Line: | 893
Trace: | #0 /var/www/html/tandem/_protected/framework/Mvc/Router/FrontController.class.php(622): PH7\Framework\Mvc\Router\FrontController->notFound('The AlbumCon...', 1) #1 /var/www/html/tandem/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter() #2 /var/www/html/tandem/index.php(46): PH7\Bootstrap->run() #3 {main}

/data/system/modules/video/files/user show that files uploaded are there.

Thanks in advance for your help

**To Reproduce**
1. Go to warsaw.ns0.it:8000/tandem/
2. Sign up as a user
3. try to upload a video

**Comment by Undefined-Variables** [comment]
I have tried and got no error message at all just loops back to the upload form. Can you copy and paste your logs here please.

**Comment by mchir** [comment]
Today everything seems to be working fine. The only significant change I have done it was increasing Mysql connection timeout. Maybe it was that.
Thanks anyway
