### ISSUE TITLE
SSL mixed content: images are served in http instead of https

### ISSUE THREAD

**Issue by mchir** [pH7Software/pH7-Social-Dating-CMS#735]
**Describe the bug**

I installed a SSL certificate by let's encrypt with Apache2 webserver on Ubuntu Linux.
When surfing the website I get the warning that the site contains mixed content and is not fully secure.

I tried to reinstall the script from httpS url just in case but everything stays the same.

Have I misconfigured something or the script was designed using for images src="http://" instead of relative urls? (I guess not)

Thanks in advance

**To Reproduce**

Just visit https://warsaw.ns0.it/tandem and click on the locker symbol at the right of the url

**Comment by Undefined-Variables** [comment]
Did you install using SSL?  

ie: https;//warsaw.ns0.it/tandem/_INSTALL/

If not delete _constants.php from the sites root then upload a new copy of the " /_INSTALL/" folder form the source and reinstall using https://example.com/_INSTALL

You will have to upload pictures again too

**Comment by Undefined-Variables** [comment]
> **Describe the bug**
> 
> I installed a SSL certificate by let's encrypt with Apache2 webserver on Ubuntu Linux.
> When surfing the website I get the warning that the site contains mixed content and is not fully secure.
> 
> I tried to reinstall the script from httpS url just in case but everything stays the same.
> 
> Have I misconfigured something or the script was designed using for images src="http://" instead of relative urls? (I guess not)
> 
> Thanks in advance
> 
> **To Reproduce**
> 
> Just visit https://warsaw.ns0.it/tandem and click on the locker symbol at the right of the url

Delete images and did you drop database or use the same one?

**Comment by Undefined-Variables** [comment]
![http](https://user-images.githubusercontent.com/52648055/79006009-0fbf0b00-7b50-11ea-9e58-b1f6a90eb0f0.PNG)

**Comment by Undefined-Variables** [comment]
Your logo bg and header are all http not https so delete them and start again

**Comment by mchir** [comment]
It was enough to upload the logo again as you suggested and it solved my issue without the need of reinstalling. Thank you for your help. The script is fully functional with SLL certificate and fully encrypted Mysql database. Testing this script has stimulated me to advance my amateur knowledge

**Comment by Undefined-Variables** [comment]
No problem glad I was able to help. 

Good luck

**Comment by polynamaude** [comment]
> It was enough to upload the logo again as you suggested and it solved my issue without the need of reinstalling. Thank you for your help. The script is fully functional with SLL certificate and **_fully encrypted Mysql database_**. Testing this script has stimulated me to advance my amateur knowledge. I appreciated it, thanks

### **_fully encrypted Mysql database_** !?!?!?

You shall go back to your books because in no way is the DB encrypted here...
