### ISSUE TITLE
Admin page can not load

### ISSUE THREAD

**Issue by Pavkebgd** [pH7Software/pH7-Social-Dating-CMS#739]
![d29b6a2e8d](https://user-images.githubusercontent.com/63584439/79109589-ee8d3300-7d78-11ea-8838-5b94c9421422.jpg)
**Describe the bug**
User page is working and everything is ok, but admin panel can not load, screenshot attached.
Any suggestions what might be wrong?
(a clear and concise description of what the bug is.)

**To Reproduce**

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)

**Comment by polynamaude** [comment]
@Pavkebgd What have you tried?  Go look on the wiki, there's a page called "how to get help".

You ask us for help but say nothing about your installation. This look not serious at all ! How you want us to answer? By guessing and using astrology?

**Comment by Pavkebgd** [comment]
I followed the installation instructions and completed installation successfully.

I can log in as user but admin panel is not loading.

Site is on Unix php 7.4, Apache 2.4. shared hosting.

I am not familiar with coding, if there is some most common solution to this problem, pls. give me some direction.

________________________________
