### ISSUE TITLE
Free chat room restriction to logged in users only

### ISSUE THREAD

**Issue by marcruiz** [pH7Software/pH7-Social-Dating-CMS#740]
Hi:)
I wonder whether the above mentioned subject can be restricted to logged in users only?
Free chat brings bad element
Thank you

**Comment by randomtech2** [comment]
Hello I ask myself the same question unfortunately there is that flashcoms community chat which does that which is unfortunately paid

**Comment by marcruiz** [comment]
Thank you

Any Chat suggestions that can be used instead and be restricted to 
logged in users only?

Thank you

**Comment by polynamaude** [comment]
@randomtech2 There's a possible user who had a solution. Ask Undefined-Variables or search closed issue.

**Comment by polynamaude** [comment]
@randomtech2 You can get a free Amazon Chime

**Comment by randomtech2** [comment]
@polynamaude yes if i am not mistaken it is this closed solution https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/612

**Comment by Undefined-Variables** [comment]
You can restrict any page to logged in members only by adding 

````
{if $is_user_auth}

<Normal Page Content>

{else}
<?php header("location:../../../login");
 ?>
exit();
{/if}
````

**Comment by Undefined-Variables** [comment]
Also if you set up the chat properly you can have usernames pulled over and used in the chat room. There is a full wiki on HTML5 Chat's website.

**Comment by Undefined-Variables** [comment]
I have HTML5 Chat for users set up and working, usernames are also carried accross... I will write a wiki page explaining how to set it up properly in the next few days.
