### ISSUE TITLE
suggestion: moderator member

### ISSUE THREAD

**Issue by randomtech2** [pH7Software/pH7-Social-Dating-CMS#741]
hi could you put a system that allows members to be only moderator without having administrator rights it is done a lot on dating sites

**Comment by polynamaude** [comment]
@randomtech2 Nothing prevent you from coding this feature.

**Comment by randomtech2** [comment]
um yes

**Comment by pH-7** [comment]
> hi could you put a system that allows members to be only moderator without having administrator rights it is done a lot on dating sites

By default, you will need to create new administrators (which aren't users) that will able to moderate the users contents. 

The 'main' reason is that the "Moderation Tools" are located in the admin panel.

Now, as @polynamaude said, you can always create a "moderation" module with different rights and allow some users with a specific membership to be able to access those 'privileges'. However, depending on your current website, it might be important or not, but in most cases, it's not a real problem. 

At the end of the day, you must trust your moderators (could be your friends, family, partner, ...), so it shouldn't be an issue to have them ad 'administrators'. And, please remember that all new admins you create will never be able to remove other admins. The only adnin that can remove other admin users are you (the first admin on the database).

**Comment by pH-7** [comment]
BTW @randomtech2, if you enjoy pH7CMS, it would be great if you can Star it (here, on GitHub) 😊
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)
