### ISSUE TITLE
Adding more genders in Ph7cms

### ISSUE THREAD

**Issue by MKDan** [pH7Software/pH7-Social-Dating-CMS#742]
Hi,

I like to add more genders such as "Sub Male", "Sub Female", "Dom Male', "Dom Female", "Switch Male", and "Switch Female".

Instead of - Male, Female and couple (or along with Male, Female and Couple)

How can I do it?

**Comment by Undefined-Variables** [comment]
This will require changes in coregendermodule, database, and mutliple changes in profile, search module and other places too. I am planing to add some extra genders soon so will explain more here when I do.

**Comment by pH-7** [comment]
Yes, unfortunately, this would involve database ENUM changes. 

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_install/data/sql/MySQL/pH7_Core.sql#L86-L87

At the moment, the ENUM only contains "male", "female", "couple". 
So, if you manually add some additional genders in the PHP form dropdown fields, it won't work as the current ENUM won't match with them.

Finally, it will also require some PHP modifications such as in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/core/classes/GenderTypeUserCore.php

**Comment by pH-7** [comment]
Anyway, if you aren't a PHP dev, I'm sure you will be able to find someone on a Freelance website (e.g., https://www.freshbooks.com/blog/freelance-jobs) that will be able to make those changes for 15~20 hours.

Good luck!

**Comment by pH-7** [comment]
P.S. Your profile image is great @MKDan Really like this kind of dog 😁, the Carlin pinscher...

**Comment by pH-7** [comment]
By the way @MKDan, if you enjoy pH7CMS, it would be amazing if you can Star it (here, on GitHub) 😊
![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by Undefined-Variables** [comment]
I plan on adding to the genders in the near future and will share how this is done on this issue once I have done so.

**Comment by MKDan** [comment]
> By the way @MKDan, if you enjoy pH7CMS, it would be amazing if you can Star it (here, on GitHub) 😊
> ![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

I've star it.

**Comment by skyfall96** [comment]
Interested too !

**Comment by Undefined-Variables** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/746

**Comment by pH-7** [comment]
Brilliant @Undefined-Variables  🤩

This is just an **AMAZING** "How To" issue!!!

**Comment by Undefined-Variables** [comment]
I have seen the question a few times so thought id explain.
