### ISSUE TITLE
Displaying "Taken" on profiles to stop unwanted messages

### ISSUE THREAD

**Issue by MKDan** [pH7Software/pH7-Social-Dating-CMS#745]
There will be many people who are recently in a relationship and don't want further requests/messages.

It can be highlighted on the profiles. Also, I want to highlight "Male Dom", "Female Sub", "Female Switch".

How can I do it?

https://i.imgur.com/4WzsPZ7.png
![Profile-taken](https://user-images.githubusercontent.com/16294954/79478814-7d27db80-8029-11ea-9fc0-37254eaf39e4.png)

**Comment by Undefined-Variables** [comment]
They can change there privacy settings 

/user/setting/privacy

This has already been thought about...
