### ISSUE TITLE
Profile signup "* How Old Are You?" registers a wrong date of birth

### ISSUE THREAD

**Issue by MKDan** [pH7Software/pH7-Social-Dating-CMS#747]
I observe that the question during registration 

> * How Old Are You?

- records the wrong date of birth. (It assumes the registration day as the birthday with the correct year)

I also not sure, is it possible to change the DOB later? (I don't think many people will change it later).

Isn't it better to ask the actual date of birth than age?

**Comment by Undefined-Variables** [comment]
You can change it in the admin panel! The format is American as in MM/DD/YY 

No you can't change DOB later as a normal user. Admin could directly in DB but why would this ever be needed?

**Comment by MKDan** [comment]
![How old are you](https://user-images.githubusercontent.com/16294954/79513292-1cb49080-8061-11ea-8546-805fa9acc678.PNG)

You can change it in the admin panel! ---> Do you mean I can change the question from "age" to "Date of birth" (or) I can change the date of birth of individual users?

why would this ever be needed? ----> There is the "Search people by birthday" option.

**Comment by polynamaude** [comment]
@MKDan Read back what @Undefined-Variables wrote... He said you can change the format of the date in the admin panel. He also said you cannot as a user modify your DOB after the account is created but the admin can do so.

**Comment by Undefined-Variables** [comment]
Yes what she said is what I ment.

**Comment by polynamaude** [comment]
@Undefined-Variables I don't use pH7CMS very often so there's stuff that I don't remember...

**Comment by Undefined-Variables** [comment]
What do you use? I assume you have an active dating site?

**Comment by polynamaude** [comment]
@Undefined-Variables Why would I have a dating site ? What do I have to offer more than what's already offered on the market ? The world is saturated with those type of offer, be it Badoo / Zoosk / Facebook or whatever...

**Comment by Undefined-Variables** [comment]
@polynamaude I just assumed you would have as you show lots of interest here. Do you run a website then? If so what is your site about? I'm just interested out of curiosity...

**Comment by Undefined-Variables** [comment]
You don't have to answer if you dont want to btw...

**Comment by polynamaude** [comment]
@Undefined-Variables Yeah, I have a website... more than one to be honest... 
One of them is some sort of résumé for what I do (software development and system analysis).
Another one is for my girlfriend (who's a writer / musician)...
Mine is currently offline for maintenance...
And I'm finishing one as a demo site for the Joomla extensions I wrote (including one that can help transform your Joomla into a dating site). Also, I've made a Joomla extension to share user base between pH7CMS and Joomla...

**Comment by Undefined-Variables** [comment]
Wow that is pretty cool! Do you then sell the extensions? or are they open source? You have to make a living somewhere along the line right, everything can't be open source or you'd never see any return for your hard work!

**Comment by polynamaude** [comment]
@Undefined-Variables All is open source. What I charge is support, service and custom development. The extension act as publicity because people come on my site to download or buy support.

**Comment by polynamaude** [comment]
@Undefined-Variables I saw you said money is start of evil.

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables I saw you said money is start of evil.

Yes I hate money and don't see why people go to such lengths to obtain it. As long as I have the basics I am happy. What I mean by basics is food, somewhere to call home and tobacco. I have no desire to be rich I think more money more problems...

**Comment by polynamaude** [comment]
@Undefined-Variables Get rid of tobacco

**Comment by Undefined-Variables** [comment]
Yeah I use a vape a lot more but can't seem to do without a morning fag!

**Comment by polynamaude** [comment]
@Undefined-Variables Morning one's a hard one because of the drug's half life is short

**Comment by Undefined-Variables** [comment]
Yeah that's it. Wake up gagging for a smoke, my meds don't help either! 

I'm installing Joomla on one of my spare domains, I have never tried it before... Just want to see what its like!

**Comment by pH-7** [comment]
> I observe that the question during registration
> 
> > * How Old Are You?
> 
>     * records the wrong date of birth. (It assumes the registration day as the birthday with the correct year)
> 
> 
> I also not sure, is it possible to change the DOB later? (I don't think many people will change it later).
> 
> Isn't it better to ask the actual date of birth than age?

Hey @MKDan!

Yes, it's a bit tricky. When it asks just the age, it's impossible to know the month or the day of birth. However, you can change it to the simple "calendar" from the admin panel.
Go to Setting -> General -> Registration section, then on "**Date of Birth field type**" option, change from "Age Range (without month and day of birth)" to "Date-Picker calendar (full date of birth)" option.

Finally, yes, since v15.2, users aren't able to update their own DOB from their settings, but admins can still do. From the admin panel, go to Users -> Browser -> Edit (and from there, you will see the Date Picker calendar to amend the DOB.

I hope it helps!

Good luck

**Comment by pH-7** [comment]
Hope this is fixed helps! 🤞
I will close it by now (since I didn't hear from you), but lease feel free to reopen it at any time if needed :)
