### ISSUE TITLE
Installing pH7-Social-Dating-CMS on Nginx with sub-folder

### ISSUE THREAD

**Issue by minh0583** [pH7Software/pH7-Social-Dating-CMS#748]
hi

I try to install pH7-Social-Dating-CMS on Nginx with sub-folder (ex: www.example.com/dating), but I got some missing css, javascript file in front-page. For admin site www.example.com/admin123/ i got 500 Error.

Is there anyway that we can set it up with sub-folder?

thanks
Micheal

**Comment by Undefined-Variables** [comment]
Unfortunately we don't offer support for Nginx. The software has been written and tested on Apache, Nginx requires a completely different setup. There is a Nginx configuration file included with the software have you read this? 

https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/nginx.conf

This is only a basic starting point but may give you some incite. I am happy to help should you swap over to Apache.

**Comment by polynamaude** [comment]
@minh0583 Sorry about this error but yes we do support Nginx and that is the reason behind the configuration file provided with the distribution. Some people get mix up between the "we" and the "I don't know that subject".

I'd suggest you search the closed issues and you will certainly find someone who had the same problem as you.

Have you looked to the Nginx website to know how you can modify base folder?

Do those thing and come.back with the result and we'll start from there.

**Comment by polynamaude** [comment]
@Undefined-Variables Nginx is faster than Apache under the need of serving static load (as the cache system deliver).

**Comment by Undefined-Variables** [comment]
@polynamaude Yes I know I have used it in the past but not flaunt in the configuration, I could configure it for my own use but not well enough to advice on.

**Comment by Undefined-Variables** [comment]
@polynamaude "We" is just used out of habit of speaking from the prospective of third person. We always comes across better. 

@minh0583  Sorry but I have been here a while and seen Nginx questions left sitting unanswered, its odd how others reply on the back of my reply and not on there own initiative hey!

**Comment by polynamaude** [comment]
@Undefined-Variables There's no "answer on your back", I answered when I saw the question and corrected the little misunderstanding.

The odd person is the one saying that he's never gonna come back on this forum and that his account is pending deletion by Github staff (because he can't on himself).

Cool down a bit

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables There's no "answer on your back", I answered when I saw the question and corrected the little misunderstanding.
> 
> The odd person is the one saying that he's never gonna come back on this forum and that his account is pending deletion by Github staff (because he can't on himself).
> 
> Cool down a bit

Sorry @polynamaude its not a big deal, think you just misunderstood my meaning, I was being sarcastic!

**Comment by polynamaude** [comment]
@minh0583 Hi !
Would be great to know if we helped you solve your problem. Just a reminder, "Thanks" is a free word and no one's obligated here !

**Comment by minh0583** [comment]
thanks for your help @polynamaude
