### ISSUE TITLE
when installed,it shows NO INTERNET CONNECTION  Whoops! Your server has to be connect to the Internet in order to get your website working.

### ISSUE THREAD

**Issue by batmannolove** [pH7Software/pH7-Social-Dating-CMS#75]
when installed,it shows NO INTERNET CONNECTION  Whoops! Your server has to be connect to the Internet in order to get your website working.
But the network connection is ok.

**Comment by pH-7** [comment]
Please check your connection again. If it shows that it means you or your sever doesn't have Internet. Please check out by visiting http://google.com
Then, please restart the installation from scratch
