### ISSUE TITLE
Substitute error in _protected/framework/Mvc/Request/Http.class.php

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#752]
Hi.

I have the following uri structure: _country_/asset/cron/96h/Database?

If _country_ e.g is _se_ and I try to run the Database  cron script the resulting uri becomes
asset/cron/96h/Databa?

 ```
public function requestUri()
    {
        $sUri = $this->getUri();

        // Remove the relative subfolder path and the first (left) slash
        $sRequestUri = ltrim($sUri, PH7_SH);

        $sRelative = ltrim(PH7_RELATIVE, PH7_SH);
        return str_replace($sRelative, '', $sRequestUri); // <-- Error 
    }

```

**Comment by pH-7** [comment]
Hi @digiloo!

Is `country` your domain name...? Just for myself to see it clearer, could you give me the FULL example URL you tried to request?

**Comment by digiloo** [comment]
The full URL is www.bogus.com/se .  The se part is added by mod_rewrite based on HTTP:Accept-Language

/ Hakan
