### ISSUE TITLE
Issue with https://www.bogus.com/se/mail/compose

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Social-Dating-CMS#756]
Sometimes it takes **_very_** long time before one get any response after the (mail)send button is clicked. 
This is especially noticeably with the Safari browser. It can sometimes take > **2 minutes** and sometimes it is momentarily.  This (both cases) happens also if one tries to send to a non existing user. 

Since I not am a frontend programmer I can't figure out where the problem lies. 

Any hints?

Regards
Digiloo

**Comment by Undefined-Variables** [comment]
How do you mean? When you click the send button what happens? Does it take a long time to load or do you mean something else?

**Comment by digiloo** [comment]
I mean the time between clicking on the send button and seeing the error box. The browser state waiting ...

**Comment by digiloo** [comment]
Anyone that has seen this or have a idea?

**Comment by Undefined-Variables** [comment]
Yes there is a couple of minor bugs, not seen this but if you send 10 messages in a row the system will flat refuse to send anymore. I am working on a major overhaul of both messenger and mail modules and will PR soon!

**Comment by digiloo** [comment]
Sounds good. Thank you!
