### ISSUE TITLE
location of  logfile - fakeprofile  pictures

### ISSUE THREAD

**Issue by virtualcrows** [pH7Software/pH7-Social-Dating-CMS#758]
Hi 

http://website/admin123/user/addfakeprofiles

i got the  message 

unable to write  logfile 

I am lost  in finding the  log  can someone tell me  in what folder  it  is  located 

Also i thought there were fake  profile  pictures  included  or  am I mistaken 

Thx for your  help ..

**Comment by Undefined-Variables** [comment]
Log is a little all over the place, there is one generated on server root and there is a log table in database, I would check permissions of your folders. 

Yes pictures are now included in the fake profile generator, have you installed using the latest release? Sounds like you may have permissions set incorrectly.

**Comment by pH-7** [comment]
Hey @virtualcrows 

I guess you might have some permissions issues with some folders. That's why the profile photos cannot be saved to your web server.

In order to see what's wrong with it, can you enable the development mode (Admin Dashboard -> Tools -> Environment Mode), and try again the action.

**Comment by virtualcrows** [comment]
Hi I tryed i understand  so now 2  quesrions`:

wich log  is  used  but he fake  profile  maker  - wich folder 

Where i can find the  images for the  fake profile 
 
This  is  my  output when i use  the  tool dev mode 

Thx 

Add Fake Profiles (with profile photo) Unable to write to log file

**Comment by Undefined-Variables** [comment]
Open a terminal and type...

**Comment by virtualcrows** [comment]
yes  thats all clear  but  my question is  wich folder  is it  in _protected or  in public  files  and what are the  names  of the  path  

THz

**Comment by Undefined-Variables** [comment]
The images are generated by a third party library that is part of the composer install. The profile pictures are saved in /public_html/data/system/modules/picture/img/username/1/   etc 

The easiest way forward for you is delete your _constants file and run the install again!

**Comment by virtualcrows** [comment]
yes  just  did  only  this  is the result  

Unable to write to log file

so where  should the  logfile  be wriiten in what folder  than i can set the  permissions  on 777

**Comment by Undefined-Variables** [comment]
The only log file is the error.log in your public root the log is held in the database! Put your site in to development mode by changing production to development in 

    /_protected/app/configs/config.ini

Then repeat the steps that led you to the error. Now you will be shown a trace of the fault. Paste that here and maybe I can help.

**Comment by polynamaude** [comment]
Setting any folder to 777 is a pretty bad idea ! Even more that logs leak much stuff

**Comment by Undefined-Variables** [comment]
Depends on the intended environment, yes 777 is not a wise idea on a live website but in this case I don’t think it’s going to harm! 

Technically you are right 777 is open to the universe!

**Comment by virtualcrows** [comment]
ok here we  go 
Cannot create "/home/THEWEBSTE /sites/www.domain/htdocs/data/system/modules/user/avatar/img/biglion718/" directory.
Please verify that the directory permission is in writing mode.
File:	/home/THEWEBSTE /sites/www.domain/_protected/framework/File/File.class.php
Line:	308
Trace:	

#0 /home/THEWEBSTE/sites/www.domain/_protected/app/system/core/classes/UserCore.php(176): PH7\Framework\File\File->createDir('/home/THEWEBSTE /si...')
#1 /home/THEWEBSTE /sites/www.domain/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(147): PH7\UserCore->setAvatar(19, 'biglion718', '/home/THEWEBSTE /si...', 1)
#2 /home/THEWEBSTE /sites/www.domain/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(60): PH7\AddFakeProfilesFormProcess->addAvatar(Array, Object(PH7\UserCore))
#3 /home/THEWEBSTE /sites/www.domain/_protected/app/system/modules/admin123/forms/AddFakeProfilesForm.php(29): PH7\AddFakeProfilesFormProcess->__construct()
#4 /home/THEWEBSTE /sites/www.domain/_protected/data/cache/pH7tpl_compile/admin123_88cdbdb6d78dc74357faed5361463c09/base/useraddfakeprofiles.cpl.php(19): PH7\AddFakeProfilesForm::display()
#5 /home/THEWEBSTE /sites/www.domain/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/THEWEBSTE /si...')
#6 /home/THEWEBSTE /sites/www.domain/_protected/data/cache/pH7tpl_compile/public_main/base/layout.cpl.phplayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('user/addfakepro...', '/home/THEWEBSTE /si...')
#7 /home/THEWEBSTE /sites/www.domain/_protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(361): require('/home/THEWEBSTE /si...')
#8 /home/THEWEBSTE /sites/www.domain/_protected/framework/Mvc/Controller/Controller.class.php(83): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/home/THEWEBSTE /si...')
#9 /home/THEWEBSTE /sites/www.domain/_protected/app/system/modules/admin123/controllers/UserController.php(108): PH7\Framework\Mvc\Controller\Controller->output()
#10 [internal function]: PH7\UserController->addFakeProfiles()
#11 /home/THEWEBSTE /sites/www.domain/_protected/framework/Mvc/Router/FrontController.class.php(660): ReflectionMethod->invokeArgs(Object(PH7\UserController), Array)
#12 /home/THEWEBSTE /sites/www.domain/_protected/framework/Mvc/Router/FrontController.class.php(618): PH7\Framework\Mvc\Router\FrontController->runController()
#13 /home/THEWEBSTE /sites/www.domain/_protected/app/Bootstrap.php(97): PH7\Framework\Mvc\Router\FrontController->runRouter()
#14 /home/THEWEBSTE /sites/www.domain/htdocs/index.php(46): PH7\Bootstrap->run()
#15 {main}

**Comment by Undefined-Variables** [comment]
Your permissions are the problem! Are you on shared hosting? If so open a ticket with your host and ask them to reset permissions on the folder you are using! Then install again from the start!

**Comment by virtualcrows** [comment]
Problem Solved THX !!!

**Comment by virtualcrows** [comment]
last question  before closing this  how  many fake profiles are there  in that file  ..

**Comment by Undefined-Variables** [comment]
You can ask for as many as you like to be created but there is only limited images and they will be used over and over again. 

The fake profiles feature is for testing and not intended for aiding the set up of dishonest dating sites!

**Comment by virtualcrows** [comment]
yes nice as a  test OK if  i walk into something again or find a  bug  i let you  know Thx again for your  help
