### ISSUE TITLE
module notes

### ISSUE THREAD

**Issue by daeressea** [pH7Software/pH7-Social-Dating-CMS#759]
Bonjour a tous.

N'ayant que de vagues notion en programmation, je suis un peu perdu.

Je souhaiterais modifier le module "notes", peut être en créant un nouveau module a partir de celui ci, pour qu'il s'affiche sous forme de vignettes (2 ou 3 colonnes selon l’écran de l utilisateur)  et modifier les champs que l utilisateur peut ou doit modifier.

Ma question est donc: ou et quels sont les fichiers que je dois modifier?

merci
___________________________
Good morning all.

Having only vague notions in programming, I am a bit lost.

I would like to modify the "notes" module, perhaps by creating a new module from it, so that it is displayed in the form of thumbnails (2 or 3 columns depending on the user's screen) and modify the fields that the user can or must modify.

So my question is: where and what files should I modify?

thank you
____________________________________

**Comment by pH-7** [comment]
Bonjour ! 🔆

Pour faire simple, vous allez devoir copier le module original "note" (situé [_protected/app/system/modules/note](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules/note) et renomer votre copie par un autre nom (par exemple *billets*).

Puis, pour modifier la mise en page souhaitée, une fois votre nouveau module fraichement créé, vous allez devoir modifier les fichiers de vue (.tpl) situé dans `_protected/app/system/modules/billets/views/base/tpl/*` (en prenant mon example de nom pour le module).


Dans un troisième temps, vous allez aussi pouvoir modifier les infos de votre module dans le `config.ini` situé dans le dossier `config/config.ini` de votre module.

Enfin, votre module sera accessible à l'adresse `https://mon-site.com/billets/` (en prenant toujours le nom d'exemple).


Bonne chance!

**Comment by pH-7** [comment]
P.S. N'oubliez pas de donner un Star à sur GitHub :)

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by afcom** [comment]
for the non french that are about to ..... here it is : 
Hello ! high_brightness

To make it simple, you will have to copy the original "note" module (located _protected / app / system / modules / note and rename your copy by another name (for example tickets).

Then, to make your desired layout for the module, once your new module has been freshly created, you will have to modify the view files (.tpl) located in "_protected / app / system / modules / tickets / views / base / tpl / * "(taking my example name for the module. So change tickets to the name of your module).

Thirdly, you will also be able to modify the info for your module in the config.ini located in the config / config.ini folder of your module.

Finally, your module will be accessible at https://mon-site.com/billets/ (always using the example name).

Good luck!

**Comment by polynamaude** [comment]
@afcom May I ask what's your .... about French people ?
Most of them are able to speak English much better than mosy of you guys can master French so your comment is pretty much non-sense.

**Comment by afcom** [comment]
oh please don't get me wrong and I apologize for the misunderstanding.

I myself don't speak french and I needed the answer for this post in
english. so I simply posted the translation for people like me to spare
them some time ...

:)

**Comment by Undefined-Variables** [comment]
@polynamaude you are right! I can say hello, goodbye, cat etc but I can read french pretty well! Not like you read it! My eyes scan for keywords and fill in the gaps in my mind!

Works pretty well!

**Comment by afcom** [comment]
Sorry to admit.
my french S**ks.
but I still drive Renault :))

**Comment by daeressea** [comment]
ok thanks to pierre henri for the answer. i 'll try this.
