### ISSUE TITLE
when finished installation, the index.php page is empty and console shows that : Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by batmannolove** [pH7Software/pH7-Social-Dating-CMS#76]
![n 2 4dhaqvk9l0 ihv 3yj](https://cloud.githubusercontent.com/assets/6482545/13083461/0b57b016-d510-11e5-96d5-c273e0a2ad92.png)

**Comment by batmannolove** [comment]
![i 4a 4ze02t p5fi 9m](https://cloud.githubusercontent.com/assets/6482545/13083499/45ae112e-d510-11e5-9865-6c6cfbd286ef.png)

**Comment by pH-7** [comment]
Your Web host config isn't OK for pH7CMS. Steps to do:

- Set development status -> Open /_protected/app/configs/config.ini
Change 
```
[mode]
    environment = production
```
to
```
[mode]
    environment = development
```

- Check if you have a log file in /_protected/data/log/
Open the file and copy/paste the text here in comment.


P.S. ALSO, "**Star**"and watch this repo Github to get the latest updates.

![star-it](https://cloud.githubusercontent.com/assets/1325411/13084933/af2bc502-d4d3-11e5-93a8-8b9668b41520.png)
