### ISSUE TITLE
Website Maintenance Page does not shown

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#761]
So far I have seen is there still an issue in the actual code regarding the Site Maintenance.
The function maintenance in the **Page.class.php** calls the function **setMaintenanceCodes** in the **Http.class.php**,
```
    public static function maintenance($iMaintenanceTime)
    {
        // Set the HTTP status codes for the Maintenance page
        Http::setMaintenanceCodes($iMaintenanceTime);

        // Prevent caching in the browser
        (new Browser)->noCache();

        // Inclusion of the HTML Maintenance page
        include PH7_PATH_SYS . 'global/' . PH7_VIEWS . PH7_DEFAULT_THEME . '/tpl/other/maintenance.html.php';

        // Stop script
        exit;
    }

```
but the function has the name  **setMaintenanceCode**

```
    public static function setMaintenanceCode($iMaintenanceTime)
    {
        header(static::getProtocol() . ' 503 Service Temporarily Unavailable');
        header('Retry-After: ' . $iMaintenanceTime);
    }

```
This results of course in an error.

**Comment by polynamaude** [comment]
@dimuller Can you do a PR?

**Comment by dimuller** [comment]
I'm not a contributor for this repository.

**Comment by polynamaude** [comment]
@dimuller Any person can make a pull request. It will be reviewed and integrated afterward.
This is a public repository.

**Comment by pH-7** [comment]
Great catch @dimuller!!! I REALLY appreciate your help 😊

PR merged by now https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/762
