### ISSUE TITLE
Suggestion: Not allow voting for own pictures, videos and albums

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#763]
At the moment is it possible to vote for the own pictures, videos and albums, what I believe that it's not good. Now only voting for the own profile is not allowed.

This feature is now already integrated in my fork. I can make a PR if you believe that it's of public interest.

**Comment by pH-7** [comment]
Great, please do so and I will be glad to review it :)

Indeed, it's not a bug, but actually it might be wrong to allow users to rate their own contents, so your PR is welcome! 🤗
