### ISSUE TITLE
Freichat integration

### ISSUE THREAD

**Issue by alainlab** [pH7Software/pH7-Social-Dating-CMS#766]
Hi
I strugling to make chat system and istant messaging work as aspected. Import users names, sex, possibly photos and so on. Html5 chat it's very nice and probably i gonna buy their service and ask them to do integration for me. But i would like to try even Freichat as, for what i've understood, is self hosted solution. I read a programmer here succede in this. Is there a possibility he's so kind  and magnianimous :) to share his code with us ?  i think a sort of driver is needed . I tried to contact Freichat people few times. But so far no replay. I'm asking because i don't have the knowledge to do it myself and i'm new to everything including Github. So forgive me if my behaviour could seem inappropiate. I have installed Ph7cms in a home server with Ubuntu  18.04 following a guide from internet and in an hosting to make some test. Then i was surprised of how  Ph7cms is  cool :) please help me

**Comment by polynamaude** [comment]
@alainlab There's stuff made for people of different level, we don't have resources to take people by the hand from the start and teach the all the wherabouts of running a dating site. We can help you with some specific questions.
Regarding the question of Freichat, I know a user of this site has integrated HTML5 Chat and it worked pretty well. You can find the discussion by looking at the closed issues.
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/740#issuecomment-614535144

**Comment by Undefined-Variables** [comment]
From what I remember it involves updating your composer .json to install the required library then you gave to pass an authentication token created by that new library as in a httprequest parameter like you would a Json api & what = how...

I will have a look for you asap

**Comment by alainlab** [comment]
@polynamaude First of all thanks for all the job you Ph7 and i suppose other programmers are doing. But i didn't ask to be taken by hand simply i know there's @dimuller who already did a great job in integrating Freichat https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/572#issuecomment-509634606 so even if i had the ability to integrate Freichat myself what's the point to do it again a second time? I think create the driver it's quite difficult task to code, but use it isn't (copy in some directory or install) and need just some minor information like db name user and password. It's the same reason because we are using Ph7cms instead to code it by the ground which it's impossible for me. Furthermore having the driver one can have a general idea of how things work in interacting with the database and Freichat, guy let's  share informations ! :D . Having different chat/im solutions which work out of the box with Ph7cms it's very nice and surely improve Ph7cms adoption

**Comment by alainlab** [comment]
@Undefined-Variables many many, but really many :) thanks

**Comment by dimuller** [comment]
I made the integration of freichat already.
You need a driver for pH7CMS on the freichat side and a small code sequence in the index.php file.
I can help if you need assistance.

**Comment by Undefined-Variables** [comment]
No you need to create an account at html5chat's site, you are given a 5 digit number that identify's you and your account. Register and have that number handy! 

I will explain now.

**Comment by alainlab** [comment]
@dimuller yes please i really appreciate. I think it can be very helpfull for others too. I don't know which is the best and more appropriate way to share the driver and the index.php modifications. Attach the files  here ? Or otherways tell me please how you want to proceed

**Comment by alainlab** [comment]
@Undefined-Variables ok I've the number and i  tatooed it on my hand too :D so happy to have all this stuff/chats to test thanks

**Comment by Undefined-Variables** [comment]
Sorry was called away. I will continue soon!

**Comment by Undefined-Variables** [comment]
Your _protected/app/system/modules/chat/controllers/HomeController.php should look like this with your details replacing the <placeholder> 

````

 ?php
/**
 * @author         Pierre-Henry Soria <ph7software@gmail.com>
 * @copyright      (c) 2012-2019, Pierre-Henry Soria. All Rights Reserved.
 * @license        GNU General Public License; See PH7.LICENSE.txt and PH7.COPYRIGHT.txt in the root directory.
 * @package        PH7 / App / System / Module / Chat / Controller
 */

namespace PH7;

use PH7\Framework\Mvc\Model\DbConfig;
use PH7\Framework\Parse\SysVar;
use PH7\Framework\Url\Url;

class HomeController extends Controller
{

    public function index()
    {

      // Sanitize values and set as empty.
      $cuser = "";
      $csex = "";
      $crole = "";
      $cimage = "";
      $cuser = $this->session->get('member_username');
      $csex = $this->session->get('member_sex');
      $cimage = $this->session->get('avatar');

      // Users Age to be displayed on chat profile.
      $cage = $this->session->get('member_age');

      // Service ID
      $cid = <5 Digit ID>;                                                                   // 5 Digit ID HERE
      // Password for HTML5-Chat HRTime\PerformanceCounter
      $password = '<YOUR PASSWORD>';                  // Html5Chat PASSWORD HERE

      // Use current users data to create the hash to be safely paseed to the chat servers API.
      $json = json_encode(array('webmasterid'=>$cid, 'password'=>$password, 'username'=>$cuser, 'gender'=>$csex, 'role'=>$crole, 'image'=>base64_encode($cimage)));

      // Encoded user data
      $curl= curl_init();
      curl_setopt_array($curl, array(
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => "https://jwt.html5-chat.com/protect/".base64_encode($json)
      ));

      $encoded = curl_exec($curl);
      $encoded_url = "https://html5-chat.com/chat/<5 Digit ID>/$encoded";                   // 5 Digit ID HERE

      // Pass all that info to the view.
      $this->view->page_title = t('Free Chat Room Dating');
      $this->view->meta_description = t('Free Online Dating Site with our Free Chat Room');
      $this->view->meta_keywords = t('chat, speed dating, meet singles, dating, free dating, chat room, chat webcam');
      $this->view->h1_title = t('Welcome to <span class="pH3">Free Chat Room</span> on <span class="pH0">%site_name%</span>');
      $this->view->chat_room = $encoded_url;
      //$this->view->load = $encodedUser

      $this->output();

    }
}

````

**Comment by Undefined-Variables** [comment]
In admin panel -> settings > api

Chat API 

    https://html5-chat.com/chat/<5 Digit ID>/%encrypted%

**Comment by Undefined-Variables** [comment]
Now add the library Freichat via composer.

**Comment by dimuller** [comment]
@alainlab, I just have seen a small problem in the latest freichat download which I want to investigate first. Once I'm ready I will give you instructions how to customize freichat.

But you could already start installing freichat. It should work even without customization.
Just follow the instruction and Cut and Paste the code, which they give at the end of the installation to the end of the pH7CMS index.php.
You can even test in a final step of the installation if freichat is working or not.

**Comment by alainlab** [comment]
@Undefined-Variables wow !! work like a charm :) :) thank you !!!!!!!! I'll not forget. I want just ask two final (very short questions :D ) when you have time . Is there a library i've to install with composer and in case which one? Because i think you used jwt encryption directly from html5chat site. But correct me if i'm wrong; like likely is :D. Final question :D: I saw you imported profile image to use in the chat avatars ? does it work for you to have the miniature of profile in chat ? because in my case i just have the usual black and white avatars

**Comment by dimuller** [comment]
1. **Download and Unzip freichat code**
Unzip freichat into your pH7CMS root directory, parallel to the _protected directory.
In case of Xamp in the htdocs directory.

1. **Freichat installation**
Open the freichat site in your browse and choose <**Install**>:
    - Step 1: Choose Customized
    - Step 2: Accept default directories
    - Step 3: Define database access
    - Step 4: Create tables
    - Step 5: Copy/Paste the code at the end of the pH7CMS index.php file

Code for Xampp installation:
```
<!--===========================FreiChat=======START=========================-->
<!--	For uninstalling ME , first remove/comment all FreiChat related code i.e below code
	 Then remove FreiChat tables frei_session & frei_chat if necessary
         The best/recommended way is using the module for installation                         -->

<?php
$ses=null;

if(!function_exists("freichatx_get_hash")){
function freichatx_get_hash($ses){

       if(is_file("C:/Xampp/htdocs/freichat/hardcode.php")){

               require "C:/Xampp/htdocs/freichat/hardcode.php";

               $temp_id =  $ses . $uid;

               return md5($temp_id);

       }
       else
       {
               echo "<script>alert('module freichatx says: hardcode.php file not found!');</script>";
       }

       return 0;
}
}
?>
<script type="text/javascript" language="javascipt" src="http://localhost/freichat/client/main.php?id=<?php echo $ses;?>&xhash=<?php echo freichatx_get_hash($ses); ?>"></script>
	<link rel="stylesheet" href="http://localhost/freichat/client/jquery/freichat_themes/freichatcss.php" type="text/css">
<!--===========================FreiChatX=======END=========================-->

```
after **$ses=null** insert the following code to save the member_id:

```
$sUID=Config::getInstance()->values['session']['prefix'] . 'member_id';
if (isset($_SESSION[$sUID])) { 
    if($_SESSION[$sUID] != null) {// Here null is guest 
        $_SESSION['userid'] = $_SESSION[$sUID]; 
        if(isset($_SESSION['userid'])) { 
            if($_SESSION['userid'] != null) { // Here null is guest 
                $ses=$_SESSION['userid']; //LOOK, now userid will be passed to FreiChat 
            } 
        } 
    } 
} 

```

1. **Customize freichat for ph7CMS**

Therefor replace **/* Custom driver */** section in the file **hardcode.php** with the following code:

```
/* pH7CMS driver */
$usertable='members'; //specifies the name of the table in which your user information is stored.
$row_username='firstName'; //specifies the name of the field in which the user's display name is stored.
$row_userid='profileId'; //specifies the name of the field in which the user's id is stored

```
1. **Freichat client configuration**

Finally open the freichat site and use <**Administer**> to configure the program.

**Comment by alainlab** [comment]
@dimuller I know you have a wife but i love you :D :D :D . I'll try everything and let you know. But i'm sure if something doesn't work it's just my fault. You're really great guys

**Comment by pH-7** [comment]
By the way, concerning Freichat integration, I got a food news. The support told me that they ‘soon’ soon create an integration for the software :)

![923FEBCE-A417-4308-8EC1-E65DD246A578](https://user-images.githubusercontent.com/1325411/81157365-3e52c900-8fca-11ea-97a6-e5d322dd01c9.jpeg)

**Comment by dimuller** [comment]
I offered them my assistance, but no response from them.

**Comment by alainlab** [comment]
@pH-7 that's a fantastic new :) thanks !

**Comment by alainlab** [comment]
@dimuller  i really appreciate your help and tried very hard to install Freichat in two different "places" a hosting and on a home server i put online with cname redirection. But without success. As i don't want to abuse of your kindness and time i'll wait for their integration. Just a quick curiosity :) to understand if the problem is some sort of thing/permission with my hosting or depend on what i wrote in Fraichat files: If i put in hardcode.php the three lines of the driver 

/* pH7CMS driver */
$usertable='members'; //specifies the name of the table in which your user information is stored.
$row_username='firstName'; //specifies the name of the field in which the user's display name is stored.
$row_userid='profileId'; //specifies the name of the field in which the user's id is stored

is it suppose to finish installation right ? Because in my case is sort of stuck in waiting just after i write credentials for database . But respond just if you have time you already did a lot thanks

**Comment by dimuller** [comment]
@alainlab what happened after the freichat installation Step2?
Did you see freichat working in the test window, which they showed after the installation?

**Comment by alainlab** [comment]
@dimuller I had to confess that at the beginning what you wrote me didn't make much sense and in my silliness i thought it was a chaotic explanation. Now i know that it's crystall clear. But i didn't see the page with the code freichat give to copy in index.php at the end of installation , simply freichat installation got stuck without an error message. Then i decided to go in easy steps and to follow a tutorial and make Freichat work standalone (at the beginning) to avoid for a moment the Ph7cms integration. Go Kiss to follow our Guru @pH-7 motto
https://www.youtube.com/watch?v=6MLySOm345g 

I installed in Xampp to be more close to your use scenario modifying the tutorial accordingly to Php7 (the tutorial has some function call removed like mysql_connect() no i don't know php just i made a lot of search :) and following logic ) but it gave me a 
an error message, i Tried then to go with php 5.6 and same error message.

Then finally i got a solution to make work Freichat 11 you have to substitute smart_ajax.php with an older version as suggested by Codologic 
https://codologic.com/forum/index.php?u=/topic/8974/error-on-install-freichat-corporate-to-localhost-mysql-php 

That's don't make sense to me but probably there's a reason i don't understand now.
So i had my installation finally working in Xampp 5.6 probably it'll work in Xampp 7.4 aswell given the same message error i had: Fatal error: Call to undefined function update_db() in /Applications/XAMPP/xamppfiles/htdocs/intranet/tools/freichat/installation/smart_ajax.php on line 1132

And then I'll try your solution in Ph7cms which now it's perfectly understandable. I think and hope everything it's going to work because till now the only problem seems related to the smart_ajax.php . Freichat look nice when finally integrated with Ph7cms'll will look even better :). I give you news soon thanks for now

**Comment by polynamaude** [comment]
@Undefined-Variables Just like that ?
If you don't have much clue about PHP why don't you start by learning the basis before trying to build a web platform. Because in the end, we'll be seeing all the problem you get and you expecting us to be your own customer support team !

And what will you do if user cause any type of problem ? If you don't know PHP then I doubt you know how to do testing for security so you don't get hacked.

**Comment by polynamaude** [comment]
@Undefined-Variables Sorry wrong name !

**Comment by alainlab** [comment]
@polynamaude i completly agree with you about the need i've to learn php. Anyway I'm not new to programming in general. Of course i don't consider you my customer support team . I don't have any customer at all :D . For the moment i was just interessed in make things works and i asked very general questions probably usefull to other people too. About security i don't have the knowledge right now, but i don't think it's an impossible task to learn rudiments or pay someone to take care of system administration in case things got serious. But I'm not in business at the moment so you worry without a real reason and in case i'll start to treat you like my customers support team (which never gonna happen) you'll have all the rights to be annoyed. Give me the time to be hacked first :D. Coming back to Freichat... Dear @dimuller i made some progress, i installed the chat and is working well in guest mode . To avoid others to have my same troubles the only problem in installation was that the last line of smart_ajax.php need to have braces removed . I don't know if it's a bug or anything but surely they know about this problem. Now i face with another problem when i put the the code  after $ses=null; in  index.php of ph7cms (the code to pass userid) the chat disappear. I modified hardcode.php in freichat according to your suggestion too. Anyway it's  just to let you know... if something come up in your mind is welcome. But i don't worry too much considering soon we'll have an official support for Ph7cms in Freichat

**Comment by polynamaude** [comment]
@alainlab Hi !
You can use PHP Code Sniffer, it does a great job for identifying issues in PHP code. If you know other languages than this would help you out.

Just like that, I don"t think the word soon is the good one. It's not because it's on the roadmap that it's gonna be done soon.

Maude

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables wow !! work like a charm :) :) thank you !!!!!!!! I'll not forget. I want just ask two final (very short questions :D ) when you have time . Is there a library i've to install with composer and in case which one? Because i think you used jwt encryption directly from html5chat site. But correct me if i'm wrong; like likely is :D. Final question :D: I saw you imported profile image to use in the chat avatars ? does it work for you to have the miniature of profile in chat ? because in my case i just have the usual black and white avatars

Hey sorry for delay in replying I have been reading but not been able to login, 2fa is a great idea until your phone gives up, should have sorted it out last time as this is not the first time! I am done with apple and their over protected mobiles! 

I have installed jwt with composer and set up so encryption happens on my server before anything is sent! The idea is to encrypt before sending accoss a public network such as the internet! 

I use usernames, avatars, sex and age from ph7cms and yes all works! 

Oh you also need to change chat api setting in admin panel ~ general settings ~ api to look like this

    https://html5-chat.com/chat/<YOUR ID>/%encrypted%

**Comment by dimuller** [comment]
@alainlab sorry to hear about your problems. I did not have to make changes to any file to get freichat working in guest mode. I just had to add the given code at the end of the pH7CMS index.php file, define the correct MySQL access data in Step 3 of the installation. I could already see freichat working together with the pH7CMS start page in the test window at the end of the installation.

Now for the pH7CMS integration make sure that all freichat tables are defined in the pH7CMS database.

With Xampp 5.6, which I use, the following code at the end of the pH7CMS index.php file should do it:
```
$ses=null;
$sUID=Config::getInstance()->values['session']['prefix'] . 'member_id';
if (isset($_SESSION[$sUID])) { 
    if($_SESSION[$sUID] != null) {// Here null is guest 
        $_SESSION['userid'] = $_SESSION[$sUID]; 
        if(isset($_SESSION['userid'])) { 
            if($_SESSION['userid'] != null) { // Here null is guest 
                $ses=$_SESSION['userid']; //LOOK, now userid will be passed to FreiChat 
            } 
        } 
    } 
} 

if(!function_exists("freichatx_get_hash")){
    function freichatx_get_hash($ses){
        if(is_file(FREI . 'hardcode.php')){
            require FREI . 'hardcode.php';
                $temp_id =  $ses . $uid;
                return md5($temp_id);
        }
        else {
            echo "<script>alert('module freichatx says: hardcode.php file not found!');</script>";
        }
        return 0;
    }
}
?>
<script type="text/javascript" language="javascipt" src="http://localhost/freichat/client/main.php?id=<?php echo $ses;?>&xhash=<?php echo freichatx_get_hash($ses); ?>"></script>
	<link rel="stylesheet" href="http://localhost/freichat/client/jquery/freichat_themes/freichatcss.php" type="text/css">
<!--===========================FreiChatX=======END=========================-->

```

finally if you define the table names in the hardcode.php file you should already be able to access the user data after a user logged in.

```
/* pH7CMS driver */
$usertable='members'; //specifies the name of the table in which your user information is stored.
$row_username='firstName'; //specifies the name of the field in which the user's display name is stored.
$row_userid='profileId'; //specifies the name of the field in which the user's id is stored

```
