### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by randomtech2** [pH7Software/pH7-Social-Dating-CMS#768]
Hello I put my site in https and I have the message your connection is not completely secure I saw that the site always loaded certain page in http how to solve this problem?

**Comment by dimuller** [comment]
Did you clear all browser cache and pH7CMS cache? Maybe there are still old http url references stored.

**Comment by randomtech2** [comment]
yes i did it it changes nothing these are mostly images like the site logo or css and js files
