### ISSUE TITLE
Question regarding the Wall

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#769]
So far I have seen does the so called **Wall** in the dashboard and start page displays at the moment comments made by other users, but this cannot be the only purpose.
In the **app\system\modules\user\assets\ajax\WallAjax.php** I have seen beside the **showCommentProfile** case also a **show** case, which displays content of the **MEMBERS_WALL** table.
There is also a **WallForm** and an **EditWallForm** in the user module, but I cannot find a reference to these forms. Does anybody have an idea what this Wall is good for and how to use it?

**Comment by randomtech2** [comment]
I think it's used for the background that the user can set

**Comment by dimuller** [comment]
Maybe, but where the user can define the content?
I played a lot with the software, but I did not find an option to define the wall content.

**Comment by randomtech2** [comment]
I didn't find it either

**Comment by Undefined-Variables** [comment]
Ajax is all over the software. Like In

     _protected/app/system/core/assets/ajax/

You will find like, rating ,smile, stat and validate core Ajax assets/libraries. Its used in the user module wall, setAjaxActivity and Api Ajax, then its used in messenger, messeges, comments, friends, note, newsletter, login, registration....

The list goes on. Guess you just can't escape the future... Skynet LOL
