### ISSUE TITLE
Question: Why use java script and ajax to write a comment onto the wall?

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#772]
I don't see any reason to display Comments on the Wall of the user start page and the user dashboard with java script and ajax instead of using the traditional way via template and design model. I think it is not necessary to show comments dynamically. It just produces more traffic and makes the the code less readable and understandable.
My philosophy is always to keep things as simple as possible, so I redesigned my version and it's just fine, looks like before and there is less activity on client and server side.

**Comment by polynamaude** [comment]
@dimuller pH7CMS was used as a basis for customized version the PH sold as services to user awhile ago.
So probably that was the start or framework for stuff he offered.

**Comment by polynamaude** [comment]
@dimuller But as you said, why make complex when we can keep simple. That's the KISS principles... or KISS the Queen if you're brittish.

**Comment by dimuller** [comment]
Thanks @polynamaude , so there is no special reason, just history.
Good to know that.

**Comment by Undefined-Variables** [comment]
> @dimuller But as you said, why make complex when we can keep simple. That's the KISS principles... or KISS the Queen if you're brittish.

Br

**Comment by pH-7** [comment]
Hi @dimuller 

Thanks for your question. 
I totally agree with you. I always try to keep it simple, stupid (KISS) as much as I can.

This is nothing related to the Pro version I was selling before.
The wall just shows real-time conversations by making ajax requests.
Because "comments" is a separate distinct module, the "user" module has to request it through ajax in order to avoid duplicating code (we don't want to duplicate what the "comment" module already does in the "user" module.

If you want to change to something different, you can edit the page https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/views/base/tpl/main/index.user.inc.tpl or enable the "User Dashboard" module (Admin Panel -> Mods -> Enable/Disable Modules -> Tick "User Dashboard").

**Comment by dimuller** [comment]
@pH-7 thanks for your comment. Now it's clear.
I did already as you suggested. I switched to dashboard as start page and moved the wall code also to the dashboard module in order to avoid duplicate code.
Thanks again. Appreciate your work and assistance!

**Comment by Undefined-Variables** [comment]
> I don't see any reason to display Comments on the Wall of the user start page and the user dashboard with java script and ajax instead of using the traditional way via template and design model. I think it is not necessary to show comments dynamically. It just produces more traffic and makes the the code less readable and understandable.
> My philosophy is always to keep things as simple as possible, so I redesigned my version and it's just fine, looks like before and there is less activity on client and server side.

Seriously? Ajax is awesome, when you post a comment it just appears like magic! Now if that is not an improvement on entire page loads and delay to receive updated info I don't know what is!

**Comment by Undefined-Variables** [comment]
> Hi @dimuller
> 
> Thanks for your question!
> I totally agree with you. I always try to keep it simple, stupid (KISS) as much as I can.
> 
> This is nothing related to the Pro version I was selling before.
> The wall just shows real-time conversations by making ajax requests.
> Because "comment" is a separate distinct module, the "user" module has to request it through ajax in order to avoid duplicating code (we don't want to duplicate what the "comment" module already does in the "user" module.
> 
> If you want to change to something different, you can edit the page https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/modules/user/views/base/tpl/main/index.user.inc.tpl or enable the "User Dashboard" module (Admin Panel -> Mods -> Enable/Disable Modules -> Tick "User Dashboard").
> 
> Hope it helps to see clearer 😊

Don't agree at all!

**Comment by polynamaude** [comment]
@Undefined-Variables I think that the reason to use AJAX is, as I said, the basis of something that could be expanded. For sure, the use of AJAX vs full reload is a good one.

Yes we can keep the code Sweet and Simple, without gettting rid of AJAX.
As a fact, I have huge doubt that "make the code easier to read" is a good reason to cut back on feature or not using the latest possibility offered.

But some people have big problem coding using pages using AJAX because of the asynchronous nature. To code a page that is sent and displayed ain't too hard, you always know the result. But coding something that is dynamically constructed is much harder.

When I talked about "pro" was only based on a vague feeling I've got. Still, when you have a page constructed of many items, you can use AJAX. I doubt we'd appreciate Gmail if it had to do a full reload everytime we asked to see the next email.

**Comment by Undefined-Variables** [comment]
Just because something is a challenge doesn't mean it shouldn't be done... Ajax is one of the webs future technology's that I have no doubt will become even more complex!

**Comment by dimuller** [comment]
@Undefined-Variables, just because it's modern it does not mean that it has to be used!
In MY site **Comments** ...
- are rarely used by the visitors,
- they are not really important for the recipient ...
- so the recipient can wait to see them on the next interaction with the site.

Yes, it's awesome if the comment just pops up like magic, .... but in case of MY website it's simply NOT necessary and it comes for a too high price.
Or can you justify to scan for an event periodically and use unnecessary server bandwidth for something what...
- most likely will not happen,
- is not important,
- and will become available anyway on the next user interaction?

I understand that it's a great feature in case of websites which remain open in the background, but this is not the case. MY users are looking around, chatting, socializing and when they have enough they leave the site.
Anyway! I did not remove the original code. If I see a change in the user behavior I can easily switch back to the dynamic version.

**Comment by Undefined-Variables** [comment]
Hey @dimuller sorry if what I said come across the wrong way I was just shocked you felt that way about the technology. You are quite right to have your own view on this.

Why are comments so unimportant to your users? Maybe you still have them hidden away behind a link on their profile pages? Allowing users to comment on aspects of each others profiles is one of the things that brings a website to life. The way they are displayed by default makes using them a chore. They need to be openly displayed on profile pages with a textarea for quick and easy use. 

By the way zero bandwidth is used by Ajax in this process as all that its doing is looking for anything new on the server. Sure it looks hectic in the console but there are thousands of processes running in the background just like this that you dont have a console to watch what is going on.

**Comment by polynamaude** [comment]
@dimuller When you say "Become available on the next user interaction"...
If I leave Github open and there's no AJAX then I'll never see if there's interaction until I choose to do a refresh.
If you want your website to only be static and never push to the possibility of having real interaction then for sure that's the way to go.

**Comment by Undefined-Variables** [comment]
@dimuller You can change the landing page to what ever you like by changing 

    $sUrlRelocateAfterLogin = Uri::get('user', 'browse', 'index');

in _protected/app/system/modules/user/forms/processing/LoginFormProcess.php

To whatever you like. I land on the Browse page myself.

**Comment by dimuller** [comment]
@Undefined-Variables, your comment did not come the wrong way. I appreciate every comment and opinion, even in case that I don't 100% agree.
You are right regarding the importance of comments. I did not hide the possibility to comment. No change to the original version. Users can comment on profiles which they visit (cool profile page). I just experienced, that this feature is rarely used by the community.
Regarding bandwidth you are of course right, but this periodical scanning of comments consumes server cpu time.
By the way! There was a reason why I started to investigate the comment topic.
You certainly know that I implemented a freichat integration. With freichat running comments did not show up anymore, so I looked for the reason.

**Comment by dimuller** [comment]
@polynamaude you are right! But as I mentioned. I observed that most of our visitors are active and don't just keep the site open.
So two reasons why I switched to the static version:

1. Users rarely comment on profiles

**Comment by dimuller** [comment]
@Undefined-Variables yes, I know about relocation. Why did you mention this feature?
I don't see a context with the comment topic.

**Comment by dimuller** [comment]
@Undefined-Variables and @polynamaude, I ask you for your opinion.
What is more important for a recipient, a comment or a message?
If I was a user I would be more interested in messages than in comments, but comments you get instantly, to see new messages you have to refresh the page.

**Comment by Undefined-Variables** [comment]
@dimuller it all comes down to way content is presented to the user, if adding a comment requires clicking a link to load another page to add a comment then when on a users profile you have to click another link to read the comments then no users will not use it... Its to much effort! But if we show comments directly on to the profile page and include a nice convenient textarea above then you will see users will comment more.

**Comment by dimuller** [comment]
@Undefined-Variables, you are right. Presentation is very important.
I list already the latest 10 comments (but without avatar and link to maintain the privacy) to invite other visitors of a profile page to add their comment .
Originally the cool profile page shows only the number of comments and you have to click on **Read the comments** to see them.

![profile1](https://user-images.githubusercontent.com/51194360/82558697-6c263900-9b98-11ea-951c-4c2e0b4590d4.png)

You can see another problem on the screen shot. It's not possible to give a score to the album due to a java script problem which I posted already with case #760. Unfortunately did I not yet find the reason.
