### ISSUE TITLE
css and protected directory

### ISSUE THREAD

**Issue by ph7ali** [pH7Software/pH7-Social-Dating-CMS#773]
I am new in programming by the way my major field is civil engineering but i am learning code for myself also and want to contribute in  project across the globe. 

I am trying  PH7CMS DATING for learning and what i found is , the css is not working . when I applied custom css code (bootstrap 4.4) then only general setting was displayed in admin homepage. 
more, the file manager system ( public file and protected files) is also not working in my chrome v 81.04.

what i expected is , no doubt to say that cms dating software is so far so goodd but it still needs improve in admin panels and the css design.
moreover, please check screesnshot attached.
I Heartly thank you.
![r1](https://user-images.githubusercontent.com/65395363/82038604-65438600-96c1-11ea-8759-63683031eac2.jpg)
![r2](https://user-images.githubusercontent.com/65395363/82038622-6d9bc100-96c1-11ea-915e-9b1eb5662667.jpg)

**Comment by pH-7** [comment]
Hey @ph7ali!

Welcome to the community! 🎉

Can you check for me if the Apache .htaccess has been correctly transfered to the root directory where pH7CMS is installed?

**Comment by ph7ali** [comment]
Yes i checked  it first.  I removed it so it shows first page.. then i put my own htaccess with just 3 to 4 lines  so it worked till homepage and after it it shows again same error. After it, i added new line of indexes so it worked. . But the problem later it became like malfunction and unsecured.  So What i did is  removed a small piece of code from htaccess. It was  for apache  version.   But I don't understand that my local server is running well its all services and function which is older version.  While my live host server is latest.  For me , Just need to work for css and few things in admin panel.  In admin panel i cannot deleted or aprove the users   . So i need to work on it in my way if i could find a solution. 
For my opinion, sonce an admin is a boss and master controller for a website  so the admon panel must be 0 failure chance. . Becaus if something wrong happens  nothing will be left  jst bcuz of a singke small mistake..

**Comment by polynamaude** [comment]
@ph7ali Hi !
The problem you are getting here is one that seems to be happening pretty often.
However we'd need at first that you do part of the job to get helped.
When you say "I removed some line","I changed some other","It kinda worked"... It is pretty hard for anyone to give you a hand there.
It sound like "Could you build me something like a bridge but underground, but not a tunnel. It's kinda to pass wire but not really either". I think you get the point here...
The clearer you are, the more chance you'll have to get helped.
We are all volunteers around here and we'll do our best. But the easiest you make it, the more chance you'll get to have a helping hand.
If you write in a clear fashion then this would also make it somewhat easier.

Not all software offer forward compatibility so some code working with older version of Apache may not work with the newer one. This is why we actually have conditional sections.

I give you a link to a page we wrote that should help you a bit...

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/%5BDRAFT%5D-Problem-Getting-Assets-(CSS-JS)-cURL

If you like the software, you can add a star on Github, that would be very nice from you and a reward for all those years of labor.

**Comment by polynamaude** [comment]
@ph7ali You can post some screenshot. This would be more useful than just saying you get error.

**Comment by ph7ali** [comment]
dear all , I am  seeking your guidence at all. I did following thing to fix it. I also request you to let me know if i did something wronng. Alike my above post i tried to explain best as i can.

1. uploadeded folders on live server normally without any failure or error.

2. the browser shows " Internal Server Error 500
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@domain.com to inform them of the time this error occurred, and the actions you performed just before this error."

More information about this error may be available in the server error log.

3.The htaccess is removed

4. website installed
 It show the text version of user index  and if i click to process more , it showed the error 404.(for example:page url/page.php not found)

5. the htaccess is places then, in same folder where i installed the site in my case folder was /public/"dating(installation folder)"

6.  I got internal server error again checkd log then added handler application x-httpd-php70

7.  uncomment and added  into root directory rewrite base  /dating/


8. I placed htaccess in root and found same errors 500 like in the step 2


9. I rearrange some code as following

""  AddHandler application/x-httpd-php70 .php
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /dating/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
  <IfModule mod_negotiation.c>
      Options +FollowSymLinks
        Options -MultiViews -Indexes
    </IfModule>
</IfModule> "
at the top of file just above the php flag url off <in myy case above the line 19>

10. It worked and logged into admin panel and went to users to delete or any operation for the users then it showed another message " Wrong parameter in URL!"


12 at last, i put following at the top
""
AddHandler application/x-httpd-php70 .php
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /dating/
RewriteCond %{REQUEST_FILENAME} !-f ( line 665 of original htaccess)
RewriteCond %{REQUEST_FILENAME} !-d
  <IfModule mod_negotiation.c>
      Options +FollowSymLinks
        Options -MultiViews -Indexes
    </IfModule>
</IfModule>"

13.finnally, it is working along with css and its function till the time i post at.
![error1](https://user-images.githubusercontent.com/65395363/82136856-b2de0100-982f-11ea-9b4e-5b691deb1a72.jpg)
![errror 2](https://user-images.githubusercontent.com/65395363/82136865-d608b080-982f-11ea-830b-9bec91025fab.jpg)
![error3](https://user-images.githubusercontent.com/65395363/82136868-f6386f80-982f-11ea-8154-1591a92ee630.jpg)
![error4](https://user-images.githubusercontent.com/65395363/82136872-02bcc800-9830-11ea-96cd-1d7f767d949f.jpg)

**Comment by meetingpote** [comment]
Hello,
I have the same problem as Ph7ali. No files have been modified. Ph7cms is in version 15.4 hosted on a shared server with IONOS / 1 & 1, I tested on two versions of PHP (7.2 / 7.3) with the same result. The solution given here "[DRAFT] Problem Getting Assets (CSS JS) cURL" does not work. I get 500 errors when I click on any link. However when I install locally with Uwamp everything works fine. I attach a screenshot of the result after installation.

![3DZW0ZZ5Ax](https://user-images.githubusercontent.com/65543274/82749746-ad426700-9dab-11ea-9b69-eba2b7af7a1c.png)

(Sorry for my English, it's a google translation).
Thanks for your help.
