### ISSUE TITLE
Splash window slideshow images drift within the frame

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#774]
The images of the slideshow of the splash page defined in **app\system\modules\user\views\base\tpl\main\index.guest.inc.tpl** slowly drift within the image frame due to a wrong width setting of **.img_reel img** in the **templates\themes\base\css\splash.css**.

![Splash](https://user-images.githubusercontent.com/51194360/82148761-0fb4d800-987f-11ea-8f44-1fba96be3144.png)

`.img_reel img {
    float: left;
    height: 300px;
    width: 588px;
}
`

The correct width would be 584px to avoid this effect.

584px works well for the login splash page, but I don't know if a modification has side effects at other locations of the site.

**Comment by pH-7** [comment]
Thank you for reporting this @dimuller! 😊 I really appreciate it.

P.S. Modification in there doesn't have any side effects elsewhere since `splash.css` is only used on the guest homepage and `img_reel` CSS class is only used for the slideshow.

**Comment by dimuller** [comment]
Welcome!
But I have overseen that there is another value for the smaller box. This one has to be changed too.

```
/* 1230px or less */
@media (max-width: 1230px) {
    .window {
        height: 200px;
        width: 393px;
    }

    .profiles_window {
        margin: 2px;
        max-height: 614px;
        max-width: 393px;
    }

    .img_reel img {
        float: left;
        height: 200px;
        width: 387px;
    }
}

```
In **.img_reel img** the correct **width** value is **387px** and not 393px.

Now there is only one problem left. If you make the window narrow until only a single column is left the slideshow column is completely messed up.

![splash](https://user-images.githubusercontent.com/51194360/82536735-2145fa80-9b73-11ea-9543-d17346d52b3d.png)
