### ISSUE TITLE
How to Add Mobile Money Payment gateway

### ISSUE THREAD

**Issue by richkayz** [pH7Software/pH7-Social-Dating-CMS#775]
Thanks for the software and the effort to make it better. I am still learning to program with intermediate PHP. Please advise me on the files to edit to add a new payment gateway. In my country, we mainly use Mobile-based USSD payments as in Mobile Money with extensive PHP implementation scripts and Libraries. How and where should I upload these scripts and where to edit to reflect this payment gateway for auto verification by the user

**Comment by pH-7** [comment]
Hey @richkayz 

Excellent question. 

This can only be done by modifying the source of the ["payment" module](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/app/system/modules/payment) and in [pH7Framework](https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/_protected/framework/Payment/Gateway/Api) (eventually, you could add a composer library such as Omnipay if available for that payment provider) and follow the same way like how I did for the current payment gateways available in the software.

You can also do it by forking this repo, do your changes, push it to your Github account and open a pull request to this repo with this new payment gateway. Don't forget to follow [pH7CMS's coding conventions](https://ph7cms.com/doc/en/code-convention).


Best of luck! 🍀

**Comment by Undefined-Variables** [comment]
Hire a developer as this is not as easy as you think, plus any code that handles payments or currency is always going to be high risk so getting wrong is not an option!
