### ISSUE TITLE
PAYMENT Options

### ISSUE THREAD

**Issue by ph7ali** [pH7Software/pH7-Social-Dating-CMS#777]
I want to integrate few payments options like ,paypal, payoneer, skrill, credit and debit cards system gateway. 

Let me to know the files and directories where I should work in.
Thank you.

**Comment by dimuller** [comment]
@ph7ali Paypal and Stripe exist already. If you want to add more check out the following module:
**_protected\app\system\modules\payment**

**Comment by ph7ali** [comment]
I tried about 6 hours to add module but could not short out the problem. It shows "invalid path id" . and when I direclty put my files into the  ".../protected\app\modules" admin panels shows two modules already installed "Hello world" and "my module payment" and when i try to uninstall both modules using admin panel so it  gives a message " uninstall finished. NO INSTRUCTION FILE FOUND" .
![module](https://user-images.githubusercontent.com/65395363/82728354-656d0280-9d0d-11ea-8130-800e6e26e06b.jpg)

![image](https://user-images.githubusercontent.com/65395363/82728320-3d7d9f00-9d0d-11ea-8ef0-19d561f1f2d4.png)


![module](https://user-images.githubusercontent.com/65395363/82728166-7406ea00-9d0c-11ea-8752-5eee0559b3aa.jpg)

**Comment by ph7ali** [comment]
I tried about 6 hours to add module but could not short out the problem. It shows "invalid path id" . and when I direclty put my files into the  ".../protected\app\modules" admin panels shows two modules already installed "Hello world" and "my module payment" and when i try to uninstall both modules using admin panel so it  gives a message " uninstall finished. NO INSTRUCTION FILE FOUND" .

![module](https://user-images.githubusercontent.com/65395363/82728430-b977e700-9d0d-11ea-9f3d-90deece8eb9f.jpg)
![module2](https://user-images.githubusercontent.com/65395363/82728443-c268b880-9d0d-11ea-8b4f-16877c5047fb.jpg)

**Comment by polynamaude** [comment]
@ph7ali Why are you creating a module if what you want is payment ??
All you have to do is modify (add) to the actual code.

**Comment by ph7ali** [comment]
First  thing, I really want to create a new module for payneer. 
2nd. I want to kill a question which rings my mind always that's Why we should need integration of 3rd party just for chat. 
My thoughts : software should be independent of 3rd party for chating. I mean I want to create a module to chat without integration of 3rd party supports that's API OR APP.  Thank you for pay attention. ..

**Comment by polynamaude** [comment]
@ph7ali Why use third party for chat ?
Because this require too much power to be run without a cloud infrastructure and if you have a cloud infrastructure, you ain't running pH7CMS or asking question here.

2nd... If you don't know what's the difference between an API (Application Programming Interface) and an APP (Application) then maybe you shall hire a developer because in the end, you'll just get hacked because you didn't sanitize your inputs or something like this.

**Comment by polynamaude** [comment]
@ph7ali Like I already said, you can just add to the actual payment system. The basis of Object Oriented programming is to make it easy to add new functions to existing system. So there's no need to build another module. You just add code to the actual payment module. That's it.

**Comment by ph7ali** [comment]
Thank you so much. .

**Comment by polynamaude** [comment]
@ph7ali What did you expect ? We take you by the hand learning the art of programming ? Don't wanna be rude but it's not really the place and we don't have much time.

If you wanna learn the hard way what it means to get unpolished code on the Internet and be hacked, you have plenty of example if you Google around. Unless you prefer to have fake hope of "everything is easy".

**Comment by ph7ali** [comment]
There is nothing like that in finally i want to say thank you so much to help me a lot.

**Comment by polynamaude** [comment]
@ph7ali You can surely host a small messaging system, for example there's UddeIM on Joomla that works pretty good.
If you really want to have something functional without much work or at least less then I suggest you search for "Joomla Community Builder".

**Comment by ph7ali** [comment]
I have already integrated Html5 chat. But , for the payment I preferred  new module.  But it's okay . I got it.

**Comment by Undefined-Variables** [comment]
Don't under estimate the power HTML5Chat gives you, no server load supporting communication, multiple layouts and complete access/devive/user control, its simple to set up and has good up time history. 

You have freedom and options use HTML5Chat from a completely new angle when you subscribe.

$8.33/m if you pay for the year in one payment.
