### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Pavkebgd** [pH7Software/pH7-Social-Dating-CMS#778]
Error when connecting to database during installation with following message:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

**Comment by meetingpote** [comment]
You had to do several installations in a row or return to the previous page during the installation. Empty your database and start over.
(Google Translate)

**Comment by Undefined-Variables** [comment]
You need to increase 


    max_execution_time = 3000;

in your php.ini configuration file or add this to your .htaccess file located in the server document root (public_html).

```` 
max_execution_time = 12000
max_input_time = 12000
memory_limit = 4096M

````

Remember to lower these again after installation has completed.

**Comment by polynamaude** [comment]
@meetingpote You can put 512M or at most 1024M for memory limit. The kid like to play hard... Never saw a PHP script using more than 1GB per instance, if so, you got memory leak and damn bad programming technique !

**Comment by Undefined-Variables** [comment]
I work hard and play harder! I was just giving a random example to allow installation and did say to lower afterwards 😎
