### ISSUE TITLE
Page does not display correctly after installation

### ISSUE THREAD

**Issue by meetingpote** [pH7Software/pH7-Social-Dating-CMS#779]
Hello,
After installation my page does not display correctly, as if CSS was not applied. . No files have been modified. Ph7cms is in version 15.4 hosted on a shared server with IONOS / 1 & 1, I tested on two versions of PHP (7.2 / 7.3) with the same result. The solution given here "[DRAFT] Problem Getting Assets (CSS JS) cURL" does not work. I get 500 errors when I click on any link. However when I install locally with Uwamp everything works fine. I attach a screenshot of the result after installation.

![3DZW0ZZ5Ax](https://user-images.githubusercontent.com/65543274/82789950-7fbcf280-9e6b-11ea-85b2-949fddbe1484.png)

**Comment by polynamaude** [comment]
@meetingpote We are not super-heros... We can't guess what you are running on...
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
