### ISSUE TITLE
Custom development 

### ISSUE THREAD

**Issue by Recoil2** [pH7Software/pH7-Social-Dating-CMS#783]
Hi, 
I need your system but I need some modifications. I need men having to pay for Tokens and then use 1 token per message. Is this possible and if yes what would it cost? I also need to keep track of the amount of messages woman receive in order to pay them a commission on messages received. Then also if possible I need a referral system. If a woman invites another woman to sign up, she also receives commission on the messages the second woman receives.

Looking forward to your reply,
Regards

**Comment by Undefined-Variables** [comment]
Yes this is possible but is a lot of work! What is your budget?

**Comment by Recoil2** [comment]
Give me a quote and I will see if I can raise the budget
