### ISSUE TITLE
MAXMIND

### ISSUE THREAD

**Issue by DBLBASE** [pH7Software/pH7-Social-Dating-CMS#786]
Hello,

Your link to MAXMIND:
 http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

does not work anymore:
Message:

"Free GeoLite2 Database Users: Due to upcoming data privacy regulations, we are making significant changes
to how you access free GeoLite2 databases starting December 30, 2019"

Currently on another Website I use the following library:

https://ip-api.com

You can see from this link, there is no database to load
 free for 45 requests / minute
 or  € 13.3/month

Of course, I cannot integrate this script into your pH7CMS

Basic example:

    function get_ip() {
    	// IP if shared internet
    	if (isset($_SERVER['HTTP_CLIENT_IP'])) {
    		return $_SERVER['HTTP_CLIENT_IP'];
    	}
    	// IP behind a proxy
    	elseif (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    		return $_SERVER['HTTP_X_FORWARDED_FOR'];
    	}
    	// Otherwise: normal IP
    	else {
    		return (isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '');
    	}
    }

    $real = get_ip();

$query = @unserialize(file_get_contents('http://ip-api.com/php/'.$real));
if($query && $query['status'] == 'success')
{
    //result:
    echo $real;  // or $query;
    echo "<br />";
    echo $query['country'];
    echo "<br />";
    echo $query['regionName'];
    echo "<br />";
    echo $query['city'];
    echo "<br />";
    echo $query['zip'];                      
}

**Comment by polynamaude** [comment]
@DBLBASE Why can't you integrate ?

**Comment by polynamaude** [comment]
@DBLBASE What prevent you from doing a integration and making a PR  ?

**Comment by DBLBASE** [comment]
I can't get my script to work in the Geo.class.php file

**Comment by polynamaude** [comment]
@DBLBASE That's really precise as a way we can know what doesn't work. As good as my computer don't work.

**Comment by pH-7** [comment]
Hey @DBLBASE 

Why don't you stick with the current Lite GeoIP database provided by default with the software?

It is true that MaxMind doesn't distribute their Geo DB freely anymore, since Dec 30th 2019

However, fortunately for pH7Builder, it got the last freely version released by MaxMind in early December 2019. That version works very well, and is still very recent for a geo database (geo database doesn't have to be updated every month. Geo lat/lng don't change quite often).
