### ISSUE TITLE
There is no admin folder

### ISSUE THREAD

**Issue by Seojobb** [pH7Software/pH7-Social-Dating-CMS#79]
I need some help. After installation there is no admin folder.
What is wrong ???

**Comment by pH-7** [comment]
http://ph7cms.com/doc/en/how-to-go-to-admin-panel

P.S. On the last page if  the installer, the admin link is showing.

**Comment by Seojobb** [comment]
There is no link to admin after installer and there is no admin folde on my server. Strange.

**Comment by pH-7** [comment]
Is in on your local machine or do you have the URL where pH7CMS is installed?

**Comment by pH-7** [comment]
@Seojobb FYI, when you finished the installation you see the following (screenshot)
![screenshot from 2016-03-08 23 17 33](https://cloud.githubusercontent.com/assets/1325411/13619959/1181402c-e584-11e5-95bb-0a526c9911ec.png)

**Comment by pH-7** [comment]
and then the admin panel (http://ph7cms.com/doc/en/how-to-go-to-admin-panel)
![admin](https://cloud.githubusercontent.com/assets/1325411/13619983/329f457e-e584-11e5-8883-419c511094f4.png)

**Comment by Leanna107** [comment]
thank you so much, I was struggling with this issue until I found the fix. Worked beautifully.
