### ISSUE TITLE
Change the ph7cms Site name font

### ISSUE THREAD

**Issue by SinglesCave** [pH7Software/pH7-Social-Dating-CMS#790]
How to change the site name font  for the ph7cms script... And/or change site name to an image. 
Any suggestions. Thanks

**Comment by Undefined-Variables** [comment]
The template file that the site name is in is 

    /templates/themes/base/tpl/top_menu.inc.tpl

You need to make changes at line 25

````
<div role="banner" id="logo" class="navbar-brand">
     <h1>
         <a href="{{ $design->homePageUrl() }}" title="{slogan}">
         {site_name}
         </a>
     </h1>
</div>

````

To change the style give it a class like...

````

<div role="banner" id="logo" class="navbar-brand">
     <h1 class="newlook">
          <a href="{{ $design->homePageUrl() }}" title="{slogan}">
          {site_name}
          </a>
     </h1>
</div>

```

Then in 

    /templates/themes/base/css/layout.css

Add this

````
.newlook a {
    font-family: Arial, Helvetica, sans-serif; /** or what ever font you want **/
    font-size: 26px;  /** or what ever font size you want **/
    color: #ff9999; /** or what ever color you want **/
}

````

This is 3 basic rules but the sky is the limit to how you want it to look.
Adding a logo image in the admin panel will add a small image to the site or you could do something like...

```` 
<div class="navbar-brand newlook">
          <a href="{{ $design->homePageUrl() }}" title="{slogan}">
              <img src="{{$root_url}}/static/img/my-logo.png" alt="{site_name}" width="200px" height="200px" />
          </a>
</div>

````

Don't forget to upload the image to the src dir as above. The width and height can be done as above or add this to the same stylesheet

````
.newlook img {
    width: 200px;
    height: 200px;
    /** Plus more css if you want! **/
}
````

Pretty simple really hope this helps...

**Comment by pH-7** [comment]
Great explanation @Undefined-Variables 💯

@SinglesCave If you have any issues seeing the new changes, please try to clear the caches as well https://www.ph7cms.com/doc/en/how-to-clear-caches (cache problems could occur, especially if the enabled template is another one than the 'base' default one).

**Comment by SinglesCave** [comment]
Hello, 
Awesome.. But it only worked in the admin area, not the front end... I did the cache reset but still no change on the front end. 
SinglesCave.com

**Comment by Undefined-Variables** [comment]
Manually remove all the folders here 

    /_protected/data/cache/*delete all these folders*

This is the cached files, the folders will be generated automatically on the next page load.

You will have to clear your browsers cache (history) too.

**Comment by SinglesCave** [comment]
Hello again, 
I have deleted all folders within... and cleared browser caches many times..
and still sames results, mobile doesn't change on neither side.... 
![Image1](https://user-images.githubusercontent.com/67323926/85619633-956f3480-b630-11ea-9199-92a48beb1b44.png)
![Image2](https://user-images.githubusercontent.com/67323926/85619644-9acc7f00-b630-11ea-8da4-8978aee7a467.png)

image1  is the font I'm trying to get
image2 is the original..
singlescave.com  can you see which image it is displaying?
thanks

**Comment by Undefined-Variables** [comment]
When going to that URL it redirects to 

````
https://click-now-on-this.online/lp/edchargin/lp4/?tag=66100&tag1=software_udate&tag2=15444355&tag3=66100&tag4=dating&clickid=f8f158a9fc96eef701b8519406b39e1e-4888-0624&device=Desktop&brand=Desktop&model=Desktop&country=GB&affid=66100&subid=15444355&ln=en&cid=%7Bsk%7D&useragent=%7Bvar:useragent%7D&ip=5.67.224.249&bv=Chrome%2083&as=pc
````

**Comment by Undefined-Variables** [comment]
What is the name of that font?

**Comment by SinglesCave** [comment]
Font Lucida Calligraphy

**Comment by Undefined-Variables** [comment]
Right this is for logged in users and changes when logged in

To do the same on the front page you need to change the following below in 

    /templates/themes/base/tpl/layout.tpl (Line 94)
````
 {if $is_guest_homepage}
          <div class="row">
              <div role="banner" id="logo" class="col-md-8">
                  <h1 itemprop="name">
                      <a href="{{ $design->homePageUrl() }}">{site_name}</a>
                  </h1>
              </div>
          </div>
 {/if}

````
To this

````
 {if $is_guest_homepage}
          <div class="row">
              <div role="banner" id="logo" class="col-md-8">
                  <h1 itemprop="name" class="newlook">
                      <a href="{{ $design->homePageUrl() }}">{site_name}</a>
                  </h1>
              </div>
          </div>
 {/if}

````

**Comment by Undefined-Variables** [comment]
Also not sure what how your Lucida Calligraphy looks like that cos googling it shows a standard font style.

You should give more than one font incase a device is unable to use the first choice so 

            font-family: Lucida, Helvetica, sans-serif;

This says use Lucida but if not use Helvetica etc...

**Comment by SinglesCave** [comment]
It's working perfectly...
Thank you so much for solving my problem..

**Comment by SinglesCave** [comment]
Is there a mobile side that I need to edit like this for the mobile phones?

**Comment by Undefined-Variables** [comment]
Glad I could help you. 

Mobile... No you will see this meta tag set in the layout

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />

This instructs the browser to set the inner page width to the outer page width (sets page content to the same width as the devices screen size). This means the user will not have to scroll horizontally or zoom out to see the hole page. Having to scroll sideways or zoom out is considered poor user experience.  

Any content that doesnt fit in is not included for mobile view by using the if statement (in smarty template style) around the content. this stops it being used in mobile devices.

````
        {if !$browser->isMobile()}
        THE CONTENT TO EXCLUDE
        {/if}

````

The menus are collapse in to a single dropdown (burger button).

So no the site as it stands is mobile ready and even includes a full pwa that allows users to add a shortcut to there devices home screen.

**Comment by Undefined-Variables** [comment]
Not sure why @pH-7 has set the

````
maximum-scale=1

````

option as it can cause issues on some devices when it comes to flipping landscape on smart phones and is not recommended to be used... I'm sure there is a good reason.

**Comment by SinglesCave** [comment]
Hello again,
It looks like I need to use an image for the logo title on the frontend of the site, so I tried using what you gave me for the /templates/themes/base/tpl/top_menu.inc.tpl  but that didnt work, how would it work on the frontend (/templates/themes/base/tpl/layout.tpl)? 
Thanks
