### ISSUE TITLE
My sitemap keeps dissapearing on my website.

### ISSUE THREAD

**Issue by Spearo552** [pH7Software/pH7-Social-Dating-CMS#791]
Keep getting this:    URL xml/sitemap/xmllink' doesn't exist or isn't a valid XML file.

**Comment by pH-7** [comment]
Hey @Spearo552 

Thanks for reporting it. 
It might be caused by the config of your server. Do you mind to paste your sitemap URL here, so I can check it for you?

**Comment by pH-7** [comment]
Hi again @Spearo552 

Please let me know if your issue still occurs. You could also send a full screenshot of your problem if you prefer :) 

Don't hesitate to give us further details, so we could help you better.


Enjoy your weekend 🎉 

Take care,

Pierre
