### ISSUE TITLE
During install Error connecting to your database. could not find driver [Step 5/7]

### ISSUE THREAD

**Issue by breisig** [pH7Software/pH7-Social-Dating-CMS#792]
**Describe the bug**
I am attempting to install from scratch. I am using php 7.3.19 + MySQL 8.0.19. If I attempt to checkout the latest version from git today ( pH7CMS 16.0.0 ABSOLUTE™ - Build 1) and run the installer. It seems at stage 5, it seems when filling out the data and saying to generate the profiles, it shows the following error message.

```
Error connecting to your database.
could not find driver
```

Even though when I check mysql, i see it created the tables.

If I try filling out the form again and clicking next, it says the following error message.

```
Error connecting to your database.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'ph7_admins.PRIMARY'
```

**Comment by Undefined-Variables** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'ph7_admins.PRIMARY'

This means the script started and had inserted some data into the database but the failed to fully exicute. So you have rows in some tables but not all. 

Drop the database and increase the max time a script is allowed to run in your php.ini configuration file.

You can start again by deleting _constants.php from your servers root directory, then you can run the installer again.

**Comment by breisig** [comment]
I already had max execution time and memory limit upgraded before installing. Here are the values from phpinfo();

```
max_execution_time | 12000
max_input_time | 12000
memory_limit | 1024M
```

Its just weird that when I first try installing that it starts creating tables but then errors out with

```
Error connecting to your database.
could not find driver
```

Obviously is *did* connect and find a driver to connect to mysql.

**Comment by Undefined-Variables** [comment]
Try...

max_execution_time = 12000
max_input_time = 12000
max_input_vars = 12000
memory_limit = 2048M
post_max_size = 2048M

**Comment by breisig** [comment]
I think i found out the issue. My config still had my old memory_limit=512M which was cached even thought I had changed it to memory_limit=1024M. I also had to removed the " parse_ini_file()" from my disable_functions restriction so the main page would load. Once I had restarted nginx+php-fpm, its now installs. 

Thank you @Undefined-Variables

**Comment by Undefined-Variables** [comment]
Oh yes nginx has its own micro cache, that has caused me a few issues too :) Best of luck!
