### ISSUE TITLE
Mutual Friends Error

### ISSUE THREAD

**Issue by Undefined-Variables** [pH7Software/pH7-Social-Dating-CMS#793]
We have this error in the database error log table and I don't really understand why this has been done in this way???

I have changed identifing info like the username, ip and table name.

````

{"Time":"07-06-2020 08:30:22","IP":"127.0.0.0","UserAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/127.0.0.1 Safari\/537.36","UrlPag":"https:\/\/domain.com\/mutual-friends\/username","Query":"mutual-friends\/username","Message":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '`<subquery2>`.`profileId` + `table_prefix`.`f`.`friendId` - 1740'","Level":"22003","File":"\/home\/domain\/_protected\/app\/system\/core\/models\/FriendCoreModel.php","Line":88}

````

if you json_decode this for easier veiwing you get this...

````

"Time":"07-06-2020 08:30:22",
"IP":"127.0.0.0",
"UserAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/127.0.0.1 Safari\/537.36",
"UrlPag":"https:\/\/domain.com\/mutual-friends\/username",
"Query":"mutual-friends\/username",
"Message":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '`<subquery2>`.`profileId` + `table_prefix`.`f`.`friendId` - 1740'",
"Level":"22003",
"File":"\/home\/domain\/_protected\/app\/system\/core\/models\/FriendCoreModel.php",
"Line":88

````

The offending function in model looks like this...

````

    public function get($iIdProfileId, $iFriendId = null, $mLooking, $bCount, $sOrderBy, $iSort, $iOffset, $iLimit)
    {
        $bCount = (bool)$bCount;
        $iOffset = (int)$iOffset;
        $iLimit = (int)$iLimit;
        $mLooking = trim($mLooking);
        $bDigitSearch = ctype_digit($mLooking);

        $sSqlSelect = !$bCount ? '(f.profileId + f.friendId - :profileId) AS fdId, f.*, m.username, m.firstName, m.sex' : 'COUNT(f.friendId)';
        $sSqlLimit = !$bCount ? 'LIMIT :offset, :limit' : '';

        $sSqlWhere = '(f.profileId = :profileId OR f.friendId = :profileId)';
        if (!empty($iFriendId)) {
            $sSqlWhere = 'f.profileId IN
           (SELECT * FROM (SELECT (m.profileId)
           FROM ' . Db::prefix(DbTableName::MEMBER_FRIEND) . ' AS m
           WHERE (m.friendId IN (:profileId, :friendId))
           UNION ALL
               SELECT (f.friendId) FROM ' . Db::prefix(DbTableName::MEMBER_FRIEND) . ' AS f
               WHERE (f.profileId IN (:profileId, :friendId))) AS fd
               GROUP BY fd.profileId HAVING COUNT(fd.profileId) > 1)';
        }

        $sSqlSearchWhere = '(m.username LIKE :looking OR m.firstName LIKE :looking OR m.lastName LIKE :looking OR m.email LIKE :looking)';
        if ($bDigitSearch) {
            $sSqlSearchWhere = '(m.profileId = :profileId AND f.friendId= :profileId) OR (m.profileId = :friendId OR f.friendId= :friendId)';
        }

        $sSqlOrder = SearchCoreModel::order($sOrderBy, $iSort);

        $rStmt = Db::getInstance()->prepare(
            'SELECT ' . $sSqlSelect . ' FROM' . Db::prefix(DbTableName::MEMBER_FRIEND) . 'AS f INNER JOIN' . Db::prefix(DbTableName::MEMBER) .
            'AS m ON m.profileId = (f.profileId + f.friendId - :profileId) WHERE m.ban = 0 AND ' . $sSqlWhere . ' AND ' . $sSqlSearchWhere .
            $sSqlOrder . $sSqlLimit
        );

        $rStmt->bindValue(':profileId', $iIdProfileId, PDO::PARAM_INT);

        if ($bDigitSearch) {
            $rStmt->bindValue(':looking', $mLooking, PDO::PARAM_INT);
        } else {
            $rStmt->bindValue(':looking', '%' . $mLooking . '%', PDO::PARAM_STR);
        }

        if (!empty($iFriendId)) {
            $rStmt->bindValue(':friendId', $iFriendId, PDO::PARAM_INT);
        }

        if (!$bCount) {
            $rStmt->bindParam(':offset', $iOffset, PDO::PARAM_INT);
            $rStmt->bindParam(':limit', $iLimit, PDO::PARAM_INT);
        }

        $rStmt->execute();

        if (!$bCount) {
            $mData = $rStmt->fetchAll(PDO::FETCH_OBJ);
        } else {
            $mData = (int)$rStmt->fetchColumn();
        }
        Db::free($rStmt);

        return $mData;
    }

````

So we take f.profileId add it to  f.friendId then subtract the profile Id  :profileId to me thias makes no sense and not sure how to solve this problem?

**Comment by pH-7** [comment]
Leave it with me. I will have a look again to that one. I wrote this query a very long time ago, and need some time to understand exactly the way how it works. Mutual friends can be quite tricky. I will read it again, but first I will get some sleep :) It's getting late for me.

**Comment by Undefined-Variables** [comment]
No problem, thank you :)

**Comment by Undefined-Variables** [comment]
Any luck with this @pH-7 ?

**Comment by Undefined-Variables** [comment]
I am also trying to get friends requests to stay in the pending state until it has been approved but this is causing me problems, when someone clicks add friend they are automatically added to the users friends list from their prospective, on the other user side it asks approve/delete. The variables $is_pending_friend and $is_approved_friend don't reflect the status they both return false or true/false in the wrong order??? This is confusing me and I have spent so much time on this... 

Reason I need approval before being seen as a friend is I have customized user profiles to be private, evaeryone and approved friends. Currently you can approve yourself just by requesting friendship which totally misses the point of only allowing friends to see your profile! 

I have tried this on newest version and 4 previous versions and they are all doing the same thing....

**Comment by pH-7** [comment]
> Any luck with this @pH-7 ?

Right now, nothing. But I will still dig into it further.

**Comment by Undefined-Variables** [comment]
LOL not getting very far with this are we...

**Comment by polynamaude** [comment]
@Undefined-Variables We are getting farhter and further away from the date it got opened ? Was that the kind of comments you'd expect !
LOL ;-)

I will make a graph in UML regarding how the process work. And from there maybe we could do some refactoring. Because now it's somewhat misleading.

**Comment by Undefined-Variables** [comment]
I am going to end up scraping the old query and doing it again in a way I understand!

**Comment by polynamaude** [comment]
@Undefined-Variables That's why we do UML schematics in the industry. And also we document not only the code itself but the process.

My things are settling now so I'll take a look.
But I'm really thinking about going with Community Builder...

**Comment by Undefined-Variables** [comment]
I do want to launch a site using CB. Mainly to see the difference and to see if its anymore popular as a platform in terms of usability, speed and effort to maintain it. Its just very expensive for what it is.

**Comment by Undefined-Variables** [comment]
This is still a problem

**Comment by polynamaude** [comment]
@Undefined-Variables Don't say that...
First rule of politics : Don't talk about a problem for long enough and people will forget it.

Sorry, I have big doubt on any kind of planning for this software as this type of error is one that show up when you design the software.

**Comment by Undefined-Variables** [comment]
@polynamaude I don't think anyone is interested in this... This works fine until the number of user friends hits a larger int... Give up!

**Comment by polynamaude** [comment]
@Undefined-Variables What do you mean ? Larger integer ?

**Comment by Undefined-Variables** [comment]
It works until the ID reaches 2000 ish... the error in the DB reads...

````
"Time":"07-06-2020 08:30:22",
"IP":"127.0.0.0",
"UserAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/127.0.0.1 Safari\/537.36",
"UrlPag":"https:\/\/domain.com\/mutual-friends\/username",
"Query":"mutual-friends\/username",
"Message":"SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '`<subquery2>`.`profileId` + `table_prefix`.`f`.`friendId` - 1740'",
"Level":"22003",
"File":"\/home\/domain\/_protected\/app\/system\/core\/models\/FriendCoreModel.php",
"Line":88
````

The data type is 'int'(10) so I am not sure why we get a bigint error...

**Comment by polynamaude** [comment]
@Undefined-Variables WoW ! Looks like the author if this software has lots of interest in this specific bug.
When someone "no where" dude write that he has problem with using a slovenian letter in username then in 24 hours he gets an answer and the promise it's gonna be look over at...
But when a bug arise that lie deeply inside the software because he screwed up on planning somewhere... Oh my god... wait for a damn long answer and expect to "shake it" every 7-14 days to make sure the ticket stays alive...
Do I laugh or cry ?

**Comment by Undefined-Variables** [comment]
Yeah @polynamaude you have a point here and I am inclined to agree with you! I am going to rewrite this myself... Lot more work than solving this problem but I have to be honest and say I don't understand the way this query has been written and why it has been done in this way! It is far more simple to start again and in a way I understand!

**Comment by polynamaude** [comment]
@Undefined-Variables There's so much interest in helping US solve this problem.

**Comment by polynamaude** [comment]
@Undefined-Variables Here's a hint...
http://nikolaynaychov.blogspot.com/2012/08/how-to-fix-mysql-error-bigint-unsigned.html#:~:text=but%20you%20get%20ERROR%201690,value%20is%20out%20of%20range.&text=The%20unsigned%20range%20is%200,store%20the%20result%20%2D%20just%20displaying.

Probably you know more of the software than me but this look the possible reason this show off.

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables There's so much interest in helping US solve this problem.

@polynamaude this issue has been open for months and until I get a response I'm not spending my time answering any issue. Why should be handle 90% of the problems if when we need some advice we just get ignored? How are you any how? Hope you are doing okay! I have been working hard lately so have not had much free time. Things should start to slow down with the new year...

**Comment by polynamaude** [comment]
@Undefined-Variables I don't think the problem is solved... is it ???
