### ISSUE TITLE
Admin and Member login problem

### ISSUE THREAD

**Issue by dimuller** [pH7Software/pH7-Social-Dating-CMS#794]
From several modules the function **framework\Mvc\Model\Engine\Util\Various.class.php>checkModelTable($sTable)**
is called to check a table, which is not listed in the switch case.

I found the following locations:
- framework\Mvc\Model\Security.class.php >addLoginLog - MEMBER_LOG_LOGIN
- framework\Mvc\Model\Security.class.php >checkLoginAttempt - MEMBER_ATTEMPT_LOGIN
- system\core\models\UserCoreModel.php >getLastUsedIp - MEMBER_LOG_SESS
- system\modules\admin123\forms\processing\LoginFormProcess.php>__construct ADMIN_ATTEMPT_LOGIN

I had to add these tables to the checkModelTable($sTable) in order to be able to login as member or admin.

It worked for me with the following code, but I'm pretty sure that there are more locations or tables which have to be added.

```
    public static function checkModelTable($sTable)
    {
        switch ($sTable) {
            case DbTableName::MEMBER:
            case DbTableName::AFFILIATE:
            case DbTableName::ADMIN_ATTEMPT_LOGIN:
            case DbTableName::ADMIN_LOG_LOGIN:
            case DbTableName::ADMIN_LOG_SESS:
            case DbTableName::MEMBER_ATTEMPT_LOGIN:
            case DbTableName::MEMBER_LOG_LOGIN:
            case DbTableName::MEMBER_LOG_SESS:
            case DbTableName::MEMBER_INFO:
            case DbTableName::AFFILIATE_INFO:
            case DbTableName::MEMBER_COUNTRY:
            case DbTableName::AFFILIATE_COUNTRY:
            case DbTableName::SUBSCRIBER:
            case DbTableName::ADMIN:
                return $sTable;

            default:
                static::launchErr($sTable);
        }
    }

```

**Comment by Undefined-Variables** [comment]
I already have them all in mine...

````

  const ADMIN = 'admins';
    const MEMBER = 'members';
    const MEMBERSHIP = 'memberships';
    const AFFILIATE = 'affiliates';
    const SUBSCRIBER = 'subscribers';
    const MEMBER_INFO = 'members_info';
    const AFFILIATE_INFO = 'affiliates_info';
    const MEMBER_PRIVACY = 'members_privacy';
    const MEMBER_NOTIFICATION = 'members_notifications';
    const MEMBER_COUNTRY = 'members_countries';
    const AFFILIATE_COUNTRY = 'affiliates_countries';
    const BLOCK_IP = 'block_ip';
    const BLOCK_COUNTRY = 'block_countries';
    const AD = 'ads';
    const AD_AFFILIATE = 'ads_affiliates';
    const PICTURE = 'pictures';
    const VIDEO = 'videos';
    const ALBUM_PICTURE = 'albums_pictures';
    const ALBUM_VIDEO = 'albums_videos';
    const ANALYTIC_API = 'analytics_api';
    const BLOG = 'blogs';
    const BLOG_CATEGORY = 'blogs_categories';
    const BLOG_DATA_CATEGORY = 'blogs_data_categories';
    const NOTE = 'notes';
    const NOTE_CATEGORY = 'notes_categories';
    const NOTE_DATA_CATEGORY = 'notes_data_categories';
    const COMMENT_BLOG = 'comments_blog';
    const COMMENT_NOTE = 'comments_note';
    const COMMENT_PICTURE = 'comments_picture';
    const COMMENT_VIDEO = 'comments_video';
    const COMMENT_GAME = 'comments_game';
    const COMMENT_PROFILE = 'comments_profile';
    const FORUM = 'forums';
    const FORUM_CATEGORY = 'forums_categories';
    const FORUM_TOPIC = 'forums_topics';
    const FORUM_MESSAGE = 'forums_messages';
    const LANGUAGE_INFO = 'languages_info';
    const LIKE = 'likes';
    const LOG_ERROR = 'log_error';
    const ADMIN_ATTEMPT_LOGIN = 'admins_attempts_login';
    const MEMBER_ATTEMPT_LOGIN = 'members_attempts_login';
    const AFFILIATE_ATTEMPT_LOGIN = 'affiliates_attempts_login';
    const ADMIN_LOG_LOGIN = 'admins_log_login';
    const MEMBER_LOG_LOGIN = 'members_log_login';
    const AFFILIATE_LOG_LOGIN = 'affiliates_log_login';
    const ADMIN_LOG_SESS = 'admins_log_sess';
    const MEMBER_LOG_SESS = 'members_log_sess';
    const AFFILIATE_LOG_SESS = 'affiliates_log_sess';
    const MEMBER_BACKGROUND = 'members_background';
    const MEMBER_WHO_VIEW = 'members_who_views';
    const MEMBER_FRIEND = 'members_friends';
    const MEMBER_WALL = 'members_wall';
    const MESSAGE = 'messages';
    const MESSENGER = 'messenger';
    const META_MAIN = 'meta_main';
    const SYS_MOD_ENABLED = 'sys_mods_enabled';
    const MODULE = 'modules';
    const REPORT = 'report';
    const SETTING = 'settings';
    const STATIC_FILE = 'static_files';
    const CUSTOM_CODE = 'custom_code';
    const GAME = 'games';
    const GAME_CATEGORY = 'games_categories';

````

**Comment by dimuller** [comment]
Should be!
I just downloaded the latest version from Github,
installed it and got this problem.
Or does the download version not contain all updates?

**Comment by pH-7** [comment]
> From several modules the function **framework\Mvc\Model\Engine\Util\Various.class.php>checkModelTable($sTable)**
> is called to check a table, which is not listed in the switch case.
> 
> I found the following locations:
> 
>     * framework\Mvc\Model\Security.class.php >addLoginLog - MEMBER_LOG_LOGIN
> 
>     * framework\Mvc\Model\Security.class.php >checkLoginAttempt - MEMBER_ATTEMPT_LOGIN
> 
>     * system\core\models\UserCoreModel.php >getLastUsedIp - MEMBER_LOG_SESS
> 
>     * system\modules\admin123\forms\processing\LoginFormProcess.php>__construct ADMIN_ATTEMPT_LOGIN
> 
> 
> I had to add these tables to the checkModelTable($sTable) in order to be able to login as member or admin.
> 
> It worked for me with the following code, but I'm pretty sure that there are more locations or tables which have to be added.
> 
> ```
>     public static function checkModelTable($sTable)
>     {
>         switch ($sTable) {
>             case DbTableName::MEMBER:
>             case DbTableName::AFFILIATE:
>             case DbTableName::ADMIN_ATTEMPT_LOGIN:
>             case DbTableName::ADMIN_LOG_LOGIN:
>             case DbTableName::ADMIN_LOG_SESS:
>             case DbTableName::MEMBER_ATTEMPT_LOGIN:
>             case DbTableName::MEMBER_LOG_LOGIN:
>             case DbTableName::MEMBER_LOG_SESS:
>             case DbTableName::MEMBER_INFO:
>             case DbTableName::AFFILIATE_INFO:
>             case DbTableName::MEMBER_COUNTRY:
>             case DbTableName::AFFILIATE_COUNTRY:
>             case DbTableName::SUBSCRIBER:
>             case DbTableName::ADMIN:
>                 return $sTable;
> 
>             default:
>                 static::launchErr($sTable);
>         }
>     }
> ```

This function only checks the "user" tables (admins, members, affiliates, subscribers, and their info data).

**Comment by pH-7** [comment]
@dimuller Before changing the code, what error did you get when you were trying to login?

**Comment by pH-7** [comment]
Probably something like `Message:	Invalid data table: "admins_attempts_login"!`?

**Comment by pH-7** [comment]
It seems you are using the v16 Beta version @dimuller. I REALLY appreciate this! 🎉 Thanks for reporting this bug. It is actually an issue introduced by some refactoring changes in Beta1 and Beta 2 versions.

**Comment by pH-7** [comment]
Patch: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/b837c25852f13cbeb4b522c4ef360ca4d6f0ee52

**Comment by dimuller** [comment]
@pH-7 yes, exactly!

Below you can see what I got when I tried to login as memeber:

**Message: | Invalid data table: "members_attempts_login"!
-- | --
File: | C:\Xampp\htdocs\ph7cms\_protected\framework\Mvc\Model\Engine\Util\Various.class.php
Line: | 259**

**Comment by dimuller** [comment]
Oh, there is another one which I did not mention yet.
Possibly it's fixed already.

You get the following error when you login:

Message: | SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profileId' in 'field list'
-- | --
File: | C:\Xampp\htdocs\ph7cms\_protected\framework\Mvc\Model\Security.class.php
Line: | 116

In the file **Mvc\Model\Security.class.php** function **addSessionLog** refers to **profileId** and **firstName** fields which don't not exist in the table members_log_login. Instead the username should be inserted.
I just got the username from the profileId and then it worked.

Maybe the problem is fixed already. I did not crosscheck!

**Comment by pH-7** [comment]
> Oh, there is another one which I did not mention yet.
> Possibly it's fixed already.
> 
> You get the following error when you login:
> Message: 	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profileId' in 'field list'
> File: 	C:\Xampp\htdocs\ph7cms_protected\framework\Mvc\Model\Security.class.php
> Line: 	116
> 
> In the file **Mvc\Model\Security.class.php** function **addSessionLog** refers to **profileId** and **firstName** fields which don't not exist in the table members_log_login. Instead the username should be inserted.
> I just got the username from the profileId and then it worked.
> 
> Maybe the problem is fixed already. I did not crosscheck!

Wow! Thanks for pointing this other issue out @dimuller. Nope, it hasn't been fixed yet, but I will work on it this evening 🤗

If you find another bug like this, please let me know and I will patch another fix before the stable release of v16. Thanks again. You rock! 💯

**Comment by pH-7** [comment]
@dimuller 

In `Security.class.php`, line 104, try to replace the method signature, from:
```php
public function addSessionLog($iProfileId, $sEmail, $sFirstName, $sTable = DbTableName::MEMBER_LOG_LOGIN)
```
to
```php
public function addSessionLog($iProfileId, $sEmail, $sFirstName, $sTable = DbTableName::MEMBER_LOG_SESS)
```

The last default parameter was not the correct database name.

**Comment by dimuller** [comment]
@pH-7 Oh! Of course! That was obvious and it works.
For now no more problems, but I will check some more functions and keep you informed if I find something ;)

**Comment by pH-7** [comment]
> @pH-7 Oh! Of course! That was obvious and it works.
> For now no more problems, but I will check some more functions and keep you informed if I find something ;)

You are amazing!

**Comment by Undefined-Variables** [comment]
Now I'm slightly confused as I seem to have completely different framework to what you two are refering too. Think I way older framework 😣

**Comment by Undefined-Variables** [comment]
Where can I see the version I can remember.

**Comment by dimuller** [comment]
@Undefined-Variables, like @pH-7 mentioned we were working on **V16 Beta2**.
I downloaded the complete framework and faced the mentioned problems.
I was also a bit confused when you posted your **const ADMIN**, which had nothing to do with the problem.

**Comment by Undefined-Variables** [comment]
@dimuller What I mean is shouldn't the newer releases of the framework have all that the previous releases have plus more? Just seemed to me a lot had been removed from code that had no issues and works nicely. Its better to add to rather than removing because if you start to remove code you make the updating process very difficult for anyone who is running a custom production site and has to manually update rather than just downloading and installing fresh each time.

I included everything as an example so you could see what I had compared to you and almost left admin out but then thought it was better to include the entire picture!

**Comment by dimuller** [comment]
@Undefined-Variables you are right, but for my part I have not seen many things removed in the new build. At least no parts which I'm using in my custom version.
To update a custom version is as you said not an easy process and in fact I have to do it manually and a detailed description of the modifications is necessary.
For this reason I always keep a clean ph7CMS version on my computer to see what has changed, but also to compare the original code with my custom version in case of problems.
If a new version is released I do always a fresh start to see the whole picture. In this case it was very useful and could cover up some bugs.

Your constant is a summery of all tables of the system, but like in case of the checkModelTable function you should check only for a subset of the tables. Or am I wrong?

**Comment by Undefined-Variables** [comment]
@dimuller Yeah I have to do manual updates for anything I add. My custom site has evolved in to an entirely different beast but occasionally I see something added to the master repo that I feel is adding to my site or is a security patch and I personally don't have a problem doing it in this way. However I know there are administrators running this CMS that would find such updates a problem so when making changes we have to consider everyone. 

Yes you are correct. I have a little time now and like to give back to the project so will finish the messaging module first.

**Comment by dimuller** [comment]
@Undefined-Variables in this case we are in a similar situation.

You are working on the messaging module? You mean the instant messaging? That would be very good!
