### ISSUE TITLE
how delete the disclamer avertissement

### ISSUE THREAD

**Issue by djmaster44** [pH7Software/pH7-Social-Dating-CMS#798]
![cats](https://user-images.githubusercontent.com/68409708/87751906-6434ef00-c7ff-11ea-8532-d45646427401.jpg)
How delete this please ; my website is not a adult website thanks

please reply at : dejaymaster48@hotmail.com

My site : https://mixnfunradio.fr/Tchat/

**Comment by pH-7** [comment]
Hey @djmaster44 

How are you so far?

In `templates/themes/base/tpl/layout.tpl` and remove
```html
      {* To avoid scammers *}
      {if $is_user_auth AND $current_url != $url_root}
        <div class="warning_block center">
          <p>
            <strong>{lang 'Attention!'}</strong>
            {lang 'Some of the women (or men) profiles you see on dating sites might be scams to collect money.'}<br />
            {lang 'People who are really interested in you will never ask for money.'}<br />
            {lang "Be careful, don't send the money to anybody!"}
          </p>
        </div>
      {/if}
```
from line 165 to 176

Hope it helps! 

Enjoy your weekend!

**Comment by djmaster44** [comment]
yes Thanks you very mutch !!! Enjoy your weekend too
