### ISSUE TITLE
Getting 403 Forbidden on CSS after fresh install using nginx.

### ISSUE THREAD

**Issue by breisig** [pH7Software/pH7-Social-Dating-CMS#800]
I just installed the latest pH7-Social Dating from git today and noticed that my menu system is broken with 1 file returning a 403 403 Forbidden.
(example: http://mywebsites.com/asset/gzip/?t=css&d=templates/themes/datelove/css/&f=menu_inverse.css returns 403 Forbidden) 

yet this file returns a regular 200
(http://mywebsites.com/asset/gzip/?t=css&d=static/css/js/jquery/box&f=box.css ).

It seems its just that one file that's returning a 403.

**Comment by Undefined-Variables** [comment]
Have you configured nginx correctly? Try signing in to admin -> tools -> cache settings and disable Gzip and try again. 

You may have to add to nginx configuration to get Gzip working correctly!

**Comment by breisig** [comment]
I have signed into my site and went to Admin->Tools-> Cache and disabled Gzip and all the other caching options just to be on the safe side..  Now I don't get a 403 error codes anymore but the page is still broken.  Looking at the developer tools in Firefox, I see all files give a 200 ok status but the following files are 0 byte files

- /asset/css/color.css [0 bytes]

It looks like color.css content is empty. When I look at my browser developer console, it says

```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. contentInject.js:5251:17
Uncaught SyntaxError: expected expression, got '<' gzip:2
Uncaught SyntaxError: expected expression, got '<' gzip:2
Uncaught SyntaxError: expected expression, got '<' gzip:2
Source map error: Error: request failed with status 404
Resource URL: http://dating.mytestsite.com/static/js/jquery/jquery.js
Source Map URL: jquery.min.map
```
And I also see a message "Style Sheet could not be loaded. http://dating.mytestsite.com/assets/css/color.css". The console mentioned something about a 4040 for jquery.js so as another test, I am try to see if I can view "http://dating.mytestsite.com/static/js/jquery/jquery.js" directly in my browser and it works as I see the contents of the file.

My nginx config is basic as follows as its running under a chroot environment. All other images are working.
```
server {
        listen 80;
        server_name dating.mytestsite.com; 
        access_log /var/log/nginx/pH7Builder.access.log main;
        error_log /var/log/nginx/pH7Builder.error.log;
        root /var/www/nginx-chroot/html/pH7Builder;
        index index.php;

        client_max_body_size 50M;

        # Main Document Root Path
        location / {
         try_files $uri $uri/ /index.php?$args;
         index index.php;
        }

        # Deny access to hidden items. (.htaccess, .htpasswd, .*) files.
        location ~ /\. {
         #access_log off;
         log_not_found off;
         deny all;
        }

        location ~ \.php$ {
         try_files $uri /index.php =404;
         fastcgi_index index.php;
         fastcgi_pass unix:/var/run/php-fpm.sock;
         fastcgi_param SCRIPT_NAME /html/pH7Builder$fastcgi_script_name;
         fastcgi_param PATH_INFO $fastcgi_path_info;
         fastcgi_param SERVER_NAME $host;
         fastcgi_param SCRIPT_FILENAME /html/pH7Builder$fastcgi_script_name;
         fastcgi_param HTTP_PROXY "";
         include fastcgi_params;
        }
}
```

Any other ideas?

**Comment by Undefined-Variables** [comment]
Have you emptied browser cache and the server cache?

Delete all the files found in 

    _protected/data/cache/*

Then delete firefox's cache (firefox is a bit naughty and lies about data it holds on to so try chrome aswell) Also when you right click -> page source and click a link can you see the scripts?

**Comment by breisig** [comment]
I tried that, restarted php and even tried running it with chrome and it still happens.

So I just wiped out my DB and started from scratch [bug kept my original nginx config] using the latest version from git and now I am back to the same 403 Forbidden error for file http://dating.mytestsite.com/asset/gzip/?t=css&d=templates/themes/datelove/css/&f=menu_inverse.css file and I still see the /asset/css/color.css file as a 0 byte file.

I even logged in as admin and disabled all the cache files and I am still getting the same 403 error and 0 byte color.css file. [even clearing out the _protected/data/cache/* folder]. 

I did however notice [I have seen it before] that during the installation and when you get to the section to set the path where the protected folder is, I see the following notice error messages. at the top of the screen.

```
Notice: Undefined index: errors in /html/pH7Builder/_install/data/caches/smarty_compile/70/08/33/700833238dfdc432b17cb3605ce745cab8b0bb01_0.file.errors.tpl.php on line 24

Notice: Trying to get property 'value' of non-object in /html/pH7Builder/_install/data/caches/smarty_compile/70/08/33/700833238dfdc432b17cb3605ce745cab8b0bb01_0.file.errors.tpl.php on line 24
```

**Comment by Undefined-Variables** [comment]
That error during installation only happens with a single release, and the URL you have provided above is nothing to do with this software?

**Comment by breisig** [comment]
I thought I would just let you know. The domain I posted is fake just as an example.

**Comment by Undefined-Variables** [comment]
I see! Its hard to help with the limited information at hand. Sharing a real URL that we can see the issue first hand on would help solve this much faster. Also is there anything in your logs? 

My gut feeling is its nginx's configuration.
