### ISSUE TITLE
smtp problem

### ISSUE THREAD

**Issue by D4rkkking** [pH7Software/pH7-Social-Dating-CMS#804]
![Screenshot_20200801_155206](https://user-images.githubusercontent.com/47460853/89102144-ff88af80-d40e-11ea-94e6-a01d101e685d.jpg)

How do I fix this problem
How do I make smtp port 587

**Comment by Undefined-Variables** [comment]
This is a server fault and not caused by the software. 

Is your server local? Hosted or what? 

You need to be able to send an email from your server first so try sending an email from the command line.

**Comment by D4rkkking** [comment]
creating membership doesn't send email for password renewal

**Comment by Undefined-Variables** [comment]
Yes but is your server able to send an email without the software? 

https://tecadmin.net/ways-to-send-email-from-linux-command-line/

We need to know if your server is even able to send emails, if you can send an email then we can help you try and find the issue but if your server can't send an email on its own it doesn't matter what the software is you will be able to never send emails though software until you are able to with your plain old server!

**Comment by D4rkkking** [comment]
I tried e-mail is coming

**Comment by D4rkkking** [comment]
![Screenshot_20200802_205440](https://user-images.githubusercontent.com/47460853/89129029-7e124980-d502-11ea-8ad7-69928778c65a.jpg)

Can you set Smtp like this?

**Comment by polynamaude** [comment]
@D4rkkking Maybe you should learn some basic SysAdmin work before trying to run a web service of any type...
That would be my best hint for life...
Because now, you're just in the beginning of the problem ahead...

**Comment by polynamaude** [comment]
@D4rkkking Was your problem solved?

**Comment by polynamaude** [comment]
> Yes but is your server able to send an email without the software?
> 
> https://tecadmin.net/ways-to-send-email-from-linux-command-line/
> 
> We need to know if your server is even able to send emails, if you can send an email then we can help you try and find the issue but if your server can't send an email on its own it doesn't matter what the software is you will be able to never send emails though software until you are able to with your plain old server!

But people just want to get rich and famous building the next Facebook without knowing much about how they can run a computer itself. They get pissed when you tell them so...

**Comment by D4rkkking** [comment]
Thanks for your help, I decided not to use the script.

**Comment by Undefined-Variables** [comment]
This is not a problem with the script it's a server configuration problem. I asked you if you are able to send an email directly from the server and you started posting pictures of some smtp software that is in no way connected to the software. 

This script sends mail in the correct way as it should be sent from a server, this means the IP address it resides on must not be on any blacklist and must not be a residential IP address. Using smtp is a method for sending mail though a third party service and this is not the right way for a professional website to handle it's emails.

**Comment by polynamaude** [comment]
@Undefined-Variables We could implement a way to send email using SMTP but that's not the point.
Some site are behind firewall and will need to use SMTP, still that's something else.

Maybe this dude shall have asked us if the software can send email using SMTP. And I would have answered.

**Comment by Undefined-Variables** [comment]
Yes I understand this and think it's been thought about before as the settings table has feilds for smtp parameters but it's not used anywhere in the software.
