### ISSUE TITLE
🤔 Why do you use pH7CMS? What’s the main core reason?

### ISSUE THREAD

**Issue by pH-7** [pH7Software/pH7-Social-Dating-CMS#805]
Feel free to describe your situation, your project and what you are doing.

I would love to learn more about you and what you do with pH7CMs solution! 🤗👍

**Comment by Undefined-Variables** [comment]
Currently adding this as a feature... I am having a lot of fun with pH7cms...

![wheel](https://user-images.githubusercontent.com/52648055/89126806-b30da480-d4e0-11ea-9d27-e3654772203d.PNG)

**Comment by polynamaude** [comment]
@Undefined-Variables I love the idea of the dude with the mask. It's really "Up to date"

**Comment by Undefined-Variables** [comment]
@polynamaude yeah I was just experimenting with paint and thought the same so kept it :)

**Comment by squelch0** [comment]
It's kind of a funny story but also bad. I was contacted by someone that wanted me to be the admin of their WordPress website. Without revealing too much personal detail, the previous admin was apparently a scammer/cybercriminal, and to make a long story short, I built her a completely new website with ph7cms instead of using her old wordpress website. It's been a bumpy ride, but I owe a big thanks to this project, for saving my bacon. So thanks to the creator and everyone here, you're all very helpful. (:

**Comment by dimuller** [comment]
@pH-7 first at all many thanks to you and everybody who contributed to this great framework.
My partner is in the dating business and she asked me if I can make a website for her. I searched the internet and I found ph7CMS which gave me wonderful base for this project. Now after one year of work the website is online, not successful yet, but we know it will take time.
When worked on her website, I realized, that it could be a great platform for my business too. I'm in the Embroidery Business and now I created a social network for all people who are in this business or who are interested in this business.
So for now I have two totally different applications for the the ph7CMS framework.
It was not easy for me to get into it, but after working for so long time with ph7CMS I realized that it's a master piece of software, very clean and well programmed. My compliments!
The only thing what is missing is a good documentation, low and high level, of the framework. That would help beginners like me a lot.
Again many thanks!

**Comment by Undefined-Variables** [comment]
@dimuller && @squelch0 && @pH-7 

I find it amazing on how alike everyone's stories are. My main use of the framework is like @dimuller I have someone close to me who is in a similar sort of game, he was being messed around by another dev who was promising the world but never actually moved forward with anything he promised would be done, deadline after deadline missed until I was getting fed up having to listen to the backlash so I used pH7cms to put together an example of what he should be seeing... We are now 2yrs in and like @dimuller we are not what I would call a success yet... We have just hit the 2500 user milestone and have a group of active users but this takes a lot of time not only on the software but promoting too. 

My friend spends hours everyday on social media, we get 15-25 new members each day but getting a nice balance of M/F users is very tricky! We don't use fake accounts and all our users are genuine people, this was very important for us, false users is the easy way to success and the site just ends up built on lies and that only ends one way! 

I agree the lack of documentation maybe the thing that stops this from its true potential, if there was an easy shared way to contribute to documentation I would help out for sure. Problem is we like to code but don't like explaining the code we write!

**Comment by polynamaude** [comment]
@Undefined-Variables Like I already explained, in life we must do things we dislike.
Also, documenting what we code is a must if we want to have maintainable software on the long term. You've not done many project until now. But in a time frame of 5 years and with many different project laying around, it's easy to forget.

Who remember in his mind what's the command to start the Pulse Audio server on a external USB audio card ? You use it once, twice, three time and after a while it gets in your head. The difference is that we don't read back the code all the time and also, we have to remember that it won't always be us that will maintain what we wrote. That's also why there's code conventions.

**Comment by Undefined-Variables** [comment]
@polynamaude yeah I finally understand this after having to go back and add to work I did over a year ago and honestly it was like reading double Douche! Took me a while to understand what I had done and now I have been  commenting my code... Lesson learned!

**Comment by dimuller** [comment]
@polynamaude & @Undefined-Variables,  in my C++ project, which I started 25 years ago, do I have a nice documentation. Every code file got a header with as description what the file is good for, where it is used and which globals it uses. Then every function also got a header with a description of the parameters, what it does and what it returns. So I'm very much used to have this kind of information. That's why I felt a little bit lost when I started with ph7CMS. Especially because it was my first web based project. So I had to learn at the same time all this php, java, ajax, css, .... stuff. But now it's ok and I just add my documentation to the new files which I add. To do the same for the whole project would be impossible. If you spend a little bit time when you code, you will get this time back in future when you don't have to think about the purpose of a code file and/or a function in it.

**Comment by Undefined-Variables** [comment]
@dimuller yeah that sounds like a luxury that must be very handy when returning 25yrs later! That is a long time. I have no issue writing documentation (I find it relaxing) but its more of a case of where to begin, the framework seems the logical place, then the template system, the core system, all the modules then finally the theme, customising and how to create a website that feels and looks unique. 

I am a big fan of CodeIgniter's level of detail in there documentation and feel a CMS should have this type of guide as a minimum. Problem is the person who would need to do the most is a very busy dude. It can be hard to get straight forward responses most of the time so don't think he has the time needed. 

Also do you ever see any other contributions from anyone outside of a small group? I dont think I have ever seen a thing that is not by me, you @pH-7 , @polynamaude  or that twat @nickpick haha! That bot just makes me feel silly for missing the obvious!

**Comment by pH-7** [comment]
The repo has now "Discussions" setup! Let's talk there when it's not related to "Issues" 🤗

https://github.com/pH7Software/pH7-Social-Dating-CMS/discussions/814 😊 Please always be nice and kind with each other! We are here to share, not to argue! 💪 And makes our mood much better. A happy day is a happy life. Thanks for understanding!

**Comment by pH-7** [comment]
This discussion is now hosted here 👉 https://github.com/pH7Software/pH7-Social-Dating-CMS/discussions/818
