### ISSUE TITLE
Need a help

### ISSUE THREAD

**Issue by szimmath** [pH7Software/pH7-Social-Dating-CMS#806]
Dear Support

I was installed the pH7-Social-Dating-CMS nsoftware on my website, but something is wrong. Can you help me?

Details of the problem can be found at the following links:

http://szimmath.com/aphrodite
http://szimmath.com/aphrodite/admin123/main/login

Regards
Robert Ven

**Comment by polynamaude** [comment]
@szimmath Hi !
**First**
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help

Configure the base folder for your installation.

**Comment by Undefined-Variables** [comment]
This is not how you ask for help. We need a full description of the issue, full server setup specs and explain the steps you have already taken before you came here.

**Comment by polynamaude** [comment]
@Undefined-Variables The links I tried did work but showed either a gZip/CSS Minifier problem or something alike.

**Comment by Undefined-Variables** [comment]
Oh okay. I never trust links so always open them using Tor so might be due to that. 

@szimmath This issue can normally be solved by disabling the gzip cache by signing in to admin then go tools->cache settings and disable it there. If you cant get to this page via a browser open

    _protected/app/configs/config.ini 

and change the 1's to 0's on the cache settings. If this doesn't solve your issue please supply us with the requested info explained on the page that @polynamaude gave you the link to above.

**Comment by polynamaude** [comment]
@Undefined-Variables It makes non-sense what you say about trusting links...
Your browser shall be secured by itself... The only thing that you do by running thru the Tor options is hiding your IP and possibly disabling many things...

**Comment by Undefined-Variables** [comment]
JavaScript is disabled so no JavaScript on the page can run. I get what your saying about anything that runs in the browser will stay in the browser but I have seen stranger things happen. Plus hidding your IP is never a bad thing IMO.

**Comment by polynamaude** [comment]
@Undefined-Variables You see things that you don't understand and presume at wrong that they are harmful... Take it easy

**Comment by Undefined-Variables** [comment]
No we are working openly on a platform that is used by developers and people who are super smart and are on the cutting edge of  computers, a subject still in its infancy and many things that are created and discovered everyday. Where there is good there is also bad and smart people are defined by good or bad they are in both groups. 

This in mind it makes sense to take every precaution you possibly can, Clicking a link exposes a lot of information to the server the page is hosted on not only your IP address.
