### ISSUE TITLE
Installation on local host with wamp issue

### ISSUE THREAD

**Issue by nootkan** [pH7Software/pH7-Social-Dating-CMS#807]
unzipped and uploaded files to localhost/mywebsitename/ and ran the installer.  Got to the part where all the login information is required for the admin backend and recieved the following fatal error:  Fatal error: Cannot use PH7\Framework\Mvc\Model\Engine\Db as Db because the name is already in use in C:\wamp\www\mywebsitename\_protected\app\system\core\models\UserCoreModel.php on line 19

Deleted everything and changed the db name to something else and still get the error.  Any ideas?

**Comment by polynamaude** [comment]
@nootkan Hi ! Welcome and thanks for trying pH7CMS.

Here's a staring point...
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-ask-for-help
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki
https://ph7cms.com/doc/

It would be some help if you'd give us more about what you are running on...
As we see the "C:" we can assume you are running from Windows with WAMP. First thing, I'd suggest you run the software from a Unix machine as we don't really support nothing on Windows. It can and may run on WAMP but that's mostly for doing test. You can't expect a real instance from running over this stack.
Also, if you ain't serving from the webroot then you'd need to change some part in the configuration file ( .htaccess ). It's well explained.

**Comment by nootkan** [comment]
Thanks I've read through all the links provided. Sorry I thought that "C:\wamp\www\" was more than enough to define my server.  Even though I got that error the install is working and so far I haven't had any issues with configuration or set up on the testing server.  I only wanted to see how it worked before installing on my linux server.  So far I like what I see and will start to tweak the look of the templates once I get all the bells and whistles sorted out.  Thanks for a great looking script!  And thanks for the quick reply and support!
