### ISSUE TITLE
License, copyright and changing the site?

### ISSUE THREAD

**Issue by rental66** [pH7Software/pH7-Social-Dating-CMS#813]
Three questions
1. No license fee? if commercial use?
2. Any cost if remove PH7cms logo/copyright?
3. Free to modify any thing if ask programmer?
thanks

Den

**Comment by polynamaude** [comment]
@rental66 Hi !
https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/Can-I-resell-the-software-and-make-money-with-it%3F

Go out and Google "GPL" and you'll get your answer.

**Comment by pH-7** [comment]
The software is published under General Public License 3 or later

https://github.com/pH7Software/pH7-Social-Dating-CMS#%EF%B8%8F-license

As you can understamd, the copyright in the source files cannot be removed. 

Hope it helps! Enjoy your weekend :) Good luck! 

Any mentions of pH7CMS or contributions are also really welcome if you appreciate the hard work behind the software. Thank you in advance for considering pH7CMS. I hope it will help you making your dream service!
