### ISSUE TITLE
Not really a bug, but more user error! - 503 errors when getting /asset/*

### ISSUE THREAD

**Issue by JamesLodge** [pH7Software/pH7-Social-Dating-CMS#815]
How is the url example.com/asset/* handled by PH7cms?

Is this a apache rewrite rule? I'm using nginx and no css/js is being download and so no theming. 

GET /asset/gzip/?t=js&d=.&f=static/js/jquery/carouFredSel.js,templates/themes/base/js/splash.js HTTP/1.0" 503 18 "http://example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"

**Comment by Undefined-Variables** [comment]
Sign in as admin, go to cache settings and disable the GZIP cache... Then clear cache on server and browser and it should load...

This is because you have to set up GZIP compression in your nginx configuration...

**Comment by JamesLodge** [comment]
Thanks, I've disabled gzip under caching and then deleted all file in _protected/data/cache/pH7_cache and pH7tpl_cache and then cleared browser cache, but still have the same issue. 

http://example.com/asset/gzip/?t=css&d=static/css/js/jquery/box&f=box.css

**Comment by Undefined-Variables** [comment]
You need to delete all four folders in 

    /_protected/data/cache/

**Comment by JamesLodge** [comment]
sorry I deleted all folder, of which there were three (ph7_cache, pH7tpl_cache and pH7tpl_compile), but still the url is http://example.com/asset/gzip/?t=*

I've restarted php-fpm and nginx and browser caching is completely clears. 

It's something I'm doing wrong, but not sure what. 

Many thanks for your help.

**Comment by Undefined-Variables** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/750

**Comment by JamesLodge** [comment]
No this is a FreeBSD machine running nginx and php-fpm. I'll take a look at the other issue you linked. 

its strange that even when gzip is disbaled in the admin>cache settings it still tries http://example.com/asset/gzip/?t=*

**Comment by Undefined-Variables** [comment]
You can double check the setting in 

    /_protected/app/configs/config.ini

Make sure all caches have 0 not 1 next to them, disable them all and once you have solved the problem enable them one at a time. The GZIP URL you keep seeing is not included if you have the setting to off! If you change "assets" to "static" does is the page found?

**Comment by Undefined-Variables** [comment]
If you are still having a problem after you do as I explained above, email me the real URL as can tell you a lot more if I can see the console output. My email is on my profile!

**Comment by JamesLodge** [comment]
yes they all look correct. 

also disbaled **Enable Static Cache. Used to store compressed/minified JS/CSS files** and **Enable Static Minify** just for testing

`[cache]
; General cache, usually for database contents, but may also involve other data
enable.general.cache = 1

; Caching for HTML contents from template files
enable.html.tpl.cache = 1

; Caching for JavaScript and CSS files, It's very important to activate it if you use the compressor code, but you must disable it when you are in dev>
enable.static.cache = 0

; Minify the code for CSS, HTML, PHP and JavaScript (also minify dynamically the code like Geo Maps code)
enable.static.minify = 0

; Gzip compression for JavaScript, CSS and other static files
enable.static.gzip_compress = 0

; base64 encode for images if file-size is lower than 24KB
enable.static.data_uri = 0

; Enable or Disabled Google Closure Compiler Service (https://closure-compiler.appspot.com )for the JS files. If you use for too many files at the sam>
enable.js.closure_compiler_service = 0

; Enable or Disabled the compressor with Java
; (Requires Java installed on your server! This option is usually available on dedicated servers, sometimes on shared hosting. Please contact your hos>
enable.static.minify_java_compiler = 0`

**Comment by JamesLodge** [comment]
> 
> 
> If you are still having a problem after you do as I explained above, email me the real URL as can tell you a lot more if I can see the console output. My email is on my profile!

Thanks I will do. Much appreaciated.

**Comment by Undefined-Variables** [comment]
Set this to 0 as well 

````

; Caching for HTML contents from template files
enable.html.tpl.cache = 1

````

**Comment by JamesLodge** [comment]
> 
> 
> Set this to 0 as well
> 
> ```
> 
> ; Caching for HTML contents from template files
> enable.html.tpl.cache = 1
> ```

still the same url being used, for example asset/gzip/?t=js&d=templates/themes/zendate/js/&f=global.js

Strange.

**Comment by Undefined-Variables** [comment]
Send me the URL so I can have a proper look!

**Comment by polynamaude** [comment]
@Undefined-Variables There's a truck load of strange stuff in this software.

**Comment by Undefined-Variables** [comment]
What happens if you change the theme?

**Comment by Undefined-Variables** [comment]
@polynamaude yeah but we can only deal with them as they arise! Think we should have GZIP set to off as the default upon install because this seems to be happening to a lot of people!

**Comment by JamesLodge** [comment]
> 
> 
> What happens if you change the theme?

cycled through all themes. the main image on the homepage changed, but still lacking formating and same gzip path to css and js. 

will email you the url in a mom

**Comment by polynamaude** [comment]
@Undefined-Variables I think this software was developed as a engineering project. That is, very nice on the planning but very bad in the real world. There's plenty of "good ideas" but there's also too many things that just don't fit. Sometime you'd better do less but make it work !

Honestly, more I see and more I get disappointed. Even if he say it got planned, yes maybe but sometime you got to get away from book and go real life. But I've look at many of his other project done and they're all doddgy.

**Comment by polynamaude** [comment]
@Undefined-Variables The worst website ever as visual. I had to go see a doctor after vomiting and getting a headache just caused by looking 30 sec.
https://lifyzer.com/

He even, wrote is own GDPR and that's the most crazy thing since the Falklands war.

**Comment by Undefined-Variables** [comment]
@polynamaude yeah I can see your point, there are many instances where code could have been written in a more efficient way but I honestly think this may have been his university learning project or course work initially and has had bits slowly added to it over time. Thing that makes me think this is I can see the improvement as the later features came along, the messenger for example... The script calls variables from the global array 6-8 times every time anything is sent or received, this is highly insufficient and resources hungry! 

I have looked at all of his repos and his code is perfect. The documentation is not so perfect! Think he should release a version that is usable for all! No one can use it with all the custom branding and its a huge task to slowly make your own version of it look professional! Think the easier it is to use the more success it will see! Just thinking out load!

**Comment by Undefined-Variables** [comment]
> @Undefined-Variables The worst website ever as visual. I had to go see a doctor after vomiting and getting a headache just caused by looking 30 sec.
> https://lifyzer.com/
> 
> He even, wrote is own GDPR and that's the most crazy thing since the Falklands war.

Oh wow that shadow on the font sent my eyes funny!

**Comment by JamesLodge** [comment]
> 
> 
> @Undefined-Variables The worst website ever as visual. I had to go see a doctor after vomiting and getting a headache just caused by looking 30 sec.
> https://lifyzer.com/
> 
> He even, wrote is own GDPR and that's the most crazy thing since the Falklands war.

it feels like the whole page is shacking up and down, its bloody horrible!

**Comment by polynamaude** [comment]
@JamesLodge I had to look if someone wasn't hidden inside my monitor and jerking off. That's wacky shacky

@Undefined-Variables It's not a thing of writing nice code but also writing code that work, code that is efficient, etc...

**Comment by kriptoblak** [comment]
Hi I decided to post a comment here because all other issue tickets are closed.
After successful installation I had an issue with the CSS not loading (403) and all the links being broken, cannot load admin page etc. (loading non-existent page)
After searching for solution I noticed that there is a lot of people having the same issues and nobody knows the answer... It is always about clearing cache etc... None of that worked for me.

The problem was with host name.
My host name was srv.
In linux terminal it looked like `root@srv:`.
I am not sure how the `/etc/hosts` looked like.
The pH7CMS wants to load data from host name that is different than what I defined in pH7CMS installation.

So I created a new VM Ubuntu 20 server and used my domain.com name as VM name.
I am using Hetzner servers. And the name of the VM is used for Ubuntu hostname.
Otherwise you define hostname on linux installation.

Now `/etc/hosts` looks like this.
127.0.1.1 domain.com domain
127.0.0.1 localhost

So the `127.0.1.1 domain.com domain` is the only thing that changed from previous installation and now works.
So everyone who will find this, try to change the host name and if it works don't forget to tip me some Brave rewards.

Thank you, good luck and stay safe.

**Comment by polynamaude** [comment]
@kriptoblak If you simply make sure your hostname resolve properly when installing then your problem wouldn't have arise. The software need that your hostname is resolvable.
You could have added srv to the hosts file and you would have been good or whatever requested name is failing.

**Comment by kriptoblak** [comment]
> @kriptoblak If you simply make sure your hostname resolve properly when installing then your problem wouldn't have arise. The software need that your hostname is resolvable.
> You could have added srv to the hosts file and you would have been good or whatever requested name is failing.
Simply... That was the point of this comment.
People don't know that.
I solved my problem on my own and posted this to maybe help others.
Both installations went trough without problems. Also no warnings that some settings on the server are not ok... Like hostname if the script is so relying on it.
Nobody mentioned anything about that in all the closed issue tickets. The tickets are closed with a comment that they didn't reply for 7 days etc. 
But the real solution is never found.
And people don't know what they are doing wrong.
Other scripts and software are not so sensitive to this.
Just saying.
Thank you, good luck and stay safe.

**Comment by polynamaude** [comment]
@kriptoblak Good that you remark that the tickets gets closed after 7 days, I think that's a problem too.
I'm not the author of this software, I used to be a user, like you.

https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/821#issuecomment-701032855

Software development / Server management is a dynamic game. There's never such thing as a top-down approach to problem solving. So you have to do your own investigation, all the time.

Also, most people who use a CMS are using the machine on the Internet so they have a adress that resolve.
By the way, if you change your server name later on, (for example if you go live), then you'll need to go into the database and change the settings for everywhere you see the server hostname.

I wouldn't say other software "don't rely on hostname as much". If you use any CMS with a caching system that use a prefetch then it will indeed be relying on the hostname. But most of the time, those will be two different package (software) that you install side-by-side, so you'll have to enter the hostname somewhere to make them communicate.

Hope this give you some hint.
