### ISSUE TITLE
pH7cms and adsense

### ISSUE THREAD

**Issue by claudioizzi** [pH7Software/pH7-Social-Dating-CMS#816]
I applied to have adsense ads on my pH7cms dating site and they rejected saying "the website uses unsupported languages", the website is in english I don't understand why they said that or how to fix it, anyone else have this problem?

thanks

**Comment by polynamaude** [comment]
@claudioizzi Make sure you set the good encoding for the documents. I know Google are very picky about this.
Pagespeed insights can give you some hint, even if the tool ain't made for this.
https://developers.google.com/speed/pagespeed/insights/

**Comment by claudioizzi** [comment]
How do I set the encoding? what files?

**Comment by polynamaude** [comment]
@polynamaude I don't think you understood what I meant.
The encoding for the pages served are set in the header by the software. Maybe this is where the problem reside. This is why I suggested you use **_pagespeed insight_** to get a diagnostic of your website.

**Comment by claudioizzi** [comment]
I ran it again and expanded all the points yet I still dont see any kind
signs of other languages

**Comment by polynamaude** [comment]
https://support.google.com/adsense/thread/18792596?hl=en
https://wordpress.org/support/topic/google-adsense-reuqest-rejected-saying-unsupported-language/

**Comment by polynamaude** [comment]
https://www.youtube.com/watch?v=YruaGd0XCfM

**Comment by polynamaude** [comment]
https://www.wpbeginner.com/beginners-guide/how-to-add-google-adsense-to-your-wordpress-site/comment-page-2/

**Comment by polynamaude** [comment]
Not specific to this CMS but shall put you on some track to find answer.
Google is very very very picky and it's specifications.

**Comment by polynamaude** [comment]
Can be as simple as the page is served in "US English" but somewhere you have your language set as "EN-CA" instead of "EN-US".
Google is always "a pain in the ass".

**Comment by Undefined-Variables** [comment]
It’s more likely that the issue is caused by the first line in the template is not a html tag! It should be <html> but there is two php lines before this that are used to insert copyright into the page! Google probably see this and assume it’s an unsupported language!

**Comment by polynamaude** [comment]
@Undefined-Variables PHP Tags aren't sent but are interpreted. But yes, if you have something that appear before de <body> then it could be interpreted as a exotic language.

But... what the f*ck !?  This is just absurd ! Okay to have copyrights in the source code but to have it poluting everywhere possible, this is just an over expressed ego. I french we have a story about a dude who looked himself so much into the reflexion he saw in a lake that he ended up drowning...

You can have a "Produced by Joomla" tag or something similar, I think it's called a creator tag, where you put the name of the software. But to create your own is a bit.... excessive and causing problem. Again, this is leftover from the time there was a paid version and a free version. The free version was a big jumbo sized publicity for the paid one ! And seem like now it's a big publicity for someone's curiculum.

**Comment by Undefined-Variables** [comment]
@polynamaude I knew you would say that haha! I know php tags are ignored but if the php says 

     <?php echo $copyright_bollox; ?>

The first thing seen is the value of the variable. This is what it does and the value of the variable is the copyright found in the framework! This causes many problems not just this!

**Comment by polynamaude** [comment]
@Undefined-Variables Good morning @Undefined-Variables  !
 Wanted to tickkle you somehow.
I'm really wondering what's the goal of this.
Btw, this can be removed. What's prohibited is to remove the copyright notice in the source code.

It's like rewritting your own GDPR, that's not allowed.

**Comment by Undefined-Variables** [comment]
@polynamaude morning... I don't understand what you are asking here... The goal is to add text to the sites header, this can be problematic as like in this case, when another service/website tries to read the first html tag it fails as the first thing seen is the copyright. This was the first thing I had to remove as I had a similar issue to this! Its not a simple task either!

**Comment by polynamaude** [comment]
@Undefined-Variables I'm saying same as you. What do you don't understand ? What part of what I'm writting.
There's a rule that say "don't create yourr own standard" and another one that say "stick to existing standard when they exist and don't go against them".

It's like, don't create your own unique HTML tag.

**Comment by Undefined-Variables** [comment]
> Wanted to tickkle you somehow.

Sorry was half asleep and not sure what tickkle is?

**Comment by polynamaude** [comment]
@Undefined-Variables To annoy someone, but not in a bad way. Something friendly... Like you'd do with someone you are good friend with. A bit like throwing a bucket of cold water over someone under the shower.

**Comment by Undefined-Variables** [comment]
Oh I see! Sorry! Makes sense now! That sounds horrible a bucket of cold water over you while your in a nice warm shower!
