### ISSUE TITLE
Plain text version of email missing in multi part mime emails

### ISSUE THREAD

**Issue by Jilt6502** [pH7Software/pH7-Social-Dating-CMS#820]
In order to get better scores from spam filters, I propose adding a plain text version along with the html version in a properly fomatted multi part mime email.

In reviewing an email sent by ph7, isnotspam.com reports the following less than desirable results

3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
0.1 HTML_MESSAGE BODY: HTML included in message
0.8 MPART_ALT_DIFF BODY: HTML and text parts are different
0.3 MIME_HTML_ONLY BODY: Message only has text/html MIME parts

One source online says to check html validity at validator.w3.org and that could help but I see no real downside to also including plain text.

**Comment by Jilt6502** [comment]
Lookng at _protected/framework/Mail/Mail.class.php, for the swift_mailer the changes needed to at least include a plain text part are:
 
adding the line:
$oMessage->addPart($sContents, self::TEXT_CONTENT_TYPE); //TODO convert $sContents to text
before the line:
$oMessage->addPart($sContents, self::HTML_CONTENT_TYPE);

and adding the line:
const TEXT_CONTENT_TYPE = 'text/plain';
before the line:
const HTML_CONTENT_TYPE = 'text/html';

It will still be necessary to convert $sContents to actual text to complete the fix. I'm working on finding an acceptable method for this conversion.

**Comment by Jilt6502** [comment]
Argggggh, if anyone could lend a hand, I'd sure appreciate it. 
I can't seem to get any php errors to output although I'm sure they are happening. I'm using a shared host so no looking in /var/log/ 
I tried turning on error printing but nothing shows on the page but it is obviously broken when I make a change because it fails to load. I've been using the forgot password screen as a test.

**Comment by Jilt6502** [comment]
Since my attempts at converting html to text have so far failed, I just added some test text string to the text/plain section and it improved the spam score slightly but not much because it still is not equivalent to the html message and is much shorter.

**Comment by polynamaude** [comment]
@Jilt6502 You could simply strip the HTML tags.

https://www.php.net/manual/en/function.strip-tags.php

What about this ?

**Comment by Jilt6502** [comment]
I tried strip_tags but it left tag attributes which still gave a bad score. I have not yet tried lowering the score even more by validating the html since it looks ugly with the line breaks and 0.9 is quite an improvement already.
Finally just now I got the spam score down to 0.9 from 4.8 using https://github.com/kranemora/html2text
The hardest part for me was getting html2text installed because it ran out of memory on my shared host. Finally I started fresh an used git clone to download pH7 and then added kranemora\html2text to the composer.json file before running composer install. I also had to change the location of the _protected folder in composer.json since I had moved it out of public_html folder.

Adding the following lines to _protected/framework/Mail/Mail.class.php before the line " $oMessage->addPart($sContents, self::HTML_CONTENT_TYPE);" then did the trick:
            $html2Text = new \kranemora\Html2Text\Html2Text;
            $sPlainContents = $html2Text->convert($sContents);
            $oMessage->addPart($sPlainContents, self::TEXT_CONTENT_TYPE);
of course at the top of the file I still had to define:
    const TEXT_CONTENT_TYPE = 'text/plain';

Now I'm hoping pH7 version 16.0.0 is stable because I didn't see how to download 15.4.0 using git

**Comment by Jilt6502** [comment]
I would submit a pull request, but I couldn't even get git to keep the changes I made to composer.json in order to require html2text to install. If I submitted for the changes to Mail.class.php it would just break things since html2text would not be installed without manually modifying composer.json. Maybe someone who has a clue about these things could submit to benefit everyone else. I didn't find composer.json in .gitignore so I don't know why it was ignored anyway.

**Comment by polynamaude** [comment]
@Jilt6502 Hi !
To download any version of Git (those are tags) do the following
_git clone
git tag
git checkout_ (**tag name**)
Here you go...

Not too sure what you mean by "If the 16.0.xx" is stable.

Regarding the pull request. You have to make your change on the master branch, then add the files, commit them, and then will you be able to push them onto your own forked repo and then make a pull request.

**Comment by polynamaude** [comment]
@Jilt6502 Have you looked into the .gitignore file ?

**Comment by polynamaude** [comment]
@Jilt6502 Have you added the file and did your commit, push onto your forked repo ?

**Comment by Jilt6502** [comment]
I found nothing to make the file ignored in .gitignore. I can try pushing again but before I pushed to my forded repo and later cloned my forked repo to another machine and had to re-modify the compose.json file.

It was my understanding that the latest stable version was 15.4.0 and that 16.0.0 is the testing branch and more likely to have bugs.

**Comment by Jilt6502** [comment]
Ok, I cheated and just made the commits directly with the editor on github and and created my first ever pull request. I welcome any constructive criticism on my code if I've done anything in less than the best way.
