### ISSUE TITLE
Installation fetal error

### ISSUE THREAD

**Issue by ph7ali** [pH7Software/pH7-Social-Dating-CMS#823]
**Describe the bug**
I've been testing ph7cms v 15.4 on two live servers and 1 local host .
Today, I wanted to update live server with  latest version 16.0  but cannot update. Again ,I have tried 4 times fresh install on local server  but it shows 
Fetal error : cannot use PH7/Framework/Mvc/Model/Engine/Db as Db because the name is already use in c:/*Mydomain*/ _protected/app/system/core/models/AdminCoreModel.php .

**Comment by pierrehenrey** [comment]
Hi @ph7ali, when navigating to what URL does this error occurred? Do you remember?
Could you give a screenshot or the full error message (showing on what line the error was given). For example, `filename.php on line 4`

Looking forward to hearing from you!

**Comment by ph7ali** [comment]
Hii Dear,
I hope you are doing well.
Today, I tried again with different folder with fresh installation.
Old error was like this.

Fetal error : cannot use PH7/Framework/Mvc/Model/Engine/Db as Db because
the name is already use in c:/*Mydomain*/
_protected/app/system/core/models/AdminCoreModel.php .

But today,  I changed folder and trued install and got same fetal error. I
am sending the screenshot of error.  I am using
W 10,
MariaDB 10.1.37
utf8 Unicode

Apache /2.5.37 win 32
php/5.6.39
.

Kindly review my screenshot to see today's error. As i see the I am
reaching installation step 5/7 successfully but when i submit
site name
username
  pass
first name last name
And required email

So page of error comes as I submitted this step.

Waiting for a positive response from you.
Thanks a lot.
Best of luck.
PH7 CMS specially Pierre H S.

**Comment by polynamaude** [comment]
@ph7ali At first, using PHP 5.6 can be the main place where your problem starts.
2nd, why using Win32 version of Apache ?

**Comment by pierrehenrey** [comment]
@ph7ali Thanks very much for getting back to me. However, the screenshot is missing. Do you mind to directly upload the image on GitHub -> https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/823 (and not from your email client)?

**Comment by Undefined-Variables** [comment]
Your PHP version is outdated and no longer supported... The newest PHP release is many times faster and has features that are needed to run this software properly. Update to version 7.2, 7.3 or 7.4!

**Comment by ph7ali** [comment]
I updated php version. . It's installed successful on my live server. Thank you so much.

**Comment by polynamaude** [comment]
@ph7ali The requirements for the software are both in the documentation (included with the software) and on the documents site (https://www.ph7cms.com/doc).

If you need some more help, don't hesitate to ask.
