### ISSUE TITLE
adding banners

### ISSUE THREAD

**Issue by zam00921** [pH7Software/pH7-Social-Dating-CMS#824]
i am not able to add or edit banners, is there any anyone who can help me ?

**Comment by polynamaude** [comment]
@zam00921 Everyone is a volunteer here. So no need to write twice your request. At most, you risk people just ignoring because they'll consider it's harassment.

https://ph7cms.com/doc/en/how-to-change-promo-texts-on-homepage

Maybe if you'd explain what doesn't work then we'll be better able to help !

**Comment by zam00921** [comment]
@polynamaude sir actually i want to add banners but i dont know how can i add banners.

**Comment by nootkan** [comment]
Login to your admin area and click the "Settings" menu. Than click the "Ad Banners" link.  It is self explanatory after that with examples.

**Comment by zam00921** [comment]
i am a bit confuse about the image path that how to write a image path in banners section

**Comment by polynamaude** [comment]
> i am a bit confuse about the image path that how to write a image path in banners section

I don't understand a word about what you are saying here...

> i am a bit confuse about the image path **that** how to **write a image path** in banners section

**Comment by polynamaude** [comment]
@zam00921 Maybe you need to learn more about web development before going on with this project.

**Comment by nootkan** [comment]
I haven't used this feature yet so can't confirm if it works but here is what an example html code would look like:
`<a href="https://www.website.com" target="_blank"><img src="images/your-banner-image.jpg" alt="Dating Service by pH7CMS" title="Dating Service powered by pH7CMS" /></a>`

You could change the href to read where your image is located if you want to preview it or make it link to the actual banner ad website.

**Comment by zam00921** [comment]
btana hai tu bta zyada shoka na ho war jani diya ani diya Thanks for your help

**Comment by polynamaude** [comment]
@zam00921 As I can see you lot of experience on Github and seem to be a really experienced user. So for sure we'll help you with every little thing you may have. Do you also need help installing Windows?
