### ISSUE TITLE
Update My App Without Losing Data

### ISSUE THREAD

**Issue by Ahmed-pk** [pH7Software/pH7-Social-Dating-CMS#827]
I am hosting my site on the Nginx server. First I have downloaded pH7-Social-Dating-CMS using ssh git but that didn't work for me it says:
![Screenshot (81)](https://user-images.githubusercontent.com/72154121/97044230-37763d80-158d-11eb-8ea8-29cdcb692b61.png)

so I download pH7-Social-Dating-CMS from [SourceForge](https://netix.dl.sourceforge.net/project/ph7socialdating/16.0.0/pH7Builder-16.0.0.zip)
and it did work for me now if developers launch a new update of this app how can I update the app without losing data or database config file with one ssh command @pH-7 @rubo77 @NicolasCARPi @meliache @ddcq

**Comment by polynamaude** [comment]
@Ahmed-pk Update won't make you loose your data
