### ISSUE TITLE
so what is best method to update my dating app @Ahmed-pk Update won't make you loose your data

### ISSUE THREAD

**Issue by Ahmed-pk** [pH7Software/pH7-Social-Dating-CMS#828]
@Ahmed-pk Update won't make you loose your data

_Originally posted by @polynamaude in https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/827#issuecomment-715650610_

**Comment by polynamaude** [comment]
@Ahmed-pk Why open another issue ???
https://ph7cms.com/doc/
In the documentation it tells you what to do.
[Upgrade](https://ph7cms.com/doc/en/upgrade)

You simply backup the configuration file at first and replace it afterward.

Tell me, what have you tried ? Don't just go out asking "How do I..." but try something. It's not like there's a life at risk. It's by trying, doing mistake, doing good stuff too and in the end we learn.
