### ISSUE TITLE
Ph7cms is not working properly after installation.

### ISSUE THREAD

**Issue by surya4521** [pH7Software/pH7-Social-Dating-CMS#829]
I installed the application through Softaculous.It installed successfully but after installation i tried to work with it but the site is not complete as it has to be.

I attached the screenshot of the problem.

![Screenshot_2020-11-01-12-02-31-399_com android chrome](https://user-images.githubusercontent.com/73770521/97796629-54b8a500-1c3a-11eb-9a61-5102b3717409.jpg)
![Screenshot_2020-11-01-12-02-48-821_com android chrome](https://user-images.githubusercontent.com/73770521/97796630-584c2c00-1c3a-11eb-949a-2f58c4ea8e42.jpg)
![Screenshot_2020-11-01-12-05-13-999_com android chrome](https://user-images.githubusercontent.com/73770521/97796643-93e6f600-1c3a-11eb-9a61-77ce7c3b1a69.jpg)
![Screenshot_2020-11-01-12-05-19-407_com android chrome](https://user-images.githubusercontent.com/73770521/97796645-96e1e680-1c3a-11eb-8593-022b3846a8ba.jpg)

**Comment by ph7ali** [comment]
Fix your htaccess files as per your server requirements.  For example,  on ngnix server we need some changes for it. This is due to css and java is not fully working on your server .

**Comment by Undefined-Variables** [comment]
@surya4521 please take a few minutes to look though closed issues before you open one that is asking for help with something that has been solved multiple times in the past. The solution can be found if you look! We don't mind helping when a genuine new issue arises but we don't have time to repeat ourselves.
