### ISSUE TITLE
ph7 redirecting to phishing page

### ISSUE THREAD

**Issue by Ahmed-pk** [pH7Software/pH7-Social-Dating-CMS#830]
hi I have installed ph7 cms on my server and somehow I lost my site database and when I was fixing it got this email from Cloudflare
![WhatsApp Image 2020-11-01 at 4 42 55 PM](https://user-images.githubusercontent.com/72154121/97809343-18169900-1c8e-11eb-83a0-3366446d864c.jpeg)
when I visited https://freedatingssites.com/templates/dx it was redirecting me to a phishing page it redirected me to https://www.palletsfrappi.it/wp-content/plugins/admin-custom-login/dd/xscdfgty/cdfrgthy/
its a phishing page 
![Screenshot 2020-11-01 173042](https://user-images.githubusercontent.com/72154121/97809568-65dfd100-1c8f-11eb-885f-4eceba3d166a.jpg)
now I have fixed the problem but I want to know why it was redirecting me to that page
@pH-7 @rubo77 @NicolasCARPi @meliache @ddcq

**Comment by polynamaude** [comment]
@Ahmed-pk Why do you send your note (@) to plenty of regular user of our site ?? For example rubo77....

Maybe if you looked thru your logs and gave more information about your server then we could help you out. But now it's something like "**_I was driving my car and got a flat tire on a dirt road. Can you please tell me where did I ran on a rusted nail_**"...

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/781#issue-627967333

**Comment by polynamaude** [comment]
@Ahmed-pk By the way, the URL you pointed to (/templates/dx/...) ain't a regular URL used by pH7CMS so maybe it comes from the initial problem you had with your database. Never had the idea that maybe it's the same intruder that broke your DB that also implemented this redirection...

**Comment by FaizanZahid** [comment]
To me this looks like a serious bug in ph7cms or some hacker has injected some plugin/source code in PH7CMS and trying to get traffic to their sites.

I though PH7CMS was a very secure CMS, what steps can you guys take to prevent this from happening in future again, and how can we make our web app fully secure ?

As per my understanding, its not likely  a hacker who has injected into @Ahmed-pk code, as he faced his DB removal issue as well, looks like there is some virus in PH7CMs or on @Ahmed-pk  server itself? But @Ahmed-pk has other sites running on same server but only this phycms site got infected, why?

**Comment by Ahmed-pk** [comment]
Mysql Database was fully corrupted due to a server issue after the database disconnected from the script the redirection is created 

I think that there is a bug in ph7cms that is giving access to intruders. I have also checked the system logs. there is no clue that a hacker hack into our server. I think you should make this script more secure

**Comment by polynamaude** [comment]
@Ahmed-pk I think you are right !
Have you took the time to read my comment ? It's not the first time we have back-linking problem with this script. And the last time it was the creator himself who did it.
