### ISSUE TITLE
RESTORE backup of database sql

### ISSUE THREAD

**Issue by ph7ali** [pH7Software/pH7-Social-Dating-CMS#832]
Today, I freshly installed  v16 CMS but failed to restore the users into database.I backed up database into sql file but now  getting such error. 
![Screenshot_2020-11-07-06-55-02-1](https://user-images.githubusercontent.com/65395363/98429392-49e39180-20cc-11eb-85b6-184adcdbcae7.png)

As I remember in the v 16 ,  there is some updates in tables'fields. I guess It cannot restore the database without edit sql back up file.

**Comment by polynamaude** [comment]
@ph7ali If you want people to help you then give information about your system
What version of MySQL / MariaDB are you using ?
This seem to be related with the lack of escaping or something similar. Have you looked at the PHP file referenced and what it does ? Have you looked at the SQL logs to know the exact command sent to the database server ?

Those are all things that may help that you helped. We ain't astrologist who can guess right what you are using as system and what are the exact error behind. Neither do we have many different installation to try the software on it.

**Comment by polynamaude** [comment]
@ph7ali I think that if you believe that your problem is related to some "password" then maybe you shall stop trying to run a website...

Password cause "authentication failure". I don't know what you are talking about for phpmyadmin password but it uses the same password as MySQL users.
Also, make sure that you copy the info from your old config files into the new ones as there's some data hashed with your private code from config file. But this is in no way related to what you are getting here.

**Comment by ph7ali** [comment]
![Uploading Screenshot_2020-11-07-07-55-31-1.png…]()

**Comment by ph7ali** [comment]
![Uploading Screenshot_2020-11-07-07-55-31-1.png…]()

**Comment by ph7ali** [comment]
![Screenshot_2020-11-07-07-55-31-1](https://user-images.githubusercontent.com/65395363/98429876-7816a080-20cf-11eb-824e-340598d6e977.png)

**Comment by ph7ali** [comment]
Yes. I am wrong thinking it's  cause of password.

**Comment by ph7ali** [comment]
I found that the sql  file "which is being created during backup" has extra quotes( '  or "  )in SQL query  in VALUES FOR column fields. File reference :_protected/framework/Mvc/Model/Engine/Util/Backup.class.php

I think there is need  to check implode method.

**Comment by ph7ali** [comment]
![vvvvv](https://user-images.githubusercontent.com/65395363/98508691-eb621300-2285-11eb-90db-d5f737b12c35.jpg)

![zzzzzzz](https://user-images.githubusercontent.com/65395363/98508706-f74dd500-2285-11eb-893d-66f0b7be7127.jpg)

In my case, the sql file created in back up form by software is giving a reference of profileId from members_table  to album_picture table.
