### ISSUE TITLE
Edit add and delete fields for registration

### ISSUE THREAD

**Issue by warmup138** [pH7Software/pH7-Social-Dating-CMS#833]
Hello
I would like to personalize the registration to add and delete fields when registering a member especially on the part of the page step 2
can you explain me how to do it
Thank you for this very nice project
cordially

**Comment by polynamaude** [comment]
@warmup138 Add the code following MVC pattern, database fields and afterward go add your new field to the template.
What else do you want to know ?

**Comment by warmup138** [comment]
sorry,
I don't understand very well
what does add the code following the MVC template, the database fields mean?
can you explain or find the template in which to add the field?
Thank you for your help

**Comment by polynamaude** [comment]
@warmup138 You have to write your own PHP code.
MVC = Model View Controller, it's a design pattern paradigm. It's a way how code is organized.
After adding your PHP code, you need to modify the template to get it displayed properly. That is, you need to add HTML code that will display the field and do pre-validation too.

I think what you expected was a "click click click, write a couple of sentence and here we go it's done". But no, this ain't the case.

Now I ain't gonna show you how do to development or run a website !
We can help you good and give you hints on the wherabout of the software code or help you do diagnostic if you have problem.

But not do the things for you...

Have you at least tried looking on Google what does MVC means ?

**Comment by warmup138** [comment]
Thanks for your help
I understood the operation

**Comment by SHAHIDHUYS** [comment]
I want to make some required fields not required but don't know how to do it and also to delete some fields from sections. (Active Matrimonial CMS)
