### ISSUE TITLE
google maps problem

### ISSUE THREAD

**Issue by warmup138** [pH7Software/pH7-Social-Dating-CMS#834]
Hello
I have a question about google maps
which tells me "Unable to load Google Maps correctly on this page."
I have an API key that I configure in the administration
but I can't find the url of ip id
can you tell me how to know her
Thanks for your help

**Comment by Undefined-Variables** [comment]
Have you set your api key up to allow maps on your google dashboard?

**Comment by polynamaude** [comment]
> Have you set your api key up to allow maps on your google dashboard?

https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/833#issuecomment-723500971

Check this one and you'll get a hint that the answer is doubtful...

**Comment by Undefined-Variables** [comment]
@polynamaude oh I see 😂

**Comment by polynamaude** [comment]
@Undefined-Variables I've re-activated the issue regarding the problem with user id.
Because, I think this is important and it means that there has never been a instance that had as much user. Also, that the automated test haven't been done properly...

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/793#issuecomment-723799634
