### ISSUE TITLE
addfakeprofile ne marche pas !!!

### ISSUE THREAD

**Issue by sebalab** [pH7Software/pH7-Social-Dating-CMS#84]
addfakeprofile ne marche pas, j'ai bien un message vert mais rien ne s'est mis dans la base de donnée

que faire???

d'avance merci

**Comment by pH-7** [comment]
Le fournisseur des profils a changé son API il y à quelques jours seulement. Je viens de mettre à jour pour vous. Vous pouvez replacer votre fichier par https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/17c9fc80680b3d381c747cb631ad5bbed45c5c7f/_protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php

**Comment by pH-7** [comment]
Ce changement sera aussi disponible dans la prochaine version 1.3.8 qui sortira ce vendredi 6 mai

**Comment by sebalab** [comment]
je vais attendre vendredi alors car ça ne marche toujours pas , je n'ai même pas de message de confirmation, par la même occasion, se serais bien dans le formulaire de pouvoir choisir certain paramètre.

**Comment by pH-7** [comment]
Le nombre d'utilisateurs à ajouter. Je ne vois pas quel autre paramètre vous voullez avoir de plus.
Si vous avez bien remplacer le fichier, vous devez voir un message vert du style "10 users have been successfully added"

**Comment by sebalab** [comment]
Justement je n'est aucun message. Les parametres en plus serais par exemple le pays et le sexe. On peut mettre des paramettre dans l'url de l'api.


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : ♚ PH⑦ Soria ♛ <notifications@github.com> 
Date : 03/05/2016  23:48  (GMT+01:00) 
À : pH7Software/pH7-Social-Dating-CMS <pH7-Social-Dating-CMS@noreply.github.com> 
Cc : sebalab <slabat@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [pH7Software/pH7-Social-Dating-CMS] addfakeprofile ne marche pas
  !!! (#84) 

Le nombre d'utilisateurs à ajouter. Je ne vois pas quel autre paramètre vous voullez avoir de plus.

Si vous avez bien remplacer le fichier, vous devez voir un message vert du style "10 users have been successfully added"

**Comment by pH-7** [comment]
J'ai ajouté les paramètres souhaité pour vous aussi. Si cela ne va toujours pas quand la version sortira, veuillez vérifier le nombre d'utilisateur (Total Users: ) dans -> Admin -> User/Admin -> User -> Browse.
Parfois le fuseau horaire n'est pas le même et les nouveaux utilisateurs sont ajoutés à la fin, donc vous devez allez aux pages suivantes (en bas de page des utilisateur, changer de page avec la pagination).
Enfin, si vous êtes sous Windows il peut aussi avoir des problèmes, car les configs ne sont pas pour des serveurs de production
