### ISSUE TITLE
Error when reset Myphpadmin  OR FTP PASSWORD 

### ISSUE THREAD

**Issue by ph7ali** [pH7Software/pH7-Social-Dating-CMS#842]
![Screenshot_2020-12-14-13-50-31-1](https://user-images.githubusercontent.com/65395363/102067361-fb3ebb00-3e20-11eb-95ce-a65089feba6b.png)
.  This is again 2nd time same error came . When my server was being upgrade into SSD I reset the password of FTP or Myphpadmin there cms shows same fetal error as it was happened in past. Later,when I reset password as it was at time of installation of cms so it works fine. Can anyone  tell me where is the file which can solve this problems? Clearly this error is due to password of mysql phpadmin and the site admin during installation. This is been one year done of testing and i couldn't reset the password of my mysal ftp bcuz if i do reset so it shows same error.

**Comment by Undefined-Variables** [comment]
This error is simply telling you the password that ph7cms has for your database doesn’t match the password you have set for the MySQL user used to access your database! You should have created a non root user in your MySQL instance running on your server and then granted this user privileges needed on your server, how you do this depends on how your server is set up and the os it is running! Then all you need to do is make sure ph7cms has the same username and password in 

‘’’’
/_protected/app/configs/config.ini
‘’’’

As long as both have the same details it will work as expected!

**Comment by ph7ali** [comment]
I am happy to share you that I have found the solution of this error as i picked up my phone to delete this issue so I saw your reply .well thanks a lot Undefined Variable. Thank to this team.
