### ISSUE TITLE
 the style is missing

### ISSUE THREAD

**Issue by xingx001** [pH7Software/pH7-Social-Dating-CMS#846]
**Describe the bug**
chrome console warning
DevTools failed to load SourceMap: Could not load content for http://localhost:6081/static/js/jquery/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**To Reproduce**

1. i installed this ph7build-16 sucessfully
2. choose  NO.1 layout 
2. then  chrome  browser  visit  the website

**Expected Behavior**

the style is missing

the resouce file path is like    http://localhost:6081/asset/gzip/?t=css&d=static/css/js/jquery/box&f=box.css 
i feel somethin wrong  with  "gzip/?t=css&d="
**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/18054242/103969490-f8758280-51a0-11eb-89f5-16f5735042e0.png)

![image](https://user-images.githubusercontent.com/18054242/103969810-bbf65680-51a1-11eb-9b0e-18209389ae69.png)

how do i  resolve this issure?

**Comment by webitman** [comment]
@xingx001 
Same thing here https://grtx.nl/
Did you solved this ? 
Because after several Installs and uninstalls and trouble checking I can't solve this issue.

**Comment by Gerritvdl** [comment]
I am also experiencing the same problem, even though I have made sure that the option in php.ini is set to off.
Is there something or somewhere else that I am missing something?

**Comment by webitman** [comment]
@Gerritvdl 
You should make sure you have all needed options in PHP available and use PHP 7.4
![serverconfig-php7 4](https://user-images.githubusercontent.com/26062929/106750923-c84ac380-6628-11eb-88ea-32c5247da669.JPG)

**Comment by Gerritvdl** [comment]
Thanks webitman, Got it to work perfect with FireFox Browser but still an issue with Chrome.

**Comment by webitman** [comment]
@Gerritvdl did you have the chrome configuration correct ?
ff checken ;-)

**Comment by Gerritvdl** [comment]
Thanks webitman, To be honest, I am very new to this so not sure where to look for chrome configuration. And what to look for.

**Comment by webitman** [comment]
@Gerritvdl 
Are you living in The Netherlands ? Send me your message at info@grtx.nl

**Comment by huntersgordon** [comment]
> @Gerritvdl
> You should make sure you have all needed options in PHP available and use PHP 7.4
> ![serverconfig-php7 4](https://user-images.githubusercontent.com/26062929/106750923-c84ac380-6628-11eb-88ea-32c5247da669.JPG)

Using 7.4 worked for me! In my cPanel I did this by going to MultiPHP Manager, selecting my domain, and applying PHP 7.4 version to it
