### ISSUE TITLE
https is not enabled behind load balancer

### ISSUE THREAD

**Issue by ehehdada** [pH7Software/pH7-Social-Dating-CMS#849]
Hello @pH-7 !

We have the site running behind of a load balancer. The load balancer has https public interface, and connects privately via http to the server, which makes $_SERVER['HTTPS'] to have value 'off'. You may check $_SERVER['HTTP_X_FORWARDED_PROTO'] and $_SERVER['REQUEST_SCHEME'] too to detect if the public interface is using http or https when creating the links to the different resources.

Thank you very much!

Best regards

**Comment by pH-7** [comment]
Thanks very much for this!! FIxed here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/8a8325c96654306803c26e0880a5bafb42f79e60
