### ISSUE TITLE
Please upgrade your membership!

### ISSUE THREAD

**Issue by sebalab** [pH7Software/pH7-Social-Dating-CMS#85]
Bonjour,

j'ai un petit soucis lorsque je fait des tests j'ai toujour "Please upgrade your membership!" lorsque je veux acceder à un membre, et meme si je passe mon membre au un niveau supperieur donnant droit à plus de jour c'est pareil ....

que faut -il faire dans ce cas ? le nombre de jour est t il bien calculer sur le moment de changement de statut? et non sur la date d'inscription?

d'avance merci de votre aide

**Comment by sebalab** [comment]
En regardant de plus pret "membership date" n'est pas renseigné dans la base de donnée, mais j'ai fait la modif par le l'administration, c'est certaineme,nt pour cela, comment faire pour mettre une date dès que l'on change le statut dans l'admin ?

**Comment by sebalab** [comment]
Il faudrait que ce champs soit renseigné dès l'inscription d'un membre que se soit par le client ou par la partie admin, et mis à jour lors de la modif de statut. car pour le moment tous mes nouveaux utilisateurs qui pourtant devrais avoir 2 jours d'essais total gratuit se retrouvent à avoir une page de paiement.

**Comment by pH-7** [comment]
Le weekend vous n'êtes pas censé avoir une réponse, mais je vais quand vite vous aider maintenant.
Si vous voulez spécifier un abonnement à expiration limité (comme deux jours). Cela ne semble pas être inclut par défaut (je ne me souviens plus de ce que j'ai fait :smiley:). Vous pouvez donc utiliser le [patch ici](https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/44d745e76d6e803ee10a1999a2fda5ede6355f48). Et ça sera OK.

Si vous avez encore un problème, veuillez indiquer étapes par étapes le plus précis comment vous faites pour avoir ce problème ansi c'est plus simple pour pouvoir reproduire votre souci.

**Comment by pH-7** [comment]
There are patches for this@
https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/44d745e76d6e803ee10a1999a2fda5ede6355f48


https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/73ac11d6905d7f75cac2e79d1e29901e1e8a3bf5

**Comment by sebalab** [comment]
Merci beaucoup de m'avoir repondu aussi rapidement et surtout pendant le week-end, ca a l'air de fonctionner maintenant sauf que j'ai une erreur d'ajout de fake profile :  (au passage merci pour les filtres :+1: )

> Message:	SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
File:	/var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/system/core/models/UserCoreModel.php
Line:	588
Trace:	
#0 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/system/core/models/UserCoreModel.php(588): PDOStatement->execute()
#1 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/system/modules/admin123/forms/processing/AddFakeProfilesFormProcess.php(66): PH7\UserCoreModel->add(Array)
#2 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/system/modules/admin123/forms/AddFakeProfilesForm.php(19): PH7\AddFakeProfilesFormProcess->__construct()
#3 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/data/cache/pH7tpl_compile/admin123_61f4ebe4370e255eed4aef2aec4cc7c8/base/user/addfakeprofiles.cpl.php(19): PH7\AddFakeProfilesForm::display()
#4 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(424): require('/var/www/vhosts...')
#5 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/data/cache/pH7tpl_compile/admin123_61f4ebe4370e255eed4aef2aec4cc7c8/base/userlayout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('user/addfakepro...', '/var/www/vhosts...')
#6 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(424): require('/var/www/vhosts...')
#7 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/data/cache/pH7tpl_compile/public_main/datelove/layout.cpl.php(19): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/var/www/vhosts...')
#8 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/framework/Layout/Tpl/Engine/PH7Tpl/PH7Tpl.class.php(424): require('/var/www/vhosts...')
#9 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/framework/Mvc/Controller/Controller.class.php(110): PH7\Framework\Layout\Tpl\Engine\PH7Tpl\PH7Tpl->display('layout.tpl', '/var/www/vhosts...')
#10 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/system/modules/admin123/controllers/UserController.php(89): PH7\Framework\Mvc\Controller\Controller->output()
#11 [internal function]: PH7\UserController->addFakeProfiles()
#12 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/framework/Mvc/Router/FrontController.class.php(572): ReflectionMethod->invokeArgs(Object(PH7\UserController), Array)
#13 /var/www/vhosts/maxi-rencontre.net/maxi/_666protected/app/Bootstrap.php(95): PH7\Framework\Mvc\Router\FrontController->runRouter()
#14 /var/www/vhosts/maxi-rencontre.net/maxi/index.php(31): require('/var/www/vhosts...')
#15 {main}

**Comment by pH-7** [comment]
Pardon, faute à moi ! En effet si vous faites cela vous devez aussi mettre à jour les deux requêtes SQL -> https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/dea16c2a001967dbfcccae3eec6a131122ac2841

**Comment by pH-7** [comment]
Enfin si vous voulez voir la page de paiement une fois que l'abonnement est expiré, ici est la requête à mettre à jour https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/1c9aef8ccea5eefe96b7360eac6e93a696e8555e

**Comment by sebalab** [comment]
Merci super
