### ISSUE TITLE
disable two factor authentication, i can no longer login as admin ph7cms .. how can I log in as admin now?

### ISSUE THREAD

**Issue by daniele7477** [pH7Software/pH7-Social-Dating-CMS#856]
**Describe the bug**

(a clear and concise description of what the bug is.)

**To Reproduce**

**Expected Behavior**

(a clear and concise description of what you expected to happen.)

**Screenshots / Screencasts**

(if applicable, add screenshots or screencast the scenario to help explain your issue the best you can.)

**Comment by coucoudan** [comment]
To deactivate two-factor authentication, go in the database to the admin account on your host and to isTwoFactorAuth put 0. You must have access to phpmyadmin from the database.
