### ISSUE TITLE
How to add or Remove gender in User form

### ISSUE THREAD

**Issue by faizans80** [pH7Software/pH7-Social-Dating-CMS#862]
I want to add gay and transgender in Ph7cms please tell me how to do it because I am not finding it anywhere.

**Comment by polynamaude** [comment]
https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/857

**Comment by pH-7** [comment]
> #857

Hey @faizans80, this should help you - https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-add-additional-genders
