### ISSUE TITLE
Record

### ISSUE THREAD

**Issue by MariaHabib2207** [pH7Software/pH7-Social-Dating-CMS#868]
Record should not be added till step 4 is completed but data is added just after step 1 is completed and if user doesn't completes his profile even then entry for the user is created in the database

**Comment by pH-7** [comment]
Hey @MariaHabib2207 🙂 I appreciate your feedback!
This is actually a "feature". Sometimes, users lose their internet connection, after submitting the Step one, or they don't have time to answer to the questions on the Step2/Step 3. However, the user's "minimum details" are already in the database. You will already have the users' email addresses, so you can still recontact them asking to come back to your service and finish the registration process.
Later on, users who left the "registration session" can also directly login back to the site and fulfil their missing information. They won't have to re-start the registration steps from the beginning. 

Hope it now makes sense 😉

Have a lovely day!

**Comment by MariaHabib2207** [comment]
I am really thankful to you for replying my email .Actually I am working
with a UK based company and they have assigned me the task to submit the
record only after user have entered all the details

Can you just guide me which file I need to edit to achieve this

I will be very thankful to you
