### ISSUE TITLE
Add Banner / Ads (submit causes blank page)

### ISSUE THREAD

**Issue by Gh0st4unt3r** [pH7Software/pH7-Social-Dating-CMS#87]
The adding of new banners after clicking submit button shows blank page and does not submit the information on the banner list.

**Comment by pH-7** [comment]
Hi there,

thanks for the issue. Has been fixed here: https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/582eb060635d6955ecde0c9a486abea8e4443403

To fix it, please just open the file `_protected/app/system/modules/admin123/forms/processing/AdsFormProcess.php` and remove the blank spaces before `<?php`
