### ISSUE TITLE
Where is webroot dir set

### ISSUE THREAD

**Issue by baxtmann** [pH7Software/pH7-Social-Dating-CMS#870]
**Describe the bug**

I'm trying to setup a preproduction version of this on a new server (that I will be migrating to in the future). I copied everything over, restored the db, and the site is not loading. The user account on the other hosting was datinga1 whereas its now baxtmann - form the below error, I understand the issue as being the software is trying to go to an old dir that is no longer there. what file Is used to set this root dir path

When trying to load site I get 500 error, and checking logs on server I see below: 

[Sat Apr 24 01:00:41 2021] [proxy_fcgi:error] [pid 8040:tid 139887748392704] [client 142.180.181.221:54826] AH01071: Got error 'PHP message: PHP Warning:  require(/home/datinga1/public_html/_protected/app/Bootstrap.php): failed to open stream: No such file or directory in /chroot/home/baxtmann/ddlgdating.net/html/preprod/index.php on line 40PHP message: PHP Fatal error:  require(): Failed opening required '/home/datinga1/public_html/_protected/app/Bootstrap.php' (include_path='.:/usr/share/pear:/usr/share/php') in /chroot/home/baxtmann/ddlgdating.net/html/preprod/index.php on line 40'

**To Reproduce**

Copy files from one server to another, and move the db too. 

**Expected Behavior**

It should work. 

ENV info: 
php7.3
centos
Interworx panel (siteworx/nodeworx) 
MySQL = 10.2.37-MariaDB

Let me know if more info is needed.

**Comment by pH-7** [comment]
Hi @baxtmann!

I had a look to your error. It looks that the `PH7_PATH_PROTECTED` path in your `_constants.php` (~line 48) hasn't been updated. It tries to reach `home/datinga1/public_html/_protected/app/Bootstrap.php` but isn't found. My guess is that you didn't update the path in your `_constants.php` file (you will probably have to rename `/home/datinga1/public_html/_protected/` to `/home/baxtmann/public_html/_protected/` or similar path to point to the correct folder).

Hope it helps! 😄

**Comment by baxtmann** [comment]
@pH-7 Hey - Thanks for your help! 

I was able to get the website posting now - but the formatting looks to be missing - see attached screenshot with console errors. 

It looks to be referring to a folder /asset/ which does not exist - either in on this server or the old server (which is fully working, with no formatting issues)

Any chance you could advise? I can provide whatever you might need to help troubleshoot. 

![preprod error](https://user-images.githubusercontent.com/18515115/116160578-4d8dc380-a6c0-11eb-83aa-6c88b2065bdb.png)

**Comment by baxtmann** [comment]
@pH-7 Hey - hate to bug ya - any ideas here?
