### ISSUE TITLE
people can't sign up to my site

### ISSUE THREAD

**Issue by AussieMysteryboxes** [pH7Software/pH7-Social-Dating-CMS#874]
The following error was found:
Oops! Somebody has recently registered with the same IP address. Do you mind waiting 5 days?

Any help would be great

**Comment by AussieMysteryboxes** [comment]
the site is www.sookbook.fun

**Comment by pH-7** [comment]
Sure, this is to prevent spam and registration flooding attack.
It means that you already have a user registered with the same IP address.

You can change this setting as simple as that.
Admin Panel -> Setting -> General -> Spam -> Registration delay for Users, and update the number to "0" to disable it (or simply decrease the number of minutes, as you wish 😁).

Hope it helps!! 🎉

Have a lovely weekend!
Psst! Don't forget to Star the GitHub repo if you appreciate the hard work behind 😉 

![Star pH7 Social Dating CMS project!](https://user-images.githubusercontent.com/1325411/34179496-6ddd8e1a-e50b-11e7-9ce9-119d3f9d2aed.png)

**Comment by pH-7** [comment]
Let me know how it helps 😉

**Comment by AussieMysteryboxes** [comment]
I have only just set the site up and no one has signed up to it, I was getting a mate to sign up to test it out, I even got the same message when I tried to sign up on my phone, I have changed it to 0 now and it will let me sign up but it will keep going back to the login page, plus it hasn't sent the email out to me, I have set up the email on the site and I know it works, I mite delete it and re-install it and start it over and see how it goes

**Comment by AussieMysteryboxes** [comment]
Thank you for your help
