### ISSUE TITLE
CSS is broken

### ISSUE THREAD

**Issue by mercadanteus** [pH7Software/pH7-Social-Dating-CMS#876]
**Describe the bug**
Appearence of site is broken, looks flat and with no format

**To Reproduce**

1. Check php is updated
2. Install PH7 using Softaculous via CPanel
3. Receive confirmation PH7 was succesfully installed
4. Open site

**Expected Behavior**

Site is adecuatelly formated, CSS is right

**Screenshots / Screencasts**

![FireShot Capture 009 - Home - Castle Love1 - servercastlehill com](https://user-images.githubusercontent.com/24380156/119778826-92f30b80-be8d-11eb-9357-f3e2e5ea82fe.png)

**Comment by pH-7** [comment]
Hey @mercadanteus 

Thanks very much for reporting this issue. With your web browser, can you view the source code (usually CTRL+U) and go to some CSS links. What do you see?

With a FTP client or thanks to cPanel files browse, can you also navigate to _protected/data/log/pH7log/ and see if there are any log files in there? If so, can you open and give the error message you see?

**Comment by pH-7** [comment]
Related to #873

**Comment by pH-7** [comment]
@mercadanteus What PHP version are you using? Could you try on another PHP 7+ version?

**Comment by pH-7** [comment]
Finally @mercadanteus, with a FTP client or thanks to cPanel files browse, can you also navigate to _protected/data/log/pH7log/ and see if there are any log files in there? If so, can you open and give the error message you see?


Hope it helps!!


Looking forward to hearing from you! 😊
