### ISSUE TITLE
Google map not working

### ISSUE THREAD

**Issue by norspeed22** [pH7Software/pH7-Social-Dating-CMS#883]
How can you change the settings from the paid for Google maps to the open source OpenStreetMap ?

**Comment by pH-7** [comment]
The software currently doesn't support any other map APIs.
However, it can be added quiet easily into the "map" module (templates part, and backend part).

**Comment by norspeed22** [comment]
---
New Outlook Express and Windows Live Mail replacement - get it here:
https://www.oeclassic.com/

Hi.
Thank you for your reply.
Which template is it ?, where about in the backend and could i add the 
https://www.openstreetmap.org api ?

Please advise.

Regards.
Keith.



----- Original Message -----
From: ♚ PH⑦ de Soria™♛ ***@***.***>
Reply-To: pH7Software/pH7-Social-Dating-CMS 
***@***.***>
To: pH7Software/pH7-Social-Dating-CMS ***@***.***>
Cc: norspeed22 ***@***.***>, Author ***@***.***>
Sent: 10/07/2021 00:41:43
Subject: Re: [pH7Software/pH7-Social-Dating-CMS] Google map not working (#883)



The software currently doesn't support any other map APIs.
However, it can be added quiet easily into the "map" module (templates part, and backend part).
