### ISSUE TITLE
Trying to Reset Password via PHPMyAdmin

### ISSUE THREAD

**Issue by baxtmann** [pH7Software/pH7-Social-Dating-CMS#884]
Hi, I need to reset admin password via phpmyadmin, and I've found the spot where it needs to change. what I need to know is what hash format does the password need to be in so that the software can read it properly? 

Thanks!

**Comment by Undefined-Variables** [comment]
Just create a normal account then copy and paste the hash from the new row in the members table.

**Comment by pH-7** [comment]
> Hi, I need to reset admin password via phpmyadmin, and I've found the spot where it needs to change. what I need to know is what hash format does the password need to be in so that the software can read it properly?
> 
> Thanks!

Hey @baxtmann 

Since pH7CMS crypts the password, this won't work. You can reset your password by going to `your-url.com/admin123/forgot/admin123`
It will send you an email to reset your password. 

Let me know if it helps :)

**Comment by pH-7** [comment]
By default, the admin reset password link is not visible on the admin login page for security reason, but of course, the feature is there 😊 -> `your-website.com/forgot/admin123`

**Comment by pH-7** [comment]
Did it help @baxtmann? Hopefully it did 😊

Just let me know how it goes 🙂
