### ISSUE TITLE
Adding additional genders creates pages that do not displaying properly.

### ISSUE THREAD

**Issue by fox562562** [pH7Software/pH7-Social-Dating-CMS#885]
I have followed the instructions multiple times (How to add additional genders - https://github.com/pH7Software/pH7-Social-Dating-CMS/wiki/How-to-add-additional-genders). I have tried to make the changes (How to add additional genders) before and after installation. Works best after it is up and running.

Now my problem is, some pages do not display properly:
When viewed in a text editor the data seems to be there up to the point of  h2 class="center underline italic s_tMarg" Quick User Search /h2 . After that all data and tags are missing
![blank screen](https://user-images.githubusercontent.com/86481407/123531613-dcb45900-d6ba-11eb-8cff-697aec114e7c.JPG)
![blank screen 2](https://user-images.githubusercontent.com/86481407/123531624-f0f85600-d6ba-11eb-85b6-58f61fbba7eb.JPG)
![blank screen 3](https://user-images.githubusercontent.com/86481407/123531831-aaa3f680-d6bc-11eb-9d01-b513a21cd3aa.JPG)
I am a localhost running XAMPP for Windows 7.4.19, 
Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
Database client version: libmysql - mysqlnd 7.4.19
PHP version: 7.4.19, 
Server version: 10.4.19-MariaDB

**Comment by fox562562** [comment]
could it have anything to do with the additional \PFBC\Element ?

**Comment by pH-7** [comment]
You see this because you have an internal error. You might have forgotten to import a class namespace (or another PHP error in your changes).

You will have to enable the development mode to see the PHP errors (exceptions) on the page. To do so, edit `_protected/app/configs/config.ini`, and replace "environment = production" to "environment = development" at the beginning of the file and then save it.

You can also see the PHP logs located at `_protected/data/log/pH7log/`

Hope it helps!

**Comment by pH-7** [comment]
BTW, "How to set the development mode" https://www.ph7cms.com/doc/en/how-to-set-the-development-mode

**Comment by pH-7** [comment]
Let me know if you are still facing an issue with this one @fox562562

If not, can the ticket be closed?

**Comment by fox562562** [comment]
I was able to get it to work. Do you have any tutorials On adding modules. I would like to add where they can upload stories and then display. Thanks

**Comment by pH-7** [comment]
Glad to hear this @fox562562!! Unfortunately, there aren't video tutorials at the moment, but it's a great idea!
