### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [pH7Software/pH7-Social-Dating-CMS#898]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by pH-7** [comment]
Thanks very much for raising this concern @JamieSlome!

Now done 😅 https://github.com/pH7Software/.github/blob/master/SECURITY.md

**Comment by pH-7** [comment]
Let me know if this sounds fine for you by now @JamieSlome

P.S. Great service you offer BTW :)

**Comment by JamieSlome** [comment]
@pH-7 - thanks!

You should have received an e-mail yesterday with more information.
