### ISSUE TITLE
Issue with membership

### ISSUE THREAD

**Issue by bkkhanny** [pH7Software/pH7-Social-Dating-CMS#902]
I using 16.2 version and facing an issue with users. When a user registers, they are unable to access any thing chat etc. They are forcefully being redirected to https://domain.com/payment/main/index even though I have setup accurate membership for that user in admin panel.

**Comment by DJYmiJ** [comment]
I have also been struggling with this issue, i have been trawling through the closed issues but am struggling to find the issue. I am consistently receiving an issue with the putenv on line 362 of frontcontroller.class.php

I will continue to dig for an answer

**Comment by eustachijus** [comment]
Same problem

**Comment by DJYmiJ** [comment]
I have updated the base software. Well uninstalled and installed the latest version. No issues found so far. Awesome bit of kit guys thank you! once I have finalised everything and go live you will receive a donation. Thanks.
