### ISSUE TITLE
Impossible to log in after fresh install

### ISSUE THREAD

**Issue by GertCauwenberg** [pH7Software/pH7-Social-Dating-CMS#906]
I've installed the latest version of your cms: pH7Builder-16.2.2.zip
This is on an Ubuntu server with PHP 7.4 and Apache 2.4.41. For now (just testing) this is http-only and only an ip-address.
Database is mysqld 10.3.30-MariaDB

However, I can't get anything to work. Any form that I try (login, register, login as admin) just redisplays empty after a submit. No error messages, nothing. http access logs show a few 301 and mostly 200 codes, nothing special there. http error logs also nothing noteworthy.

After some debugging, I nailed it down to this:

- when I submit a form, the $_POST array does contain the submitted values
- the $_GET array contains 'login'
- the $_SESSION array contains only [pH7325fb_member_group_id] => 1
- hence the form validator finds the id 'form_login_user', but doesn't find a form to unserialize, and says 'sorry, empty form, invalid'...

but why?

**Comment by GertCauwenberg** [comment]
I guess I found the solution: if you don't use a domainname, the application sets the cookie-domain to .<ipaddress>. Notice the dot in front. And subsequently set-cookie is refused because the domain doesn't match.

**Comment by robotfx** [comment]
> I guess I found the solution: if you don't use a domainname, the application sets the cookie-domain to .. Notice the dot in front. And subsequently set-cookie is refused because the domain doesn't match.

So how did you fix it? I think I have the issue with the script settings a cookie as .domain.com instead of the domain.com. I cannot find how to get rid of the DOT

**Comment by GertCauwenberg** [comment]
Well, I just hard-coded it. In _constants.php you see a line 
$sDomain_cookie = '.' . str_replace('www.', '', $sDomain);
you can just replace that line with
$sDomain_cookie = <whatever you want>

But of course that is not a general solution, and probably won't survive an upgrade.

**Comment by robotfx** [comment]
Thanks, it probably doesn't apply to me then. I have deleted the _install dir after installation, as instructed. Must be something else.
