### ISSUE TITLE
Cannot login/register

### ISSUE THREAD

**Issue by robotfx** [pH7Software/pH7-Social-Dating-CMS#908]
Cannot login as admin or create user as visitor, possible due to inexistent .js/.css files ([again](https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/907)) 
Strangely enough, I've been able to login for one time after finally managing to install the script (see the link above), and in the DB I appear as **Logged in!** in the **status** field, table **admins_log_login**
For example, the admin login page (admin123) loads the script https://datesite.com/asset/js/mailcheckConfig.js, however the script request ends in 404. I'd upload an image but can't see an option here. So the following resources are missing:

/asset/js/mailcheckConfig.js
/asset/js/script.js
/asset/css/style.css
/asset/css/color.css
/asset/gzip/?t=css&d=templates/themes/datelove/css/&f=menu_inverse.css

**Comment by robotfx** [comment]
![Screenshot 2021-08-13 104033](https://user-images.githubusercontent.com/46458914/129338582-ad0c39bc-55de-46d7-8628-094624d7811b.png)
found the attach files option :)

**Comment by robotfx** [comment]
Never mind, too many things to fix. I'll just go back to the old osdate or maybe buddypress.

**Comment by Hostile** [comment]
dont work on demo either https://www.softaculous.com/demos/pH7CMS
