### ISSUE TITLE
loging in to Admin after install

### ISSUE THREAD

**Issue by RayatDK** [pH7Software/pH7-Social-Dating-CMS#936]
Really wierd issue here... I installed the CMS, when i tried to log into the admin, i cant seem to get in! 

Keeps saying wrong password, im positive its the correct password. I've even tried to enter it incorrectly (like having caps lock on)

Is there an easy way to reinstall the CMS? or reset the admin password from the console?

Or is it a reinstall ?

**Comment by pH-7** [comment]
Hey @RayatDK  😃

Are you sure you tried to login on the admin login form (generally at /admin123). Further info: https://ph7cms.com/doc/en/how-to-go-to-admin-panel

**Comment by anonsven** [comment]
same problem with the correct url

**Comment by ilitbey** [comment]
I installed the CMS, when i tried to log into the admin, i cant seem to get in!
6 time removed and installed. same problm not admin login
