### ISSUE TITLE
EMAIL

### ISSUE THREAD

**Issue by Mdajijur688** [pH7Software/pH7-Social-Dating-CMS#938]
When User Forget Their Password , Then Not Receive Password Reset Email , Please Fix

**Comment by pH-7** [comment]
Hey @Mdajijur688 

Thank you for reporting this annoying issue! 

Two quick questions for you:

1. What web hosting are you using? Could you ask them the email server log?
2. Are you sure the email is not in your spam folder?


Enjoy your day! ☀️

**Comment by Mdajijur688** [comment]
I Using Infinity Free Web Hosting , 

I am Sure That Nothing come Any Email On Spam Folder 

Please solve the Issue Immediately i request 

And I Request Second on We need Verification Option On Ph7cms , That Admin Verify User , We Need This Feature

**Comment by Amandacottoncandy** [comment]
U  fucking  liar  this  your wife  hore

Amanda

**Comment by pH-7** [comment]
Without SMTP logs, I can't really guess what's the issue on your side. Please contact the web hosting company as said in my previous message.

Please also keep in mind that pH7CMS is generally not compatible with free web hosting and free web hosting plans generally disable you to send email to prevent spam. This is maybe what happens for you. 


Have a great day!

**Comment by pH-7** [comment]
I've looked into your web hosting, and indeed, you can't send emails on their free plan InfinityFree. 

https://forum.infinityfree.net/t/webmail-hosting-free/32279


Hope it helps now knowing why the emails aren't send 🙂 


![InfinityFree, email sending disabled](https://user-images.githubusercontent.com/1325411/144748549-77ed84a4-16be-4b9f-99b2-bf0269b8ee17.jpeg)


Hope it helps! Good luck with your dating web app! 😊
