### ISSUE TITLE
Maintenance Mod 

### ISSUE THREAD

**Issue by Mdajijur688** [pH7Software/pH7-Social-Dating-CMS#944]
Can I Edit Maintenance Page ?

**Comment by pH-7** [comment]
Absolutely! The maintenance page is located in [_protected/app/system/global/views/base/tpl/other/maintenance.html.php](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/global/views/base/tpl/other/maintenance.html.php).

You can also use the File Management tool located in the admin dashboard.

**Comment by pH-7** [comment]
Absolutely! The maintenance page is located in [_protected/app/system/global/views/base/tpl/other/maintenance.html.php](https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/master/_protected/app/system/global/views/base/tpl/other/maintenance.html.php).

You can also use the File Manager tool located in the admin dashboard (Admin -> File/Page -> Protected File Manager_

Hope it helps! 😃
