### ISSUE TITLE
Nothing In Module

### ISSUE THREAD

**Issue by Mdajijur688** [pH7Software/pH7-Social-Dating-CMS#945]
![Screenshot_20211121-022446_Chrome](https://user-images.githubusercontent.com/91095640/142740672-9cf5103d-28e7-4a19-819f-9fac65e93760.jpg)

Why Nothing In Module , That Is A Problem ?

**Comment by pH-7** [comment]
This is normal. It just means that you don't have any third-party modules.
What modules do you want to install @Mdajijur688?
All the core modules included in the software are already pre-installed (as they are built-in). You can enable/disable them in Admin Dashboard -> Mods -> Enable/Disable modules.


I hope it helps. Enjoy your social dating site! 😃

**Comment by Mdajijur688** [comment]
I need Many 3rd party Module Please Add

**Comment by pH-7** [comment]
At the moment, there are not many 3rd-party modules freely available out there pH7CMS . What kind of modules are you looking to install on pH7CMS?
