### ISSUE TITLE
See this weird error it comes every time i have tried on mysql and Maria db both but same error

### ISSUE THREAD

**Issue by Sandeepatwork** [pH7Software/pH7-Social-Dating-CMS#950]
![image](https://user-images.githubusercontent.com/95039601/143464300-57f74074-347b-46a1-8f1b-30279d1eb59c.png)

**Comment by Sandeepatwork** [comment]
Error connecting to your database.
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'file_cdn_url'

**Comment by amanmeena801** [comment]
I'm also getting the same error did you figure out how to solve it?

**Comment by kleozzy** [comment]
I have the same issue on install . Not sure how to fix tis.

**Comment by pH-7** [comment]
This one has been fixed and the patch has now been merged to master. Thanks for mentioning this issue! I really appreciate that!

**Comment by pH-7** [comment]
FYI, the SQL bugfix fixing that issue is: https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/954

**Comment by pH-7** [comment]
> I have the same issue on install . Not sure how to fix tis.

That's the patch 😉 => https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/954

**Comment by kleozzy** [comment]
Awesome, many thanks. Can you update releases as well ? Github doesnt have the libs and dont really wanna do the whole composer install shebang :D
