### ISSUE TITLE
error in install 

### ISSUE THREAD

**Issue by rkhyd** [pH7Software/pH7-Social-Dating-CMS#951]
**Describe the bug**
The installation does not proceed after the step 7. It shows HTTP 500 error with the following error logged in php_error.log
https://prnt.sc/20x3mvc
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PH7\Database::isMySQL(), 0 passed`

I am using ubuntu 20.04 with php7.4.3 and MySQL 8.0.27

Any thoughts?

**Comment by pH-7** [comment]
Thank you so much for reporting this error @rkhyd. This error has now been patched here https://github.com/pH7Software/pH7-Social-Dating-CMS/commit/d088bfe62758c85e8f83586da9c49574165ab05e
