### ISSUE TITLE
Another Issue after installation done.

### ISSUE THREAD

**Issue by Sandeepatwork** [pH7Software/pH7-Social-Dating-CMS#952]
Showing these warnings

![image](https://user-images.githubusercontent.com/95039601/143564586-ab5ae17a-14e0-4d6e-a056-925e1abbd343.png)

Warning: syntax error, unexpected '|' in /var/www/html/_protected/app/configs/config.ini on line 129 in /var/www/html/_protected/framework/Config/Config.class.php on line 165

Warning: array_merge(): Expected parameter 1 to be an array, bool given in /var/www/html/_protected/framework/Config/Config.class.php on line 78

Notice: Trying to access array offset on value of type null in /var/www/html/_protected/framework/Config/Config.class.php on line 170

Notice: Trying to access array offset on value of type null in /var/www/html/_protected/framework/Config/Config.class.php on line 171

Notice: Trying to access array offset on value of type null in /var/www/html/_protected/app/Bootstrap.php on line 129

**Comment by pH-7** [comment]
Thank you so much for reporting this bug @Sandeepatwork!

In your `_protected/app/configs/config.ini`, at line 129, please change `#` to `;`

<img width="934" alt="Screenshot 2021-11-27 at 11 14 06" src="https://user-images.githubusercontent.com/1325411/143662820-6aac5923-3510-43fa-9e6e-d33b1d5d8b0b.png">

**Comment by Sandeepatwork** [comment]
Yes I did it. Thanks

**Comment by pH-7** [comment]
Awesome. Once you did this (and perhaps [applied this bug fix](https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/954)), everything should work properly fine 🤞
