### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'luv_games_categories.PRIMARY'

### ISSUE THREAD

**Issue by lual712003** [pH7Software/pH7-Social-Dating-CMS#955]
the error occurs when installing ph7cms in step 4/8

The installation is manual, I downloaded the software and the database was created manually, I have already verified it and it is correct, but it does not allow me to advance from this point.

I tried to do a clean installation 3 times from 2 different hosts thinking that it was the one that had been hired, but the result is the same.

I have been two days and I can not locate the error, if someone can support me.
Thanks

**Screenshots / Screencasts**

![error sql](https://user-images.githubusercontent.com/96151129/146094246-3c887a30-db3a-4b75-908f-6bd9514117c9.png)

**Comment by pH-7** [comment]
Thank you for reporting this. I will publish a patch in a few hours 😉

**Comment by lual712003** [comment]
Thanks for your comment. could you let me know when the patch is ready

**Comment by pH-7** [comment]
@lual712003 So far, I wasn't able to reproduce your issue.

**Comment by pH-7** [comment]
Do you mind trying again against a fresh new database? 

And also with the latest version from the master branch of the GitHub repo.

**Comment by LuvDuv** [comment]
I am getting the same error regardless trying endless times on mamp / xammp. However, when trying to install using the GitHub files the installation doesn't work either because it needs certain files that are not included on the GitHub version.

My question is,

Where can i download the older version of ph7cms?

**Comment by johnempotts** [comment]
I had the same issue. It is that the installer is not installing all the databases. You get about seven installed, I believe it's because you're still using width constraints on Integer type, i.e blah int(10). Can't have the ten part. MySQL??? If you have the problem, just go into myadmin and install everything manually. Look under the project files _install/data/sql/... to get all the databases.

**Comment by LuvDuv** [comment]
Thanks for the comment but how do i install everything manually? 

An example would do

Thanks

**Comment by johnempotts** [comment]
Go into your phpmyadmin. You should be able to find it in your cpanel (shared hosting) or login to your mysql console if running on your localhost machine. Look under this repo for the project files  _install/data/sql/[something].sql. Just grab all that code. At the top of the file you'll see @username = 'blahOrSomething'. Change the string portion accordingly for all those @somethings. Most show up in the 'ph7_settings' table so you could just do a search and replace.

Sorry doing this by memory LOL. 

Then load that into your database: For phpmyadmin select your database on the right and go to SQL tab and paste that code into the box. On you localhost machine from console(terminal) type : mysql -u [yourusername] -p [yourdatabase] < '/path/to/your/file.sql., On XAMP you might need to do a web search. I haven't used a factory web server in ages.

If you already tried installing you have to delete a file. _contstants.php under your web root and still have your _install file, then go back to where you left off in the install process and finish. 

Hope that helps. This is a alright little project but requires a good bit of know how to get working. But can be done.

John - trigsie dot com

**Comment by lual712003** [comment]
> Do you mind trying again against a fresh new database?
> 
> And also with the latest version [from the master branch of the GitHub repo](https://github.com/pH7Software/pH7-Social-Dating-CMS).

thanks to all.

I try different solutions, but without good results.
Digging through the community, I found a comment on the version16.3.2 build, i foud.

and the problem was dissapeared.

thanks for the support
