### ISSUE TITLE
Videos & Chat Roulette - No such file or directory

### ISSUE THREAD

**Issue by DanDan66** [pH7Software/pH7-Social-Dating-CMS#96]
Hi, getting this 
Uploaded file could not be moved from OS temp directory

my videos dont' work or the chat roulette

**Comment by pH-7** [comment]
Hi Dan! pH7CMS doesn't have **Uploaded file could not be moved from OS temp directory** error message. Are you sure it's with pH7CMS?

Could you please provide a full screenshot (containing the URL as well) so I can localise the error
