### ISSUE TITLE
Cannot install CMS due to errors

### ISSUE THREAD

**Issue by Sergey-bhw** [pH7Software/pH7-Social-Dating-CMS#971]
**Describe the bug**

After I set up the project via the composer, and went to the website link, I received an error of missing vendor folder.

Warning: require_once(/home/serega/www/11/_install/vendor/autoload.php): failed to open stream: No such file or directory in /home/serega/www/11/_install/index.php on line 24

Fatal error: require_once(): Failed opening required '/home/serega/www/11/_install/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/serega/www/11/_install/index.php on line 24

I noticed that those folders are in the _protected folder so I moved them to _install. But then I receive errors for missing functions like `is_url_rewrite`

I am using Ubuntu 18 and Apache server with PHP 7.4

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/21155423/151710202-1cf3acc2-a6a5-42af-a2b4-1c06ca6f23f3.png)

**Comment by pH-7** [comment]
Hi @Sergey-bhw 👋

Thanks very much for taking the time. You will also need to run composer in `_install` folder. 

From a command line opened for the project, go to the `_install` folder `cd _install`, then `composer install`.


Hope it helps!
