### ISSUE TITLE
Installer blank page

### ISSUE THREAD

**Issue by mateable** [pH7Software/pH7-Social-Dating-CMS#975]
Iam running haproxy as the load balancer
when I go to the install page it’s blank all of the permissions are right on the folder.  

Has anyone ran into this.

**Comment by pH-7** [comment]
Hi there @mateable 

Thanks very much for reporting this. What PHP version are you using?

Can you check the PHP logs? Could be available in ‘_install/data/log‘

**Comment by mateable** [comment]
@pH-7 

using PHP Version 7.4.3 


This is the error i got   
[05-Feb-2022 18:54:12 UTC] PHP Warning:  require_once(/var/www/html/ph7builder/_install/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/ph7builder/_install/index.php on line 22
[05-Feb-2022 18:54:12 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/ph7builder/_install/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/ph7builder/_install/index.php on line 22

**Comment by mateable** [comment]
here is my phpinfo  https://mateable.com/test/info.php

  I am getting a new error   took out line 22 to see what happens 
[06-Feb-2022 07:21:57 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function PH7\is_url_rewrite() in /var/www/html/ph7builder/_install/inc/init.inc.php:21
Stack trace:
#0 /var/www/html/ph7builder/_install/index.php(24): require()
#1 {main}

**Comment by pH-7** [comment]
It's weird you are having this issue. Have you installed it with composer or from the archive at SourceForge?

**Comment by pH-7** [comment]
Do you have Composer installed on your machine? You could potentially try to go to `_install` folder through your terminal and run `composer dump-autoload` in there.

**Comment by pH-7** [comment]
Alternatively, in `_install/index.php`, you could add `require_once inc/fns/misc.php` to fix that missing file.

**Comment by mateable** [comment]
@pH-7 I have composer installed     I deleted and install it from SourceForge   I got the install page to work   Iam on 5 or out 7 and i got and error Error connecting to your database.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

not sure how to fix that

**Comment by mateable** [comment]
I fixed it.

**Comment by pH-7** [comment]
> I fixed it.

Awesome! So glad to hear that @mateable 😊

Your SQL error was probably caused by a previous installation done on the same database.
