### ISSUE TITLE
SMTP Host Settings

### ISSUE THREAD

**Issue by setiawan912** [pH7Software/pH7-Social-Dating-CMS#976]
Oops! Our email server encountered an internal error. The email could not be sent. Please try again later

My smtp server is not detected. 

Where do you set the smtp host, user name and password?

There is smtp host and password in database ph7_settings, But it doesnt seem to have an effect on the email portion. Can anyone help me point to where I can change the setting? 

I can not change the php.ini because im using a shared hosting.  Thank you in advance.

Regards

Agus

**Comment by mrsauron69** [comment]
I have the same problem
