### ISSUE TITLE
Country blank

### ISSUE THREAD

**Issue by mateable** [pH7Software/pH7-Social-Dating-CMS#977]
I went to make a user and the country is blank  and it won’t let me move forward 
![59560412-9CC3-4BE3-BD0E-C3789E30062C](https://user-images.githubusercontent.com/81281401/153738492-d4834f62-463e-4286-8065-f102b0a51f41.png)

how do I fix this

**Comment by pH-7** [comment]
Hi there @mateable! Thanks very much for reporting this. 
Could you see in `_protected/data/log/php_error.log` if you have any log files in there. If you do, can you let me know what errors you see in the log file?

**Comment by pH-7** [comment]
Finally, if you don't have any log errors, can you go to Admin Panel -> User/Admin -> Users -> Country Restriction and make sure at least one country has been selected in there.

**Comment by mateable** [comment]
Ok Thank you I got it   :)
@ @pH-7  Why does the ip address always show 127.0.0.1   How can i get it to show the clients IP address ?
