### ISSUE TITLE
How to separate the admin panel like Laravel or other frameworks. Completely different layout and UI or look and feels?

### ISSUE THREAD

**Issue by Monarul007** [pH7Software/pH7-Social-Dating-CMS#981]
**Flexible UI**

Suppose we want a different UI and layout for our admin panel. Want to use CSS frameworks like Tailwind or the higher Bootstrap version.

**Comment by mateable** [comment]
I would like to know how to do this too

**Comment by pH-7** [comment]
Thank you for this suggestion! But why would you really want this...? The admin dashboard is fully integrated with the rest of the software. Everything is consistent. Two different themes for the admin dashboard and the rest isn't possible. Themes are used everywhere as the admin dashboard is part of the rest 🙂

Have a great weekend to you both @mateable @Monarul007! Happy coding and enjoy your social dating web app!

Looking forward to speaking with you on GitHub issues!
