### ISSUE TITLE
Payment Gateways

### ISSUE THREAD

**Issue by EaglecoastHosting** [pH7Software/pH7-Social-Dating-CMS#986]
Good day.
The 5 Payment Gateways in PH7 CMS is not supported in South Africa.
One of the preferred gateways in South Africa is  PayFast. 
Is there a Bank Transfer / Wire gateway available ? 
Kind Regards
Doep Du Plessis

**Comment by pH-7** [comment]
Hi there @EaglecoastHosting ,
Thanks very much for your message! Unfortunately, at the moment this is not supported. There was already a similar request a little while ago, and my reply was: https://github.com/pH7Software/pH7-Social-Dating-CMS/issues/526#issuecomment-488922355
