### ISSUE TITLE
I am trying to install the lastest version17.1.2 but too many errors

### ISSUE THREAD

**Issue by norspeed22** [pH7Software/pH7-Social-Dating-CMS#988]
I am trying to install the lastest version17.1.2, however, despite having provisioned the server for PDO, and exif, i am still getting the following errors: You have 3 error(s): and unable to install, any ideas as to why ?

❌ 1) Please install "PDO" PHP extension.
❌ 2) Please install "exif" PHP extension.
❌ 3) Please install "exif" PHP extension.

http://mangostore.co.uk/_install/

**Comment by pH-7** [comment]
Hi @norspeed22 

It seems that your web hosting isn't compatible with gmail he software. If these errors are showing up, it means that the script couldn't find them. The extensions might be installed but not activated. I suggest you to contact again your web hosting provider. 

You can also create a `phpinfo.php` file with `<?php phpinfo();` inside and look what is enabled/disabled.

If you are 100% sure everything is ok (which I doubt at the moment...), you can comment everything in `_install/requirements.php` and save it.


Hope it helps

**Comment by norspeed22** [comment]
Hi.
I am my own web host, with my own VPS, how would I activate it, it has been installed ? it is showing as installed, and enabled on my server for PHP 7.4.
